### ISSUE TITLE
مشکل جزیی

### ISSUE THREAD

**Issue by rahim1234** [persepolisdm/persepolis#1]
یه مشکل کوچیک داره اونم وقتی 
pause
رو میزنی بعد
stop 
رو میزنی برنامه نمیتونه فایل رو دانلود کنه و پیغام 
aria2 did not respond! try agian!
میده و باید برنامه رو ببندی و دوباره اجرا کنی تا درست شه.
میزکار unity . ubuntu 16.04

ممنون از برنامه خوبتون.

**Comment by alireza-amirsamimi** [comment]
ممنونم
باگ رو تایید کردم
الان شروع میکنم حلش کنم
:)

**Comment by alireza-amirsamimi** [comment]
مشکل حل شد
آپدیت کن :)
دوباره برنامه رو نصب کن
چک میکنم اگر مشکل مشابهی بود اون رو هم حل میکنم
ممنون از کمکت
