### ISSUE TITLE
کرش کردن برنامه بعد از کلیک ۲بار بر روی دکمه ادامه

### ISSUE THREAD

**Issue by Sosha1996** [persepolisdm/persepolis#10]
سلام.
امیدوارم خوب باشید.

من سعی داشتم این [لینک](https://as7.asset.aparat.com/aparat-video/a_57i09g3h1i85kk4gn84j8l2986ig5h26i5k8j2036454-508v__68d7a.mp4) رو بارگیری کنم که با پیغام این مواجه شدم:
_Aria2 did not respond!
Try again!_

مجددا که روی دکمه **ادامه** کلیک کردم برنامه **_کرش_** شد و در لاگ متاسفانه چیزی ننوشت که بتنونم به خدمتتون بفرستم.

موفق باشید!

**Comment by alireza-amirsamimi** [comment]
سلام ممنون از باگ ریپورت
یک ساعت پیش یه آپدیت جدید انجام دادم تا این مشکل رو رفع کنم
دوباره دانلود و نصب کن ببین رفع شده یا نه
ممنون

**Comment by Sosha1996** [comment]
**مشکل حل شد!**

خسته نباشید و سپاس!

**Comment by alireza-amirsamimi** [comment]
ممنونم از همکاریت
