### ISSUE TITLE
لیست دانلود

### ISSUE THREAD

**Issue by cnmeysam** [persepolisdm/persepolis#100]
سلام یه پیشنهاد داشتم برای ورژن جدید
نمیدونم با IDM کار کردین یا نه
ولی یک آپشن داره که خیلی کار رو راحت میکنه
مثلا توی یک سایت اگه بخوام 10تا لینک رو با هم بزنم بره توی لیست دانلود 10تا لینک رو انتخاب میکنم و روی دانلود با آی دی ام کلیک میکنم همه لینکهایی که انتخاب کردم میاد توی لیست دانلودم نیاز نیست تک تک یکی یکی لینکها رو به لیست اضافه کنم توی این دانلود منیجر من همچین چیزی پیدا نکردم اگه داره میشه بگین چطوری استفاده کنم اگر نه هم بنظرم آیتم عالیی برای نسخه جدید باشه
و یک آیتم دیگه هم که داره اینه دانلود هایی که کامل شدن رو میشه زد از لیست حذف بشن نیازی نیست یکی یکی حذف کنی یا اول انتخاب کنی بعد حذف کنی
.  زمانی که دانلود جدید میزنی صفحه لینک دانلود جدید always on top باشه خیلی خوب میشه
 اگه میشه این 3 تا آپشن رو به برنامتون اضافه کنید عالی میشه

**Comment by alireza-amirsamimi** [comment]
@cnmeysam سلام
برای مورد اول
اگر از فایرفاکس استفاده میکنید
کافی هست که لینکهاتون رو هایلایت کنید و راست کلیک کنید و با 
Flashgot selection
برای پرسپولیس بفرستید
درباره مورد دوم هم نیازی نیست . پرسپولیس در دانلود صف از دانلود هایی که به پایان رسیدند صرف نظر میکنه

**Comment by cnmeysam** [comment]
سلام شرمنده وقتتون رو میگیرم میدونم وظیفه و اجباری ندارید و دارید لطف میکنید و حق ندارم چیزی بخوام
در مورد اول من از کروم استفاده میکنم
در مورد دوم هم میونم صرف نظر میکن ولی باعث شلوغ شدن لیست دانلود میشه مثل اینه سطل آشغال رو خالی نکنی اگه دنبال چیزی هم بگردی کارت سخت میشه در هر صورت قشنگ نیست این مدلی و با یه حلقه وایل ساده این مشکل حل میشه

**Comment by alireza-amirsamimi** [comment]
سلام
دیدگاه من و بقیه دوستان نسبت به پیشنهادات اینجوری نیست :)
لطفا هر چی به ذهنتون مبرسه همیشه اطلاع بدید
مورد اول به دوستمون که افزونه کروم رو توسعه میدند اطلاع میدم
@JafarAkhondali 
انشالله روش کار میکنند و اضافه میکنند
🌹
درباره مورد دوم
IDM
دکمه ای داره که دانلودهایی که تمام شدند رو حذف میکنه؟
من ویندوز و آی دی ام ندارم . ممنون میشم توضیح بدید

**Comment by JafarAkhondali** [comment]
@cnmeysam @alireza-amirsamimi 
سلام
بله این آپشن توی برنامه اصلیمون بوده و میخواستیم روش کار کنیم ممنون که شما هم پیگیری کردین منتظر پیشنهادات دیگرتون هم هستیم :)

**Comment by cnmeysam** [comment]
سلام
بله توی idm 
یک آیتم هست که اسمش حذف تکمیل ها هستش و وقتی اون رو بزنید دانلودهایی که تکمیل شده از لیت دانلود حذف میشه
تمام آیتم هایی که گفتم توی آ دی ام وجود داره و چند تای دیگه هم هست مثل زمانبندی صف که سر یک زمان معین شروع بشه سر یک زان مشخص متوقف بشه صف یا بعد از دانلود آنتی ویروس اسکن کنه یا اینکه چه نوع پسوندهایی رو خدکار بعد از کلیک روی لینک دانلود کنه نیاز به راست کلیک و اضافه به لیست نباشه البته توی همه بروزرها و .... فقط من قصد مزاحمت و زیاد کردن کار شما رو نداشتم دانلود منیجر آی دی ام نقطع ضعف زیاد داره مثلا بعد از دانلود گاهی پیش میاد مجبور بشیم فایل رو یا دوباره دانلود کنید یا مثلا فایل های فشرده رو ریپیر کنیم اگه آیتمهایی که گفتم به برنامه اضافه بشه و نسخه ویندوزی هعم بیرون بدین بدون شک بهترین و پر مصرف ترین دانلود منیجر میشین
از آپشن ها زیاد هست مثل اضافه کرد یوزر پس سایتهایی که اکانت دارن برای دانلود ولی کم کم جلو برین بنظرم هم برای شما خسته کننده نمیشه هم اینکه کاربر هر بار آپشن جدید میبینه ذوغ میکنه ?:D:D:D:

**Comment by zeinaly** [comment]
سلام و عرض خسته نباشید به اعضای تیم توسعه دهنده

**Comment by zeinaly** [comment]
سلام و عرض خسته نباشید به اعضای تیم توسعه دهنده 
چندتا پیشنهاد داشتم :

**Comment by zeinaly** [comment]
سلام و عرض خسته نباشید به اعضای تیم توسعه دهنده 
چندتا پیشنهاد داشتم
۱-بشه از صف دانلودی که اینجاد کردیم بک اپ بگیریم 
۲-یک دکمه برای پاک کردن دانلود های کامل شده 
۳-وقتی لیست رو درک میکنم تا یک سری رو گروهی از لیست پاک کردنم نمیشه تکی حذف میکنه 
۴-در صف دانلودی که ایجاد شده اگه سورت دستکاری بشه صف دانلود بهم میخوره بهتره یه فکری براش بشه 
۵-اینکه بشه تغیین کرد چه تعدادفایل همزمان باهم دانلود بشن (شاید وحود داره من پیدا نکردم  )
۶-در صفحه ای که لینک دانلود اضافه میشه بجای 
Ok 
از 
start download 
و در صغحه ای که در پایان دانلود نمایش داده میشه بجای 
ok
از 
Done 
استفاده بشه بهتره 
این نظر در مورد ورژن ۲.۳ هست و هنوز به ۳.۲.۳ اپدیت نکردم 
با ارزوی موفقیت برای تیم توسغه :)))

**Comment by alireza-amirsamimi** [comment]
@zeinaly سلام
ممنونم از پیشنهاد هاتون
درباره مورد سوم منظورتون رو درست نفهمیدم . اگر مشکل شما پاک کردن چند آیتم با هم هست فقط کافی هست در لیست راست کلیک کنید و گزینه
Select multiple items
رو تیک بزنید
درباره مورد چهارم ، فکر میکنم منطقی هست ، چون شما داری بر اساس یک نیاز لیست رو مرتب میکنی ، مثلا دوست دارید دانلود های حجیم اول در صف دانلود بشن یا ...
پیشنهاد های بسیار خوبی دادید
سپاس از شما
فقط لطفا سعی کنید ازین به بعد برای هر پیشنهاد یک موضوع جدا باز کنید تا تگ زدن و بررسی برای ما ساده تر باشه.
قویا توصیه میکنم به ورژن
2.3.2
آپدیت کنید

**Comment by JafarAkhondali** [comment]
This feature is implemented in new version of Persepolis-WebExtension with more advanced features.
