### ISSUE TITLE
openSUSE repository unavailable

### ISSUE THREAD

**Issue by amirsina-mashayekh** [persepolisdm/persepolis#1003]
**System Details:**
* Operating System: GNU/Linux
* Distro: openSUSE Tumbleweed
* Desktop Environment: KDE Plasma 6

The [link](https://software.opensuse.org/download.html?project=home%3Ahayyan71&package=persepolis) you provided for openSUSE in the installation instructions is unavailable.

I also found [this page](https://software.opensuse.org/package/persepolis) but versions seem to be out of date.

**Comment by alireza-amirsamimi** [comment]
Unfortunately, the person who maintained Persepolis for  OpenSuse is not available. It would be great if someone could do this

**Comment by amirsina-mashayekh** [comment]
How should someone maintain the package for openSUSE? Maybe I can do this.

**Comment by alireza-amirsamimi** [comment]
I think you should check out this [link](https://openbuildservice.org/).

**Comment by amirsina-mashayekh** [comment]
Please check [this page](https://build.opensuse.org/package/show/home:amirsina/persepolis).

It can be installed from [here](https://software.opensuse.org//download.html?project=home%3Aamirsina&package=persepolis):

1. Click on your OS (Tumbleweed, Leap 15.6, etc.). If the downlod doesn't start automatically, right click on your OS and select "Save link as".
2. Open persepolis.ymp (downloaded file) using "YaST 1-Click Install". Double clicking the file in file manager should work.
3. Continue install steps in YaST GUI.

Please report any package related problem to me.

**Comment by alireza-amirsamimi** [comment]
Thank you very much.
We will add them to the site and wiki soon..🌹.

**Comment by alireza-amirsamimi** [comment]
@amirsina-mashayekh 
Please add python3-pysocks to dependencies. Thanks

**Comment by amirsina-mashayekh** [comment]
[Done](https://build.opensuse.org/package/rdiff/home:amirsina/persepolis?linkrev=base&rev=4). Thanks for feedback. ❤️

**Comment by bitrot-alpha** [comment]
`python3-pyside6` is no longer offered on the openSUSE repos for Tumbleweed and Leap. The Python 3.11 version is available, `python311-pyside6`. I tried installing the Python 3.11 version, but I guess 3.11 and whatever previous version corresponds to `python3` are isolated from each other, as Persepolis couldn't find the library and didn't start.

I read https://github.com/persepolisdm/persepolis/wiki/git-installation-instruction and tried to install `python3-qt5` and that worked well.

**Comment by amirsina-mashayekh** [comment]
@bitrot-alpha
My system's default python is 3.11.10. While installing persepolis, it shows this message:

> 'python3-pyside6' not found in package names. Trying capabilities.
> 'python311-pyside6' providing 'python3-pyside6' is already installed.

Zypper resolves it automatically and works well. Did you change default python3 version of your system?

**Comment by bitrot-alpha** [comment]
I use Leap. I believe Leap uses Python 3.6 *as its default.
I ran `python3 --version` and got Python 3.6.15.

If `python3-qt5` is added as a dependency in the OBS configuration, I believe any issues installing on Leap will be resolved.

Thank you for the quick response!

**Comment by amirsina-mashayekh** [comment]
@bitrot-alpha 
Would you please tell me which version of Leap are you using?

**Comment by bitrot-alpha** [comment]
@amirsina-mashayekh 

```
user@host [18:47:24] ~ $ uname -a
Linux raizing-top 6.4.0-150600.23.25-default #1 SMP PREEMPT_DYNAMIC Tue Oct  1 10:54:01 UTC 2024 (ea7c56d) x86_64 x86_64 x86_64 GNU/Linux
user@host [18:47:29] ~ $ cat /etc/os-release 
NAME="openSUSE Leap"
VERSION="15.6"
ID="opensuse-leap"
ID_LIKE="suse opensuse"
VERSION_ID="15.6"
PRETTY_NAME="openSUSE Leap 15.6"
ANSI_COLOR="0;32"
CPE_NAME="cpe:/o:opensuse:leap:15.6"
BUG_REPORT_URL="https://bugs.opensuse.org"
HOME_URL="https://www.opensuse.org/"
DOCUMENTATION_URL="https://en.opensuse.org/Portal:Leap"
LOGO="distributor-logo-Leap"
```
