### ISSUE TITLE
Please make available for Fedora the last version, it is 2 versions behind the current one.

### ISSUE THREAD

**Issue by formlessdao** [persepolisdm/persepolis#1014]
1. Please make available for Fedora the last version, it is 2 versions behind the current one.

2. Also the current version i just installed 4.1.0 does not recognize yt-dlp and ffmpeg as installed although I have them both installed on Fedora 39.

**Comment by alireza-amirsamimi** [comment]
Hello
Please checkout this [issue](https://github.com/persepolisdm/persepolis/issues/1004) and leave a comment there if you like.

**Comment by formlessdao** [comment]
2. Also the current version i just installed 4.1.0 does not recognize yt-dlp and ffmpeg as installed although I have them both installed on Fedora 39.
Please help me troubleshoot.

**Comment by alireza-amirsamimi** [comment]
@formlessdao 
Please test new version of persepolis and tell me the results.

**Comment by formlessdao** [comment]
> @formlessdao Please test new version of persepolis and tell me the results.

How do you want me to test it if it is not available yet in Fedora 39 repo?

I only have 4.1.0 and that one installs but yt-dlp and ffmpeg are not recognized properly even if I know they are already installed.

**Comment by alireza-amirsamimi** [comment]
Uninstall Persepolis with dnf and install it [in this way](https://github.com/persepolisdm/persepolis/wiki/git-installation-instruction).
