### ISSUE TITLE
youtube download won't start mixing audio and video

### ISSUE THREAD

**Issue by ali-ghanati** [persepolisdm/persepolis#1018]
**System Details:**
* Operating System: arch linux
* Distro(For GNU/Linux and BSD users): parch linux
* Desktop Environment(For GNU/Linux and BSD users): kde plasma
* Persepolis Version: 5.0.0.r9.gdd16434-1
* How do you install Persepolis? yay

I had so many problems while launching persepolis 5 and all of them was related to installing dependencies with python pip, that i found from terminal launching and installed missing libraries, now it works fine but youtube downloader after downloads audio and video won't start mixing these and starting manually doesn't help unfortunately doesn't log anything in persepolis logs so i'm guessing for a missing library can you guys help me to find that? 

note: i did not have any problems with persepolis 4.2 installed from pacman

**Comment by alireza-amirsamimi** [comment]
Hello 
I confirm this bug. I am trying to fix this bug.  I think it will be fixed soon. Thanks for reporting this bug.

Do you see the installation instructions in [wiki](https://github.com/persepolisdm/persepolis/wiki/git-installation-instruction)? Didn't it helpful?

**Comment by ali-ghanati** [comment]
> Hello I confirm this bug. I am trying to fix this bug. I think it will be fixed soon. Thanks for reporting this bug.
> 
> Do you see the installation instructions in [wiki](https://github.com/persepolisdm/persepolis/wiki/git-installation-instruction)? Didn't it helpful?

yes it did help me, but it was too late,started to search from hard way, i believe this project needs better readme to redirect users to documentation or more simple explanation, also thank you for your time for this amazing app i enjoy it every time i'm downloading anything  <3

**Comment by alireza-amirsamimi** [comment]
@ali-ghanati 
The bug has been fixed! Thanks for reporting🌹🌹
