### ISSUE TITLE
مشکل در عملکرد دکمه stop [bug] 

### ISSUE THREAD

**Issue by Monirzadeh** [persepolisdm/persepolis#102]
اگر پرسپولیس در دریافت لینکی به مشکل برخورد کند دکمه stop کارکرد خودش را از دست میدهد  
در چنین شرایطی دکمه stop پنجره پیشرفت دانلود را نمیبندد و باید برای بستن پنجره پیشرفت دانلود از ضربدر استفاده کرد.
همینطور دکمه stop در پنجره اصلی برنامه هم عملکرد خود را از دست میدهد. تنها راه بستن کامل برنامه و اجرای مجدد است که لینک مورد نظر به حالت stop تغییر وضعیت میدهد.
برای باز تولید شرایط به پرسپولیس لینکی با پورت پروکسی فرضی(غیر موجود ) بدهید.
اگر در حین دانلود ارتباط با aria2c قطع شود همین مشکل تکرار میشود
ubuntu 16.0.4 + unity + Persepolis 2.3.1

**Comment by alireza-amirsamimi** [comment]
@Monirzadeh سلام
این مشکل مربوط به نسخه قدیمی آریا هست که در مخازن اوبونتو وجود داره
در توزیع های بروزتر مثل آرچ و فدورا و سوزه این مشکل رفع شده
انشاالله با بروز شدن نسخه آریا در اوبونتو در آینده این مشکل رفع خواهد شد
