### ISSUE TITLE
ffmpeg Error: Permission Denied During Muxing Process on Windows 10 Pro

### ISSUE THREAD

**Issue by samomar** [persepolisdm/persepolis#1023]
**System Details:**
- Operating System: Windows 10 Pro
- Version: 22H2
- OS build: 19045.4894
- Experience: Windows Feature Experience Pack 1000.19060.1000.0
- Persepolis Version: 5.0.0
- How do you install Persepolis? https://github.com/persepolisdm/persepolis/releases/download/5.0.0/persepolis_5.0.0.0_windows_64bit.exe

* _Please attach log files if crash or paste error message_

**Issue Description and steps to reproduce:**
- When trying to download files via Persepolis, I receive the following error related to **ffmpeg**:
  
  ```
  2024-09-23 21:10:05,200 - Persepolis - ERROR - ffmpeg error: [in#0 @ 000001a92b697080] Error opening input: Permission denied
  Error opening input file C:\Users\Sam\Downloads\Persepolis.
  Error opening input files: Permission denied
  ```

- The issue occurs even when running as an administrator. Attempts to adjust file permissions or move files to different directories have not resolved the problem.

- Adding the link successfully fetches the data, and downloads proceed as expected. However, the problem arises during the **muxing** process, where ffmpeg is unable to open the input file and the error occurs.

**Comment by alireza-amirsamimi** [comment]
Hello
Thanks for reporting. I think this problem has been fixed by this [commit](https://github.com/persepolisdm/persepolis/commit/b4bf7661de82db1208a431a455f0ada0b3f89e8e). This issue is related to issue #1018. We will release new version soon. Please reopen this issue if the problem persists.
