### ISSUE TITLE
suggestion add option to check updates for yt-dlp

### ISSUE THREAD

**Issue by qwerty59b** [persepolisdm/persepolis#1024]
Yt-dlp is a powerful tool thanks for including it in persepolis but yt-dlp is constantly updated and it would be nice to have an option in persepolis settings to check for updates for yt-dlp.

**Comment by alireza-amirsamimi** [comment]
Hello
There is no problem with Linux distributions and the Yt-dlp is updated with the OS update. But we cannot do this in M.S.Windows and Mac OSX because we have to release the frozen version of Persepolis.
