### ISSUE TITLE
عدم اجرا برروی mac os 15

### ISSUE THREAD

**Issue by abbasalim** [persepolisdm/persepolis#1026]
**System Details:**
* Operating System: ? **mac os 15**
* Persepolis Version: ? **5.0.0**
* How do you install Persepolis? **github release page**
<img width="262" alt="Screenshot 2024-09-29 at 08 17 01" src="https://github.com/user-attachments/assets/c9fbc966-5465-4e50-a361-6eb3ca9f1136">

برروی مک او اس ۱۵ نسخه جدید رو نصب کردم، از قبل هم نسخه ای روی سیستم عامل نصب نبود. اما یخورده اون پایین روی نوار داک ، بپر بپر می کنه ایکونش بعدش هم بسته میشه

**Comment by kiahamedi** [comment]
> **System Details:**
> 
> * Operating System: ? **mac os 15**
> 
> * Persepolis Version: ? **5.0.0**
> 
> * How do you install Persepolis? **github release page**
> 
> <img width="262" alt="Screenshot 2024-09-29 at 08 17 01" src="https://github.com/user-attachments/assets/c9fbc966-5465-4e50-a361-6eb3ca9f1136">
> 
> 
> 
> برروی مک او اس ۱۵ نسخه جدید رو نصب کردم، از قبل هم نسخه ای روی سیستم عامل نصب نبود. اما یخورده اون پایین روی نوار داک ، بپر بپر می کنه ایکونش بعدش هم بسته میشه

با سلام و احترام
ممنون میشم نسخه جدید را تست بفرمایید و از اگر اجرا نشد از طریق ترمینال مک اقدام به اجرا نمایید تا لاگ خروجی را مشاهده کنیم
برای اجرا از طریق ترمینال روی برنامه راست کلیک کرده و وارد محتوای برنامه بشید در پوشه macOS فایل باینری پرسپولیس وجود دارد و آن را بکشید داخل ترمینال و سپس اجرا کنید.

با تشکر

**Comment by abbasalim** [comment]
من این دستور رو زدم
` /Applications/Persepolis\ Download\ Manager.app/Contents/MacOS/Persepolis\ Download\ Manager `
اما این خطا رو میده
`
PermissionError: [Errno 13] Permission denied: '/Users/****/Library/Application Support/BraveSoftware/Brave-Browser'
`

**Comment by abbasalim** [comment]
رفتم این پوشه ای که گفته رو پاک کردم.داخلش خالی بود. مجدد ساخت و یه فایل داخلش گذاشت درست شد!!!

**Comment by kiahamedi** [comment]
> رفتم این پوشه ای که گفته رو پاک کردم.داخلش خالی بود. مجدد ساخت و یه فایل داخلش گذاشت درست شد!!!

جالبه چون پرسپولیس نباید به لایبرری بریو نیاز داشته باشه، امکانش هست اون فایلی که میفرمایید درست کرده و مشکل برطرف شده رو برای ما قرار دهید تا بررسی نماییم؟

**Comment by alireza-amirsamimi** [comment]
سلام
این پوشه حاوی فایل تنظیمات برای ارتباط پرسپولیس با مرورگر brave هست که توسط پرسپولیس از پیش ساخته میشه که اگر کاربر این مرورگر رو نصب کرد و افزونه پرسپولیس رو هم روی مرورگر نصب کرد، پرسپولیس بتونه با مرورگر ارتباط برقرار کنه. این که permission denied داشتید، مربوط به سیستم خودتون هست. شاید قبلا برنامه رو با دسترسی ریشه اجرا کردید یا مجوزهای دسترسی سیستمتون به هر دلیلی دچار اشکال بوده.

**Comment by abbasalim** [comment]
ممنون از پاسخگوییتون به هرحال فکر میکنم بهتر باشه این خطاها رو هم در نظر بگیرید و کنترلشون کنید تا مانع اجرا روی سیستم کاربران دیگه نشه.
