### ISSUE TITLE
Overdownload?

### ISSUE THREAD

**Issue by northvector** [persepolisdm/persepolis#1028]
**System Details:**
* Operating System: Windows 11 x86
* Persepolis Version: 5.0.1

![image](https://github.com/user-attachments/assets/f89e6cc5-25de-42a4-82a2-30185475a863)

**Issue Description and steps to reproduce:**
Download percentage goes over 100% and it just downloads nothing
stopping and resuming fixes the problem

**Comment by alireza-amirsamimi** [comment]
Hi
Thanks for reporting this issue. Can you share your link?

**Comment by northvector** [comment]
[Part 3](https://dl5.downloadha.com/hosein/Game/November2023/10/Repack/Days.Gone.v1.07-FitGirl_www.Downloadha.com_.part3.rar)
[Part 4](https://dl5.downloadha.com/hosein/Game/November2023/10/Repack/Days.Gone.v1.07-FitGirl_www.Downloadha.com_.part4.rar)
[Part 5](https://dl5.downloadha.com/hosein/Game/November2023/10/Repack/Days.Gone.v1.07-FitGirl_www.Downloadha.com_.part5.rar)

**Comment by alireza-amirsamimi** [comment]
This bug has been fixed. Thanks for reporting.
