### ISSUE TITLE
Fedora repository is outdated

### ISSUE THREAD

**Issue by Ali-ABL** [persepolisdm/persepolis#1029]
**System Details:**
* Operating System: GNU/Linux
* Distro(For GNU/Linux and BSD users): Fedora 40
* Desktop Environment(For GNU/Linux and BSD users): KDE
* Persepolis Version: 4.1.0-3
* How do you install Persepolis? (Repositories, source, ...) dnf

**Issue Description and steps to reproduce:**
Persepolis hasn’t received updates in Fedora’s official repositories for quite some time, with the latest available version being 4.1.0-3.

**Comment by alireza-amirsamimi** [comment]
Hello
Please check this [issue](https://github.com/persepolisdm/persepolis/issues/1004).
