### ISSUE TITLE
Fusion Style UI Scaling Issue in Persepolis v5.0.1

### ISSUE THREAD

**Issue by Panahifarah** [persepolisdm/persepolis#1031]
**System Details:**
- **Operating System**: Arch GNU/Linux
- **Distro**: Arch Linux
- **Desktop Environment**: GNOME
- **Persepolis Version**: v5.0.1
- **Installation Method**: AUR

**Issue Description**:  
When using the **Fusion** style in Persepolis v5.0.1, the interface doesn't scale properly. In contrast, other styles, such as the **System** style, work as expected. The scaling issue causes certain UI elements to appear misaligned or incorrectly sized, which affects the overall user experience.

I’ve attached screenshots for reference:
- **Fusion style issue**:  
  ![Screenshot From 2024-10-02 21-01-15](https://github.com/user-attachments/assets/d8ea4276-f901-407b-a6c4-67707fa8750c)
  
- **System style (correct)**:  
  ![Screenshot From 2024-10-02 21-17-08](https://github.com/user-attachments/assets/929a0013-ee5e-4d83-be30-1a73430e4b26)

**Steps to Reproduce**:
1. Launch Persepolis.
2. Switch the interface style to **Fusion**.
3. Notice the scaling issues in the UI.

Are there any known workarounds for this, or is there a fix planned in future releases?

Thank you for your time and assistance!

**Comment by alireza-amirsamimi** [comment]
Hello
Thanks for reporting.  "System" style and "Fusion" style are not suitable for GNOME. Please install this package from AUR and select "Adwaita" style.
`yay -S adwaita-qt6`

If you want to use Fusion style, change font size from preferences window.

**Comment by thenebular** [comment]
Hello,

I've just installed version 5.0.1 on Windows 10 Pro 22H2 19045.4780 and I am having the exact same issue with Fusion. Also the styles Windows, Windows Vista, and Windows 11 look exactly the same as System.

**Comment by alireza-amirsamimi** [comment]
> Hello,
> 
> I've just installed version 5.0.1 on Windows 10 Pro 22H2 19045.4780 and I am having the exact same issue with Fusion. Also the styles Windows, Windows Vista, and Windows 11 look exactly the same as System.

hello
Thanks for reporting. From edit menu select preferences. In preferences window select and set the font size. It's fix the issue.

**Comment by itskazemk** [comment]
I have done but it has font and scaling size.
i have tried restarting app or windows but it's not working correctly (theme and style i mean)
![image](https://github.com/user-attachments/assets/2e23bac8-59cb-4dbb-8f0b-8a5ca97502dc)

**Comment by itskazemk** [comment]
it is Fusion theme issue.
![image](https://github.com/user-attachments/assets/cfac2196-6055-48b2-bd12-f6a3b4fdf369)

**Comment by itskazemk** [comment]
still, it has styling issues.
![image](https://github.com/user-attachments/assets/9bb207fd-acb5-4e4b-bed1-293856596c79)

**Comment by alireza-amirsamimi** [comment]
I think the font size issue is solved with this [commit](https://github.com/persepolisdm/persepolis/commit/472c9492a267704db5045403f2d64b84d119e23e). If it is possible for you, test it and let me know.
