### ISSUE TITLE
FYI: upgrading Persepolis from v. 4.3.0 to 5.0.1 under Debian and derivatives

### ISSUE THREAD

**Issue by Sadi58** [persepolisdm/persepolis#1037]
This upgrade just came in under Debian Trixie, but apt package management system got its dependencies wrong it seems, requiring removal of pipewire audio system.
![persepolis-synaptic](https://github.com/user-attachments/assets/0658620a-12a9-4675-8e69-49a4c25a945b)

**Workaround:**

1. Manually install the new package `python3-persepolis-lib` (e.g. `sudo apt install python3-persepolis-lib`)
2. Download `https://github.com/persepolisdm/persepolis/releases/download/5.0.1/persepolis_5.0.1.0_all.deb`
3. Manually install it, with no additional requirements like installing and/or removing any other package (e.g. `sudo dpkg -i persepolis_5.0.1.0_all.deb`)

**Comment by alireza-amirsamimi** [comment]
Hello
Thank you for reporting. Is there a problem with the version that is in the [official Debian repositories](https://packages.debian.org/trixie/persepolis)?

**Comment by mostafaasadi** [comment]
Hi 
this is the dependency of persepolis release deb 
` python3 (>= 3.8), libqt5svg5 (>= 5.11), python3-pyqt5 (>= 5.11), libnotify-bin (>= 0.7), python3-setproctitle (>= 1.1), python3-urllib3 (>= 1.25), python3-requests (>= 2.20), python3-psutil (>= 5.5), adwaita-qt (>= 1.0), yt-dlp (>= 2022.03.08), ffmpeg (>= 7:4.1), sound-theme-freedesktop (>= 0.8), python3-pyqt5.qtsvg (>= 5.11)`
and we don't need pulseaudio, also according to your screenshot you are going to install aria2, that also we don't have it in this version.
some thing is wrong with the package that downloaded.

**Comment by Sadi58** [comment]
@mostafaasadi Yes, I also checked the dependencies in the deb file from the Debian repositories, and couldn't see anything that would result in such an odd situation. I don't have any software skills to understand why this happened. So I thought I should better report it here together with the workaround which might also be useful for others that might face the same problem.

**Comment by mostafaasadi** [comment]
thank you for reporting
would you please tell me the output of `md5sum` command for that file you try to install with dpkg?

**Comment by Sadi58** [comment]
@mostafaasadi It seems there's a confusion: the file manually downloaded from here, and installed with `dpkg` (or another deb package installer) locally works just fine.
The problem arises when I try to install it from the official Debian Testing repositories (e.g. via Synaptic Package Manager). When I try to install it in that way, I get the prompt in the screenshot above, and I give up, because I don't want to mess with the audio system, before I can choose to "Download package only" without installing/removing any packages. That's why I can't run `md5sum` command for that file I try to install - which you might be in a better position to check.

**Comment by mostafaasadi** [comment]
it seems because of enabling testing repo your dependency tree faced with conflicts, so when you try to install a package with same name you get these dependencies, so you can install perspolis from testing repo (that i recommand) or from the file

**Comment by Sadi58** [comment]
@mostafaasadi I haven't **enabled** testing repo; this is the only repo I use, because I use Debian Trixie. There's no other package with the **same name**. This occurred when I was trying to install persepolis from testing repo. Only after facing such an odd situation, I gave up, and downloaded the deb file from GitHub, which installed just fine.

**Comment by mostafaasadi** [comment]
so it's fine now?

**Comment by Sadi58** [comment]
@mostafaasadi Yes, it's working fine after giving up on Debian testing repositories, and using the deb file downloaded from here.
I just tried once again; removed persepolis, and tried installing it via Synaptic Package Manager, but I had the same problem. So, I chose manual installation again.
