### ISSUE TITLE
can't work with GUI components, not clickable 

### ISSUE THREAD

**Issue by elogikalaf** [persepolisdm/persepolis#1039]
* Operating System: linux
* Distro (For GNU/Linux and BSD users): fedora 40
* Desktop Environment (For GNU/Linux and BSD users): gnome 46 on wayland
* Persepolis Version: 5.0.1
* How do you install Persepolis? source

after removing persepolis version 4, and installing the new version from [source](https://github.com/persepolisdm/persepolis/wiki/git-installation-instruction) I can't click some gui components such as file, edit, help and etc. all options in the related pic are not clickable.
![image](https://github.com/user-attachments/assets/844adaf4-35a4-4a02-aaf0-85c3cde2d3cd)

**Comment by alireza-amirsamimi** [comment]
Hello
Thanks for reporting. So far, none of the users using GNOME and Wayland have reported the same problem. I will have to test on GNOME and Wayland and let you know.

**Comment by elogikalaf** [comment]
Thanks!
I'd be happy to help you with the testing however I can.

**Comment by alireza-amirsamimi** [comment]
Please try other styles. For example, adwaita style is the best style for gnome. You can change the style from the preferences window. You can install adwaita style.
`  sudo dnf install adwaita-qt`

**Comment by elogikalaf** [comment]
I just tried xorg and the issue was resolved there so I guess it's a wayland problem
and I switched the style to adwaita-dark and adwaita in xorg, but the menu still doesn't work when I boot in wayland (preferences isn't accessible in wayland as it's part of the options that aren't clickable). 
also the adwaita-qt package isn't available in fedora repos so I installed adwaita-qt6 and adwaita-qt5. is that an issue?

**Comment by alireza-amirsamimi** [comment]
adwaita-qt6 is ok!

**Comment by elogikalaf** [comment]
alright then
should I test anything else?

**Comment by alireza-amirsamimi** [comment]
Please run persepolis from terminal and see if there is an error?

**Comment by elogikalaf** [comment]
no, no errors.

**Comment by alireza-amirsamimi** [comment]
So, I Think it's related to Gnome and Wayland in fedora.
