### ISSUE TITLE
[better UI] sort کردن لیست

### ISSUE THREAD

**Issue by Monirzadeh** [persepolisdm/persepolis#105]
در صورت امکان sort کردن لینک ها در برنامه با کلیک بر روی عناوین آنها در پنجره ااصلی را به برنامه اضافه کنید
با تشکر

**Comment by alireza-amirsamimi** [comment]
سلام
چون برای همه عناوین حالت 
sort
نیاز نبود این کار رو نکردم
سپاس از اینکه مطرح کردید

**Comment by Monirzadeh** [comment]
برای چند مورد مثل تاریخ ها یا
status
 یا درصد بسیار کاربردی است البته نمیدانم این 
sort
شدن روی ترتیب دانلود هم موثر است یا خیر

**Comment by alireza-amirsamimi** [comment]
@Monirzadeh بله
مثلا در یک صف میتونید قبل از شروع دانلود ، صف رو به ترتیب سایز مرتب کنید و دانلود کنید
