### ISSUE TITLE
[bug] بازشدن پنجره اصلی در زمان ارسال لینک به فایرفاکس[better UI]

### ISSUE THREAD

**Issue by Monirzadeh** [persepolisdm/persepolis#106]
سلام
در صورت بسته بودن برنامه و ارسال لینک از فایرفاکس ابتدا پنجره اصلی برنامه سپس پنجره اضافه کردن لینک جدید باز میشود
در صورت کمینه بودن برنامه یا حضور برنامه در panel تنها پنجره اضافه کردن لینک نمایش داده میشود
بهتر است در زمان ارسال لینک از مرورگر درصورت بسته بودن برنامه پنجره اصلی نمایش داده نشود
موفق باشید خدانگهدار
ubuntu 16.04 - unity - persepolis 2.3.2

**Comment by alireza-amirsamimi** [comment]
سلام
سپاس از پیشنهاد شما

**Comment by JafarAkhondali** [comment]
I think this is fixed now.
Please open a new issue if the problem exists within new version.
