### ISSUE TITLE
درگ/دراپ و انتخاب همزمان چند آیتم برای اضافه کردن به لیستی خاص

### ISSUE THREAD

**Issue by LinArcX** [persepolisdm/persepolis#108]
علی جان این یه درخواست هست .
فانکشنلایتیش به واسطه 
select multiple items
توسط شما پیاده سازی شده.اما حس میکنم چندان یوزرفرندلی نیست.یعنی کاربر بیشتر تمایل داره با نگه داشتن دکمه شیفت و انتخاب چند آیتم، اونا رو به یه لیست خاص ازدانلود ها بفرسته یا شاید دلش بخواد با عمل درگ کردن اونا رو بفرسته تو لیست.
به نظرم این موارد پیاده سازی بشن خیلی کاربر پسند تر میشن.
هر چند از زحماتت خیلی تشکر میکنم.همواره کردم.و بازم خواهم کرد.

**Comment by alireza-amirsamimi** [comment]
ممنونم از پیشنهادت
ولی این حالت کارایی بیشتری داره
ینجوری کاربر مثلا میتونه توی یه لیست صد تایی  ۱۰ تا دانلود رو که نمیخوات بدون هیچ نظمی انتخاب کنه و پاک کنه یا اصلا به دسته دیگه ای بفرسته
اینجوری انعطاف پذیری بیشتری در برنامه وجود داره
