### ISSUE TITLE
دانلود اتوماتیک (هنگام چپ/کلیک) توسط پرسپولیس در کروم و کرومیوم

### ISSUE THREAD

**Issue by LinArcX** [persepolisdm/persepolis#109]
تو فایرفاکس همه چی گل و بلبله.البته به لطف فلش/گات.
 منظورم زمانی هست که شما رو یه لینکی کلیک میکنید و قصد دانلودشو دارین.اونجا یه پنجره ای بهتون نشون داده میشه و  می تونید دانلود منیجرتونو انتخاب کنید.حتی بهتون پیشنهاد میده که میخواین این تصمیم تونو واسه سری های بعد به خاطر بیارم.که خوب خیلی فوق العاده ست.
الان تو افزونه کرومی که زحمت کشیده شده واسش حس میکنم جای این ویژگی خالی هست.
یعنی کاربر حتما باید راست کلیک کنه و گزینه 
download with persepolis
رو انتخاب کنه.
اگر یادش نمونه این قضیه رو،کنترل دانلود به کروم سپرده میشه و خوب گاهی وقتا اذیت کننده ست.
نمایش اون دیالوگ امکان پذیر هست پیاده سازی ش؟

**Comment by alireza-amirsamimi** [comment]
سلام
کاش پیشنهادات مربوز به افزونه رو توی مخزن خودش بنویسی که دوستمون که مسئول توسعش هستند رسیدگی :)کنند
https://github.com/persepolisdm/persepolis-chrome-wrapper
