### ISSUE TITLE
مشکل عدم نمایش آیکون های برنامه 

### ISSUE THREAD

**Issue by ghost** [persepolisdm/persepolis#11]
با سلام 

تصاویر مربوط به آیکون های برنامه نمایش داده نمیشود 

Mint 18 Cinamon  (Sarah)

![screenshot from 2016-07-18 13-18-18](https://cloud.githubusercontent.com/assets/17552516/16910084/be356d06-4ceb-11e6-903e-81df9c6bd600.png)

**Comment by alireza-amirsamimi** [comment]
سلام
برنامه رو به وسیله نصاب نصب کنید و از طریق منوی برنامه ها اجرا کنید

**Comment by ghost** [comment]
از طریق نصاب چجوریه ؟

از طریق همین کدی که گذاشتید نصب کردم

```
$ cd
$ cd /tmp
$ wget -O persepolis.tar.gz https://github.com/alireza-amirsamimi/persepolis/archive/master.tar.gz
$ tar  --overwrite-dir -xf persepolis.tar.gz
$ cd persepolis-master
$ sh install
```

**Comment by alireza-amirsamimi** [comment]
عجیبه روی سینامون با آرچ مشکلی نداره
برنامه رو دوباره نصب کنید شاید درست نصب نشده
خروجی این دستور رو به من بدید
`ls /usr/share/persepolis`
`ls /usr/share/persepolis/Archdroid-Blue/`

**Comment by ghost** [comment]
ls /usr/share/persepolis

`
about.py               icon.png                     progress.py
addlink.py             mainwindow.py                progress_ui.py
addlink_ui.py          mainwindow_ui.py             properties.py
Archdroid-Blue         newopen.py                   setting.py
Archdroid-Red          notifications                setting_ui.py
bubble.py              palettes.py                  shutdown_script
download.py            persepolis-download-manager  shutdown_script_root
icon_notification.png  play.py
`

ls /usr/share/persepolis/Archdroid-Blue/

`
about.svg   minimize.svg   play.svg         stop_all.svg
add.svg     ok.svg         preferences.svg  stop.svg
exit.svg    pause_all.svg  remove.svg       trash.svg
folder.png  pause.svg      setting.svg      window.svg
`

**Comment by alireza-amirsamimi** [comment]
برنامه بدون مشکل نصب شده
این مشکل مربوط به لینوکس مینت هست و بقیه توزیع ها مشکلی ندارند
لینوکس مینت رو گذاشتم دانلود بشه
توی ماشین مجازی نصبش میکنم ببینم چه جوری میشه این مشکل لینوکس مینت رو حل کرد و اینجا اطلاع میدم
ممنون از همکاریت

**Comment by alireza-amirsamimi** [comment]
زیر سر توسعه دهنده های مینت هست قضیه :|
اجازه نمیده توی کیوت آیکن داخل پوشه برنامه تعریف کنم
روش کار میکنم و نهایتا یه تم سیستم به برنامه اضافه میکنم برای مینت

**Comment by alireza-amirsamimi** [comment]
باگ مربوط به لینوکس مینت هست . به تیم لینوکس مینت اطلاع دادم . امیدوارم سریعتر حلش کنند

**Comment by alireza-amirsamimi** [comment]
برای حل مشکل نشان ندادن آیکن ها در لینوکس مینت این بسته رو نصب کن حل میشه :)

`sudo apt install libqt5svg5`

**Comment by ghost** [comment]
ممنون ... حل شد
