### ISSUE TITLE
[Question] Windows support

### ISSUE THREAD

**Issue by Kristinita** [persepolisdm/persepolis#110]
Do you have plans to support Windows operating system? aria2 is cross-platform utility, with Windows compatible. Thanks for nice download manager!

**Comment by alireza-amirsamimi** [comment]
@Kristinita Hello
Yes , We have plans for supporting Windows and BSD :)

**Comment by smaragdus** [comment]
**@alireza-amirsamimi** 
I would appreciate a Windows version very much.

**Comment by alireza-amirsamimi** [comment]
@smaragdus 
We will publish Windows version , when we release version 2.4 (our next release) . so please stay tuned :)

**Comment by smaragdus** [comment]
**@alireza-amirsamimi**

For me Linux is definitely the OS of the future (I will never update to Windows 10) but Windows is still my main OS right now (Windows 8).

My default download manager is still **Free Download Manager** (the classic edition- latest version- 3.9.7 Build 1632) and I do not plan to use the latest "modern" version 5 which for me is terrible. The classic edition is rarely updated and has problems with some downloads. I have also tried **EagleGet** and **Xtreme Download Manager** but I do not like their interface. **AWGG** is decent but it is most likely abandoned- it hasn't been updated for more than a year. So a Windows version of Persepolis Download Manager would be great- under Windows there is not a great choice of free, open-source and cross-platform download managers.

I have one wish about the future Windows release of **Persepolis Download Manager**- a portable version- either a dedicated portable archive, or a portable mode installation, or a command line switch (for example- "pdm.exe --portable", "pdm.exe -portable", "pdm.exe /portable", etc) which forces **Persepolis Download Manager** to save data and settings in program folder not using the Windows registry and AppData and thus being fully portable.

For me a portable Windows version of **Persepolis Download Manager** would have an advantage- an option to use it from external drives with all its data and settings on other machines without leaving any traces and junk behind. So I think that a future portable version of **Persepolis Download Manager** for Windows will make the program more flexible and more universal.

**Persepolis Download Manager** looks very nice so I feel excited about a Windows version and I will definitely follow this project.

Best regards and happy coding! :)

**Comment by dimqua** [comment]
Can someone please close the issue?
