### ISSUE TITLE
Select

### ISSUE THREAD

**Issue by NarimanMokarami** [persepolisdm/persepolis#111]
سلام خدا قوت
لطفا تنظیمات سلکت مالتی آیتم رو هم بالا ببرین خیلی ممنون میشم 
مثلا سلکت کنه فقط اونایی که کامل شدن یا سلکت کنه اونایی که ایستادن.
و اینکه بشه بعد از سلکت کردن  همه دانلود رو ادامه داد مثل وقتی که همه رو سلکت می کنی و پاک کردن رو میزنی.
خیلی خیلی ممنون بابت رایگان قرار دادن نرم افزار تون.
یا حق

**Comment by alireza-amirsamimi** [comment]
@sat3007 سلام
ممنونم که خبر دادید
باگ رو بر طرف کردم
به زودی آپدیت خواهیم داد

**Comment by alireza-amirsamimi** [comment]
سلام 
آپدیت کنید باگ برطرف شد
