### ISSUE TITLE
‫عدم امکان resume برای چند queue

### ISSUE THREAD

**Issue by Hitaro** [persepolisdm/persepolis#113]
‫اگر چند تا خط دانلود در وضعیت stoppped داشته باشیم و بخواهیم همه رو با هم فرمان دانلود بدیم، این کار با کلیک راست و زدن گزینه resume انجام نمیشه و فقط برای یکی از متوقف شده ها شروع می کنه به دانلود

‫در حالی که باید همه انتخاب‌شده‌ها رو resume کنه

Version: 2.3.2
OS: Linux

**Comment by alireza-amirsamimi** [comment]
سلام
سپاس از پیشنهاد شما
اکیدا توصیه میکنم برنامه رو آپدیت کنید
نسخه ۲.۳.۲ پرسپولیس در زمانبندی صف دانلود اشکال دارد

**Comment by JafarAkhondali** [comment]
Please open a new issue if the problem exists within new version.
