### ISSUE TITLE
عدم پیروی فونت برنامه از تنظیمات پیش فرض دسکتاپ

### ISSUE THREAD

**Issue by Hitaro** [persepolisdm/persepolis#114]
‫توی KDE Plasma راحت می‌شه از تنظیمات (Settings)، فونت بخش‌های مختلف رو تنظیم کرد و برنامه‌ها ازش پیروی می‌کنند. اما در پرسپولیس وقتی چک کردم فونت روی ۹ بود در حالی که کوچک ترین سایز تنظیم شده برای فونت‌های سیستمم ۱۲ هستش.

**Comment by alireza-amirsamimi** [comment]
سلام
میتوانید از تنظیمات برنامه فونت و سایز دلخواه خود را انتخاب کنید

**Comment by Hitaro** [comment]
اون که آره

اما خوب منطقیه که پیش‌فرضش تنظیمات سیستم من باشه نه پیش فرضی فیکس شده از قبل
‪‫یعنی بعد از نصب، در هنگام اجرا، تنظیمات فونت سیستم من رو بخونه، مثل برنامه dolphin و غیره

**Comment by alireza-amirsamimi** [comment]
من سوالتون شما را اشتباه متوجه شدم
سپاس از پیشنهاد شما

**Comment by alireza-amirsamimi** [comment]
سلام پیشنهاد شما رو اضافه کردم
در نسخه جدید برنامه در تنظیمات برنامه میتونید تیک مربوط به فونت رو بردارید
موفق باشید
