### ISSUE TITLE
شخصی‌سازی سربرگ‌ها

### ISSUE THREAD

**Issue by Hitaro** [persepolisdm/persepolis#116]
![qqqqqqqq](https://cloud.githubusercontent.com/assets/18015032/22180533/ac402f20-e087-11e6-90bd-abbea645ac45.png)

من نمی‌خوام بعضی از این سربرگ‌هایی که توی عکس بالایی می بینید، باشه و می‌خوام برشون دارم اما با کلیک راست روی سربرگ‌ها امکانی برای حذف/افزودن نیست
از طرفی می‌خوام بتونم به چپ و راست جابجاشون کنم

**Comment by alireza-amirsamimi** [comment]
سپاس از پیشنهاد شما

**Comment by alireza-amirsamimi** [comment]
<div dir="rtl">
پیشنهاد شما رو در نسخه ۲.۴ اضافه کردم . شما میتونید از منوی Edit وارد پنجره Preferences بشید و از تب column customization تیک ستونهایی که دوست ندارید دیده بشند رو بردارید . و در ضمن در این نسخه عرض ستون ها رو اگر تغییر بدید ، اندازش ذخیره میشه.
آپدیت بفرمایید. سپاس از پیشنهاد شما :)
