### ISSUE TITLE
راهی برای عدم نمایش پنجره اضافی دانلود؟

### ISSUE THREAD

**Issue by Hitaro** [persepolisdm/persepolis#117]
‫دانلودی رو که با پرسپولیس شروع می‌کنم و یا صفی رو resume می‌کنم، بک پنجره جدید باز می‌کنه که نوار پیشرفت داره و...، اما این پنجره اضافی برای من آزار دهنده است و همین‌که در صفحه اصلی برنامه جزییات نمایش داده بشه برام کافیه. ‫آیا می‌تونم نمایش این پنجره اضافی رو که به سبک IDM است، غیرفعال کنم؟

‫در واقع اگر مثل DownThemAll، نوار پیشرفت در صفحه اصلی برنامه هم باشه خیلی خوبه. مثلا در ستون Persentage، در پس‌زمینه عددی که نمایش می‌ده، نواری شروع به پر شدن کنه

**Comment by alireza-amirsamimi** [comment]
سلام
من مدتهاست ویندوز ندارم و سالهاست آی دی ام استفاده نکردم
ولی اگر سوالتون این هست که چگونه پنجره پیشرفت دانلود نمایش داده نشه میتونید از منوی
edit
وارد
preferences
بشید وتیک گزینه
show download's progress window 
را بردارید و البته دقت کنید که گزینه ای مشابه روی ابزار آیکن برنامه  در پنجره اصلی برای نمایش یا عدم نمایش این پنجره در هنگام دانلود وجود دارد. در ضمن بستن این پنجره حین دانلود خللی در دانلود شما به وجود نمی آورد.
