### ISSUE TITLE
It does not support for tray facility | Plasma KDE

### ISSUE THREAD

**Issue by Hitaro** [persepolisdm/persepolis#118]
‫در دسکتاپ پلاسما، برنامه رو که می‌بندیم، در tray نمی‌ره و یک‌ضرب Exit می‌شه!

‫خب من نمی‌خوام برنامه در status bar دسکتاپ باشه و باید بره اون پشت-مشت‌ها کارشو انجام بده ):

‫تنظیمی هم نتونستم براش پیدا کنم که بشه بهش گفت با بسته شدن (close) به tray بره، نه این‌که کلا Quit بشه.

Version: 2.3.2

**Comment by alireza-amirsamimi** [comment]
سلام
در حال حاضر برنامه این امکان رو ندارد و انشالله در نسخه های جدیدتر اضافه خواهد شد
در ضمن نسخه برنامه شما قدیمی هست
توصیه مکینم به روز کنید
برای حل مشکلتون میتوانید گزینه 
minimize to system tray
را از نوار ابزار برنامه در پنجره اصلی یا از منوی
view
انتخاب نمایید
