### ISSUE TITLE
نمایش حجم فایل دریافتی در صفحه اضافه کردن لینک

### ISSUE THREAD

**Issue by Monirzadeh** [persepolisdm/persepolis#119]
با سلام
لطفا نمایش حجم فایل در خواستی در پنجره اضافه کردن لینک را به برنامه اضافه کنید
در حال حاظر برنامه فقط بعد از اضافه کردن کامل لینک حجم را نمایش میدهد

**Comment by alireza-amirsamimi** [comment]
@Monirzadeh سلام
قبل از وارد کردن لینک برنامه نمیتواند حجم را حدس بزند :) بعد از وارد کردن لینک هم برای این کار باید یک پنجره تایید لینک مثل آی دی ام به وجود آورد ، که به نظر من اضافه است و عملیات دانلود را به تاخیر میاندازد .

**Comment by Monirzadeh** [comment]
متوجه قسمت اول نشدم
مثلا وقتی با 
flashgot 
لینکی به نرم افزار فرستاده میشود نیازی به تایید نیست

**Comment by alireza-amirsamimi** [comment]
@Monirzadeh آها منظورتون رو حالا متوجه شدم
پیشنهاد خوبی هست
سپاس

**Comment by alireza-amirsamimi** [comment]
<div dir="rtl">

سلام پیشنهاد شما رو در نسخه ۲.۴ اضافه کردم. آپدیت کنید متوجه میشید :)
سپاس از پیشنهادتون
