### ISSUE TITLE
افزودن open directory

### ISSUE THREAD

**Issue by Mr-undead** [persepolisdm/persepolis#12]
افزودن گزینه 
open directory
 به منوی باز شده به وسیله کلیک راست برای دانلود های کامل شده تا کاربر مستقیما به پوشه دانلود اون فایل منتقل بشه

**Comment by msajadi832** [comment]
و افزودن یه 
open file 
به همون منویی که فرمودن
و همچنین با دابل کلیک روی اون مورد کامل شده، فایلش با برنامه پیش فرض سیستم عامل باز شه

ممنون

**Comment by alireza-amirsamimi** [comment]
ممنونم از پیشنهادات خوب
حتما توی ورژن های آینده اضافه میکنم :)
