### ISSUE TITLE
فریز شدن برنامه و دانلود شدن فایل در بکگراند 

### ISSUE THREAD

**Issue by Mr-undead** [persepolisdm/persepolis#123]
سلام به یه مشکل برخوردم گفتم گزارش کنم. پرسپولیس گاه گاهی وقتی که لینک دانلود بهش میدم عملیات دانلود را شروع نمیکنه و 
waiting
مینویسه. وقتی که روی دکمه های رابط کاربری کلیک میکنم. هیچ کدوم کار نمیکنه حتی برنامه بسته هم نمیشه تا زمانی که پیغام بیاد و 
end procces
انتخاب بشه . در این حالت ظاهرا برنامه بسته شده ولی همچنان برنامه در بکگراند در حال اجرا است. نکته جالب این هست که اگر به دایرکتوری موقتی که برای دانلود برنامه ازش مراجعه کنم میتونم ببینم فایل دانلودی داره کامل تر میشه تا اینکه فابل کامل دانلود میشه ولی پرسپولیس این فایل را به دایرکتوری نهاییش منتقل نمیکنه . خلاصه مجبور هستم با 
killall persepolis
از خجالت پرسپولیس در بیام. و برنامه را دوباره اجرا کنم.

**Comment by alireza-amirsamimi** [comment]
ممنون از پیغامی که دادی
برای چه لینکی اینطور میشه یا در چه شرایطی
آخه تا اینو ندونم نمیتونم برطرف کنم مشکل رو

**Comment by Mr-undead** [comment]
اگر مجدد تکرار شد جزئیات را میگم

**Comment by alireza-amirsamimi** [comment]
@behroozramezani سپاس :)

**Comment by Monirzadeh** [comment]
هرد دو مورد را امروز تجربه کردم
در مورد لیست دانلود بود که درصد پیشرفت افزایش پیدا نمیکرد با توقف یا حتی بستن برنامه هم مشکل برطرف نشد
تا جایی که من متوجه شدم در این شرایط 
aria2c 
از پرسپولیس دستور نمیگیرد و کار دانلود را انحلم میدهد
نهایتا با
kill aria2c
مشکل حل شد
در مورد مشکل دوم اگر دانلود را در محلی ذخیره کنید مثلا یکی از درایورهای
mount 
شده
بعد از کمی پیشرفت دانلود سیستم را ریست کنید و بدون 
mount 
کردن آن درایو اقدام یه دانلود کنید پروسه دانلود به طور کامل صورت میگیرد ( فایل در مسیر موقت پرسپولیس ذخیره میشود) بعد از اتمام دانلود چون برنامه دسترسی به درایو برای ذخیره سازی ندارد فایل در همان مسیر موقت باقی میماند در نتیجه فایل را نمیتوانید از داخل پرسپولیس مستقیم اجرا کنید
به طور خلاصه پرسپولیس مرحله ای برای کنترل انتقال فایل به مسیر نهایی ندارد

**Comment by alireza-amirsamimi** [comment]
خب کاربر باید حواسش باشه و پارتیشنش رو مونت کنه و بعد استفاده کنه
 :)
البته باید یه پیغام خطا براش اضافه کنیم
ممنون که خبر دادی
@Monirzadeh

**Comment by JafarAkhondali** [comment]
Please open a new issue if the problem exists within new version.
