### ISSUE TITLE
افزودن sort by

### ISSUE THREAD

**Issue by Sosha1996** [persepolisdm/persepolis#13]
با سلام امیدوارم خوب باشید.

لطفا به این بخش روی گزینه ها قابلیت **sort by** رو اضافه کنید.
![2016-07-18 19-43-59](https://cloud.githubusercontent.com/assets/16008585/16919705/03956804-4d20-11e6-866e-0c5246999fc6.png)

با تشکر.

**Comment by alireza-amirsamimi** [comment]
ممنونم
روش کار میکنم
