### ISSUE TITLE
محدودیت سرعت

### ISSUE THREAD

**Issue by efazati** [persepolisdm/persepolis#136]
من یک کیو ساخته ام و این کیو را استارت کرده ام
حالا یک محدودیت ست میکنم
و اعمال میشود 
ولی وقتی فایل دوم شروع به دانلود میکند. محدودیت نادیده گرفته میشود و با تمام سرعت دانلود میکند

![screenshot_2017-02-08_12-51-23](https://cloud.githubusercontent.com/assets/1132647/22731195/09d740d6-edff-11e6-882b-f71f0c8932a2.png)

Ubuntu 16.04
i3wm
2.3.3

**Comment by alireza-amirsamimi** [comment]
سپاس از اینکه اطلاع دادید :)
انشالله در ورژن جدید مشکل رو حل میکینم

**Comment by alireza-amirsamimi** [comment]
سلام
سال نو مبارک
این باگ رو در این کامیت
[Commit](https://github.com/persepolisdm/persepolis/commit/27d0454423c437528dc0d4034751af6f46dff2aa)
درست کردم . سپاس از اینکه اطلاع دادید
در آپدیت بعدی این مشکل رو نخواهید دید
