### ISSUE TITLE
جلوگیری از یا اختیاری کردن ساختن زیرپوشه‌های دانلود

### ISSUE THREAD

**Issue by onrea** [persepolisdm/persepolis#137]
‫فایلی رو دادم پرسپولیس دانلود کنه و مشتی از پوشه های الکی مثل Compressed‏، ‏Videos‏، Documents و... رو توی پوشه Download سیستمم ساخته! آخه برای چی این پیش‌فرضه، کی این دوره-زمونه فایل‌های دانلودیش رو توی پوشه دانلود  دسته بندی می‌کنه ؟!

‫به هر حال، لطفا در اولین اجرا اجازه بدید کاربر از طریق یک Prompt Box بتونه یکسری از رفتارهای پرسپولیس رو به دلخواه خودش مشخص کنه و یا هر راه حل دیگه‌ای!

‫‫این‌که پوشه-پوشه بکنه آزار دهنده است. بعد از هر دانلود باید برم ۵ ، ۶ تا پوشه delete کنم

**Comment by alireza-amirsamimi** [comment]
@onrea سلام
بسیاری از نرم‌افزار های دانلود منجر این تقسیم بندی را دارند. و در ضمن در این دوره و زمانه بسیاری از کاربران ترجیح میدهند که فایل های بارگیری شده به شکل دسته بندی شده ذخیره شوند و پیشنهاد دسته بندی دانلود ها هم در ورژن یک پرسپولیس وجود نداشت و به پیشنهاد کاربران محترم اضافه شده است.
انشاالله گزینه ای را اضافه خواهیم کرد که اگر کسی نخواست این کار انجام نشود .
سپاس از پیشنهاد شما
موفق باشید

**Comment by aqmorisny** [comment]
i'm agree with @onrea

**Comment by alireza-amirsamimi** [comment]
سلام
پیشنهادتون رو به برنامه اضافه کردم
انشالله در آپدیت بعدی منتشر میشه
موفق باشید

**Comment by parsedarweb** [comment]
‫می خواستم در این مورد تاپیکی بزنم اما از قبل هست (:

Vesrsion: persepolis-2.4.2-1 (AUR)

‫یعد از اینکه نصب شد، تا اجرا کردم، اومد یه پوشه Downloads ساخت و بعد توی اون رو perspolise گذاشت و بعد توی Perspolise هم چندین پوشه ساخت

‫۱. ‫اما پوشه دانلودهای من، Downloads نبوده و در فایل ‎.config/user-dirs.dirs مسیر دیگه‌ای تعریف کرده بودم

‫۲. حالا اگر مورد یک رو هم اصلاح کنید، اما تیک ساختن subfolders پیش‌فرض فعاله و به محض اولین اجرای برنامه پوشه‌های کذایی رو می‌سازه و فرصت نمی‌ده بریم از تنظیمات غیرفعالش کنیم! کاش ساخت پوشه‌ها موکول به وقت دانلود بشه. ممکنه یکی هیچ وقت فیلم یا کلیپ دانلود نکنه که بنابراین نیازی هم به بودن پوشه Videos از اول کار برای این فرد نیست. این پوشه وقتی ساخته بشه که کاربر اولین ویدیوش رو دانلود می‌کنه. بقیه‌ای هم که کلا این فیچر رو نمی‌خوان ، فرصت می‌کنند برن غیرفعالش کنند
