### ISSUE TITLE
باز نشدن برنامه

### ISSUE THREAD

**Issue by Sosha1996** [persepolisdm/persepolis#14]
وقتی برنامه رو **minimize to system tray** می کنم، و اگر از **Launcher** و یا **bash** بخوام برنامه رو باز کنم برنامه باز نمیشه و فقط پیام میده که: _is still running!_
و بعضی از مواقع هم پیام نمیده.

اگر کاری کنید که برنامه مثل سایر برنامه های دیگه اگر توی **system tray icon** بود و ما از روی **Launcher** و یا **Bash** خواستیم اجراش کنیم باز بشه خیلی خوب میشه.

با تشکر!

**Comment by alireza-amirsamimi** [comment]
مدیونی اگه فکر کنی فهمیدم چی نوشتی:))
همه خط ها ریخته بهم
البته اگر خطای 
still running
رو دیدی
وبرنامه باز نبود از طریق ترمینال
kill
کن . این اتفاق موقعی رخ میده که برنامه درست بسته نشده باشه
