### ISSUE TITLE
Global menu problem

### ISSUE THREAD

**Issue by sarvad** [persepolisdm/persepolis#143]
Hi
I'm using Persepolisdm v2.4 alpha and Ubuntu 16.04.
When I choose **_minimize in system tray_** and then back, global menu disappeared.
After exit and restart Persepolisdm everything is OK.

Also, I don't know why there are two menus. 1) Global menu 2) Menu at the top-left corner
I think it is not necessary in Unity desktop environment.

Persepolisdm is an awesome download manager :+1: 
Good luck :)

**Comment by Alirezaies** [comment]
Thank you for using Persepolis and opening issue.
By global menu, do you mean the top menu in the unity bar? if so, I don't think that you may need global menu when Persepolis is minimized to system tray (minimizing to system tray is more likely to run Persepolis in background), 
are you suggesting any feature for next versions?

**Comment by sarvad** [comment]
@Alirezaies 
**1.**
![issue](https://cloud.githubusercontent.com/assets/10045681/22943402/b48eaa34-f302-11e6-9e2d-2ea2b5b31fe8.png)

**2.**
![two menus](https://cloud.githubusercontent.com/assets/10045681/22943622/6d6629c4-f303-11e6-940d-645f35d14ecc.jpg)

**Comment by alireza-amirsamimi** [comment]
Hello
Unity 7 global menu have weird problems with QT and it's unity's bug. When pyqt program's main window hided by hide method (minimizing to system tray icon) and then shown by show method , menu is disappeared!

I added menu 2 for solving this issue in unity . so user can use menu even after global menu disappeared.

I strongly suggest that to use our stable release . If you are ubuntu user you can use launchpad repository for installing persepolis. The github version is only suitable for testing and it's not stable.

**Comment by sarvad** [comment]
@alireza-amirsamimi 
You should mention this explanation about github version in [wiki](https://github.com/persepolisdm/persepolis/wiki/git_installation_instruction).
Anyway, I will install PersepolisDM from [releases section](https://github.com/persepolisdm/persepolis/releases).

Thanks a lot :)
