### ISSUE TITLE
کرش برنامه بعد از از سرگیری صف ناموفق

### ISSUE THREAD

**Issue by mojtaba-baghban** [persepolisdm/persepolis#144]
سلام
من چند تا فایل از آپلود بوی گذاشتم توی صف دانلود بعد از یک روز و به دلیل اینکه ظاهرا لینک دیگه معتبر نبود همه دانلودها شکست خورد که تا اینجا عادیه. اما به محض اینکه همون صف دانلود رو شروع میزنم با این ارر کرش میکنه:
Traceback (most recent call last):
  File "/usr/share/persepolis/mainwindow.py", line 2801, in startQueue
    self.toolBarAndContextMenuItems(current_category_tree_text)
  File "/usr/share/persepolis/mainwindow.py", line 2605, in toolBarAndContextMenuItems
    self.queuePanelWidget(category)
  File "/usr/share/persepolis/mainwindow.py", line 3071, in queuePanelWidget
    limit_status = self.queue_list_dict[str(category)].limit
AttributeError: 'Queue' object has no attribute 'limit'
fish: “persepolis” terminated by signal SIGABRT (Abort)

**Comment by alireza-amirsamimi** [comment]
سلام
سپاس از اینکه اطلاع دادید
مشکل رو بررسی خواهم کرد
فقط یک سوال
اگر صف دیگه ای هم اضافه کنید باز هم این مشکل وجود داره؟
از چه سیستم عاملی استفاده میکنید؟
چه جوری برنامه رو نصب کردید؟
ورژن برنامه شما چند هست؟

**Comment by mojtaba-baghban** [comment]
سلام
ببخشید اطلاعات ناقص دادم
این مشکل دیگه وجود نداره ولی چندین بار اتفاق افتاد.
من از آرچ استفاده میکنم و پرسپولیس رو از aur نصب کردم.
از آخرین ورژن حال حاضر یعنی 2.3.3

**Comment by alireza-amirsamimi** [comment]
ممنونم از اینکه اطلاع دادید
حتما بررسی خواهم کرد و در ورژن بعد انشالله رفع میشه

**Comment by aqmorisny** [comment]
pdm : 2.3.3
os : linux mint 18.1 cinnamon 64 bit
I have same problem after restart a queue program was crashed , please see the screen cast :
[screencast_persepolis_queue_crash_20170209_mp4.zip](https://github.com/persepolisdm/persepolis/files/802548/screencast_persepolis_queue_crash_20170209_mp4.zip)

**Comment by alireza-amirsamimi** [comment]
@aqamorisny 
سلام 
برنامه رو از ترمینال اجرا کنید و خطا رو بفرستید
سپاس

**Comment by aqmorisny** [comment]
@alireza-amirsamimi 
```
~ $ persepolis 
c4b2b82267c90bc8 Starts
None Starts
c4b2b82267c90bc8 stopped
c4b2b82267c90bc8 Starts
None Starts
c4b2b82267c90bc8 stopped
None Starts
None stopped
None stopped
Traceback (most recent call last):
  File "/usr/share/persepolis/mainwindow.py", line 2801, in startQueue
    self.toolBarAndContextMenuItems(current_category_tree_text)
  File "/usr/share/persepolis/mainwindow.py", line 2605, in toolBarAndContextMenuItems
    self.queuePanelWidget(category)
  File "/usr/share/persepolis/mainwindow.py", line 3071, in queuePanelWidget
    limit_status = self.queue_list_dict[str(category)].limit
AttributeError: 'Queue' object has no attribute 'limit'
Aborted

```

**Comment by alireza-amirsamimi** [comment]
I fixed this issue before but I forgot to close the issue.
Thanks for reporting :)
