### ISSUE TITLE
افزودن open و یا open as

### ISSUE THREAD

**Issue by Sosha1996** [persepolisdm/persepolis#15]
با سلام

جای خالی این قابلیت که از توی خود برنامه باز کنیم هم به شدت احساس میشه

با تشکر

**Comment by alireza-amirsamimi** [comment]
انشالله اضاقه میکنم
مرسی :)

**Comment by LinArcX** [comment]
علیرضا جان یه نکته.پیشنهاد میکنم تا زمانی که تسک ها ریزالو نشدن کلوزشون نکن.اینجوری راحت تر میشه پیگیری کرد چه کارهایی انجام شدن یا چه کارهایی انجام نشدن

**Comment by alireza-amirsamimi** [comment]
باگ ها رو نمیبندم :)
پیشنهاد ها رو یادداشت میکنم و میبندم
چون اینجوری شلوغ میشه نمیفهمم دارم چیکار میکنم :))

**Comment by dinamycam** [comment]
خب اینجوری برای من که نمیدونم چه فیچر هایی اضافه شدن یا نشدن سخت میشه.
شاید یکی دیگه هم بخواد کمک کنه.بعد باید هم بین مشکلات close ها بگرده هم open.
