### ISSUE TITLE
black background convert to gray, Linux Mint 18.1 Cinnamon 64-bit

### ISSUE THREAD

**Issue by aqmorisny** [persepolisdm/persepolis#151]
background changed for unknown reason screen shots added .
![screenshot from 2017-02-27 04-36-03](https://cloud.githubusercontent.com/assets/20615529/23345666/38c02604-fca7-11e6-80b1-4776d9662b7b.png)
![screenshot from 2017-02-27 04-29-50](https://cloud.githubusercontent.com/assets/20615529/23345667/38c71bb2-fca7-11e6-8109-0c1581821a6b.png)

**Comment by alireza-amirsamimi** [comment]
Hello
Perhaps restarting persepolis solve the problem.

**Comment by JafarAkhondali** [comment]
Please open a new issue if the problem exists within new version.
