### ISSUE TITLE
Remove download in qeue doesn't work , multiple selection using ctrl or shift  doesn't work

### ISSUE THREAD

**Issue by aqmorisny** [persepolisdm/persepolis#152]
please see the screencast:
[Screencast_2017-02-27_05_24_07_mp4.zip](https://github.com/persepolisdm/persepolis/files/802517/Screencast_2017-02-27_05_24_07_mp4.zip)

**Comment by alireza-amirsamimi** [comment]
Thanks for reporting :)
I tested this and i have no problem with removing downloads in archlinux . did you try to removing items from toolbar?

**Comment by JafarAkhondali** [comment]
Please open a new issue if the problem exists within new version.
