### ISSUE TITLE
باز نشدن پنجره اصلی نرم افزار در هنگام شروع دانلود

### ISSUE THREAD

**Issue by mohammadnoori** [persepolisdm/persepolis#153]
سلام خسته نباشید به تیم توسعه این نرم افزار.
میخواستم ببینم میشه که این برنامه در هنگام شروع دانلود پنجره اصلی نرم افزار رو باز نکنه و فقط خود پنجره دانلود باز بشه ؟
و خود نرم افزار در پس زمینه اجرا بشه.

**Comment by mostafaasadi** [comment]
@mohammadnoori سلام 
شما نرم افزار بصورت زیر در استارت‌اپ خود قرار دهید  (اگر هم از آخرین نسخه گیت استفاده می کنید گزینه‌ای در تنظیمات برای افزودن به استارت‌اپ گنجانده شده است) 
`persepolis --tray`
اینطور همواره در پس زمینه اجرا باقی خواهند ماند و در زمان شروع یک دانلود جدید فقط پنجره شروع دانلود به شما نمایش داده می‌شود

**Comment by mohammadnoori** [comment]
متاسفانه تفاوتی نکرد.
و باز هم با اینکه نرم افزار در پس زمینه در حال اجراس بازم در هنگام شروع دانلود خود نرم افزار و پنجره دانلود با هم باز میشن و حتی اگه پنجره اصلی نرم افزار رو ببندی دانلود هم در پنجره دانلود قطع میشه

**Comment by mostafaasadi** [comment]
برای من که اینطور نیست 
یعنی اگر پرسپولیس در سیستم تری باشد و دانلود جدیدی شروع شود فقط پنجره دانلود جدید نمایش داده می شود 
شما پرسپولیس را از چه طریقی و روی چه توزیع و میزکاری نصب کردید ؟
و اما در رابطه با بستن برنامه و قطع شدن دانلود این امری معقول است ، بستن برنامه به معنای خاتمه دادن به همه فرآیندهای آن برنامه است ، اگر می خواهید که که دانلود را داشته باشید و پنجره اصلی پرسپولیس هم مزاحمتان نباشد  ، آن را به  تری بفرستید

**Comment by alireza-amirsamimi** [comment]
@mohammadnoori 
حتما انشالله مسئله رو بررسی میکنم و این قابلیت اگر وجود نداره اضافش میکنم
در ضمن برای اینکه برنامه در پس زمینه اجرا بشه میتونید برنامه رو به آیکن 
system tray
مینیمایز کنید

**Comment by JafarAkhondali** [comment]
Please open a new issue if the problem exists within new version.
