### ISSUE TITLE
عدم وجود فایل دانلود شده در زیر دایرکتوری مربوطه

### ISSUE THREAD

**Issue by Mr-undead** [persepolisdm/persepolis#154]
یکی از دوستان یه مشکلی داره با پرسپولیس به صورت تصادفی بعد از اتمام موفقیت آمیز دانلود در برنامه ولی فایل دانلود شده نه در مقصد نهایی وجود داره و نه در دایرکتوری موقت

**Comment by alireza-amirsamimi** [comment]
@behroozramezani سلام
احتمالا مسیر نهایی دانلود رو که انتخاب کردند یا mount نشده ، یا فضای کافی نداشت. برای ورژن بعدی تمهیداتی در نظر میگیرم که خطا بده
