### ISSUE TITLE
crash on ubutnu 16.04

### ISSUE THREAD

**Issue by dddeveloperrr** [persepolisdm/persepolis#156]
hi, 
it seems that there is a crash when downloading files. i use ubuntu 16.04
i attached a screen shot from the crash report
![ubuntu-perspolis-crash](https://cloud.githubusercontent.com/assets/11577640/23895810/5c5cb426-08bc-11e7-8c71-083df5e08d98.png)

**Comment by alireza-amirsamimi** [comment]
Hello
Thanks for reporting
Please unhide the traceback part in error window . It's useful for me :)
Or run persepolis from terminal and send me error message .
Thank you.

**Comment by dddeveloperrr** [comment]
sorry for delay in response.

here is the traceback message
![crash-report](https://cloud.githubusercontent.com/assets/11577640/24242531/a02d391c-0fd5-11e7-9c99-9a4c6d284ffe.png)

**Comment by alireza-amirsamimi** [comment]
Thanks
when  is crashing occurred?

**Comment by dddeveloperrr** [comment]
when i clicked on download link
it showed the download dialogue successfully and also downloaded the file successfully but this error also happened

**Comment by alireza-amirsamimi** [comment]
It's weird!No one report an error like this
Please update and upgrade ubuntu and then reinstall persepolis

**Comment by dddeveloperrr** [comment]
ok, thanks
