### ISSUE TITLE
داپلیکیت شدن آیتم ها، هنگام اضافه به صف

### ISSUE THREAD

**Issue by LinArcX** [persepolisdm/persepolis#157]
من یه صف دانلود به نام نایت ساختم مخصوص دانلود شبانه هام.یه سری فایل دانلود تو 
all downloads 
داشتم و میخواستم همه رو یه جا انتقالش بدم به صف دانلود شبانه م.
این کارو به کمک 
send selected downloads to : night
انجام دادم.
خواستم ببینم آیا اگه برای بار دوم این گزینه رو بزنم برنامه عکس العملش چه خواهد بود که دیدم بازم تمام فایل هارو گذاشت تو صف دانلود شبانه.یعنی داپلیکیت فایل ها!!
<a href="http://uupload.ir/" target="_blank"><img src="http://uupload.ir/files/q8c8_saeeeeddddd.png" border="0" alt="آپلود عکس" /></a>
علی جان این باگ نیست به نظرت؟
برنامه باید چک کنه ببینه اگه یه سری آیتم به خصوص رو فرستادم تو یه صفی نباید اجازه بده دوباره بتونم اونا رو اد کنم.

**Comment by hayyan71** [comment]
<div dir="rtl">
@LinArcX درود دوست عزیز.

متاسفانه نتوانستم مشکل شما را در Perspolis 2.3.3 مشابه سازی کنم. پس از چندین تلاش، هر بار دریافت های قبلی موجود در صف، در هنگام انتخاب چندگانه ی فایل ها، به صورت خودکار از حالت انتخاب بیرون می آیند.

میتوانید نسخه ی پرسپولیس خود را بگویید؟

**Comment by LinArcX** [comment]
درود.نسخه پرسپولیس من 2.3.3 هست

**Comment by alireza-amirsamimi** [comment]
سپاس
مشکل رو چک خواهم کرد

**Comment by alireza-amirsamimi** [comment]
سلام
باگ فیکس شد
ممنونم
