### ISSUE TITLE
محو بودن دکمه apply هنگام اعمال محدودیت

### ISSUE THREAD

**Issue by LinArcX** [persepolisdm/persepolis#158]
علی جان من یه صفی رو شروع به دانلود میکنم.بعد مدتی میخوام محدودیت سرعت اعمال کنم.
موقعی که چک باکس
limit speed 
رو تیک میزنم.فقط اون مولتی سلکت مربوط به سرعت و گزینه یکای سرعت برام ظاهر میشه و دکمه اپلای غیر فعال هست.
تا زمانی که عدد داخل اون مولتی سلکت رو عوض نکنم دکمه اپلایی نخواهم داشت.
به نظرت نباید تریگر فعال شدن دکمه اپلای همزمان بشه با تریگر فعال شدن تیک چک باکس؟

**Comment by hayyan71** [comment]
درود

**Comment by hayyan71** [comment]
<div dir="rtl">
درود دوست عزیز.

متاسفانه نتوانستم مشکل شما را در پرسپولیس 2.3.3 مشابه سازی کنم و به محض فعالسازی گزینه ی محدودیت سرعت، دکمه ی اعمال فعال میشود.

اگر اشتباه نکنم منظور شما باید این قسمت باشد:
<div dir="ltr">
http://s9.picofile.com/file/8289684976/Screenshot_20170316_133238.png
<div dir="rtl">

آیا تغییراتی در تنظیمات پیش فرض پرسپولیس (تغییرات نمایشی، مانند تغییر تم و ...) داده اید؟
یکی از نکاتی که به توسعه دهندگان کمک میکند تا سریعتر به عیب یابی بپردازند، مشابه سازی ایراد در شرایط یکسان است. اگر اطلاعات و جزییات خاصی (توزیع، میزکار، تغییرات در تنظیمات نرم افزار، ...) وجود دارد که به توسعه دهندگان در عیب یابی و رفع سریعتر مشکل کمک میکند وجود دارد، بهتر است این اطلاعات و جزییات نیز ذکر شود.

**Comment by LinArcX** [comment]
والا من هیچ تنظیمات خاصی رو پرسپولیس اعمال نکردم و طبق تنظیمات دیفالت دارم ازش استفاده میکنم.
توزیع م آرچ هست و میزکارم سینمون.
البته اینم بگم که تو سری اول همه چی اوکیه.ولی از سری دوم به بعد اون دکمه دیزیبل هست برام.

**Comment by alireza-amirsamimi** [comment]
سپاس
مشکل رو چک میکنم

**Comment by alireza-amirsamimi** [comment]
سلام سعید عزیز
باگ رو در این کامیت
[Commit](https://github.com/persepolisdm/persepolis/commit/b861624d8f700d6c33cebb33e915bf5b3a5d9666)
حل کردم
سپاس از اینکه اطلاع دادی
