### ISSUE TITLE
عدم نصب پلاگین کروم

### ISSUE THREAD

**Issue by salehmontazeran** [persepolisdm/persepolis#159]
موقع نصب پلاگین از کروم استور با ارور زیر مواجه میشم
‍‍‍
`There was a problem adding the item‍‍ to Chrome. Please refresh the page and try again‍
‍Image decode failed‍‍‍`

**Comment by JafarAkhondali** [comment]
@skytask سلام
باید از فیلتر شکن استفاده کنین.
من نصب کردم اررور نداد، لطفا سوالات مربوط به افزونه رو در ریپو مربوط بپرسین. ممنون

**Comment by hayyan71** [comment]
<div dir="rtl">

درود دوست عزیز

مدت زمان زیادی است که فروشگاه افزونه های کروم از طریق ایران در دسترس نیست و باید از روش های رفع تحریم برای نصب افزونه ها اقدام شود. ممکن است شما نیز برای نصب افزونه به این روشها نیازمند باشید
