### ISSUE TITLE
بروز نشدن فایل install به نسخه 2.0.1

### ISSUE THREAD

**Issue by msajadi832** [persepolisdm/persepolis#16]
من با 
git pull
و اجرای دوباره برنامه با 
sh install
برنامه رو بروز کردم. 
مشکلی نداشت ولی موقع اجراش نسخه برنامه بروز نشده بود و هنوز روی ۲.۰.۰ بود
در فایل های پروژه تون هم دیدم، فایل 
perspolis 
هم نسخه توش بروز نشده بود

ممنون

**Comment by alireza-amirsamimi** [comment]
با دستورهایی که با
wget
گذاشتم دانلود کن ببین باز همینجوره؟

**Comment by msajadi832** [comment]
باگ ترسناکی نیست!

در فایل های زیر
[https://github.com/alireza-amirsamimi/persepolis/blob/master/persepolis](https://github.com/alireza-amirsamimi/persepolis/blob/master/persepolis)
[https://github.com/alireza-amirsamimi/persepolis/blob/master/install](https://github.com/alireza-amirsamimi/persepolis/blob/master/install)
‫این خط ها رو بروز نکردید:

`echo "***********************************"

echo "***********************************"

echo "***_Persepolis Download Manager**_*"

echo "***\*  Version : 2.0.0 Unstable ****"

echo "***********************************"

echo "***********************************"`

**Comment by alireza-amirsamimi** [comment]
ممنون این مشکل رو یکی دو ساعت پیش حل کردم :)
یه چک کن فکر میکنم درست شده
