### ISSUE TITLE
End Time Queue

### ISSUE THREAD

**Issue by NarimanMokarami** [persepolisdm/persepolis#160]
سلام خسته نباشید اول تشکر بابت ساپورت
سال جدید مبارک
 مشکلی که هست اینه که من وقتی یه لیست برای دانلود قرار میدم و یه زمان رو برای توقف بهش میدم متوقف نمیشه و کله لیست رو دانلود می کنه 
لطفا درستش کنین 
os: ubuntu 16.10 64bit
PDM-Version:2.3.3
پیشاپیش ممنون.
موفق باشید.

**Comment by alireza-amirsamimi** [comment]
سلام
سال نو مبارک
بررسی میکنم و مشکل رو حل خواهم کرد
انشالله سعی میکنم به زودی در ورژن جدید مشکل رو حل کنم
سپاس از اینکه اطلاع دادید

**Comment by alireza-amirsamimi** [comment]
سلام
در این کامیت
[Commit](https://github.com/persepolisdm/persepolis/commit/e81471243516ab6c7b4402708c13484fec18402a)
باگ رو حل کردم . انشالله در آپدیت بعدی پرسپولیس دیگه این مشکل وجود نخواهد داشت
سپاس از اینکه باگ رو اطلاع دادید

**Comment by NarimanMokarami** [comment]
سلام صبح بخیر.
خیلی ممنون :)
موفق باشید.

2017-03-27 17:14 GMT-08:00 AliReza AmirSamimi <notifications@github.com>:
