### ISSUE TITLE
درخواست چند ویژگی

### ISSUE THREAD

**Issue by dddeveloperrr** [persepolisdm/persepolis#161]
سلام اقای امیر صمیمی نوروزتون مبارک

اینو دیگه فارسی مینویسم انگلیسیمون ته کشید :)))

دو سه تا ویژگی هست که به نظرم اومد بهتون پیشنهاد بدم اگر مناسب بود اعمال کنید در برنامه
توی عکس توضیح دادم اینجا هم توضیح میدم
اول اینکه کاری کنید که با کلیک بر روی عنوان ستون، کل جدول سورت بشه

دوم اینکه، موقع دانلود فایل چک کنید که ایا قبلا دانلود شده یا نه

سوم اینکه، دوتا کتگوری به برنامه اضافه کنید به نام های 
finnished 
و
unfinnished
و هر کدوم از اینها هم برای خودشون ساب کتگوری داشته باشن با نام های

video
music
compressed
pdf
دقیقا مانند 
idm
در ویندوز

وقتی روی ویدیو کلیک کردیم، اگر در سابکتگوری 
finnished 
بود، تمام ویدیو هایی که دانلودشون تموم شده رو در جدول نشونمون بده
یا وقتی روی خود 
unfinnished 
کلیک کردیم تمام فایل هایی که دانلودشون تموم نشده رو بهمون نشون بده

ببخشید اینجوری نشوتم چون کلمه ی انگلیسی رو همراه فارسی مینویسی قاطی میشه

با تشکر
![ax222](https://cloud.githubusercontent.com/assets/11577640/24244285/d6a2f850-0fdb-11e7-83e7-2a60cbe6a12c.jpg)

**Comment by alireza-amirsamimi** [comment]
سلام
سال نو مبارک
خب از اول فارسی مینوشتید
 😄
سپاس از پیشنهاداتتون 🌹

**Comment by dddeveloperrr** [comment]
:))))))

اخه میخام که وقتی توسعه دهندگان خارجی بازدید میکنن اونا هم ترغیب بشن و کمک بکنن به توسعه برنامه، به همین خاطر باید دیگه سعی کنیم
 که کامنت ها به انگلیسی باشه 

ممنونم از شما
