### ISSUE TITLE
Downloaed file isn't in the expected directory.

### ISSUE THREAD

**Issue by omidsaedi** [persepolisdm/persepolis#162]
Ubuntu 16.10 / Perspolis v 2.3.3 
i have downloaded an iso image(.iso) file which must be saved under Compressed subdirectory in perspolis directories whereas when download is done there's no iso image in perspolis subdirectories. on the application using "open file" option results not found message too.

**Comment by alireza-amirsamimi** [comment]
hello
always make sure that partition of your destination folder is mounted before downloading! beacause it caused you miss your download file.

See this folder too
```
~/.persepolis
```
you can check contents of this folder with your file manager or ls command. for example:

```
ls ~/.persepolis
```

**Comment by omidsaedi** [comment]
there's no problem with mount and existence of destination folder. i had two parallel downlaods; the other one exists and the file is healthy. also ~/.perspolis is empty too.
Thanks for response.

**Comment by alireza-amirsamimi** [comment]
@omidsaedi Is it possible for you to get me the download link ? so i can test it
thanks

**Comment by omidsaedi** [comment]
for sure ; here's the[ link](http://cdimage.ubuntu.com/ubuntu/daily-live/20170321/zesty-desktop-amd64.iso).

**Comment by alireza-amirsamimi** [comment]
I downloded that link without problem.
But I tag this issue as bug ! I will try to improve copying progress in persepolis and I will add some notifications for unsuccessful copying and ... for preventing issues like that in next version .
Thanks

**Comment by alireza-amirsamimi** [comment]
I fixed this bug on github [in this commit](https://github.com/persepolisdm/persepolis/commit/90d2a1d859be7b12638cc155133d93876aefd5da). thanks for reporting . you can update after we release newer version :)
