### ISSUE TITLE
قطع نشدن صدای نوتیفیکیشن

### ISSUE THREAD

**Issue by aminbahraini** [persepolisdm/persepolis#163]
سلام 
صدای نوتیفیکیشن اتمام دانلود رو هرکاری میکنم قطع نمیشه (حتی کم هم نمیشه)
از توی قسمت نوتیفیکیشن هم تیک رو برداشتم کار نکرد!!

**Comment by alireza-amirsamimi** [comment]
سلام
سال نو مبارک
از چه توزیعی و از چه نسخه ای استفاده میفرمایید

**Comment by aminbahraini** [comment]
سال نو مبارک

ubuntu 16.04
perespolis 2.3.3

**Comment by alireza-amirsamimi** [comment]
این سه تا دستور رو تست کنید و به من بگید آیا صداشون با هم تفاوت داره یا نه

```
paplay --volume="65500"   /usr/share/persepolis/notifications/ok.ogg
paplay --volume="35500"   /usr/share/persepolis/notifications/ok.ogg
paplay --volume="15500"   /usr/share/persepolis/notifications/ok.ogg
```
سپاس

**Comment by aminbahraini** [comment]
paplay --volume="65500"   /usr/share/persepolis/notifications/ok.ogg
paplay --volume="35500"   /usr/share/persepolis/notifications/ok.ogg
این ۲ دستور بالا صدا دارند و صداشون با هم متفاوته
ولی دستور ‌پایین صدا نداره
paplay --volume="15500"   /usr/share/persepolis/notifications/ok.ogg

**Comment by alireza-amirsamimi** [comment]
حالا خروجی این دستور رو  در دوحالت بذارید
```
cat ~/.config/persepolis_download_manager/persepolis.conf
```

حالت اول : بدون اینکه تنظیمات صدای ناتیفیکیشن رو در پرسپولیس تغییر بدید
حالت دوم : تنظیمات صدا و ... رو حسابی! تغییر بدید و بعد دوباره خروجی دستور رو بذارید

**Comment by verico1** [comment]
سلام لطفا من رو توی گیت هاب فالو کنید ممنون میشم
verico.TL

**Comment by aminbahraini** [comment]
حالت بدون تغییرات

[AddLinkWindow]
position=@Point(313 75)
size=@Size(520 565)

[AfterDownloadWindow]
position=@Point(300 300)
size=@Size(570 290)

[MainWindow]
position=@Point(361 110)
size=@Size(900 500)

[PreferencesWindow]
position=@Point(252 141)
size=@Size(578 465)

[ProgressWindow]
position=@Point(300 300)
size=@Size(595 284)

[PropertiesWindow]
position=@Point(300 240)
size=@Size(700 500)

[add_link_initialization]
download_user=
ip=
port=0
proxy_user=

[settings]
AboutWindow\position=@Point(300 300)
AboutWindow\size=@Size(363 300)
AddLinkWindow\position=@Point(300 175)
AddLinkWindow\size=@Size(520 565)
AfterDownloadWindow\position=@Point(300 300)
AfterDownloadWindow\size=@Size(570 290)
MainWindow\position=@Point(265 134)
MainWindow\size=@Size(900 500)
PreferencesWindow\position=@Point(300 272)
PreferencesWindow\size=@Size(578 465)
PropertiesWindow\position=@Point(318 110)
PropertiesWindow\size=@Size(700 500)
add_link_initialization\download_user=
add_link_initialization\ip=
add_link_initialization\port=0
add_link_initialization\proxy_user=
after-dialog=yes
color-scheme=Persepolis Dark Red
connections=16
download_path=/home/amin/Downloads/Persepolis
download_path_temp=/home/amin/.persepolis
font=Ubuntu
font-size=9
icons=Archdroid-Red
max-tries=5
notification=Native notification
retry-wait=0
rpc-port=6801
settings\after-dialog=yes
settings\color-scheme=Persepolis ArcDark Red
settings\connections=16
settings\download_path=/home/amin/Downloads
settings\download_path_temp=/home/amin/.persepolis
settings\font=Ubuntu
settings\font-size=9
settings\icons=Archdroid-Red
settings\max-tries=5
settings\notification=Native notification
settings\retry-wait=2
settings\rpc-port=6801
settings\show-menubar=yes
settings\show-progress=yes
settings\show_sidepanel=no
settings\sound=yes
settings\sound-volume=12
settings\style=Fusion
settings\timeout=60
settings\tray-icon=yes
show-menubar=no
show-progress=yes
show-sidepanel=yes
show_sidepanel=yes
sound=yes
sound-volume=99
style=Fusion
timeout=60
tray-icon=yes

[version]
version=2.2999999999999998


حالت دوم 
با تغییرات
[AddLinkWindow]
position=@Point(313 75)
size=@Size(520 565)

[AfterDownloadWindow]
position=@Point(300 300)
size=@Size(570 290)

[MainWindow]
position=@Point(361 110)
size=@Size(900 500)

[PreferencesWindow]
position=@Point(300 272)
size=@Size(578 465)

[ProgressWindow]
position=@Point(300 300)
size=@Size(595 284)

[PropertiesWindow]
position=@Point(300 240)
size=@Size(700 500)

[add_link_initialization]
download_user=
ip=
port=0
proxy_user=

[settings]
AboutWindow\position=@Point(300 300)
AboutWindow\size=@Size(363 300)
AddLinkWindow\position=@Point(300 175)
AddLinkWindow\size=@Size(520 565)
AfterDownloadWindow\position=@Point(300 300)
AfterDownloadWindow\size=@Size(570 290)
MainWindow\position=@Point(265 134)
MainWindow\size=@Size(900 500)
PreferencesWindow\position=@Point(300 272)
PreferencesWindow\size=@Size(578 465)
PropertiesWindow\position=@Point(318 110)
PropertiesWindow\size=@Size(700 500)
add_link_initialization\download_user=
add_link_initialization\ip=
add_link_initialization\port=0
add_link_initialization\proxy_user=
after-dialog=yes
color-scheme=Persepolis ArcDark Red
connections=16
download_path=/home/amin/Downloads
download_path_temp=/home/amin/.persepolis
font=Ubuntu
font-size=9
icons=Archdroid-Red
max-tries=5
notification=Native notification
retry-wait=0
rpc-port=6801
settings\after-dialog=yes
settings\color-scheme=Persepolis ArcDark Red
settings\connections=16
settings\download_path=/home/amin/Downloads
settings\download_path_temp=/home/amin/.persepolis
settings\font=Ubuntu
settings\font-size=9
settings\icons=Archdroid-Red
settings\max-tries=5
settings\notification=Native notification
settings\retry-wait=2
settings\rpc-port=6801
settings\show-menubar=yes
settings\show-progress=yes
settings\show_sidepanel=no
settings\sound=yes
settings\sound-volume=12
settings\style=Fusion
settings\timeout=60
settings\tray-icon=yes
show-menubar=yes
show-progress=yes
show-sidepanel=yes
show_sidepanel=no
sound=yes
sound-volume=5
style=Fusion
timeout=60
tray-icon=yes

[version]
version=2.2999999999999998

**Comment by aminbahraini** [comment]
آقا ممنون درست شد
notification type
رو از روی حالت
native 
گذاشتم روی حالت 
‌QT

**Comment by alireza-amirsamimi** [comment]
راستش رو بگم اصولا نباید درست میشد
به هم کاری ندارند 😉
اگه مشکل ادامه داشت به من خبر بدید که بررسی دوباره ای انجام بدم
سپاس
