### ISSUE TITLE
مشکل show menubar

### ISSUE THREAD

**Issue by mrbadboy17** [persepolisdm/persepolis#165]
از توی تنظیمات برنامه، show menubar رو زدم 
منو بار نمایش داده شد
اما گزینه اش توی منوی view > show menubar هنوز تیک نداره
و وقتی روش کلیک می کنم تیک دار میشه و اتفاقی نمیفته
دفعه بعدی که کلیک می کنم روی همون گزینه منوبار هیدن میشه و درست کار میکنه
آرچ لینوکس و اپن باکس دارم

**Comment by alireza-amirsamimi** [comment]
سپاس از اینکه اطلاع دادید
انشالله به زودی برطرف میشه

**Comment by alireza-amirsamimi** [comment]
سپاس
باگ رو فیکس کردم
