### ISSUE TITLE
کار نکردن روی مک

### ISSUE THREAD

**Issue by hosseinizadeh** [persepolisdm/persepolis#167]
سلام آقا روی مک هیچکدوم از نسخه ها کار نمیکنه همه رو تست کردم
تصویر ضمیمه شد
موفق باشید
![screen shot - - at](https://cloud.githubusercontent.com/assets/26816720/24549435/7b10d904-162e-11e7-9ec1-5f2583f806f7.jpg)

**Comment by mavahedinia** [comment]
@hosseinizadeh با سلام، میتونید بگید رو کدوم ورژن مک هستید؟

**Comment by hosseinizadeh** [comment]
El Capitan 10.11.5
