### ISSUE TITLE
درست کار نکردن افزونه کروم

### ISSUE THREAD

**Issue by mojtaba-baghban** [persepolisdm/persepolis#168]
با سلام
هنگامی که پزسپولیس در system tray
  در حال اجرا نیست اگر لینکی از طریق افزونه مربوطه به پرسپولیس اضافه شوپ، پرسپولیس باز و در کسری از ثانیه بسته میشود. در حالیکه اگر قبل از اضافه شدن لینک پرسپولیس در حال اجرا باشد به درستی کار می‌کند.
در ضمن با اینکه پرسپولیس را به افزونه فلش گات اضافه کرده‌ام و در لیست منو میاید، هنگامی که لینکی را از طریق فلش گات به پرسپولیس میفرستم هیچ اتفاقی نمی افتد.
سیستم من آرچ + کی دی ای
نسخه پرسپولیس 2.4 آلفا
نصب از طریق yaourt نسخه persepolis-git
با تشکر از زحمات شما

**Comment by alireza-amirsamimi** [comment]
سلام
قضیه مربوط به کروم باگ هست و برطرفش میکنم و اطلاع میدم
فلش گات رو چک کردم مشکلی نداشت
چک کنید که تنظیمات فلش گات رو درست انچام دادید یا نه
سپاس از اینکه باگ رو اطلاع دادید

**Comment by alireza-amirsamimi** [comment]
سلام
باگ رو فیکس کردم و مشکل رو میبندم
مشکل جدیدی بود یه موضوع جدید براش باز کنید
سپاس
