### ISSUE TITLE
تنظیمات شروع و پایان صف

### ISSUE THREAD

**Issue by mojtaba-baghban** [persepolisdm/persepolis#169]
من صفی به نام شبانه ساخته‌ام و تنظیمات شروع  و پایان صف را انجام داده ام امادر زمان مورد نظر صف شروع به بارگیری نمی‌کند.
در ضمن اگر گزینه hide option را بزنم تنظیمات شروع و پایان صف پنهان می شوند ولی پس از آن اگر گزینه show option را بزنم این تنظیمات ظاهر نمی‌شوند و فقط پس از ریستارت پرسپولیسا می‌توان این تنظیمات را مشاهده کرد
سیستم من آرچ + کی دی ای
نسخه پرسپولیس 2.4 آلفا
نصب از طریق yaourt نسخه persepolis-git
با تشکر از زحمات شما

**Comment by alireza-amirsamimi** [comment]
سلام
میبخشید که دیر پاسخ میدم
کمی سرم شلوغ هست
پیغامتون به خاطر مشکل نشان دادن کلمات انگلیسی و فارسی و ...به هم ریخته
متوجه مشکل نشدم
میشه پیغام رو بازنویسی کنید و برای نوشتن کلمات انگلیسی به خط بعدی برید
سپاس

**Comment by mojtaba-baghban** [comment]
من صفی به نام شبانه ساخته‌ام و تنظیمات شروع و پایان صف را انجام داده ام امادر زمان مورد نظر صف شروع به بارگیری نمی‌کند.
در ضمن اگر گزینه 
hide option
 را بزنم تنظیمات شروع و پایان صف پنهان می شوند ولی پس از آن اگر گزینه
 show option
 را بزنم این تنظیمات ظاهر نمی‌شوند و فقط پس از ریستارت پرسپولیس می‌توان این تنظیمات را مشاهده کرد
سیستم من آرچ + کی دی ای
نسخه پرسپولیس 2.4 آلفا
نصب از طریق yaourt نسخه persepolis-git
با تشکر از زحمات شما

**Comment by alireza-amirsamimi** [comment]
سلام
سپاس از اینکه همیشه آخرین نسخه رو نصب میکنید و همیشه باگ ریپورت میکنید
گزینه پنهان کرن و نشان دادن، باگ هست و روش کار میکنم
بعد از تنظیم شروع و پایان صف حتما روی دکمه
Start queue
رو بزنید
الان تست کردم و مشکلی نداشت و کار میکرد
یک باز دیگه پرسپولیس رو بارگیری کنید و تست کنید

برای قضیه
Show options
یک تگ باگ میزنم اینجا و وقتی رفع شد اطلاع میدم
سپاس

**Comment by alireza-amirsamimi** [comment]
سلام باگ رو در این کامیت
[commit](https://github.com/persepolisdm/persepolis/commit/89b765813ac52d88720dceb23f4d9e5229d57a28)
فیکس کردم
فعلا مشکل رو میبندم
اگر مشکل قبلی ادامه داشت ، اطلاع بدید
ممنونم از همکاریتون 👍
