### ISSUE TITLE
Download Information

### ISSUE THREAD

**Issue by Sosha1996** [persepolisdm/persepolis#17]
کلا وقتی چیزی دانلود می کنم و این صفحه باز میشه که اطلاعات رو به صورت لحظه ای بده، نمیده و هر چند ثانیه اطلاعات رو به روز می کنه!

توی نسخه قبل از این به روز رسانی برنامه همچین مشکلی نداشتم!

**Comment by alireza-amirsamimi** [comment]
برای من که لحظه ای نشون میده
عجیبه
بازم تست کن

**Comment by Sosha1996** [comment]
چندین بار امتحان کردم. هر چند ثانیه به روز می کنه!

**Comment by alireza-amirsamimi** [comment]
ممنونم
بررسی میکنم
