### ISSUE TITLE
۸کارنکردن در یونیتی

### ISSUE THREAD

**Issue by shahabsafaei** [persepolisdm/persepolis#172]
آیا پرسپولیس درکل توی یونیتی ۸ کار نمیدهه، یا کلا هنوز برای یونیتی۸ توسعه داده نشده؟

**Comment by mavahedinia** [comment]
@shahabsafaei با سلام
پرسپولیس بر اساس qt توسعه داده شده تا بتواند کراس-پلتفرم باشد و به راحتی روی هر میزکار و سیستم‌عاملی اجرا شود! به هر حال، با توجه به گزارش‌های داده شده توسط دوستان به نظر میرسد که روی یونیتی۸ مشکل داره! 😐

**Comment by hayyan71** [comment]
<div dir="rtl">
درود دوست عزیز

کنونیکال توسعه ی یونیتی ۸ را متوقف کرده است و از اوبونتو 18.04 دیگر اوبونتو به میزکار Gnome باز خواهد گشت. بعید است پروژه ی پرسپولیس برنامه ای برای پشتیبانی از unity 8 داشته باشد.

<div dir="ltr">
http://news.softpedia.com/news/canonical-to-stop-developing-unity-8-ubuntu-18-04-lts-ships-with-gnome-desktop-514604.shtml
<div dir="rtl">
موفق باشید.

**Comment by alireza-amirsamimi** [comment]
سلام
یونیتی ۸ در حالت آزمایش بود و مشکلاتی داشت و توسعش برای استفاده روزمره کامل نشده بود و با اعلام اخیر مایک شاتلورث ظاهرا متاسفانه! قرار نیست هیچوقت هم تکمیل بشه و توسعش فعلا متوقف شده. مشکلات اجرای پرسپولیس هم از جانب یونیتی ۸ هست و از پرسپولیس نیست
موفق باشید
