### ISSUE TITLE
افزودن دکمه applay برای اعمال تغییرات تنظیمات صف

### ISSUE THREAD

**Issue by mojtaba-baghban** [persepolisdm/persepolis#173]
سلام
در حال حاضر ما برای اعمال تنظیم ساعات شروع و پایان صف مجبور به زدن دکمه
start this queue
هستیم. در صورتیکه از این دکمه توقع می‌رود که صف را در همان موقع زدن دکمه شروع کند. و مشکل دیگر این 
 است ما بعد از این که صف یکبار شروع شد و پایان یافت برای روز بعد و روزهای بعد مجبور به زدن دوباره دکمه
start this queue
هستیم.
پیشنهاد بنده این است که یک دکمه
appay
برای اعمال تغییرات شروع و پایان و دیگر تنظیمات صف از جمله خاموش شدن بعد از اتمام دانلود کار گذاشته شود.
همچنین می‌توان تنظیماتی قرار داد تا دانلود صف در زمان مقرر به روزهای خاصی از هفته یا ماه محدود شود
با سپاس از شما و تیم همراهتان

**Comment by alireza-amirsamimi** [comment]
سپاس از پیشنهادتون

**Comment by JafarAkhondali** [comment]
Duplicate of https://github.com/persepolisdm/persepolis/issues/579.
