### ISSUE TITLE
‫بسته شدن بعد از استفاده از FlashGot ‫در حالت  Minimize to system tray

### ISSUE THREAD

**Issue by msajadi832** [persepolisdm/persepolis#18]
وقتی لینکی رو با 
flashGot 
می گیرم و دانلود تموم میشه، برنامه بدون خطا بسته میشه. 
(با ترمینال تست کردم. خطای نمی داد)

ممنون

**Comment by msajadi832** [comment]
‫الان دوباره تست کردم، وقتی برنامه در حالت  Minimize to system tray هست، این اتفاق می افته.
در حالتی که پنجره اصلی باز باشه، مشکلی نداره

**Comment by alireza-amirsamimi** [comment]
ممنون از اینکه خبر دادی
مشکل عجیبی هست!هیچ خطایی هم نمیده
سعی میکنم مشکل رو پیدا کنم و بر طرفش کنم
:)

**Comment by alireza-amirsamimi** [comment]
یه تهمیداتی به کار بردم که این مشکل رخ نده
 :)
دوباره نصب کنی مشکل حل شده
