### ISSUE TITLE
مناسب نبودن اندازه پنجره preferences

### ISSUE THREAD

**Issue by Mr-undead** [persepolisdm/persepolis#182]
اندازه پنجره preferences به صورت پیشفرض مناسب نیست.
جهت دیدن اخرین گزینه در این پنجره باید پنجره به صورت دستی بزرگ شود

**Comment by alireza-amirsamimi** [comment]
@behroozramezani روی فونت من خوبه
اندازه پنجره ذخیره میشه؟

**Comment by Mr-undead** [comment]
خیر اندازه پنجره ذخیره نمیشه

**Comment by alireza-amirsamimi** [comment]
@behroozramezani بقیه پنجره ها چه طور

**Comment by Mr-undead** [comment]
بقیه پنجره‌ها از چه نظر چطور؟

**Comment by Mr-undead** [comment]
تغییر اندازه بقیه پنجره‌ها را چک کردم همگی ذخیره می شوند

**Comment by alireza-amirsamimi** [comment]
مرسی
روش کار میکنیم

**Comment by alireza-amirsamimi** [comment]
سلام باگ فیکس شد

**Comment by Mr-undead** [comment]
چقدر سریع عالیه
