### ISSUE TITLE
چندتا درخواست کوچیک 

### ISSUE THREAD

**Issue by Pakrohk** [persepolisdm/persepolis#187]
به نام خدا 
سلام خسته نباشید 
ممنون که برنامه مفیدی مثل این رو تولید کردین 
ولی چنتا امکان رو کم داره مثلا دسته بندی دانلود ها 
برای
 video و music و..... 
قسمت مخصوص به خودش رو نداره 
از مرورگر
 vivalde
پشتی بانی نمی کنه 
وعالی میشد اگه یه نسخه برای 
ubuntu touch & Android 
هم تولید می کردین

**Comment by Pakrohk** [comment]
ببخشید 
vivaldi 
چرا این github 
edite 
نداره 
😑😑😑😑

**Comment by alireza-amirsamimi** [comment]
<div dir="rtl"> 
سلام
گیت هاب گزینه ادیت داره. اسکرین شات رو ببینید

![edit](https://cloud.githubusercontent.com/assets/7452500/25228345/59b81e30-25e1-11e7-99ba-7dad6c8acebc.png)

سپاس از پیشنهادتون
تیم توسعه ما شامل افرادی هست که در وقت آزادشون پرسپولیس رو توسعه میدند و به خاطر همین قضیه وقت محدودی داریم و مجبوریم اولویت بندی کنیم . به همین دلیل دوستی که افزونه ها رو برای مرورگرهای مختلف مینویسند ، اولویت رو روی فایرفاکس و کروم گذاشتند . همونطور که میدونید ویوالدی  جزء مرورگرهای معمول نیست . و اگر کاربر این مرورگر هستید استقبال میکنیم که افزونه کروم و ...  که روی گیت هاب گذاشته شده رو فورک کنید و برای ویوالدی درستش کنید و در نهایت به شکل آزاد منتشر بشه و در اختیار همه کاربران قرار بگیره
 .
[افزونه فایرفاکس پرسپولیس](https://github.com/persepolisdm/persepolis-firefox-wrapper)
[افزونه کروم پرسپولیس](https://github.com/persepolisdm/persepolis-chrome-wrapper)
در مورد اندروید و تلفن های هوشمند:
فعلا ما تمرکزمون روی سیستم های دسکتاپ هست . ولی اگر کسی از جامعه کاربری مایل به انتشار پرسپولیس برای اندروید باشه و کارهاش رو انجام بده استقبال میکنیم.
موفق باشید

**Comment by Pakrohk** [comment]
ببخشید من با 
ubuntu touch 
میام و اینجا متاسغانه
Edite 
توی قالب سایت نیست
بعله ولی مشکل اینجاست ویوالدی برپایه افزونه عمل نمی کنه و مکانیزمی مجزا داره 
ولی بازم چهارنین پر استفاده ترین مرور گر هست 
و پشتی بانیه اون خالی از لطف نیست
https://vivaldi.com/
ولی سعیی می کنم در موردش اطلاعات بیشتری کسب کنم و بهتون کمک برسونم

**Comment by Pakrohk** [comment]
ببخشید 
چهارومین
پشتیبانی

**Comment by mostafaasadi** [comment]
<div dir="rtl"> 
سلام

کاش برای سوالی که باز کردید عنوان بهتری انتخاب می کردید 
مرورگر ویوالدی از افزونه پشتیبانی می کند و اتفاقا هم افزونه های کروم بر ویوالدی قابل نصب هستند 
[techdows.com/2015/03/you-can-now-install-extensions-in-vivaldi-browser-from-chrome-web-store.html](techdows.com/2015/03/you-can-now-install-extensions-in-vivaldi-browser-from-chrome-web-store.html)
در تستی که من کردم افزونه کروم پرسپولیس هم بر روی ویوالدی نصب می شود و کاملا هم کار می‌دهد
 
ولی فعلا در این ورژن بصورت خودکار قابلیت اینترگریت نیست ، ان شاء الله برای آپدیت های بعدی 
ولی فعلا شما از این راهکار می‌توانید پرسپولیس را در کنار ویوالدی استفاده کنید و بازخورد خود را به ما اطلاع دهید :  

[ابتدا افزونه کروم پرسپولیس را از استور نصب کنید ](https://github.com/persepolisdm/persepolis/wiki/Chrome-Extension-fa)
مسیر زیر را اگر موجود نیست بسازید :
<div dir="ltr"> 
 
`~/.config/vivaldi/NativeMessagingHosts/`

<div dir="rtl"> 
فایل زیر را از حالت فشرده خارج کرده و فایل جیسون را در مسیر بالا قرار دهید
 
[persepolisjson.zip](https://github.com/persepolisdm/persepolis/files/943092/persepolisjson.zip)

دقت کنید که هم اکنون باید فایل در چنین مسیری قرار داشته باشد :

<div dir="ltr">
  
`~/.config/vivaldi/NativeMessagingHosts/com.persepolis.pdmchromewrapper.json `

<div dir="rtl"> 
در نهایت یکبار مرورگر را بازوبسته کنید و لینک ها از طریق منوی راست کلیک با پرسپولیس قابل دانلود هستند

منتظر بازخوردهای شما هستیم

**Comment by alireza-amirsamimi** [comment]
<div dir="rtl">

@APakrohk 

سلام
در این کامیت پیشنهاد شما رو به برنامه اضافه کردیم

[commit](https://github.com/persepolisdm/persepolis/commit/475149858dca163d22a81296d8bb452294ad0d3f)

انشالله از نسخه بعد پرسپولیس رو میشه به مرورگرهای Opera و Vivaldi متصل کرد.
سپاس از پیشنهادتون
موفق باشید

**Comment by Pakrohk** [comment]
ممنون ازتون واقعا ممنون عالی هستید.

**Comment by LinArcX** [comment]
Dear ali, what is the preliminaries for get android apk?

**Comment by Pakrohk** [comment]
Hey,

I just signed the petition "Let Iranian Gamers Play Apex Legends -
#ApexforIran" and wanted to see if you could help by adding your name.

Our goal is to reach 1,500 signatures and we need more support. You can
read more and sign the petition here:

http://chng.it/z5wZXPDfyS

Thanks!
Ali
