### ISSUE TITLE
ادامه ندادن دانلود بعد از قطع و وصل شدن اینترنت

### ISSUE THREAD

**Issue by RezaOptic** [persepolisdm/persepolis#189]
سلام
اگه وسط دانلود کردن فایل ها تو صف اینترنت قطع و دوباره وصل بشه دانلود ادامه پیدا نمیکنه 
status رو downloading میمونه اما چیزی دانلود نمیکنه.

**Comment by alireza-amirsamimi** [comment]
@RezaOptic سلام
سیستم عامل و نسخه سیستم عامل شما چی هست ؟

**Comment by RezaOptic** [comment]
ubuntu 16.04

**Comment by alireza-amirsamimi** [comment]
@RezaOptic مشکل از نسخه قدیمی آریا در توزیع اوبونتو هست . نرم‌افزار ها در مخازن اوبونتو و به خصوص اوبونتو ال تی اس به کندی نسخه جدیدشون اضافه میشه یا اصلا اضافه نمیشه . این مشکل رو بخونید و اگر مشکلتون رفع نشد، دوباره اطلاع بدید
https://github.com/persepolisdm/persepolis/issues/171

**Comment by hayyan71** [comment]
<div dir="rtl">
درود دوست عزیز

سعی شد مشکل مشابه سازی بشه، اما در توزیع openSUSE Tumbleweed که از بسته های به روز استفاده میکنه (aria2 1.31.0) مشکل مشابه سازی نشد. میتونین در ویدیوی زیر ببینین:
<div dir="ltr">
http://s9.picofile.com/file/8292684392/video1_2017_04_21_13_13_26.mkv.html
<div dir="rtl">
توجه کنید برخی ایرادات پیش آمده ناشی از قدیمی بودن نسخه ی aria2 در مخازن هستش و نیاز هستش که نسخه های به روزتری از این نرم افزار در مخازن توزیع ها وجود داشته باشند.

موفق باشید

**Comment by alireza-amirsamimi** [comment]
انشالله آریا ۲ رو به روز کنید خیلی خیلی خیلی بهتر میتونید با پرسپولیس کار کنید :)
موفق باشید

**Comment by alireza-amirsamimi** [comment]
<div dir="rtl">
راستی یه نکته رو فراموش کردم. اگر از منوی Edit وارد قسمت Preferences بشید ، یک تب وجود داره به نام Download Options که یه سری گزینه داره مثل تعداد بارهای سعی مجدد در صورتی که دانلود نا موفق بشه یا زمانی که بین هر تلاش دوباره باید دانلود منحر صبر کنه یا زمانی که دانلود منجر صبر میکنه و دانلود رو به عنوان time out محسوب میکنه . اینا رو هم میتونید جوری تنظیم کنید که از مشکلات جلوگیری بشه

![options](https://cloud.githubusercontent.com/assets/7452500/25309860/26c85400-27ed-11e7-9146-b95dbd30bcc0.png)
