### ISSUE TITLE
مشکل minimize to system try

### ISSUE THREAD

**Issue by rahim1234** [persepolisdm/persepolis#19]
سلام وقتی از منو 
view
گزینه 
 minimize to system try
رو میزنم و سپس با کلیک روی ایکن کوچک شده و انتخاب
show main window
دیگه منو های 
file - edit - view - download - help
نمایان نمیشه و باید برنامه رو دوباره ری استارت کنم
ubuntu 16.04- unity
pdm ver 2.0.1
# همین قابلیت ها خوبه اگه مشکل باگ ها حل بشه

**Comment by alireza-amirsamimi** [comment]
احتمالا مشکل مربوط به ورژن کیوت اوبونتو هست یا میزکار یونیتی
چون روی آرچ و ... این مشکل وجود نداره
چک میکنم ببینم میشه چه کارش کرد
ممنون از اینکه اطلاع دادی
