### ISSUE TITLE
بهم ریختن سایز تکست باکس ها در صفحه تنظیمات لینکها

### ISSUE THREAD

**Issue by LinArcX** [persepolisdm/persepolis#190]
سلام بر تیم خوب توسعه پرسپولیس و عرض خسته نباشید بابت ریلیز جدیدتون.
 به یه باگِ دیداری برخوردم.اونم اینه که وقتی رو دکمه
properties
 لینک ها کلیک کنیم و سعی در تغییر سایز ابعاد اون داشته باشیم، با بهم ریختگی تسکت باکس ها مواجه میشیم که خیلی تو چشم میزنه:
http://uupload.ir/files/nda5_myimage.gif

**Comment by alireza-amirsamimi** [comment]
<div dir="rtl">
فکر میکنم مربوط به نوع Layout هست. نمیدونم بشه برطرفش کرد یا نه . انشالله بررسی میکنم

**Comment by JafarAkhondali** [comment]
Please open a new issue if the problem exists within new version.
