### ISSUE TITLE
هماهنگ نبودن رنگ icon ها با رنگ color shema 

### ISSUE THREAD

**Issue by LinArcX** [persepolisdm/persepolis#193]
اگه 
color schema
های مختلف رو با 
icon
های مختلف ترکیب بکنید ملاحظه می کنید که بعضی هاشون از لحاظ زیبایی اصلا ترکیب خوبی در نمیان.
مثلا:آیکون 
breeze
رو با
Persepolis Dard Red
ترکیب کنید.
آیکون ها تقریبا محو به نظر میان!!!
چون پس زمینه تیره هست و اصلا به چشم نمیاد.این صرفا یه مثال بود.تو ترکیب های رنگ های دیگه هم، کم و بیش این مشکلات هست.
پیشنهاد میکنم یه سازوکاری واسه این ترکیبات در نظر بگیری که کاربر هر چیزی رو با هرچیزی نتونه قاطی کنه و اگه کرد برنامه تو طوری بنویسی که این رنگ ها رو به نحو بهتری بتونه نمایش بده.
به هر حال، زیبایی هم در کنار عملکردِ مثبتِ برنامه از لحاظ روانی خیلی میتونه روی کاربر تاثیر بذاره:(

**Comment by alireza-amirsamimi** [comment]
<div dir="rtl"> 
سلام سعید جان
آیکن Breeze و Breeze Dark رو برای هماهنگی پرسپولیس با میزکار KDE اضافه کردیم
استایل Breeze در میزکار KDE به طور پیش فرض در میزکار های دیگه مجود نیست. و البته آیکن ها Breeze Dark هماهنگی خوبی با استایل مکینتاش و ویندوز داره . ایینجا اسکرین شات هاش رو ببین

https://github.com/persepolisdm/persepolis/wiki/How-to-change-Persepolis-theme-fa

Persepolis Dark Red هماهنگی خوبی با استایل Fusion داره که در ویکی پرسپولیس هم توضیح دادم. برای اون رنگ بندی بهتره از همون آیکن های نسخه های قبلی پرسپولیس استفاده بشه.
