### ISSUE TITLE
مشکل صدا

### ISSUE THREAD

**Issue by ghost** [persepolisdm/persepolis#194]
usr/bin/pacat
و
`paplay --volume="65500"   /usr/share/persepolis/notifications/ok.ogg
`
ارور میده 
Connection failure: Protocol error
Segmentation fault (core dumped)
تنظیمات کانفیگ  رو تغیر دادم نتیجه حاصل نشد

**Comment by alireza-amirsamimi** [comment]
سلام
یعنی وقتی ناتیفیکیشن پخش میشه برنامه کرش میکنه؟

**Comment by ghost** [comment]
سلام آقای امیر صمیمی
خوشبختانه نه برنامه سر جاشه فقط قسمت صدا  کرش میکنه اصلا کلا صدا پخش نمیشه

**Comment by alireza-amirsamimi** [comment]
<div dir="rtl">
 مسئله مربوط به سیستم خودتون و Pulse Audio میشه و باید مشکل رو بررسی کنید.
مثلا این کد رو در ترمینال بزنید هم احتمالا صدا پخش نمیکنه و خطا میده

<div dir="ltr">

```
 paplay --volume="65500" /usr/share/persepolis/notifications/ok.ogg
```

**Comment by ghost** [comment]
سلام علیرضا جان   
رو نهایتا حذف و دوباره نصب کردم درست شد ممنونمpulseAudio

**Comment by alireza-amirsamimi** [comment]
@jali316 🙏🌹
