### ISSUE TITLE
مشکل اتصال به کرومیوم

### ISSUE THREAD

**Issue by verico1** [persepolisdm/persepolis#195]
سلام موقع دانلود افزونه برای کرومیوم این ارور رو میده 
An error has occurred
There was a problem adding the item to Chrome. Please refresh the page and try again.

**Comment by JafarAkhondali** [comment]
@verico1 سلام
از فیلتر شکن استفاده کنید، store برای ایران تحریم هست.

**Comment by verico1** [comment]
@JafarAkhondali

ممنون حل شد
