### ISSUE TITLE
کار نکردن دکمه delete

### ISSUE THREAD

**Issue by mehdirajabi59** [persepolisdm/persepolis#196]
سلام
مواقعی که می خواهم از لیست دانلود با دکمه دلیت چیزی را حذف کنم کار نمی کند و حتما باید با روی آیکون دلیت کلیک کرد

**Comment by alireza-amirsamimi** [comment]
<div dir="rtl">
جا داره که برای یه سری چیزها شرتکات کیبرد تعریف کنم در برنامه
انشالله اضافه میکنم
البته برای پاک کردن یه دانلود از لیست و نه از روی هارد میتوتید از CTRL+D استفاده کنید
موفق باشید
