### ISSUE TITLE
اجرا نشدن perspolis در شروع به کار

### ISSUE THREAD

**Issue by Monirzadeh** [persepolisdm/persepolis#199]
در تنظیمات پرسپولیس گزینه
run persepolis at startup
وجود دارد که با وجود فعال بودن پرسپولیس در هنگام بالا آمدن سیستم اجرا نمیشود
ubuntu 16.04
آیا باید برای ابونتو به صورت دستی از طریق سیستم عامل این کار را انجام داد یا این بخش به درستی عمل نمیکند

**Comment by mostafaasadi** [comment]
سلام
از طریق ترمینال خروجی این دستور را قرار دهید :‌
`ls -lrth ~/.config/autostart/persepolis.desktop`

**Comment by JafarAkhondali** [comment]
Please open a new issue if the problem exists within new version.
