### ISSUE TITLE
python-pyqt5

### ISSUE THREAD

**Issue by Alirezaies** [persepolisdm/persepolis#2]
`python-pyqt5 is already the newest version (5.5.1+dfsg-3ubuntu4).`

`$ sh install` :

Checking dependencies
Traceback (most recent call last):
  File "./checkpyqt.py", line 4, in <module>
    from PyQt5.QtCore import  QT_VERSION_STR
ImportError: No module named 'PyQt5'
pyqt5 not installed
Installation Failed!

**Comment by alireza-amirsamimi** [comment]
سلام
بسته رو اشتباه نصب کردی
python-pyqt5
مربوط به پایتون ۲ هست
python3-pyqt5
رو باید نصب کنی.توی فیلم هم گفته بودم :)

**Comment by Alirezaies** [comment]
آره درست شد
فقط یه چیز دیگه
لینک هایی مثل همین دانلود از گیتهاب که لینک مستقیم نیست رو دانلود نمیکنه
پنجره دانلود فایرفاکس بالا میاد اما وقتی پرسپولیس رو انتخاب میکنم و اوکی میکنم 
fail میشه

**Comment by alireza-amirsamimi** [comment]
فکر میکنم مربوط به فیلترینگ و... هست
حالا یه امکان به برنامه اضافه میکنم که دلیل خطا رو به کاربر اطلاع بده که ببینیم مشکل از کجاست
