### ISSUE TITLE
بالا نیامدن دانلود منیجر بعد از آپدیت

### ISSUE THREAD

**Issue by NarimanMokarami** [persepolisdm/persepolis#200]
درود خسته نباشید دوستان امیدوارم حالتون خوب باشه من امروز پرسپولیس رو آپدیت کردن به ورژن جدید ولی متاسفانه بالا نمیاد.
پاک کردم دوباره نصب کردم ولی بازم بالا نمیاد.
سیستم عامل ubuntu 16.10
64 bit
پیشاپیش ممنون.

**Comment by alireza-amirsamimi** [comment]
سلام
از ترمینال اجرا کنید و بگید چه خطایی میده

**Comment by NarimanMokarami** [comment]
درود برشما آقای علیرضا جان
وقتی از ترمینال با سودو باز می کنم.
باز میشه اما امکانات کامل نیست
بالا باید منو ها باشه که نیست متاسفانه
http://s8.picofile.com/file/8293076676/Screenshot_from_2017_04_25_00_25_54.png
وقتی بدون سودو اجرا می کنم ارور زیر رو میده.
http://s9.picofile.com/file/8293076642/Screenshot_from_2017_04_25_00_27_36.png
که می گه با سودو اجرا کنید.

**Comment by alireza-amirsamimi** [comment]
<div dir='rtl'>
به هیچ وجه برنامه های گرافیکی رو با sudo اجرا نکنید مگر اینکه توسعه دهندش به شما اطمینان داده باشه و این قضیه شامل پرسپولیس هم میشه . امیدوارم دسترسی فایلهاتون دچار مشکل نشده باشه!
سیستم رو یک ری استارت بفرمایید و بدون sudo پرسپولیس رو اجرا کنید و خطا رو بگذارید.

**Comment by NarimanMokarami** [comment]
درود پاک کردم دوباره نصب کردم ری استارت کردم بدون سود اجرا کردم
اررور پایین رو داد.


Traceback (most recent call last):
  File "./Persepolis Download Manager", line 83, in <module>
    import initialization
  File "/usr/share/persepolis/initialization.py", line 125, in <module>
    f = open(log_file, 'w')
PermissionError: [Errno 13] Permission denied: '/home/sat3007/.config/persepolis_download_manager/persepolisdm.log'

**Comment by mostafaasadi** [comment]
@sat3007 سلام 
یکبار کاملا با دستور 
`sudo apt purge persepolis`
پاک کنید و دوباره پس از آپدیت نصب کنید 
`sudo apt update && sudo apt upgrade && sudo apt install persepolis`

**Comment by mostafaasadi** [comment]
@mostafaasadi همچنین پوشه کانفیگ و تمپ را نیز پاک کنید سپس نصب کنید 
sudo rm -rf ~/.persepolis
sudo rm -rf ~/.config/persepolis_download_manager
همچنین با دسترسی سودو پوشه پرسپولیس و فایل لاک که با نام یوزرنیم شما همراهند و در مسیر /tmp قرار دارند را  پاک کنید 
سپس دوباره نصب کنید

**Comment by NarimanMokarami** [comment]
درود ارروره تغیر کرد به این


Traceback (most recent call last):
  File "./Persepolis Download Manager", line 83, in <module>
    import initialization
  File "/usr/share/persepolis/initialization.py", line 183, in <module>
    browserIntegration(browser)
  File "/usr/share/persepolis/browser_integration.py", line 132, in browserIntegration
    f = open(native_message_file, 'w')
PermissionError: [Errno 13] Permission denied: '/home/sat3007/.config/google-chrome/NativeMessagingHosts/com.persepolis.pdmchromewrapper.json'

**Comment by alireza-amirsamimi** [comment]
<div dir="rtl">
ظاهرا به خاطر استفاده از sudo دسترسی فایلهاتون در سیستمتون حسابی به هم ریخته . با راهنمایی های دوستمون یه سری ازینا حل شدو خب بریم دنبال ادامه : 
این کد رو هم بزنید

```
sudo rm -rf ~/.config/google-chrome
```
باید همه پوشه هایی که با sudo ایجاد شده در اون دفعه رو پاک کنید.

**Comment by NarimanMokarami** [comment]
درود صبح شما بخیر با تشکر از شما دوستان عزیز آقای امیر صمیمی و آقای اسدی امیدوارم همیشه موفق و سلامت باشین.
بعد زدن دستور بالا باز هم به مشکل خوردم ولی با ایده گرفتن از دستور شما مشکل حل شد باید چند تا فایل دیگه رو هم حذف می کردم.
و همچنین ممنون بابت اینکه فرمودید نرم افزار های گرافیکی رو نباید با سودو اجرا کرد.
بسیار بسیار متشکرم از شما دو دوست عزیز موفق و سلامت باشید. :) :+1: 

و اینکه اگر امکانش هست اون دکمه رو هم به اون جا اضافه کنید.
:+1: 
بازم موفق و سلامت باشید :D

**Comment by alireza-amirsamimi** [comment]
خوشحالم که مشکل حل شده :)
فقط نفهمیدم منظور شما رو
کدوم دکمه رو کجا اضافه کنیم؟

**Comment by NarimanMokarami** [comment]
درود دکمه تصویر پایین رو به تصویر پایین تر اضافه کنید :D
 http://s9.picofile.com/file/8292361418/1.jpg
 http://s8.picofile.com/file/8292361468/3.jpg
همون دکمه change file name :_)
ممنون

**Comment by alireza-amirsamimi** [comment]
چشم
انشالله روش کار میکنیم و اضافه میکنیم :)

**Comment by mostafaasadi** [comment]
@sat3007 البته بنده «اسدی» هستم

**Comment by rezamohammady** [comment]
سلام دوستان خسته نباشید
من گوشیم G7 prim هستش
بعد از آپدیت رو لوگو مونده دیگه بالا نمیاد. باید چه کار کنم. ممکنه راهنمایی کنید

**Comment by rezamohammady** [comment]
کسی اینجا هست  آیا

**Comment by JafarAkhondali** [comment]
@rezamohammady What does have to do with PDM ??!‌
