### ISSUE TITLE
اپدیت کردن aria2

### ISSUE THREAD

**Issue by mohammadnoori** [persepolisdm/persepolis#201]
سلام.خسته نباشید.
موقع شروع دانلود از بعضی سایت ها aria2 ارور میده و کرش میکنه.
فک کنم به این خاطر هست که نسخش قدیمیه.
چطور میتونم اپدیتش کنم ؟
من از مینت سینامون استفاده میکنم اخرین نسخه

**Comment by alireza-amirsamimi** [comment]
<div dir="rtl">
سلام
ظاهرا تنها راه کامپایل کردن هست
اجازه بدید خودم یک بار این کار رو روی یک توزیع دبین بیس انجام بدم و به شما اطلاع بدم

**Comment by JafarAkhondali** [comment]
Please open a new issue if the problem exists within new version.
