### ISSUE TITLE
سرعت کم پرسپولیس

### ISSUE THREAD

**Issue by mehdirajabi59** [persepolisdm/persepolis#202]
سلام
آقای صمیمی منو ببخشید انتقاد میکنیم از برنامه خوب پرسپولیس این انتقاد ها جهت بالا بردن کیفیت این برنامه می باشد.

سرعت این برنامه پایین می باشد. وقتی روی یک لینک دانلودی کلیک میکنم تا پرسپولیس بیاد بالا و پنجره دانلود باز بشه خیلی طول میکشه

**Comment by alireza-amirsamimi** [comment]
سلام
این ویدیوی میزکار من هست و تست کردم و فیلم گرفتم . بسیار زمان کوتاهی طول میکشه. اگر در سیستم شما تفاوت زیاده باید مشکل سیستمتون رو پیدا کرد

[time.zip](https://github.com/persepolisdm/persepolis/files/957024/time.zip)

موفق باشید

**Comment by alirezaafzalaghaei** [comment]
منم همین مشکل رو دارم. بعضی وقت ها تا ۱۰ ثانیه هم طول میکشه تا بالا بیاد.متاسفانه تقریبن دیگه بیخیال استفاده از این دانلود منیجر شدم با خود فایرفاکس دانلود میکنم:|
روی سیستم خونه(زوبونتو ۱۶.۰۴ ) و همچنین لپتاپم (کوبونتو ۱۶.۰۴ ) این مشکل رو داشتم...

**Comment by alireza-amirsamimi** [comment]
@alirezaafzalaghaei از قبل پرسپولیس رو باز کنید. چون وقتی پرسپولیس از قبل باز نباشه ، موقع شروع باید با آریا۲ ارتباط برقرار کنه و تا این ارتباط پایدار نشه به شما اجازه کار نمیده. وقتی از قبل باز باشه همانطور که در ویدیو من میبینید این زمان خیلی زیاد نخواهد بود. میتونید پرسپولیس رو در استارت آپ سیستم عامل بگذارید که موقع اجرای میزکارتون پرسپولیس اجرا بشه و در سینی نمایه بره

**Comment by alirezaafzalaghaei** [comment]
الان لپتاپ رو از ۱۶.۰۴ به ۱۷.۰۴ اپدیت کردم دیگه کلا پرسپولیس بالا نمیاد.حتی یه بار حذف کردم و دوباره هم نصب کردم ولی بازم نشد
توی این تاپیک جاش نیست اینو بپرسم ولی برای این مشکلی راهی دارید؟

**Comment by alireza-amirsamimi** [comment]
@alirezaafzalaghaei کاش یه مشکل جدید براش باز کنید
توی ترمینال بنویسید
persepolis
ببینید چه خطایی میده و در موضوع جدید ارسال کنید

**Comment by alirezaafzalaghaei** [comment]
مشکل حل شد. گویا توی اوبونتوی جدید یا نسخه جدید پرسپولیس از پایتون ۳ استفاده شده و منم 
pyqt5
رو روی ۳ نصب نداشتم. با نصب اون مشکل حل شد

راستی یه پیشنهاد خیلی ریز برای بهبود پرسپولیس
روی لینک ک کلیک میکنم فرم دانلود پرسپولیس باز میشه. اون فرم دانلود رو اگه بشه با دکمه
Esc 
بست بهتر میشه

ارزش تاپیک زدن نداشت :smile: 
در اخر هم بگم در مورد سرعت پایین پرسپولیس حق با شما بود. اگه اپلیکیشن باز باشه زیر یک ثانیه فرم دانلود میاد...

**Comment by JafarAkhondali** [comment]
Please open a new issue if the problem exists within new version.
