### ISSUE TITLE
گزارش یک مشکل

### ISSUE THREAD

**Issue by MortezaMoFa** [persepolisdm/persepolis#203]
هنگام ذخیره تغییرات در منو تنظیمات دانلودر ( بدون راه اندازی مجدد) ، اقدام به  ایجاد یک صف دانلود داشتم که با تایید اسم آن با مشکل زیر مواجه شدم

OS:
```
 Name	Microsoft Windows 10 Pro
Version	10.0.14393 Build 14393

```
Error:
```
Traceback (most recent call last):
  File "Persepolis Download Manager", line 305, in <module>
  File "mainwindow.py", line 683, in __init__
  File "osCommands.py", line 28, in touch
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\Morteza\\AppData\\Local\\persepolis_download_manager\\queue_info\\'
```

**Comment by alireza-amirsamimi** [comment]
<div dir="rtl">
سلام
موفق به شبیه سازی مشکلتون نشدم
از چه نسخه ای از پرسپولیس استفاده میکنید؟
و اینکه اگر صف دانلود دیگه ای هم در حال حاضر ایجاد کنید برنامه کرش میکنه؟
میتونم اسمی که برای صف ایجاد شده انتخاب کردید رو بدونم و ببینم آیا مشکلی با اون اسم وجود داشته؟
سپاس

**Comment by MortezaMoFa** [comment]
سلام و احترام به خدمتتون
اگر اشتباه نکنم با اسم زیر سعی داشتم صفی ایجاد کنم:
`First`
.
در حال حاضر دیگر نمی تونم برنامه را اجرا کنم و با مشکلی که در [تصویر](https://drive.google.com/open?id=0B2MUQi2xvU0bUk1pNkpGNXRNOGc)آمده برخورد می کنم.
![perspolis](https://cloud.githubusercontent.com/assets/15952600/25561627/8925ba3c-2d85-11e7-9dad-95bccdac75cb.png)

**Comment by alireza-amirsamimi** [comment]
<div dir="rtl">
ممنونم از اینکه باگ رو اطلاع دادید
روی این مشکل کار میکنیم و در آپدیت بعدی باگ رو حل میکنیم
الان برای حب مشکل روی reset perspolis کلیک کنید .
در این حال لیست دانلود شما پاک میشه ولی دانلود های شما سرجاش هست و اگر لینک دانلودتون رو دوباره به برنامه بدید از ادامه اون دانلود میکنه

**Comment by alireza-amirsamimi** [comment]
<div dir="rtl">
سلام
این باگ رو در نسخه قبل فیکس کردم ولی فراموش کردم که این مشکل رو ببندم.
ممنونم از اینکه اطلاع دادید
