### ISSUE TITLE
مشکل فعال نشدن دکمه ها

### ISSUE THREAD

**Issue by verico1** [persepolisdm/persepolis#204]
سلام  
resume download من موقع ی که وارد برنامه میشم بعد روی فایلی که می خوام دانلود کنم کلیک میکنم ولی دکمه فعال نمیشه

**Comment by verico1** [comment]
نسخه قبل خیلی بهتر بود 
خیلی باگ داره این نسخه

**Comment by verico1** [comment]
مشکل دیگه این هست که من یک صف ساختم می خوان لینک هام رو بفرستم داخلش کل لینک هایی که می‌خوام رو انتخاب می‌کنم می‌فرستم تا دکمه ارسال رو می‌زنم برنامه خراب میشه قفل می‌کنه همه کاری کردم بازم همین مشکل رو دارم

**Comment by alireza-amirsamimi** [comment]
<div dir="rtl">
سلام
لطفا برای هر مشکل موضوع جدا باز کنید تا بهتر بتونیم پیگیری کنیم

۱- باید ببینید دلیل فعال نبودن دکمه چیه؟
من الان برنامه رو باز کردم و دکمه resume کاملا فعال هست.
![1](https://cloud.githubusercontent.com/assets/7452500/25447923/315aec52-2acc-11e7-82d7-ddaa5a7f786a.png)

دکمه وقتی غیر فعال هست که یا دانلود منجر با آریا۲ ارتباط برقرار نکرده یا وضعیت دانلود نیازی به ادامه نداره (مثلا دانلود تمام شده) یا اصلا روی آیتمی که میخواید resume کنید کلیک نکردید. 

۲- ما سورس نسخه های قبلی رو حذف نمیکنیم . در صورت تمایل به این لینک برید و سورس هر نسخه ای که دوست دارید رو دانلود کنید و نصب کنید
http://github.com/persepolisdm/persepolis/releases
اگر هم دوست دارید به ما در توسعه کمکی کنید ، به جای گله و شکایت  یا نصب نسخه های قبلی، برنامه رو از ترمینال اجرا بفرمایید و خطا ها رو با توضیحات برای ما بفرستید.
۳- لطفا همیشه متن خطا رو و سیستم عاملی که استفاده میفرمایید رو برای ما بفرستید . برای این کار لطفا برنامه رو از ترمینال اجرا کنید.
در این صورت میتونیم باگها رو بررسی کنیم و رفع کنیم.
این مورد رو تست کردم و برای من مشکلی نبود . توی ویدیو زیر میتونید ببینید
[queue.zip](https://github.com/persepolisdm/persepolis/files/959346/queue.zip)

در هر صورت علم غیب نداریم :) باید متن خطا رو بفرستید تا مشکل رو متوجه بشیم
سپاس

**Comment by verico1** [comment]
آها ممنون با ترمینال اجرا میکنم مشکل رو میگم
موفق باشید.

**Comment by verico1** [comment]
Traceback (most recent call last):
  File "/usr/share/persepolis/mainwindow.py", line 3074, in categoryTreeSelected2
    download_info_file_list = readList(download_info_file, 'string')
  File "/usr/share/persepolis/newopen.py", line 110, in readList
    f = Open(file_path, 'r')
  File "/usr/share/persepolis/newopen.py", line 66, in __init__
    shutil.copy(str(self.file_name), str(self.temp_file_path))
  File "/usr/lib/python3.5/shutil.py", line 235, in copy
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "/usr/lib/python3.5/shutil.py", line 114, in copyfile
    with open(src, 'rb') as fsrc:
FileNotFoundError: [Errno 2] No such file or directory: '/home/verico/.config/persepolis_download_manager/download_info/f4fa8ecda0d8277b'

**Comment by verico1** [comment]
اینا از اول باز کردن پرسپولیس بود تا موقع خراب شدن و قفل کردن صفحه برنامه

**Comment by alireza-amirsamimi** [comment]
<div dir="rtl">
سپاس از اینکه فرستادید
هر مشکلی که بر خورد کردید ممنون میشم ریپورت کنید
انشالله روش کار میکنیم و رفعش میکنیم

**Comment by verico1** [comment]
خواهش می‌کنم
ولی الان من چیکار کنم؟

**Comment by alireza-amirsamimi** [comment]
الان پرسپولیس باز نمیشه؟

**Comment by verico1** [comment]
نه باز میشه قسمت صف خراب هست
یک صف ساختم نمی توانم لینک های فایل هام رو داخلش ارسال کنم یعنی تا دکمه ارسال به صف رو می‌زنم قفل می‌کنه پرسپولیس باید بری از تسک کیل کنی پرسولیس رو تا از از برنامه خارج بشه

**Comment by alireza-amirsamimi** [comment]
<div dir="rtl">
اون صف رو پاک کنید و یه صف جدید بسازید و با این راهنما راه های دیگه صف رو اضافه کردن دانلود به صف رو تست کنید ببینید جواب میده؟
https://github.com/persepolisdm/persepolis/wiki/How-to-create-queue-fa

**Comment by alireza-amirsamimi** [comment]
سلام
باگ فیکس شد
انشالله در نسخه بعد این باگ وجود نخواهد داشت
سپاس از اینکه اطلاع دادید
