### ISSUE TITLE
‫مشکل نصب از AUR

### ISSUE THREAD

**Issue by parsedarweb** [persepolisdm/persepolis#208]
error: failed to commit transaction (conflicting files)

    Errors occurred, no packages were upgraded.
    ==> ERROR: 'pacman' failed to install missing dependencies.
    :: failed to build persepolis package(s)

Full output: http://paste.ubuntu.com/24547111/

**Comment by ghost** [comment]
did you install `python-requests` manually without using `pacman`? for example by `pip`.
It seems that you have it installed and `pacman` did not know about it.

**Comment by parsedarweb** [comment]
Right. Thank you for the hint.
