### ISSUE TITLE
ویژگی هایی که با وجودشون می تونید برترین باشید

### ISSUE THREAD

**Issue by Pakrohk** [persepolisdm/persepolis#209]
سلام بر تیم عالیه پرس پلیس باید بگم که واقعا کارتون عالیه من توی ویندوز کلی دانلود منیجر رو تست کردم ولی فقط شما رقیب خوبی برای 
idm 
هستید 
میدونم برای رقابت نیومدید و فقط کمک به کار برا هست ولی چند ویژگی وجود داره که اگه اضافش کنید 
واقعا عالی میشید
اولین ویژگی این که بعد از کپیه لینک پاپ آب برنامه اجرا بشه این طوری نیاز نیست برای هر مرور گر افزونه برای دانلود رو نصب کرد و افزونه فقط برای امکانات بیشتر و بهتر خواهد بود
دوم لینک افزونه هارو در برنامه نیز قرار بدید تا راحت تر و بدون نیاز به خوندن ویکی بشه ازشون استفاده کرد
سوم زبان های بیشتری به برنامه اضافه کنید چرا فقط انگلیسی 
فارسی وعربی و فرانسوی و چینی در بیشتر برنامه ها وجود  دارن و شما هم برای بهترین بودن باید استفاده کنید 
یا حداقل فارسی رو چون این برنامه فارسیه بالاخره
چهارم تنظیمات صف باید کامل تر از اینی که هست باشه(باز شدن یا نشدن دانلود کمپلیت بعد از هر دانلود . خاموش شدن سیستم بعد از پایان صف .مکان دانلود برای صف .تنظیم پسورد برای دانلود فایل های رمز دار و نیاز مند اکانت در صف و.....) و برای ساخت و یا حذف صف باید دکمی در بالای ستون صف ها وجود داشته باشه 
پنجم 
![alt text](http://uupload.ir/files/pw7w_screenshot_(7).png)
![alt text](http://uupload.ir/files/cp39_screenshot_(8).png)
![alt text](http://uupload.ir/files/j2bx_screenshot_(9).png)
![alt text](http://uupload.ir/files/lws2_screenshot_(10).png)
![alt text](http://uupload.ir/files/k318_screenshot_(11).png)
![alt text](http://uupload.ir/files/yi68_screenshot_(12).png)
![alt text](http://uupload.ir/files/vp86_screenshot_(13).png)
این امکان در 
idm 
جالب بود و گفتم شاید شما هم اضافه کنید
ششم بهتر نیست یه ویکی داخلی در برنامه قرار بدید این  نظر منه 
و دوستان یه باگ هم در ویندوز وجود داشت که در گنو بش بر نخوردم اونم فعال بودن در استارت آپ بود
بعد از زدنه دکمه ضربدر و بسته شدن برنامه برنامه کامل بسته می شه و به استارت آپ نمیره .
راستی در ویندوز 10 
Power Shell
جای 
cmd  
رو گرفته البته هنوز در سیستم وجود داره ولی بیشتر فعالیت ها رو 
PowerShell 
انجام میده و دیگه نیاز به 
cmd 
نیست ولی یکم کد هاش فرق داره دیگه
 
![PowerShell](http://uupload.ir/files/btux_screenshot_(14).png)
ممنون از توجه شما

**Comment by Pakrohk** [comment]
[لینک فیل عکس های نصفه نیمه ](http://uupload.ir/view/9sf1_screenshots.rar)

**Comment by alireza-amirsamimi** [comment]
<div dir="rtl">
سلام
سپاس از پیشنهاداتتون
پرسپولیس امکان خاموشی اتوماتیک بعد از پایان صف رو داره.

بسیار پیشنهادات خوبی در نوشته شما بود که انشالله سر فرصت بهش میپردازیم .
در مورد پاور شل که فرمودید . پرسپولیس رو باید جوری آماده کنیم که هم روی ویندوز ۷ و هم ۸ و هم ۱۰ کار کنه .
و یه صحبت کلی این هست که ما برنامه رو جوری باید آماده کنیم که علاوه بر گنو/لینوکس که پلتفورم مورد علاقه ماست ، روی ویندوز و مک هم بتونه کار کنه و باید راه حل های ما Cross Platform باشه . در ضمن من شخصا قصدی ندارم که آی دی ام رو کپی کنم و یا رقابت کنیم و ... . 

صرفا من و دوستان خواستیم این جای خالی یک نرم افزار مدیریت دانلود آزاد در گنو/لینوکس رو در وقت آزادمون پر کنیم :)

**Comment by Pakrohk** [comment]
بله علی آقا وجود داره و من هم این رو می دونم ولی بعد از شروع صف امکانش هست که تیکش رو فعال کنی نه در هنگام زمان بندی 
و زمان‌بندی برای خاموش شدن وجود نداره
و یک پیشنهاد که فراموشش کرده بودم این بود که پیغامی برای فایل های هم نام قرار بدین 
درضمن من قصدم این نبود که از 
IDM 
کپی کنید یک امکان در این برنامه وجود داشت که خودم به شخصه خیلی ازش خوشم میاد و گفتم چطور توی گنو وجود نداشته باشه
البته بالاهم نوشتم قصد شما کمک و قصد منم فقط پیشنهاد برای بهتر شدن شماست

**Comment by alireza-amirsamimi** [comment]
@APakrohk سلام
متوجه منظورتون نشدم که فرمودید زمانبندی برای خاموشی وجود نداره

**Comment by Pakrohk** [comment]
ببینید زمان بندی برای صف وجود دارد که کی شروع و کی پایان یابد ولی تا صف شروع نشه گذینه های تیک خاموش شدن وجود نداره و یا زمان بندیی برای خاموش شدن سیستم در ساعت خاصی حتی با وجود فعال بودن هر دانلودی 
به صورت مجزا.

**Comment by alireza-amirsamimi** [comment]
@APakrohk ساعت برای صف تعیین کنید و گزینه خاموشی رو بزنید ، سر اون ساعت صف متوقف میشه و سیستم خاموش میشه.
برای دانلود های تکی هم میتونید در هنگام اضافه کردن دانلود ساعت تعیین کنید . وقتی هم پنجره دانلودشون باز شد ، در قسمت گزینه‌های بیشتر خاموشی سیستم رو انتخاب کنید

**Comment by Pakrohk** [comment]
چند امکان دیگه که جای فکر کردن داره 
یک در هنگام شروع صف برنامیی که در حال دانلود هست پنجری دانلودی نداره این نقسه البته در ویندوز تست کردم 
چون اصلا در اپنسوزه دانلودی ندارم 
 دو معمولا ۱۶ کانکشن به سایت برای دانلود ایجاد میشه بهتره مقدار دانلودی توست هر کانکشن نمایش داده بشه و وصل بودن و قطع بودن در لحظه 
این طوری کاربر حس بهتر و حرفیی تری داره
سه من قرار دانلود هام ۲ شب شروع بشه و ۵ خواموش ولی من ساعت ۱۲ مخوابم و نمی تونم تا ۲ بیدار بمونم که باشروع صف به دانلودهام بگم بعد پایان خاموش کن 
چهار وقتی فایلی به صف اضافه میشه باید کنار اون فایل ایکن و نامی برای نمایش صف اون برنامه اضافه بشه 
پنج هر فایل فرمتی داره که نشانگر نوع اون فایله و گاهی فراموش میشه که اسم فایل رو تغییر بدیم و در دانلود های زیاد در بین فایل های دیگه گم میشن بهتره کنار فایل ها بسته به نوع فرمت اون ها ایکن هایی برای نمایش به وجود بیاد
باتشکر از علی رضا جان و برنامه عالی و کاربردیش

**Comment by alireza-amirsamimi** [comment]
@APakrohk <div dir="rtl">
سلام
یک. من فکر میکنم همینطور بهتره
دو. امکانش نیست، آریا۲ این اطلاعات رو به پرسپولیس نمیده.
سه . قرار نیست تا دو بیدار بمونید. ساعت شروع و پایان تعیین کنید و استارت رو بزنید و  راحت بخوابید :-) دانلود از ساعت دو شروع میشه. برای اطلاعات بیشتر راهنمای نرم‌افزار رو بخونید
چهار . ستون category رو ببینید
موفق باشید

**Comment by JafarAkhondali** [comment]
Please open new issues separately for features that you think are good to implement.
