### ISSUE TITLE
افزودن Name

### ISSUE THREAD

**Issue by Sosha1996** [persepolisdm/persepolis#21]
با سلام و خسته نباشید.

وجود **name** برای لینک هایی مثل [این](https://as2.asset.aparat.com/aparat-video/a_9c99e783h78i4jm5eep1589e45fi2jhh0e7j20925884-243t__47cf2.mp4) بسیار واجبه
گاهی ما چیزی رو دانلود می خوایم بکنیم و اسمش درست نیست یا اصلا دلمون می خواد با اسم دیگه ای ذخیره شه.
![2016-07-19 07-47-15](https://cloud.githubusercontent.com/assets/16008585/16937572/685802b4-4d85-11e6-8886-e3b7ed503b4b.png)
توی این بخش وجود همچین چیزی لازمه.

اگه اضافه شه عالی میشه

تشکر!

**Comment by alireza-amirsamimi** [comment]
انشالله توی ورژن
۲.۱
اضافه میکنم
مرسی :)
