### ISSUE TITLE
add language file,plesae

### ISSUE THREAD

**Issue by leoxxx** [persepolisdm/persepolis#210]
I want to localize it.
Add language file,please.

**Comment by JafarAkhondali** [comment]
@leoxxx Thanks for your message, we'll work on it and let you know when it's done.

**Comment by Riajyuu** [comment]
looking forward for that as well.

**Comment by JafarAkhondali** [comment]
We've delayed localization in order to change storage system of Persepolis. Afterwards that would be our first priority.

**Comment by JafarAkhondali** [comment]
Check out https://github.com/persepolisdm/persepolis/wiki/translators-guide.
