### ISSUE TITLE
ترجمه پرسپولیس به زبان‌های مختلف

### ISSUE THREAD

**Issue by Mr-undead** [persepolisdm/persepolis#211]
سلام
گفتم اینجا هم مطرح کنم در دو تا 
issue
مطرح شده بحث ترجمه پرسپولیس به زبان‌های دیگه مطرح شده بود که به نظرم کار خوبی میشه اگر انجام بشه بنده قبلا به صورت خصوصی در تلگرام خدمت آقای امیرصمیمی عرض کردم که ترجمه پرسپولیس را در www.transifex.com
انجام بدیم که برای چنین کارهای طراحی شده. به نظرم کار خوبی میشه اگر هم دنبال نفر برای این بخش باشید من اعلام امادگی میکنم برای بخش ترجمه

**Comment by JafarAkhondali** [comment]
سلام
در حال بررسی این طرح هستیم
برای سایت یکی این دو سایت رو احتمالا انتخاب کنیم
https://www.transifex.com/
https://poeditor.com/
دلیل اصلیش هم رایگان بودن طرح برای پروژه های اپن سورس و کیفیتشون هست.
ممنون بخاطر پیشنهادتون

**Comment by Mr-undead** [comment]
من یه پروژه به نام پرسپولیس در 
www.transifex.com
ساختم. فقط منتظر فایل های زبان برنامه هست

**Comment by JafarAkhondali** [comment]
@behroozramezani 
به دلیل تغیرات بنیادی در فایل های پرسپولیس فعلا نمیتونم ترجمه رو پیش ببریم

**Comment by JafarAkhondali** [comment]
https://github.com/persepolisdm/persepolis/wiki/translators-guide
