### ISSUE TITLE
ابدیت

### ISSUE THREAD

**Issue by Pakrohk** [persepolisdm/persepolis#212]
سلام دوستان مخواستم ببینم میان گین زمان آبدیت بعدیه پرسپلیس و امدن پلاگین و قابلیت های جدیدش کیه بی صبرانه منتظرم.
راستی سعیی کنید پرسپولیس به سایت های مثل 
P30download
یا 
Soft98
راه پیداکنه این طوری خیلی خیلی سریع تر حداقل در ایران 
کسترش پیدا می کنه و معروف میشه.

**Comment by alireza-amirsamimi** [comment]
@APakrohk سلام
احتمالا اواخر ماه آینده نسخه جدید میاد.
برنامه در مرحله آزمایش هست . ما هنوز به هیچ سایت داخلی و خارجی معرفی نکردیم . حتما انشاالله این کار رو در آینده انجام میدیم.
سپاس
