### ISSUE TITLE
دانلود خودکار

### ISSUE THREAD

**Issue by Hamid7143** [persepolisdm/persepolis#214]
سلام آقای صمیمی
اگر امکانش هست لطف کنید دانلود خودکار رو اضافه کنید که وقتی روی لینک کلیک کنیم خودکار بیاد بالا و دانلود کنه
مرسی

**Comment by alireza-amirsamimi** [comment]
<div dir="rtl">
سلام
باید پرسپولیس رو به مرورگرتون متصل کنید
این راهنما رو بخونید

[link](https://github.com/persepolisdm/persepolis/wiki/home-fa#%D8%A7%D9%81%D8%B2%D9%88%D9%86%D9%87-%D9%87%D8%A7)

**Comment by Hamid7143** [comment]
مرسی از راهنماییتون
