### ISSUE TITLE
Bad Luncher!

### ISSUE THREAD

**Issue by ghost** [persepolisdm/persepolis#215]
لانچر ورژن جدید خراب میشه بعد یه مدت.
باید از ترمینال ران کنیم حتمن علیرضا جان.
مرسی.
رو اوبنتو هم تست کردیم

**Comment by alireza-amirsamimi** [comment]
<div dir="rtl">
سلام
خروجی این رو به من میدید لطفا؟

`cat /usr/share/applications/persepolis.desktop`

و همینطور خروجی این لطفا

`ls -l /usr/share/applications/persepolis.desktop`

**Comment by ghost** [comment]
سلام این واسه دستور اول!

[Desktop Entry]
Name=Persepolis Download Manager
Name[fa]=پرسپولیس
Comment=Download Manager
GenericName=Download Manager
GenericName[fa]=نرم افزار مدیریت بارگیری
Keywords=Internet;WWW;Web;
Terminal=false
Type=Application
Categories=Qt;Network;
StartupNotify=true
Exec=persepolis 
Icon=persepolis
StartupWMClass=Persepolis Download Manager
Actions=Open;Tray;

[Desktop Action Open]
Name=Start Persepolis
Name[fa]=اجرای برنامه
Exec=persepolis

[Desktop Action Tray]
Name=Start in System Tray
Name[fa]=اجرای برنامه در سینی نمایه
Exec=persepolis --tray

**Comment by ghost** [comment]
اینم دومی!

-rw-r--r-- 1 root root 611 Apr 17 23:34 /usr/share/applications/persepolis.desktop

**Comment by alireza-amirsamimi** [comment]
<div dir="rtl">
به طرز عجیبی فایل شما از حالت executable خارج شده
این کد رو بزنید حل میشه

<div dir="ltr">

`sudo chmod +x /usr/share/applications/persepolis.desktop `

**Comment by ghost** [comment]
زدم این رو دیروز علیرضا جان.
بازم درست نشد.
جالبه که چندتا از دوستامم که دیدم این مشکل رو دارن.

-rwxr-xr-x 1 root root 611 Apr 17 23:34 /usr/share/applications/persepolis.desktop

**Comment by hayyan71** [comment]
<div dir="rtl">

درود دوست عزیز.

طبیعتا نیازی نیست فایل دسکتاپ بیت اجرایی داشته باشد.
مشکل شما کمی غیرعادی به نظر میرسد. در صورتیکه اطلاعات بیشتری در مورد مشکل بدهید ممکن است در روند یافتن مشکل سرعت بیشتری داشته باشیم.

 - با چه توزیع هایی به مشکل برخورد کرده اید؟
- با کدام میزکار ها به این مشکل برخورد کرده اید؟
- آیا در هنگام بروز مشکل، بررسی کرده اید که پروسه ی پرسپولیس از قبل باز بوده است یا خیر ( از لیست پروسه های در حال اجرا چک کرده اید؟)

**Comment by ghost** [comment]
ubuntu
unity
بله ، اطمینان دارم که پروسسی از پرسپولیس باز نبوده!

**Comment by hayyan71** [comment]
<div dir="rtl">
با تشکر بابت اطلاعات مفید شما. 

یکی از کاربران اوبونتو نیز مشکل مشابه شما را گزارش داده است  و با اوبونتو 16.04 و میزکار یونیتی به مشکلی مشابه مشکل شما برخورد کرده است. 

در چند روز آینده سعی میشود مشکل مشابه سازی و تایید شود تا توسعه دهندگان اقدامات لازم را برای رفع ایراد انجام دهند.

**Comment by ghost** [comment]
دمتون گرم.
خوبه که این باگها گزارش میشه که فیکس بشه.
مرسی از پیگیریتون.
پس همین تاپیک رو باز بزارید که توو همین آمارش رو داشته باشیم.

**Comment by ghost** [comment]
دوستان مشکل در چه وضعی هست؟
ممنون میشم یه آمار بدید.

**Comment by alireza-amirsamimi** [comment]
<div dir="rtl">
یه سوال
همیشه برنامه رو از مخزن لانچپد نصب کردید یا تا حالا شده از گیت هاب هم نصب کرده باشید؟

**Comment by mehrdadPc** [comment]
معمولن اول توو ریپو ادد میکنم بعد از خوده ریپو نصب میکنم.
از گیت نصب نکردم تاحالا.

**Comment by ghost** [comment]
معمولن اول توو ریپو ادد میکنم بعد از خوده ریپو نصب میکنم.
از گیت نصب نکردم تاحالا.

**Comment by mehrdadPc** [comment]
معمولن اول توو ریپو ادد میکنم بعد از خوده ریپو نصب میکنم.
از گیت نصب نکردم تاحالا.

**Comment by alireza-amirsamimi** [comment]
@mehrdadPc <div dir="rtl">

از نصب خارج کردن و نصب دوباره هم فایده نداره؟

**Comment by ghost** [comment]
نه امیر جان.
این رو هم تست کردم.
راستی توو پاک کردن لیست دانلود هم مشکل هست.
اول اینکه تمامش رو پاک نمیکنه.
دوم اینکه گاهی اوقات لیست دانلود رو کلن پاک نمیکنه.
حالا اون باشه واسه یه تیکت دیگه!
