### ISSUE TITLE
یه پیشنهاد 

### ISSUE THREAD

**Issue by Pakrohk** [persepolisdm/persepolis#216]
چطور در نسخه بعدیه برنامه به جای کتاب خونه های گرافیکیه پایتون کامل از HTML
برای گرافیک برنامه استفاده کنید 
مثل ATOM 
البته زبان برنامه نویسیه اتم تاجایی که از ویکی پدیا خوندم کافه اسکریبت بود 
ولی قطعا با پایتون هم میشه این کار رو کرد
و گرافیک رو شدید بهتر و راحت تر می کنه

**Comment by alireza-amirsamimi** [comment]
@APakrohk سلام
زمان و نیروی کافی برای اینکار نداریم . البته تصمیمی هم برای تغییر کیوت نداریم
QT
بسیار پرقدرت هست و الان خیلی از پروژه های بزرگ نرم‌افزار آزاد مثل کی دی ای ، میوزاسکور ، لیبره آفیس و ... بر اساس کیوت دارند جلو میرن

**Comment by Pakrohk** [comment]
بله فکر کنم‌ منظور من رو اشتباه گرفتید منظور من این نبود که زبان برنامرو کامل عوض کنید منظور من این بود کد هارو جوری توسعه بدین که از 
HTML5
برای پوسته و از زبان کیوتی و پایکیوت و پایتون که خودتون دارید برای فرامین برنامه استفاده بشه 
چون قدرت 
HTML 
در طراحیه پوسته بسیار عالیه و می تونه یه افزونه پوسته گذاریه محشر باشه 
اگه که می بینید 
تیم یا وقتش رو ندارید من از بعد از خرداد خودم برای کمک به شما آمادم 
و تسلت کامل به پایتون و زبان های تحت وب دارم 
ولی 
QT
بلد نیستم که سعیی می کند در زمان کمک به آموختنش بپردازم
