### ISSUE TITLE
بسته شدن برنامه 

### ISSUE THREAD

**Issue by Mr-undead** [persepolisdm/persepolis#217]
سلام یه فایل تکست دارم حاوی ۹۲۴ خط لینک وقتی به برنامه اضافه میکنم برنامه بسته میشه . داخل ترمیتال این ارور را میگیرم
```
[behrooz@Lenovo-G500 ~]$ persepolis

(persepolis:2120): Gtk-WARNING **: Invalid input string

(persepolis:2120): Gtk-WARNING **: Invalid input string
Gtk-Message: GtkDialog mapped without a transient parent. This is discouraged.

(persepolis:2120): GLib-ERROR **: Creating pipes for GWakeup: Too many open files

/usr/bin/persepolis: line 18:  2120 Trace/breakpoint trap   (core dumped) ./Persepolis\ Download\ Manager "$@"


```

**Comment by alireza-amirsamimi** [comment]
<div dir="rtl">
ظاهرا خطا مربوط به پرسپولیس نیست

[link](https://stackoverflow.com/questions/9809413/program-received-signal-sigtrap-trace-breakpoint-trap)

شاید به خاطر تعداد خط های زیاد این اتفاق افتاده. مطمئن نیستم بشه کاری کرد یا نه . ولی انشالله سر فرصت روش کار میکنم.
ممنونم

**Comment by JafarAkhondali** [comment]
Please open a new issue if the problem exists within new version.
