### ISSUE TITLE
Some changes take effect after restarting persepolis

### ISSUE THREAD

**Issue by ghost** [persepolisdm/persepolis#219]
<p dir='rtl' align='right'>سلام این پیام نیاید همیشه بیاد باید فقط وقتی که تغییرات ایجاد شده نیاز به ریستارت داشت بیاد و بعدش از کاربر بپرسه میخواد restart کنه یا ن</p>

<p align="right">که اگه تایید کرد برنامه به صورت خودکار ریستارت بشه</p>

**Comment by Alirezaies** [comment]
خیلی ممنون
میشه بگید چه موقع با این پیام مواجه شدید که نباید نمایش داده میشد؟

**Comment by alireza-amirsamimi** [comment]
سلام
بله باگ هست
انشاالله تصحیح میکنیم

**Comment by ghost** [comment]
<p dir='rtl' align='right'>همیشه میاد یعنی وقتی بری تنظیمات، هیچ کاری هم نکنی اوکی رو بزنی بازم میاد</p>

**Comment by alireza-amirsamimi** [comment]
<div dir="rtl">

سپاس از اینکه باگ رو اطلاع دادید. درستش کردم:)
