### ISSUE TITLE
بسته شدن برنامه 

### ISSUE THREAD

**Issue by Mr-undead** [persepolisdm/persepolis#22]
زمانی که یک لینک درحال دانلود هست در پنجره اصلی ( پنجره پروگرس بسته است) روی اون کلیک راست میکنم و 
progress
میزنم برنامه بسته میشه لازم به ذکر هست این اتفاق به صورت تصادفی ممکن هست پیش بیاد خروجی ترمینال و فایل ارور
ترمینال

``` bash
[behrooz@Lenovo-G500 ~]$ persepolis
***********************************
***********************************
****Persepolis Download Manager****
****  Version : 2.0.0 Unstable ****
***********************************
***********************************
0
Aria2 Version : 1.25.0
Aborted (core dumped)
```

و خروجی فایل ارور
‍‍‍```bash
Traceback (most recent call last):
File "/usr/share/persepolis/mainwindow.py", line 733, in progressButtonPresse
member_number = self.progress_window_list_dict[gid]
KeyError: '46ebb159feefb9a0'

```
```

**Comment by alireza-amirsamimi** [comment]
برنامه قبلش کرش نکرده بوده؟
این اتفاق فقط وقتی میتونه بیفته که پنجره پروگرس بار اصلا به وجود نیامده باشه
