### ISSUE TITLE
ی مشکل جزیی

### ISSUE THREAD

**Issue by ehsang1855** [persepolisdm/persepolis#221]
هنگامی که  پرسپولیس در حال دانلود و من می خوام فیلم ببینم 
(پلیرم smplayer ) 
پلیر حدودا هر یک دقیقه  مثل این که موس رو تکون داده باشی نوار پایین ظاهر میشه و ی کم
 اذیت میکنه به خصوص اگه زیر نویس داشته باشه و فقط زمانی اینطور که پرسپولیس در حال اجرا باشه
OS: Arch Linux 
Kernel: x86_64 Linux 4.11.3-1-ARCH
DE: GNOME
Persepolis Download Manager 2.4.2

**Comment by alireza-amirsamimi** [comment]
@ehsang1855 سلام چه جور رو نصب کردید؟

**Comment by alireza-amirsamimi** [comment]
@ehsang1855 سلام
چه جور پرسپولیس رو نصب کردید

**Comment by ehsang1855** [comment]
yaourt -S persepolis-git

**Comment by alireza-amirsamimi** [comment]
@ehsang1855 برید توی تنظیمات پرسپولیس. یه گزینه هست که برای جلوگیری از به خواب رفتن سیستم اضافه شده.
تیک اون رو بردارید

**Comment by ehsang1855** [comment]
کلا اون گزینه فعال نبود

**Comment by alireza-amirsamimi** [comment]
<div dir="rtl">

خروجی اینو به من میدی لطفا


<div dir="ltr">

```
cat ~/.config/persepolis_download_manager/persepolis.conf | grep "awake"
```

**Comment by ehsang1855** [comment]
`awake=no
`
`
settings\awake=no
`

**Comment by alireza-amirsamimi** [comment]
<div dir="rtl">
مشکل رو حل کردم. آپدیت کنید.
سپاس از اینکه باگ رو اطلاع دادید :)

**Comment by ehsang1855** [comment]
خیلی ممنون
خواهش می کنم
