### ISSUE TITLE
How to download *torrent file use this tool on Win10 64bit OS ? thx!

### ISSUE THREAD

**Issue by ugvf2009** [persepolisdm/persepolis#223]

**Comment by alireza-amirsamimi** [comment]
@ugvf2009 Hello
Persepolis can not download torrent now. But we are planning to add it in future :)

**Comment by ugvf2009** [comment]
@alireza-amirsamimi ok,thx for your reply

**Comment by jo90j00** [comment]
@alireza-amirsamimi 希望能夠實現下載 .torrent BT種子檔案的文件。

**Comment by lauriehjb** [comment]
@alireza-amirsamimi Hope to support torrent

**Comment by JafarAkhondali** [comment]
duplicate of https://github.com/persepolisdm/persepolis/issues/501
