### ISSUE TITLE
Set keyboard shortcut to close windows in PDM

### ISSUE THREAD

**Issue by alirezaafzalaghaei** [persepolisdm/persepolis#226]
سلام. به کمک 
import from link 
چند تا لینک رو وارد کردم ولی بعد از تایید دانلود شروع نمیشه.
حتی اگه چند تا فایل اضافه شده رو انتخاب کنم و بعد دکمه شروع رو بزنم بازم دانلود شروع نمیشه
باید تک تک فایل رو انتخاب کنم و بعد شروع رو بزنم

من راه درستی نمیرم یا باگ هست؟

**Comment by Alirezaies** [comment]
@alirezaafzalaghaei 
سلام.
منظورتون `import links from text file` هست؟

**Comment by alirezaafzalaghaei** [comment]
@Alirezaies 
اره

**Comment by Alirezaies** [comment]
@alirezaafzalaghaei 

آیا لینک ها هر کدوم توی یک خط قرار دارن؟

اگر اینطور هست شیوه نصب و نسخه پرسپولیس و همچنین نوع سیستم عامل رو مشخص کنید تا در اسرع وقت پاسختون داده بشه.
ممنون.

**Comment by alirezaafzalaghaei** [comment]
لینک ها ایمپورت میشن
دانلود شروع نمیشه

**Comment by alirezaafzalaghaei** [comment]
@Alirezaies
لینک ها ایمپورت میشه و توی برنامه نشون داده میشه
دانلود خودکار شروع نمیشه
ورژن پرسپولیس ۲.۴.۲
توزیع کوبونتو ۱۷.۰۴
نصب هم با apt

**Comment by alireza-amirsamimi** [comment]
<div dir="rtl">
بعد از اینکه لینک ها رو اضافه کردید و نمایش داده شد، براش یه صف ایجاد کنید و به صف دانلود مورد نظر اضافشون کنید.
بعدش شما یه صف دارید که لینک هاتون داخلش اضافه شده
در مرحله بعدی در پنجره اصلی برنامه، از پنل سمت چپ وارد صف مورد نظرتون بشید و گزینه start queue رو از نوار ابزار برنامه انتخاب کنید

**Comment by alirezaafzalaghaei** [comment]
@alireza-amirsamimi 
الان که حجم ندارم بزنم دانلود ولی ان شا الله مشکل حل میشه با روش شما
اگه امکانش هست به اون صفحه ای که لینک ها رو نشون میده(بعد از ایمپورت) یه دکمه اضافه کنید برای ایجاد صف. 
قشنگتره به نظرم :smile:

**Comment by alireza-amirsamimi** [comment]
<div dir="rtl">
این گزینه رو الان هم داره :)
اسکرین شات رو ببینید

![screenshot_20170612_093546](https://user-images.githubusercontent.com/7452500/27020009-a271b59c-4f52-11e7-935d-0981249cce8a.png)

**Comment by alirezaafzalaghaei** [comment]
عه چه باحال. ندیده بودم :laughing: 
تشکر :+1: 
راستی یه چیزی که الان تو ذوقم زد کار نکردن دکمه
escape 
برای بستن پنجره ها هست. اگه میشه اینو اضافه کنید دستمون رو روی موس نبریم :smile:

**Comment by JafarAkhondali** [comment]
Duplicate of https://github.com/persepolisdm/persepolis/issues/207
