### ISSUE TITLE
showing file size before downlaoding

### ISSUE THREAD

**Issue by dddeveloperrr** [persepolisdm/persepolis#227]
hi

thank you for  creating this download manager

i think it would be nice if the user knows the size of the file before actually starting to download it

In the dialogue box where we enter the URL to download, make a request to server to get its size and show to user somewhere in that box

thank you

**Comment by alireza-amirsamimi** [comment]
Hello
Persepolis already has this feauture ! See the ScreenShot please.
Just add link to persepolis with your browser plugin and then you can see size of file in "Add Link Window" . 

![screenshot_20170612_223901](https://user-images.githubusercontent.com/7452500/27048166-0952614a-4fc0-11e7-8d77-31283789cf74.png)

**Comment by dddeveloperrr** [comment]
this feature isn't available when adding links manually from the main gui

**Comment by alireza-amirsamimi** [comment]
Yes,Because before clicking on "Ok" button or "Download later" button, download link hasn't been approved by user.If user click on "download later" , then download manager will find size of file and it will show size in main window.

**Comment by dddeveloperrr** [comment]
you are right.
but you could pop up a small window first and grab the link from the users, then when they approve it and click OK, pop up another window and show the size and other options to them, just as IDM does

![1](https://user-images.githubusercontent.com/11577640/27050726-de0d20a2-4fc8-11e7-9601-233c94d744d6.png)


![2](https://user-images.githubusercontent.com/11577640/27050734-e40ca234-4fc8-11e7-9242-471b457f2436.png)

**Comment by alireza-amirsamimi** [comment]
I think it is not appropriate way.Because with this additional window, download progress will postponed for a few seconds and It is not necessary.

**Comment by smaragdus** [comment]
**@alireza-amirsamimi**
I don't think the download should be approved in order to show the download size - see **DownloadStudio** - "_Add Job_" window:
 
![DownloadStudio](https://s20.postimg.org/tb0xdfv2l/Download_Studio_10.0.3.0_-_2017-06-12_-_002.png)

**Off-topic**
Do you plan "Get time and date from server" option?

**Comment by alireza-amirsamimi** [comment]
It seems good 👍 
I will work on it :)
@smaragdus 
Please feel free to open new issue for new request and ... . this help us to manage issues better :)
Thank you

**Comment by smaragdus** [comment]
**@alireza-amirsamimi**
I followed your advice and added a new feature request:
[Get time and date from server](https://github.com/persepolisdm/persepolis/issues/228)

**Comment by dddeveloperrr** [comment]
"I think it is not appropriate way.Because with this additional window, download progress will postponed for a few seconds and It is not necessary."

showing another extra window was a suggestion but as @smaragdus  said, you can do it in just a single window. 
When adding link manually, it automatically catches the link in clipboard and at the same time it can send a get request and show the file size before the user hits OK or Download later.

thank you for your attention sir

**Comment by alireza-amirsamimi** [comment]
@dddeveloperrr 
Please don't close this issue :)
Keep it open , because this issue reminds me to add your feature request.

**Comment by alireza-amirsamimi** [comment]
Dear @dddeveloperrr 
Your feature request is added now .
Thanks for your request 👍 :)

**Comment by dddeveloperrr** [comment]
@alireza-amirsamimi  I really appreciate that Sir
