### ISSUE TITLE
مرتب کردن لیست دانلود

### ISSUE THREAD

**Issue by alirezaafzalaghaei** [persepolisdm/persepolis#229]
سلام. لیست دانلود صف رو از منوی 
view
 مرتب میکنم
اگه چند تا لینک جدید به صف اضافه کنم دیگه اون ترتیب رعایت نمیشه و باید دوباره مرتب کنم. 

الان که دقت کردم اگه چیزی در حال دانلود باشه و دانلودش تموم بشه لیست بازم از حالت مرتب شده خارج میشه.
ینی مثلا من برا اساس استاتوس مرتب کرده بودم و یه فایلی استاپ بود. چون توی صف بود شروع به دانلود کرد و کامپلیت شد ولی هنوزم اون ایتم درون بخش استاپ هست نه بخش کامپلیت شده ها 

پرسپولیس :‍۲.۴.۲

**Comment by alireza-amirsamimi** [comment]
سلام
سپاس از اینکه اطلاع دادید
مشکل رو بررسی خواهم کرد

**Comment by JafarAkhondali** [comment]
Please open a new issue if the problem exists within new version.
