### ISSUE TITLE
افزودن زمانبندی به منوی preferences

### ISSUE THREAD

**Issue by Mr-undead** [persepolisdm/persepolis#23]
در صورت امکان یک تب به قسمت 
preferences
جهت تعیین زمانبندی دانلود اضافه شود تا بتوان چندین با اعمال آن روی جندین فایل زمان شروع و پایان دانلود را به صورت دسته جمعی تعیین کرد.

**Comment by alireza-amirsamimi** [comment]
فکر نمیکنم کار درستی باشه
معمولا کاربر تمایل داره این جور وقت ها صف دانلود تشکیل بده
انشالله صف دانلود و دانلود دسته ای رو بعد اضافه خواهم کرد
