### ISSUE TITLE
نمایش دوباره پنجره های دانلود  پس از تغییر تم

### ISSUE THREAD

**Issue by alirezaafzalaghaei** [persepolisdm/persepolis#230]
سلام من با این سناریو به مشکل خوردم:
چند بار 
import link from file 
زدم و به یه صف خاص اضافه کردم
چند تا تک لینک هم برای دانلود به  یه صف دیگه اضافه کردم

پرسپولیس در حال دانلود بود که رفتم تم عوض کنم. بعد از تعویض تم اون هشدار
بعضی تغییرات پس از ریستارت اعمال میشود اومد
بعد از تایید اون تمام پنجره هایی که برای دانلود تک لینک یا ایپورت شده از فایل اومده بود و من تایید کرده بودم و حتی دانلود اونا تموم شده بود دوباره ظاهر شد!

**Comment by alireza-amirsamimi** [comment]
سلام
سپاس از اینکه اطلاع دادید
بررسی میکنم مشکل رو

**Comment by alireza-amirsamimi** [comment]
<div dir="rtl">
سلام تمهیداتی چیدم که این اتفاق در نسخه جدید نیفته
سپاس
