### ISSUE TITLE
some bug and new feature request

### ISSUE THREAD

**Issue by naderdl** [persepolisdm/persepolis#232]
**System Details:**
* Operating System / Distro: Linux / ubuntu-16.04.2 64bit (amd64) with unity desktop
* Persepolis Version: 2.4.2
* Browser: Chromium Version 58.0.3029.110 Built on Ubuntu, running on Ubuntu 16.04 (64-bit)
* _Please attach log files if crash or paste error message_
**Issue Description and  #steps to reproduce:**
hi, 
1. when I download something the download window should pop up at the top of the browser window but it will pop up behind the browser window. (always on top is not enabled by default)
2. when I close Persepolis it should minimize to tray and from tray icon, we should quit it but it will close.
3. add a feature so we can set the default queue at download window.
4. add a check box starts in the tray for startup. (I know there is a command `Persepolis --tray`. )
tanks for the first and the best Iranian download manager.
wish you the bests.

**Comment by alireza-amirsamimi** [comment]
Hi
Thanks for your feature requests :)
Number 4 is already available. Just go to the Edit >> Preferences >> Preference Tab 
and check "run persepolis at startup" :)

**Comment by naderdl** [comment]
but it's not working.I should add it to startup apps manual with `Persepolis --tray` command.

**Comment by chinkiko** [comment]
#bug# auto startup service didn't remove automatically by uninstall.py script

**Comment by alireza-amirsamimi** [comment]
@chensenmo 
Normally uninstall scripts must not change user home directory(config folder and ...).
