### ISSUE TITLE
وقفه دانلود در بین هر فایل در صف

### ISSUE THREAD

**Issue by msajadi832** [persepolisdm/persepolis#238]
‫لطفا در تنظیمات صف گزینه ای افزوده شود تا بین هر فایل زمان وقفه (sleep) را مشخص کنیم.

‫علت این درخواست این است که در بعضی ISP ها اگر حجم زیادی دانلود پشت سر هم دانلود شود، سرعت را پایین می آورند ولی اگر بین هر دانلود زمان وقفه ای وجود داشته باشد، این کار را نخواهند کرد!

با تشکر فراوان

**Comment by ghost** [comment]
<p align="right" dir="rtl">
به نظرم درخواست جالبی نیست به خاطر چند تا ISP خاص این کار رو کرد
</p>

**Comment by alireza-amirsamimi** [comment]
<dev dir="rtl">
میتونه خوب باشه
به این شکل که تنظیم زمان  وقفه  رو اختیاری بگذاریم و به طور پیش فرض صفر بشه و اگر کاربر لازم شد اضافه کنه

**Comment by msajadi832** [comment]
‫@Mosi2772 برای سرویس های نامحدود این مورد زیاد هست!
@alireza-amirsamimi عالیه. ممنون

**Comment by alireza-amirsamimi** [comment]
<div dir="rtl">
سلام

پیشنهادتتون اضافه شد و انشالله با انتشار نسخه ۲.۵ منتشر میشه.
برای ایجاد وقفه از منوی ادیت وارد پتجره preferences بشید و در زبانه download options گزینه wait between every downloads in queue رو ببینید
