### ISSUE TITLE
[Feature ReQ] نمایش چندبخشی در نوار پیشرفت دانلود

### ISSUE THREAD

**Issue by Hitaro** [persepolisdm/persepolis#239]
![ADM Pro](https://user-images.githubusercontent.com/18015032/27302742-8f4d9642-554d-11e7-8dbc-645e3f03fdfd.png)

‫در عکس بالا به نوار پیشرفت نگاه کنید. همچنانی که دانلود منیجر ADM Pro داره در چند نخ دانلود انجام میده، این چندین پروسه مربوط به دانلود رو در نوار پیشرفت هم نمایش میده.

**Comment by alireza-amirsamimi** [comment]
<dev dir="rtl">
سلام
سپاس از پیامتون
پرسپولیس برای دانلود از آریا ۲ استفاده میکنه و آریا ۲ هم به همین شکلی که میفرمایید دانلود رو چند بخش میکنه و همزمان دانلود میکنه . در این حالت پرسپولیس در نقش یک کلاینت عمل میکنه که به کمک ای پی آی های آریا۲ باهاش ارتباط برقرار میکنه. ولی در ای پی آی های آریا۲ گزینه ای وجود نداره که بشه اطلاعات کانکشن ها و سگمنت ها رو جدا گرفت و به همین دلیل متاسفانه نمیشه این پیشنهاد شما رو به برنامه اضافه کنیم :)
