### ISSUE TITLE
  7 شماره 

### ISSUE THREAD

**Issue by Mr-undead** [persepolisdm/persepolis#24]
سناریو تست به این صورت بود رفتم به یه سایت تا داخل مرورگر یه ویدیو ببینم بعد از پلی شدن ویدیو اون ایکون رنگی هست بالا سمت راست فایرفاکس ظاهر میشه روی اون کلیک کردم تا دانلود منیجر ویدیو را دانلود کنه دانلود منیجر باز شد و من تایید کردم پنجره دانلود را ولی ارور داد مه با ایا نمیتونم ارتباط برقرار کنم بعد از دو سه باز بستن برنامه و تکرار این سناریو الان دیکه وقتی به صورت معمولی برنامه را اجرا میکنم پنجره برنامه نمایس داده نمیشه و در قسمت نتیفیکیسن مینویسه برنامه ران هست اما خبری از پنجره اون حتی در قسمت 
systemtry
نیست . وقتی در ترمینال برنامه را اجرا میکنم خروجی شماره ۷ بهم میده و دوباره خط فرمان را تحویل میده 
`[behrooz@Lenovo-G500 ~]$ persepolis

---

---

***_Persepolis Download Manager**_*
***\*  Version : 2.0.1 Unstable ****

---

---

7
`
اومدم یه 
ps
گرفتم اینم خروجیش
`[behrooz@Lenovo-G500 ~]$ ps -ef | grep persepolis
behrooz  14417     1  0 12:48 ?        00:00:00 /usr/bin/python3 /usr/share/persepolis/persepolis-download-manager --link http://cdn.gotoclass.ir/Courses/LPIC1/Hooshmandi/16.networking/2.debian-network-configuration/2.debian-network-configuration.m4v?1468916233474 --name Video_debian_network_configuration_1_Lpic19422????????_2.debian_network_configuration.m4v --cookie /tmp/flashgot.c0hvyb1e.default/cookies-3 --referer http://my.gotoclass.ir/courses/course-v1:Arjang+Lpic19422+1394_Q2/courseware/dcf2fa614ee541a9b97d3f3259eb149f/badfa7a3767147a48eff29b2ae69826a/ --agent Mozilla/5.0 (X11; Linux x86_64; rv:47.0) Gecko/20100101 Firefox/47.0 --execute yes
behrooz  14510     1  0 12:49 ?        00:00:00 /usr/bin/python3 /usr/share/persepolis/persepolis-download-manager --link http://cdn.gotoclass.ir/Courses/LPIC1/Hooshmandi/16.networking/2.debian-network-configuration/2.debian-network-configuration.m4v?1468916233474 --name Video_debian_network_configuration_1_Lpic19422????????_2.debian_network_configuration.m4v --cookie /tmp/flashgot.c0hvyb1e.default/cookies-4 --referer http://my.gotoclass.ir/courses/course-v1:Arjang+Lpic19422+1394_Q2/courseware/dcf2fa614ee541a9b97d3f3259eb149f/badfa7a3767147a48eff29b2ae69826a/ --agent Mozilla/5.0 (X11; Linux x86_64; rv:47.0) Gecko/20100101 Firefox/47.0 --execute no
behrooz  14613     1  0 12:49 ?        00:00:00 /usr/bin/python3 /usr/share/persepolis/persepolis-download-manager --link http://cdn.gotoclass.ir/Courses/LPIC1/Hooshmandi/16.networking/1.networking/1.networking.m4v?1468916359384 --name Video_networking_Lpic19422????????_1.networking.m4v --cookie /tmp/flashgot.c0hvyb1e.default/cookies-5 --referer http://my.gotoclass.ir/courses/course-v1:Arjang+Lpic19422+1394_Q2/courseware/dcf2fa614ee541a9b97d3f3259eb149f/fe2812fe4307439ea63e320e566531f1/ --agent Mozilla/5.0 (X11; Linux x86_64; rv:47.0) Gecko/20100101 Firefox/47.0 --execute no
behrooz  14955 14747  0 12:50 ?        00:00:00 /usr/bin/python3 /usr/share/persepolis/persepolis-download-manager --link http://cdn.gotoclass.ir/Courses/LPIC1/Hooshmandi/16.networking/2.debian-network-configuration/2.debian-network-configuration.m4v?1468916412005 --name Video_debian_network_configuration_1_Lpic19422????????_2.debian_network_configuration.m4v --cookie /tmp/flashgot.c0hvyb1e.default/cookies --referer http://my.gotoclass.ir/courses/course-v1:Arjang+Lpic19422+1394_Q2/courseware/dcf2fa614ee541a9b97d3f3259eb149f/badfa7a3767147a48eff29b2ae69826a/ --agent Mozilla/5.0 (X11; Linux x86_64; rv:47.0) Gecko/20100101 Firefox/47.0 --execute no
behrooz  15004 14747  0 12:50 ?        00:00:00 /usr/bin/python3 /usr/share/persepolis/persepolis-download-manager --link http://cdn.gotoclass.ir/Courses/LPIC1/Hooshmandi/16.networking/2.debian-network-configuration/2.debian-network-configuration.m4v?1468916412005 --name Video_debian_network_configuration_1_Lpic19422????????_2.debian_network_configuration.m4v --cookie /tmp/flashgot.c0hvyb1e.default/cookies-1 --referer http://my.gotoclass.ir/courses/course-v1:Arjang+Lpic19422+1394_Q2/courseware/dcf2fa614ee541a9b97d3f3259eb149f/badfa7a3767147a48eff29b2ae69826a/ --agent Mozilla/5.0 (X11; Linux x86_64; rv:47.0) Gecko/20100101 Firefox/47.0 --execute no
behrooz  15045 14747  0 12:50 ?        00:00:00 /usr/bin/python3 /usr/share/persepolis/persepolis-download-manager --link http://cdn.gotoclass.ir/Courses/LPIC1/Hooshmandi/16.networking/2.debian-network-configuration/2.debian-network-configuration.m4v?1468916412005 --name Video_debian_network_configuration_1_Lpic19422????????_2.debian_network_configuration.m4v --cookie /tmp/flashgot.c0hvyb1e.default/cookies-2 --referer http://my.gotoclass.ir/courses/course-v1:Arjang+Lpic19422+1394_Q2/courseware/dcf2fa614ee541a9b97d3f3259eb149f/badfa7a3767147a48eff29b2ae69826a/ --agent Mozilla/5.0 (X11; Linux x86_64; rv:47.0) Gecko/20100101 Firefox/47.0 --execute no
behrooz  15090 14747  0 12:50 ?        00:00:00 /usr/bin/python3 /usr/share/persepolis/persepolis-download-manager --link http://cdn.gotoclass.ir/Courses/LPIC1/Hooshmandi/16.networking/2.debian-network-configuration/2.debian-network-configuration.m4v?1468916412005 --name Video_debian_network_configuration_1_Lpic19422????????_2.debian_network_configuration.m4v --cookie /tmp/flashgot.c0hvyb1e.default/cookies-3 --referer http://my.gotoclass.ir/courses/course-v1:Arjang+Lpic19422+1394_Q2/courseware/dcf2fa614ee541a9b97d3f3259eb149f/badfa7a3767147a48eff29b2ae69826a/ --agent Mozilla/5.0 (X11; Linux x86_64; rv:47.0) Gecko/20100101 Firefox/47.0 --execute no
behrooz  15740 15145  0 12:52 pts/0    00:00:00 grep persepolis
`
داخل فایل ارور پرسپولیس هم هیچ خروجی موجود نیست احتمالا مشکل با 
kill 
کردن پروسه خحل بشه

**Comment by alireza-amirsamimi** [comment]
یه راهنمایی اگه هنگام دانلود ویدیو از آپارات با فلش گات خطا گرفتی
https
لینک دانلود رو به
http
تبدیل کن . مشکل فنی از سایت آپارات هست و چون اتصالش امن نیست این اتفاق میفته
مشکل رو بهشون اطلاع دادم
انشالله حل کنند
