### ISSUE TITLE
دانلود نکردن فایل از سایت هایی خاص

### ISSUE THREAD

**Issue by LinArcX** [persepolisdm/persepolis#242]
**System Details:**
* Operating System / Distro: Arch
* Persepolis Version: 2.4.2
* _Please attach log files if crash or paste error message_

**Issue Description and steps to reproduce:**
علی جان یه سری سایت ها هستن مثلا:
p30download.com
99 درصد فایل هایی که تو این سایت هستن رو پرسپولیس نمیتونه دانلود کنه.مثلا:
http://p30download.com/fa/entry/70714/
متن ارور هم این شکلیه:
```
Error - the response status is not successful.
status 400
```
در صورتی که همین فایل ها رو با خود آریا2 و از داخل ترمینال دانلود میکنم مشکلی ندارم باهاشون.
البته سایت های دیگه ای هم بودن که این مشکلو داشتن ولی چون خیلی از ویدیوهای آموزشی رو از 
p30downlaod
میگیرم گفتم خبر بدم شاید مشکل بقیه هم باشه و حل بشه ایشاله.

**Comment by alireza-amirsamimi** [comment]
@LinArcX سلام سعید جان
اگه بدون مرورگر لینک رو بهش بدی چه طور؟

**Comment by LinArcX** [comment]
نه مشکلی ندارن!
یعنی مشکل از 
flashgot
میتونه باشه؟
آخه چرا فقط این سایت خاص؟

**Comment by alireza-amirsamimi** [comment]
<div dir="rtl">

**Comment by alireza-amirsamimi** [comment]
<div dir="rtl">
فکر نمیکنم مشکل از فلش گات باشه
فکر میکنم مشکل از کوکی های خود اون سایت باشه
ولی بررسی دقیق تری خواهم کرد :)

**Comment by JafarAkhondali** [comment]
سلام
بنظر مشکل از فلش گات هست چون با افزونه کروم تست کردم جواب داد

**Comment by Monirzadeh** [comment]
با picofile.com 
هم این مشکل وجود دارد و یک صفحه html
دانلود میکند
چه با flashgot و چه به صورت دستی

**Comment by Masoud-Zarrin** [comment]
منهم همین مشکل دارم ولی توی کروم البته همیشه نه توی ویندوز مشکل داشتم 
توی لینوکس هم با برنامه airdroid 
که وصل میشم میخوام چیزی از موبایلم دانلود کنم ارور میده با فایرفاکس بدون نرم افزاری فقط اکستنشن پرسپولیس نصب دارم ارور نمیده راحت دانلود میشه

**Comment by JafarAkhondali** [comment]
@LinArcX  @Monirzadeh @Masoud-Zarrin 
 مشکل کوکی ها در ورژن ۱.۵.۱ افزونه برطرف شدن میتونید از استور کروم آپدیت کنین
برای فایرفاکس هم ثبت کردیم و تا چند روزه دیگه باید تایید بشه
هدف اینه وابسته به فلشگات نباشیم دیگه
میتونید تست کنید اگه باگی بود بگین برطرف کنیم
