### ISSUE TITLE
Change language to English

### ISSUE THREAD

**Issue by vikas5914** [persepolisdm/persepolis#243]
**System Details:**
* Operating System / Distro:  antergos / arch based
* Persepolis Version: 2.4.2
* _Please attach log files if crash or paste error message_

**Issue Description and steps to reproduce:**
Just installed using `yaourt -S persepolis `
and the UI is not in English. I also read the wiki but didn't find the answer. 

![screenshot from 2017-06-24 00-57-34](https://user-images.githubusercontent.com/7912297/27497427-2e901a40-5878-11e7-9813-514480677800.png)

**Comment by ghost** [comment]
Is your local setting correct? 
```/etc/locale.conf```

**Comment by vikas5914** [comment]
cat /etc/locale.conf
`LANG=en_IN.UTF-8`

**Comment by ghost** [comment]
Change Font

**Comment by alireza-amirsamimi** [comment]
Do you set language and local information in your desktop environment?
what is your desktop environment?

**Comment by vikas5914** [comment]
Sorry for late reply 

@Mosi2772 no effect 

@alireza-amirsamimi  I use gnome. and I have set language and local information

**Comment by hayyan71** [comment]
Your locale is en_IN instead of en_US, which may caused issue.

For now,  you may change your locale to en_US.UTF-8 to fix your problem. I'll notify the Persepolis devs to check the different en_* locales and make changes if needed.

Thanks for submitting this bug.

**Comment by hayyan71** [comment]
tried to duplicate the problem, seems it's not related to your locale.
can you check this output of this command?

`lsof -p $(pidof persepolis) | grep -i font`

**Comment by vikas5914** [comment]
persepoli 3342 marcus5914  mem       REG                8,2   757076 37107398 /usr/share/fonts/TTF/DejaVuSans.ttf
persepoli 3342 marcus5914  mem       REG                8,2   705684 37107402 /usr/share/fonts/TTF/DejaVuSans-Bold.ttf
persepoli 3342 marcus5914  mem       REG                8,2   277888 36449449 /usr/lib/libfontconfig.so.1.9.3
persepoli 3342 marcus5914  mem       REG                8,2   103840 23071542 /var/cache/fontconfig/8d4af663993b81a124ee82e610bb31f9-le64.cache-7
persepoli 3342 marcus5914  mem       REG                8,2   217832 20719069 /home/marcus5914/.cache/fontconfig/88a6d207245ea8bdb91073d6f633ef66-le64.cache-7
persepoli 3342 marcus5914  mem       REG                8,2    69068 37108228 /usr/share/fonts/TTF/mal1-b.ttf
persepoli 3342 marcus5914  mem       REG                8,2   129400 23071538 /var/cache/fontconfig/f6b893a7224233d96cb72fd88691c0b4-le64.cache-7
persepoli 3342 marcus5914  mem       REG                8,2    69408 37108229 /usr/share/fonts/TTF/mal1-n.ttf
persepoli 3342 marcus5914  mem       REG                8,2     6368 23071539 /var/cache/fontconfig/6ba42ae0000f58711b5caaf10d690066-le64.cache-7
persepoli 3342 marcus5914  mem       REG                8,2    86760 23069726 /var/cache/fontconfig/f349e9996a5320f6dd491cedd2b1f964-le64.cache-7

**Comment by hayyan71** [comment]
@vikas5914 

Your system is using a wrong font (mal1-n.ttf. see [this](https://github.com/BlackArch/blackarch-iso/blob/master/live-iso/airootfs/usr/share/fonts/TTF/mal1-b.ttf)) for Persepolis. it happens in some programs when you give higher priority to your selected fonts in your conf file (when you install a new font , your fontconfig will be updated automatically and maybe some new fonts gets higher priority)

to solve this:

 - find where is these settings are stored:

`grep -Ril mal1 /etc/fonts/conf.d/` 
(hint: seems the full name of the font is akrutimal1)

For me (openSUSE) it's in /etc/fonts/conf.d/60-family-prefer.conf . other distros may save these settings somewhere else (but same directory).

- After you found the right conf file, open it with an editor with super user permissions.

- Search for your font in that file. it should be something like this:
`<family>Akrutimal1</family>`

Delete that line ( or give it lower priority than other fonts) and save the file. Restart Persepolis


P.S. if you've found this guide too much complicated or unclear, there is another (lazy) way. you may delete that font! (mal1-n.ttf and mal1-b.ttf)

**Comment by hayyan71** [comment]
I've forgot to tell something.

if you don't like to change your fontconfig priorities, you may tell Persepolis to use another font. 

it's possible from Persepolis settings. but if you can't access there, you can do this:

- open this file with an editor as normal user:
`.config/persepolis_download_manager/persepolis.conf`

- change
`custom-font=no`
to
`custom-font=yes`

and 

`font=something`

to 

`font=your_desired_font`

e.g

`font=Roboto`

- save the file and check the new settings.

**Comment by vikas5914** [comment]
@hayyan71 

I was not able to find that font in the etc. folder.  This package installed that font

https://www.archlinux.org/packages/extra/any/ttf-indic-otf/

your second option also not worked. 

FInally, I just deleted that font, and now it's in English.
