### ISSUE TITLE
افزودن پروکسی 

### ISSUE THREAD

**Issue by Mr-undead** [persepolisdm/persepolis#25]
در صورت امکان مقادیر پروکسی های زیر

``` bash
Polipo
Privoxy
Proxychains
```

به قسمت پروکسی به صورت اماده اضافه شود تا کاربر بتواند یکی را به دلخواه انتخاب کند و با این انتخاب مقادر آدرس و پورت برنامه به صورت اتوماتیک در برنامه تنظیم شود

**Comment by alireza-amirsamimi** [comment]
برنامه الان آخرین پورت و پروکسی رو سیو میکنه که کاربر نخوات دوباره بنویسه
ولی چرا چنتاشون با هم؟

**Comment by Mr-undead** [comment]
برای راختی کاربر میگم که دیگه نخواد چیزی تایپ کنه. ولی چرا چنتاشون با هم چون معمولا گنو/لینوکس کارها از تور به عنوان چیز شکن استفاده میکنند و با یکی از این برنامه ها پروکسی ساکس را به 
http
 تبدیل میکنند

**Comment by alireza-amirsamimi** [comment]
روش کار میکنم :)
