### ISSUE TITLE
side panel problem

### ISSUE THREAD

**Issue by aminbahraini** [persepolisdm/persepolis#250]
* Operating System / Distro: Linux / ubuntu 16.04
* Persepolis Version: 2.4.2

when i unchecked the "**show side panel**" (in preferences) it will checked again automatically after restarting persepolis.

**Comment by alireza-amirsamimi** [comment]
Hello
Thanks for reporting this bug.
I solved this bug with this [commit](https://github.com/persepolisdm/persepolis/commit/2b75f45442e031a088cb197e5f5f429f2543598b)
