### ISSUE TITLE
wiki: git installation instruction update

### ISSUE THREAD

**Issue by wulungnet** [persepolisdm/persepolis#251]
**System Details:**
* Operating System: linux
* Distro(For GNU/Linux and BSD users): ubuntu xenial
* Persepolis Version: git-latest

**Issue Description and steps to reproduce:**
Correctly install all requrements.
Run `sudo python setup.py install` got error `Linux detected!`
`Error : python3-pyqt5 is not installed!`
Try to install pyqt5-dev, still no luck.
**resolved** by using this command :
`sudo python3 setup.py install`
My linux obviously have `python2` and `python3`, with `python` command default to `python2`.

**Comment by alireza-amirsamimi** [comment]
Hello
Please see [Persepolis Wiki](https://github.com/persepolisdm/persepolis/wiki) for installation instaruction.
For ubuntu you can use our launchpad repository and install persepolis very easy! see [this](https://github.com/persepolisdm/persepolis/wiki/Ubuntu-installation-instruction) please.

If you want to test the latest change, make sure that all dependencies are installed on your system. Please see [this](https://github.com/persepolisdm/persepolis/wiki/git-installation-instruction) for more information.

**Comment by wulungnet** [comment]
Already resolved.
Just want you to update the [wiki](https://github.com/persepolisdm/persepolis/wiki/git-installation-instruction).
`sudo python setup.py install` >> `sudo python3 setup.py install`
Thanks for quick reply.

**Comment by alireza-amirsamimi** [comment]
Thank you for reporting this problem :) I'm Arch Linux user and I forgot that python2 is default in ubuntu!
I update wiki now 👍
