### ISSUE TITLE
مشکل در ادامه دانلود

### ISSUE THREAD

**Issue by abbasnaqdi** [persepolisdm/persepolis#252]
سلام . 
روی اوبونتو 16.4 مشکل داره وقتی اینترنت ضعیفه و روی دانلود میزنم دانلود انجام نمیشه هیچ اطلاعاتی نمایش نمیده و همونطوری ممونه وقتی هم روی حتی دکمه استپ هم کار نمیکنه و وقتی روی دکمه های پاوز و  ریزوم کلیک میشه صدا میده و خطای آریانا 2 میده .

لطفا رفع کنید . تشکر .

**Comment by alireza-amirsamimi** [comment]
@AbbasX <div dir="rtl">
سلام
اگر ممکن هست و به زبان انگلیسی تسلط نسبی دارید، در اینجا انگلیسی بنویسید ،تا افراد غیر فارسی زبان هم بتونن نوشته شما رو بخونند

مشکلی که میفرمایید از نسخه قدیمی آریا۲ در اوبونتو ۱۶.۰۴ هست.این مشکل در نسخه ۱.۳۲ نرم افزار آریا۲ حل شده ولی متاسفانه هنوز این نسخه وارد مخازن اوبونتو ۱۶.۰۴ نشده.
موفق باشید

**Comment by abbasnaqdi** [comment]
متاسفانه زبانم خوب نیست میترسم نتونم مفهوم رو درست برسونم . 
ورژن پرسپولیس من 2.4.2 هست .

**Comment by JafarAkhondali** [comment]
Please open a new issue if the problem exists within new version.
