### ISSUE TITLE
مشکل در دانلود فایل های بزرگ

### ISSUE THREAD

**Issue by abbasnaqdi** [persepolisdm/persepolis#253]
سلام ظاهرا در دانلود فایل ها مخصوصا فایل های بزرگ مشکل داره احتمال میدم از سر هم بندی 16 پارت فایل باشه اگر پارت بندی میکنه و یا اینکه از اول خراب دنلود میکنه

**Comment by alireza-amirsamimi** [comment]
@AbbasX <div dir="rtl">
من و بسیاری از دوستان فایل های چند گیگی زیادی با ۱۶ کانکشن باهاش دانلود میکنیم و مشکلی نیست (مثل فایلهای iso توزیع های لینوکسی و ...)
اگر اینترنتتون مشکلی داره و احتمال خرابی فایل رو میدید تعداد کانکشن رو بذارید روی ۱
البته این توضیح رو ضرروی میدونم که  بگم پرسپولیس کلاینت aria2c هست

**Comment by JafarAkhondali** [comment]
Please open a new issue if the problem exists within new version.
