### ISSUE TITLE
نرم افزار متوقف شد bug 

### ISSUE THREAD

**Issue by Pakrohk** [persepolisdm/persepolis#255]
```
GNU gdb (Ubuntu 7.11.1-0ubuntu1~16.04) 7.11.1
Copyright (C) 2016 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from /usr/bin/python3.5...(no debugging symbols found)...done.
Attaching to program: /usr/bin/python3.5, process 5284
Could not attach to process.  If your uid matches the uid of the target
process, check the setting of /proc/sys/kernel/yama/ptrace_scope, or try
again as the root user.  For more details, see /etc/sysctl.d/10-ptrace.conf
ptrace: Operation not permitted.
(gdb) 
```
دوستان علاوه بر مشکل بالا من هیچ دانلود شروع شدیی ای رو نمی تونم متوقف کنم و درضمن بعد از پاک کردن تعدادی از دانلود هام در لیست نرم افزار دیگه دانلودی رو حذف نمی کنه از صف 
در هنگام نمایش مقدار دانلود شده هم افزایش درصد ۵ درصدی هستش و گاهی دانلود در یک در صد خاص قفل میشه

ورژن پرسپولیس ۲.۴.۲
توزیع مینت کی دی ای ۱۸.۲  
نصب هم با
apt-get

**Comment by alireza-amirsamimi** [comment]
<div dir='rtl'>
سلام

اگه بتونید انگلیسی پیغام بگذارید که کاربران غیرفارسی زبان هم متوجه پیغام بشن خیلی خوب هست.
راستش متوجه مشکل و خطایی که فرستادید نشدم.
لطفا توضیح کامل تری بدید.
این گزارش چند مشکل هست یا یک مشکل؟ اگر لطف کنید جدا جدا برای هر مشکل Issue باز کنید ممنون میشم.اینجوری بهتر میشه مشکلات رو پیگیری کرد.

سپاس

**Comment by Pakrohk** [comment]
گذارش بالا برای یک مشکل هستش که متوقف شدن برنامه بود 
و خود مینت به من این ریپورت رو داد
در مورد مشکل های دیگی که وجود داره هم چشم 
سعیی می کنم در تایپیکی بهتر توصیح بدم ولی فعلا بگم که 
هنگامی که دانلود شروع میشه دیگه متوقف نمیشه

**Comment by JafarAkhondali** [comment]
Please open a new issue if the problem exists within new version.
