### ISSUE TITLE
Progress windows bug? + suggestion

### ISSUE THREAD

**Issue by hoquangnam45** [persepolisdm/persepolis#258]
**System Details:**
* Operating System: Linux
* Distro(For GNU/Linux and BSD users): Ubuntu 16.04
* Desktop Environment(For GNU/Linux and BSD users): Unity
* Persepolis Version: 2.4.2
* How do you install Persepolis? (Repositories, source, ...): Official PPA

When i maximize chrome, and persepolis is minimized to tray, the pop-up always appear behind chrome window, not on top of it, so i have to switch to the popup to begin download, which is kind of a hassle. Firefox is working correctly though.

Also why is there easy shortcut to delete file? And there's no easy way to select all of them, which is not very convenient when you have lots of files to delete.  

And is there any plan to add the ability create new category or detect duplicate link in the future

**Comment by hoquangnam45** [comment]
I found the solution for the first problem though, go to compiz > general > general option > focus and raise behavior > change focus prevention level to off

**Comment by alireza-amirsamimi** [comment]
Hello
Thanks for your report.
I fixed the bug of popup window before(for new version of persepolis) , and we will release new version very soon :)

Thanks for your feature requests. we will work on it.

**Comment by alireza-amirsamimi** [comment]
I added your feature request.
Now user can set custom shortcut in preferences window.
You can also clear download list from edit window and you can select all downloads with Ctrl+A.
Thanks for your request :+1:
