### ISSUE TITLE
Can't download from google drive and dropbox

### ISSUE THREAD

**Issue by hoquangnam45** [persepolisdm/persepolis#261]
**System Details:**
* Operating System: Linux
* Distro(For GNU/Linux and BSD users): Ubuntu 16.04
* Desktop Environment(For GNU/Linux and BSD users): Unity
* Persepolis Version: 2.4.2
* How do you install Persepolis: PPA 

As the title say, when i download from google drive, it download a servicelogin file not the file that i want and for dropbox it doesn't download anything, also i can't stop the download if i download from dropbox, has to run `sudo killall aria2c` to stop the download

**Comment by JafarAkhondali** [comment]
@hoquangnam45 Please upgrade extension to version 1.5.1 and try again. If problem didn't solve try installing Persepolis from git or wait for our new release which comes soon.

**Comment by hoquangnam45** [comment]
My extension is at 1.5.1. Aria2 seem to be the problem here, download google drive from the terminal result in aria2 download the servicelogin file. The error is
