### ISSUE TITLE
schedule

### ISSUE THREAD

**Issue by ghost** [persepolisdm/persepolis#27]
امیر جان به نظرم توو تمام دانلود منیجرهای لینوکسی هیچ کدوم مثل آی دی ام برنامه زمان بندی نداره
میتونی به عنوان یک گزینه مهم بهش نگاه کنی

**Comment by alireza-amirsamimi** [comment]
والا ویندوز و آی دی ام ندارم ببینم اون چه جوریه
انشالله روی سیستم یکی از رفقا که آی دی ام داره چک میکنم :)
ممنونم
البته فعلا پرسپولیس صف دانلود نداره ولی انشالله بهش اضافه میکنم که کاربر بتونه صف دانلود هم با زمانبندی داشته باشه :)

**Comment by ghost** [comment]
آی دی ام به نطر من بهترین سیستم زمان بندی رو داره توو دانلود منیجرا.
ولی همونطور که گفتی ، آره واسه لینوکس نداره متاسفانه
