### ISSUE TITLE
Persepolis failed to open

### ISSUE THREAD

**Issue by Mhs-220** [persepolisdm/persepolis#272]
**System Details:**
* Operating System: GNU/Linux
* Distro(For GNU/Linux and BSD users): Ubuntu 17.04
* Desktop Environment(For GNU/Linux and BSD users): Unity
* Persepolis Version: last version(sorry i cant open it)
* How do you install Persepolis? repositories

Traceback (most recent call last):
  File "./Persepolis Download Manager", line 305, in <module>
    mainwindow = MainWindow( start_in_tray , persepolis_download_manager , persepolis_download_manager.setting )
  File "/usr/share/persepolis/mainwindow.py", line 668, in __init__
    f = Open(queues_list_file)
  File "/usr/share/persepolis/newopen.py", line 66, in __init__
    shutil.copy(str(self.file_name), str(self.temp_file_path))
  File "/usr/lib/python3.5/shutil.py", line 241, in copy
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "/usr/lib/python3.5/shutil.py", line 121, in copyfile
    with open(dst, 'wb') as fdst:
PermissionError: [Errno 13] Permission denied: '/tmp/persepolis_mhs/14376500605403047460'

**Issue Description and steps to reproduce:**
hi there!
after i see that i cant' download any file with Persepolis (also same with uget) i think it should be for persepolis privilege to access where i located to save downloaded file. so i try to run from terminal and root privilege.. after then, i saw this message after open it.. but the ridiculous part is that it's still open from terminal with sudo but all of my queue is erased and its seem to this is the first day of an installed program.

**Comment by alireza-amirsamimi** [comment]
Hello
First of all : NEVER! run persepolis as root! :)
I don't think uget problem caused by persepolis.
For solving problem, you must delete all the files that was created by persepolis with root user.
Delete config folder first!
```
sudo rm -rf ~/.config/persepolis_download_manager/
```

Delete persepolis temp files

```
sudo rm -rf  /tmp/persepolis*
sudo rm -rf ~/.persepolis
```

Delete persepolis plugin wrapper folders

```
sudo rm -rf ~/.config/google-chrome/NativeMessagingHosts
sudo rm -rf ~/.mozilla/native-messaging-hosts/
```
Then run persepolis from terminal (WITHOUT ROOT ACCESS) and tell me if you have any error message.

**Comment by Mhs-220** [comment]
Hello again 
Thank you for your help!
every things work very well now
