### ISSUE TITLE
Main window & download window 

### ISSUE THREAD

**Issue by Omid888** [persepolisdm/persepolis#276]
OS : Arch(deepin) - Ubuntu(unity)
Persepolis version : 2.4.2
Installed by AUR & PPA

When I click on a link in my browser(chromuim & firefox) the download manager comes up and I can start downloading. But the issue is by clicking on a link in the browser , the Persepolis "main window" is launched from system tray(which I **don`t** need it to be launched) and the "download window" **doesn't come** up on top of all other windows (especially browser) for me to click on the start button. In fact it is launched but in the minimized mode and I have to click on it in the system's menu to open it and then click on start download button.
Thanks for your excellent effort.
It really means a lot to us.

**Comment by alireza-amirsamimi** [comment]
Hello
Thank you :)
I solved this problem in this [commit](https://github.com/persepolisdm/persepolis/commit/d102e22948b5dced5c796d1891a6b5bd88f898a6) .
We will release new version soon and this bug is solved in 2.5 .
