### ISSUE TITLE
open two windows for a file

### ISSUE THREAD

**Issue by mehdirajabi59** [persepolisdm/persepolis#28]
سلام

من دوبار کلیک کردم روی آیکون استارت دانلود برای یک فایل که دو پنجره باز شد برای دانلود که یکش کار میکرد یکش هم کار نمی کردو اینکه بعد اینکه دوبار کلیک اروو زیر رو داد

در اصل باید وقتی یکبار کلیک میکنی آیکون استارت غیر فعال بشه
aria2 not response

**Comment by mehdirajabi59** [comment]
screenshot

https://i.imgsafe.org/058b338cbf.png

**Comment by alireza-amirsamimi** [comment]
درود بر دست سریعت که باگ رو گرفت :))
مرسی
درستش کردم :)
