### ISSUE TITLE
Error while adding new link from flashgot on firefox (when /tmp space is full)

### ISSUE THREAD

**Issue by behnambagheri** [persepolisdm/persepolis#280]
**System Details:**

- OS: Arch ( x86_64 Linux 4.11.9-1-ARCH )
- DE: KDE 5.36.0 / Plasma 5.10.4
- Persepolis Download Manager 2.4.2
- * How do you install Persepolis? AUR 

_In the last line it says **OSError: [Errno 28] No space left on device** But it is not!_

* _Please attach log files if crash or paste error message_ 
```
**Traceback (most recent call last):
  File "./Persepolis Download Manager", line 305, in <module>
    mainwindow = MainWindow( start_in_tray , persepolis_download_manager , persepolis_download_manager.setting )
  File "/usr/share/persepolis/mainwindow.py", line 708, in __init__
    f = Open(queues_list_file)
  File "/usr/share/persepolis/newopen.py", line 66, in __init__
    shutil.copy(str(self.file_name), str(self.temp_file_path))
  File "/usr/lib/python3.6/shutil.py", line 241, in copy
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "/usr/lib/python3.6/shutil.py", line 122, in copyfile
    copyfileobj(fsrc, fdst)
OSError: [Errno 28] No space left on device**
```

**Comment by hayyan71** [comment]
@behnambagheri please run the "df" command and paste the output here:

**Comment by alireza-amirsamimi** [comment]
Thanks for reporting.
Check your /tmp and ~/home
Do you have enough space in /tmp and ~/home?

**Comment by behnambagheri** [comment]
@alireza-amirsamimi 
Yes, there are about 20G of free space
@hayyan71
`df`:
https://beepaste.io/view/zkCtoc
```
Filesystem     1K-blocks      Used Available Use% Mounted on
dev              4044340         0   4044340   0% /dev
run              4048828      1484   4047344   1% /run
/dev/nvme0n1p3  41022688  17990356  20918796  47% /
tmpfs            4048828        40   4048788   1% /dev/shm
tmpfs            4048828         0   4048828   0% /sys/fs/cgroup
tmpfs            4048828   4048828         0 100% /tmp
/dev/nvme0n1p4  72489356  26754440  42009640  39% /home
/dev/nvme0n1p1    523248     59220    464028  12% /boot
/dev/sda1      488385532 334271592 154113940  69% /Internal
tmpfs             809764        80    809684   1% /run/user/1000
```

**Comment by alireza-amirsamimi** [comment]
/tmp space is full!!
reboot your system.
What is output of this command
```
persepolis --version
```

**Comment by behnambagheri** [comment]
Thank you very much for answering. <3
> persepolis --version
`Persepolis Download Manager 2.4.2`

i use this command to cleanup /tmp:
`find /tmp -ctime +10 -exec rm -rf {} +`
and persepolis is work but i don't see my Queue :(

**Comment by alireza-amirsamimi** [comment]
Thanks for reporting again.
I add BUG tag to this issue and I will work on this issue :)
