### ISSUE TITLE
Undefined name 'dictvalue' in update.py

### ISSUE THREAD

**Issue by cclauss** [persepolisdm/persepolis#286]
This issue will only be seen on Mac and Windows.

flake8 testing of https://github.com/persepolisdm/persepolis

$ __flake8 . --count --select=E901,E999,F821,F822,F823 --show-source --statistics__
```
./persepolis/scripts/update.py:115:44: F821 undefined name 'dictvalue'
                        osCommands.xdgOpen(dictvalue['win64dlurl'])
                                           ^
./persepolis/scripts/update.py:117:44: F821 undefined name 'dictvalue'
                        osCommands.xdgOpen(dictvalue['win32dlurl'])
                                           ^
./persepolis/scripts/update.py:120:40: F821 undefined name 'dictvalue'
                    osCommands.xdgOpen(dictvalue['macdlurl']) # it will download latest release for mac
                                       ^
```

**Comment by alireza-amirsamimi** [comment]
I have no idea why flake8 shows this, But I tested persepolis and every thing is ok! :)

**Comment by cclauss** [comment]
Tested on Windows or on Mac?  These lines will only get executed on those platforms.

**Comment by alireza-amirsamimi** [comment]
I tested in ArchLinux. I'm GNU/Linux user.
Please see our [wiki](https://github.com/persepolisdm/persepolis/wiki) for installing persepolis on Mac or MicroSoft Windows
