### ISSUE TITLE
Some feature requests

### ISSUE THREAD

**Issue by msm1365** [persepolisdm/persepolis#287]
<div dir=rtl>
در بخش download all links طبیعتا فایل های زیادی پیدا میکنه که همه اونها مورد نیاز نیست و باید یکی یکی تیک بزنیم یا برداریم. بهتره یک سری گزینه های کلی بالای صفحه بذاریم که تیک کلی انجام بده. مثلا گزینه PDF اگه کلیک کنیم همه PDF ها انتخاب شوند و بقیه از انتخاب حذف شوند. گزینه های PDF MKV MP4 MP3 HTML پیشنهاد میشوند. ( در بخش فیلم اگر امکانی اضافه شود کیفیت های مختلف مثل 480 و 720 هم تیک داشته باشند بسیار کامل می شود )

دکمه remove all files و Clean Downloded Files  تو بخش لیست اصلی نداره.

گزینه تعداد دانلود همزمان و دانلود از یوتیوب توسط کروم هم که دوستان اشاره کردن.

با توجه به اینکه برنامه بسیار کاربردی است سعی میکنیم به مخازن اصلی فدورا اضافه شود.

**Comment by msm1365** [comment]
به هم ریخته است که متن!!!

**Comment by alireza-amirsamimi** [comment]
Thanks for your feature requests :)
Please always use english language here, Because of the other Non-Persian language followers.
Please open new issue for every feature request.

**Comment by JafarAkhondali** [comment]
@msm1365 This featured is now implemented is WebExtension, perhaps it would take a while to implement this in PDM itself, please open a new issue if you really need it on PDM itself.
