### ISSUE TITLE
یه مشکل خیلی بد

### ISSUE THREAD

**Issue by msm1365** [persepolisdm/persepolis#288]
وقتی فیلم دانلود میکنیم نمیشه مقدار دانلود شده تماشا کنیم. اما خود آریا این امکان داره.

**Comment by alireza-amirsamimi** [comment]
Please use english language here and please select proper subject for issues :)
Please explain more.

**Comment by msm1365** [comment]
موافق متن انگلیسی نیستم. خارجی ها تلاش کنند زبان ما را یاد بگیرند. اگر هم به انگلیسی سوالی کردند به انگلیسی جوابش را بدهید.

**Comment by hayyan71** [comment]
<div dir="rtl"> 

درود دوست عزیز.

به علت اینکه مرجع پاسخگویی و رفع مشکلات کاربران پرسپولیس صفحه ی گیت هاب پروژه میباشد، و همچنین کاربران غیر پارسی زبان پرسپولیس نیز موجود هستند. باید سوالات و مشکلات به زبان انگلیسی مطرح شوند تا سایر کاربران نیز موضوع را درک کرده و در صورت داشتن مشکل مشابه آن را اعلام کنند.

موفق باشید.

**Comment by hayyan71** [comment]
<div dir="rtl">
درود دوست عزیز. 
 
به علت اینکه مرجع پاسخگویی و رفع مشکلات کاربران پرسپولیس صفحه ی گیت هاب پروژه میباشد، و همچنین کاربران غیر پارسی زبان پرسپولیس نیز موجود هستند. باید سوالات و مشکلات به زبان انگلیسی مطرح شوند تا سایر کاربران نیز موضوع را درک کرده و در صورت داشتن مشکل مشابه آن را اعلام کنند. 
 
به طور قطع صحبت کردن به زبان پارسی برای ما راحت تر است، اما پیگیری ایرادات پر تکرار و مهم پرسپولیس در اولویت ماست.

موفق باشید.

**Comment by JafarAkhondali** [comment]
@msm1365 Aria2c uses 1 thread by default ( unless run with -x option). Persepolis uses -x option and download the file in parallel. That's how the speed gets higher, and this features wont let you watch movie before finishing (at least easily).
