### ISSUE TITLE
اینترگیت نشدن فلش گات با پرسپولیس

### ISSUE THREAD

**Issue by LinArcX** [persepolisdm/persepolis#29]
علی جان طبق صحبت هایی که تو  آموزش هات داشتی در مورد اینتگریت کردن فلش گات با پرسپولیس، من تمامی مراحل رو قدم به قدم رفتم.
منتهی رو هر لینکی کلیک میکنم و اسه دانلود اون پنجره انتخاب دانلود منیجر میاد 
اما روی pdmt که میزنم 
عملا هیچ اتفاقی نمیفته.یعنی کلا برنامه باز نمیشه که دانلودی انجام بده.

**Comment by alireza-amirsamimi** [comment]
روح مرحوم 
pdmt
شاد:))
احتمالا اطلاعات فلش گات رو اشتباه مینویسی
یه اسکرین شات از تب های مختلف فلش گات به من بده ببینم مشکل کجاست
ورژن ۲.۰.۲ رو نصب کن

**Comment by LinArcX** [comment]
بله حق با شما بود.ایراد از تنظیمات من بود که به اشتباه تنظیمات قدیمی رو کپی کرده بودم.
این تنظیمات باید اعمال میشده در اصل:
[--link URL][--name FNAME][--cookie CFILE][--referer REFERER][--headers HEADERS][--agent UA]

**Comment by alireza-amirsamimi** [comment]
:)
