### ISSUE TITLE
Estimated time isn't 0 but download is finished!

### ISSUE THREAD

**Issue by Navid-Ivanian** [persepolisdm/persepolis#291]
**System Details:**
* Operating System: Linux
* Distro(For GNU/Linux and BSD users): Ubuntu 16.04.2
* Desktop Environment(For GNU/Linux and BSD users): Unity
* Persepolis Version: 2.4.2
* How do you install Persepolis?Repositories

I think the issue is clear from title!Just a shot from the problem to make it more clear :)

![screenshot](https://user-images.githubusercontent.com/21077608/29176957-eec5f044-7ddc-11e7-804c-5091671771c8.jpg)

**Comment by alireza-amirsamimi** [comment]
I fixed this bug.
Thanks for reporting :+1:
