### ISSUE TITLE
flashgot should disable for activate multiprocess in firefox 55

### ISSUE THREAD

**Issue by Monirzadeh** [persepolisdm/persepolis#296]
**System Details:**
* Operating System: Linux
* Distro(For GNU/Linux and BSD users): Ubuntu 16.04
* Desktop Environment(For GNU/Linux and BSD users): unity
* Persepolis Version: 2.4.2
* How do you install Persepolis?Repositories

the new version of Firefox release (55 v) for Ubuntu and you can active multiprocess by disabling some add-ons that not compatible with new Firefox system( v57 ). you can read about electrolysis project and https://support.mozilla.org/en-US/kb/firefox-add-technology-modernizing?as=u&utm_source=inproduct
unfortunately Flashgot not compatible with the new system so we can't use Flashgot for Persepolis.
please if it possible, release Persepolis add-ons that compatible with new system sooner

**Comment by alireza-amirsamimi** [comment]
Hello
Thanks for reporting this :)
Our firefox plugin is almost ready for use now. We introduce it in our next release :)

**Comment by JafarAkhondali** [comment]
@Monirzadeh 
Thanks for reporting, As @alireza-amirsamimi mentioned earlier Firefox plugin is ready to use and is it's based on WebExtensions (what Firefox +57 supports). We are now improving it's performance a little bit but feel free to download and test the extension in Mozilla repository, and give us a feedback.

**Comment by Monirzadeh** [comment]
hi, I install add-ons 
https://addons.mozilla.org/en-US/firefox/addon/persepolis-dlm-integration/
and click integrate with Firefox in Persepolis (Show done) but add-ons don't work

**Comment by JafarAkhondali** [comment]
@Monirzadeh Sorry for delay, Maybe you installed the git version? currently it's under development and seems to have some temporary problems.

**Comment by Monirzadeh** [comment]
no, i install from the repository 
I uninstall and install Persepolis again but doesn't work

**Comment by JafarAkhondali** [comment]
Can you post the content and permission of this file ? 
`~/.mozilla/native-messaging-hosts/com.persepolis.pdmchromewrapper.json `
If it doesn't exists, Enable Firefox integration in Help menu of PersepolisDM

**Comment by Monirzadeh** [comment]
`{"path": "/usr/bin/persepolis", "allowed_extensions": ["com.persepolis.pdmchromewrapper@persepolisdm.github.io", "com.persepolis.pdmchromewrapper.offline@persepolisdm.github.io"], "name": "com.persepolis.pdmchromewrapper", "type": "stdio", "description": "Integrate Persepolis with firefox using WebExtensions"}`

permission of file is 775

**Comment by Monirzadeh** [comment]
and one more problem. sometimes like this [link]( https://longreadsblog.files.wordpress.com/2017/08/gettyimages-653027122.jpg?w=1200)
you can't access Persepolis in right-click menu

**Comment by JafarAkhondali** [comment]
It's a weird problem, We'll work on it before new release.
The link you have provided is an image/webp so chromium renders it as an image. Currently we are using a.href in document to find links, do you think it's a good practice to add images in finding links too?

**Comment by Pakrohk** [comment]
I had no problem with version 57

**Comment by grahamperrin** [comment]
> … click integrate with Firefox in Persepolis (Show done) …

Where's this?

**Comment by Monirzadeh** [comment]
> > … click integrate with Firefox in Persepolis (Show done) …
> 
> Where's this?

for old version that has this option in about menu but now you don't need that option anymore.
only install this [add-ons](https://addons.mozilla.org/en-US/firefox/addon/persepolis-dlm-integration/)
if you use windows run Persepolis in the system try or if use Linux not necessary to do that.
Persepolis run automatically and get the links

**Comment by JafarAkhondali** [comment]
Please create a new issue if it still exists with new version.
