### ISSUE TITLE
یک گذینه ی جدید

### ISSUE THREAD

**Issue by Pakrohk** [persepolisdm/persepolis#298]
یک دکمه به پرسپولیس اضافه کنید. که در هنگام شروع دانلود تعیین کند که دانلود پس از پایان دانلود در حال انجام شروع شود یا در جا
مثلا تصور کنید در حال دانلود چند موزیک هستید و می خواهید فایلی که الان در صف گذاشتید بجایی که شروع به دانلود کند بعد از پایان دانلود قیلی شروع کن حالت اولویت بخشی

**Comment by alireza-amirsamimi** [comment]
@APakrohk Please use English language here. thank you

**Comment by hayyan71** [comment]
@APakrohk This is not a good idea. If you wanna Download 1 file each time, you may put them in the queue
