### ISSUE TITLE
کار نکردن بخش Properties 

### ISSUE THREAD

**Issue by farhadhp** [persepolisdm/persepolis#3]
با سلام برای من منوی 
**Properties**
 کار نمیکنه روش کلیک میکنم ولی باز نمیشه.
بقیه منوها درست کار میکنند.
از ابونتو ۱۶.۰۴ استفاده میکنم.

**Comment by alireza-amirsamimi** [comment]
داخل ترمینال بزنید
persepolis
وقتی برنامه اجرا  شد ، پنجره 
properties
رو باز کنید و به من بگید چه پیغامی میده
ممنونم

**Comment by farhadhp** [comment]
فقط موراد زیر رو نشون میده.
البته با کلیک روی ‍پراپرتیز
`

---

---

***_Persepolis Download Manager**_*
***\*  Version : 2.0.0 Unstable ****

---

---

0
Aria2 Version : 1.19.0
`

اما وقتی روی دکمه استارت و استا‍ کلیک میکنم کدهایی نشون میده.

**Comment by alireza-amirsamimi** [comment]
عجیبه
فقط دو نفر از دوستانی که اوبونتو دارند این مشکل براشون پیش اومده و برای بقیه کار میکنه
یه زحمت میکشی ؟
تنظیمات برنامه رو از توی پوشه برنامه حذف کن (مثل هممون کاری که تو فیلم کردم)
و بعد دوباره برنامه رو دانلود کن و نصب کن. ببین مشکل حل میشه؟

**Comment by farhadhp** [comment]
با تشکر با آپدیت مشکل حل شد.
ممنون از راهنماییتون.
