### ISSUE TITLE
remove download

### ISSUE THREAD

**Issue by Mr-undead** [persepolisdm/persepolis#30]
زمانی که چندین دانلود را انتخاب کرده و قصد حذف کردن آنها را از لیست دانلود ها داریم با کلیک بر روی دکمه 
remove download 
ایتم های انتخاب شده تک به تک حذف میشوند که این خود باعث گرفتن وقت زیادی از کاربر خواهد شد در صورت امکان مکانیزمی جهت حذف کردن یکباره دسته جمعی ایتمها تعبیه شود

**Comment by alireza-amirsamimi** [comment]
پیشنهاد خوبی هست
فعلا کلیات برنامه به حالت استیبل برسه و آرام آرام جزئیات رو اضافه میکنم
