### ISSUE TITLE
Left-Side Panel BUG

### ISSUE THREAD

**Issue by aminbahraini** [persepolisdm/persepolis#300]
* Operating System: Linux
* Distro(For GNU/Linux and BSD users): Mint 18.2
* Desktop Environment(For GNU/Linux and BSD users): Cinamon
* Persepolis Version: 2.4.2
* How do you install Persepolis? repo - persepolis/ppa

hi,
**unchecked** the "**show side panel**" (in preferences) won't be saved, after restarting persepolis it will checked again automatically
and it wont save the **resize**(side panel) either...

thanks.

**Comment by alireza-amirsamimi** [comment]
Hello
Thanks for reporting
I think you reported it [before](https://github.com/persepolisdm/persepolis/issues/250), am i right?
I solved this bug, But it will publish in our new release :)

**Comment by aminbahraini** [comment]
yes i reported before but resize is a **NEW BUG**
anyway...
can i fix it NOW?
because it's reallllllllly annoying!


thanks

**Comment by alireza-amirsamimi** [comment]
Thanks for reporting
It's reported [before](https://github.com/persepolisdm/persepolis/issues/265)
We will work on it :)
