### ISSUE TITLE
Add internationalizatoin support

### ISSUE THREAD

**Issue by hedayat** [persepolisdm/persepolis#301]
It seems that currently Persepolis doesn't have internationalization support, so it cannot  be translated to other languages. I think this is an important future, and pretty easy to add, so I hope to see it soon.

Then, I'd suggest using Zanata or Transifex platforms for Persepolis translation.

**Comment by hayyan71** [comment]
@hedayat 

We've added support for other language in the latest commits. So, now everyone can translate Persepolis to their native language!

You can find a quick guide how to translate Persepolis here:
https://github.com/persepolisdm/persepolis/wiki/translators-guide

Maybe we missed some phrases for translations. So, feel free to report bugs in Persepolis github page.

Regards

**Comment by hedayat** [comment]
Thanks, so I think this issue can be closed (although, internationalization support isn't limited to translations, but the main point of this issue was translations). 

BTW, you might still think about using translation platforms, which allows non-developers (and people who don't know/like to work with git & cmdline) to also participate in translating Persepolis.

Thanks again!

**Comment by hayyan71** [comment]
@hedayat many pyqt projects are using Qt built-in feature for translations. So, we've decided to use Qt features for translating Persepolis to other languages.

Transifex/Zenata are using GNU Gettext for translations, which is different method.

**Comment by hedayat** [comment]
If I'm not mistaken, both Zanata & Transifex do support Qt .ts files in addition to GNU Gettex .po files (and also some other formats).

**Comment by hayyan71** [comment]
@hedayat

**Comment by hayyan71** [comment]
@hedayat 

Thanks. I'll check both website and see which project will make translation process much easier

**Comment by leoxxx** [comment]
I hope support edit a language file directly.
Files such as:ini,lua and so on.
The file contents is text.
For example:

>  [Audio]
> volume = 音量
Or
> msgid "This means that your system is running dbvm. This means ce will make use of some advanced tools that are otherwise unavailable"
> msgstr "这表示你的系统正在运行 DBVM.以及 CE 还可以使用一些更先进的工具"

Then save it. Change the file name to your translation.
For example: EN.ini--->SC.ini(简体中文)
Go to software and select the language.
I think it's easy to a non-developer.
Everyone only commit the text in file here.

**Comment by hedayat** [comment]
@hayyan71 You're welcome!
@leoxxx No, that wouldn't work. But using a translation service like the mentioned ones should be both good for developers to consume and update translations, and for non-developers to actually do the translations. It is actually even easier than editing a text file as you said. Using such services, you'll be also able to contribute to many other projects too.

**Comment by hayyan71** [comment]
submitted a pull request for integrating Persepolis translation files with Transifex.

https://github.com/persepolisdm/persepolis/pull/423

**Comment by leoxxx** [comment]
@hedayat
I agree with your opinion for using translation platform.
It's helpful to contribute to the project.
But it need integrating by developer.
I hope WYSIWYG,
So I hope our opinions are used together.

**Comment by hayyan71** [comment]
We've uploaded translation files on transifex.org. from transifex.com, you can start to work on translating Persepolis without installing any additional software.

Also, we just updated our wiki page: https://github.com/persepolisdm/persepolis/wiki/translators-guide

Regards

**Comment by leoxxx** [comment]
@hayyan71
https://crowdin.com/
After regsiter,it can select projects and any languages to translate free.
https://www.transifex.com
Need click "Join team" and select one language to receive a translation request.
It must pass request by project master,not free.

**Comment by hayyan71** [comment]
@leoxxx 

Just checked both. crowdlin.com and transifex.com services are free for open source projects.
Transifex integration was easier to setup, and seems people like to work on Transifex.com more than other
 services (more than 1 person requested to use Transifex platform for translating Persepolis.)

and I've changed team settings in transifex.com, so anyone who was accepted as translator can join any team.
