### ISSUE TITLE
Add AppStream metadata

### ISSUE THREAD

**Issue by hedayat** [persepolisdm/persepolis#302]
AppStream is used to present applications in software center applications (e.g. Gnome Software). It'd be great to add AppData for Persepolis, which will be used by different distributions.

https://www.freedesktop.org/software/appstream/docs/chap-Quickstart.html#sect-Quickstart-DesktopApps

**Comment by alireza-amirsamimi** [comment]
xml file was added in this [commit](https://github.com/persepolisdm/persepolis/commit/fc0b3a0cc1b1bb05486f41da83f375ab1ecf28c3). please check the xml file :) Thanks.
