### ISSUE TITLE
'python3 setup.py build' doesn't work properly!

### ISSUE THREAD

**Issue by hedayat** [persepolisdm/persepolis#303]
**System Details:**
* Operating System: GNU/Llinux
* Distro(For GNU/Linux and BSD users): Fedora
* Persepolis Version: Git

Running 'python3 setup.py build', does build the project. However, in the last steps it removes all build artifacts, effectively does a build & clean operation at once! Which makes setup.py build completely useless.

This is the last 2 lines of 'setup.py build' output:
```
....
build is removed!
persepolis.egg-info is removed!
```

**Comment by alireza-amirsamimi** [comment]
@hedayat Hello
It's remove them after installation complete. because after installation , user doesn't want them.
I strongly recommend you to use our repository for installing persepolis.
Using setup.py and installing from git is only for testing and development.
For now I'm beasy for rewriting codes and we have many changes in next version and because of this , the git version is unstable now! Please use stable version of persepolis from our repositories.
Thank you :)

**Comment by hedayat** [comment]
Yes, I understood what was intended, but it should be limited to 'setup.py install'. 'setup.py build' is expected to produce build artifacts.
Well, as you are doing a rewrite, I think I'll wait for that. Actually, my intention is not to simply install Persepolis, I want to create a proper Fedora .rpm package for it (to submit to Fedora official repositories). While it is possible to skip the 'build' step and do an install directly, it is better to have separate build & install stages, which is supported by Python setuptools. But your package effectively doesn't support setuptools 'build' command. 

To be more standard, I'd suggest to follow the normal convention for build & install commands. To cleanup build artifacts, it is preferred to support the standard 'setup.py clean' command.

Regards

**Comment by alireza-amirsamimi** [comment]
@hedayat Thanks for your explanation :)
For package build and ... you must use
--root
 .
see our [aur package build](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=persepolis-git)  , may it helps you.
Thanks for trying to submit persepolis for fedora official repository but please wait until our new release in end of September :-)
If
--root
didn't solve the problem, please feel free to inform me :-)

**Comment by hedayat** [comment]
:) Your welcome, OK I'll wait for your new release.
However, it seems that I failed to explain well. `--root ` is used for 'setup.py install'. The problem is that you go using `setup.py install` in your AUR package build. It is possible, but discouraged in Fedora. In Fedora, it is encouraged to do all build steps in a build stage (all what is done before creating the `--root` directory), done by `setup.py build`, then to ONLY install files in `setup.py install`. This is supported by most Python `setuptools` packages, but it seems that your package's support of setup.py differs from the standard method. 

To make my intention more clear, let me explain the standard method used in Fedora to build Python setup tools packages:

We `build` the package using this command:
`/usr/bin/python3 setup.py  build --executable="/usr/bin/python3 -s"`
(which doesn't actually do anything in current Persepolis master).

Then, there is an `install` step in which this command is run:
`/usr/bin/python3 setup.py  install -O1 --skip-build --root /some/directory/`
which is supposed to install the package in the given directory, and explicitly skips the build stage.

Well, since your package is a pure Python package, it is probably not much important to have a separate 'build' step. But anyway, to be a standard setuptools package, I'd encourage you supporting build, install and clean commands properly and to NOT cleaning everything after the install command.

But if you feel it is not needed for Persepolis, you can close this issue. :)

**Comment by alireza-amirsamimi** [comment]
@hedayat Thanks for your explanation again :) It's different in ArchLinux.
I am rewriting code of persepolis for next release in another repository and finally after I finish writing, I will send pull request for this main repository. Many things will change after that final pull request. 
I will change setup files for fedora too and notify you here for testing changes. So please don't close the issue and stay tuned :)
Regards

**Comment by hedayat** [comment]
Thanks again. :)  Looking forward for the new version.

**Comment by alireza-amirsamimi** [comment]
@hedayat 
Hello
I fixed the problem.
Please check again:)

**Comment by hedayat** [comment]
Oops, for whatever reason, I didn't see you fixed it. :) Thanks!

**Comment by hedayat** [comment]
Oops, for whatever reason, I didn't see you fixed it. :) Thanks!
