### ISSUE TITLE
Do not change the filename

### ISSUE THREAD

**Issue by Pakrohk** [persepolisdm/persepolis#304]
Hi
The file name does not change.
I'll name it, but after downloading it will remain the same name

**Comment by alireza-amirsamimi** [comment]
Thanks for reporting this bug.

**Comment by par6n** [comment]
I think [this line](https://github.com/persepolisdm/persepolis/blob/master/persepolis/scripts/addlink.py#L446) should be changed in order to squish this bug.

**Comment by alireza-amirsamimi** [comment]
I fixed the Bug :)
We will release new version  soon
