### ISSUE TITLE
queue doesn't have any download limits

### ISSUE THREAD

**Issue by salehiali1374** [persepolisdm/persepolis#307]
**System Details:**
* Operating System: GNU/linux
* Distro(For GNU/Linux and BSD users): ubuntu 16.04
* Desktop Environment(For GNU/Linux and BSD users): gnome
* Persepolis Version: 2.4.2
* How do you install Persepolis? Repositories

it seem's queue doesn't have any download limits, like the single downloads. so if I start queue, I can't even open a web page.

**Comment by alireza-amirsamimi** [comment]
@salehiali1374 Hello
Please start a queue. when queue starts , you can find limit option on the left side of main window.

**Comment by salehiali1374** [comment]
thank you.
