### ISSUE TITLE
دریافت تاییدیه هنگام حذف فایل یا حذف صف دانلود

### ISSUE THREAD

**Issue by LinArcX** [persepolisdm/persepolis#309]
درود علی جان.
آقا من جدیدا چندین فایلمو به خاطر سهل‌انگاری خودم یا درگیربودن ذهنم از دست دادم هنگام دانلود.
ببین قضیه از این قراره که کارهای روزمره تو داری با کامپیوتر میکنی و یه فیلم یا موزیکی هم برای دانلود گذاشتی، بعد هر ازگاهی وسط کارت میای به پرسپولیس سر میزنی ببینی وضعیت دانلود چطوری هست.
یا مثلا یه جایی نیاز داری صف رو استاپ کنی تا کارهای دیگه تو با اینترنت با سرعت بیشتری انجام بدی.
اینجاست که اون وضعیت بد پیش میاد.
از اونجایی که دکمه‌ی حذف از لیست و حذفِ صف در کنار دکمه های استاپ و ریزوم قرار گرفته‌اند و هنگام حذف کردن هیچ تاییده‌ای بهت نمیده که آقا فلان فایلت حذف شد یا فلان لیست داره حذف میشه، به نظر من بهتره روی دومرحله‌ای کردن حذف فایل‌ها و صف‌ها از کاربر تاییدیه بگیری و اینو پیش‌فرضش کنی و درنهایت آپشنی در تنظیمات بذاری که کاربر بتونه خودش به دلخواه این رفتار رو کنترل کنه.
فک می‌کنم مشکل آدم‌های حواس پرت و عجولی مثل من هم که سهوا میزنن یه فایلی رو حذف میکنن، با این کار جلوگیری میشه.
ممنونم پیشاپیش

**Comment by alireza-amirsamimi** [comment]
Hello :)
Please use english language :)
I fixed the problem.
