### ISSUE TITLE
غیر فعال کردن نوتیفیکش ها

### ISSUE THREAD

**Issue by LinArcX** [persepolisdm/persepolis#31]
تو تنظیمات میشه گزینه ای رو اضافه کرد که کاربر در صورت صلاحدید نوتیفیکشن ها رو غیر فعال کنه.
تو سینی سینمون هم هی عدد این نوتیفیکشن میره بالا و یجورایی کلا ارتباط برقرار نمیکنم باهاش :)

**Comment by alireza-amirsamimi** [comment]
نوتیفیکیشن ضروری هست
یه وقت هایی به کاربر اخطار میده
و اخطار ها هم گهگاهی مهم هست

**Comment by LinArcX** [comment]
Hi dear ali. Notifications sometimes acutally very annoying. Today i  wanted to clear all items from persepolis that downloaded before. After a while, all items cleared one by one with a delay and ringing a bell sound. any way...
After that for every item, a pop up notification brings in right corner and said to me: "that file Not Found!"
Ok. i know that the Notifications are very important for debugging/troubleshooting for the app. ‌‌But you can deliver it to the user to choose if he/she want nofication or not. and for those critical messages for trobleshooting, you can always push them in a log file. Every time user face a problem he/she can go to log file and send it for you. I think this strategy will improve the user experience (UX).
