### ISSUE TITLE
پیش نمایش وضعیت دانلود جاری در سینی دسکتاپ

### ISSUE THREAD

**Issue by LinArcX** [persepolisdm/persepolis#310]
در راستای ایشوی 
https://github.com/persepolisdm/persepolis/issues/309
می خواستم یه پیشنهاد دیگه هم بدم علی جان.
اینکه برای خودم خیلی پیش اومده وسط یه کاری نیاز داشتم پرسپولیس رو متوقف کنم و از نتم جای دیگه بهره ببرم.کاری که میکنم سوییچ بین پنجره های پرسپولیس و نرم افزارهامه که ببینم مثلا چند درصد دیگه از دانلودم باقی مونده.
اگه نزدیک به 100 باشه ولش میکنم تا کارشو انجام بده و بعد میرسم به سراغ کارهای اصلیم و اگه خیلی از دانلود مونده باشه به صورت موقت قطعش میکنم و از نتم در جاهای دیگه استفاده میکنم.
پیشنهادی که داشتم این بود که توی سینی میزکارها امکانی رو اضافه کنی که دانلود جاری رو به همراه سرعت دانلود و زمانی که تا انتهای دانلود مونده نشون بده و دکمه های استاپ و ریزوم هم براش بذاری که کاربر دیگه مدام بین پنجره ها سوییچ نکنه.هم سینی چیزی هست که همواره در دسترسه و ذهن رو دچار پرش نمیکنه و هم اینکه تجربه کاربری ملایم تری خواهیم داشت.
واسه مثال هم [دیلاگ](http://uupload.ir/files/2e0x_sini.png) که تورنت دانلودر هست این ایده رو هرچند خیلی ضعیف پیاده کرده.
اگه بتونی دکمه های استاپ و ریزوم هر در همون سینی نشون بدی فوق العاده میشه.

**Comment by alireza-amirsamimi** [comment]
Nice 👍 
Please use english language:)

**Comment by alireza-amirsamimi** [comment]
Hello
I added this feature :)

![screenshot_20180203_135051](https://user-images.githubusercontent.com/7452500/35766300-da8990ec-08ea-11e8-8009-3ee77b69012f.png)
