### ISSUE TITLE
How to change the download data folder of system's hard disk?

### ISSUE THREAD

**Issue by BFNOC** [persepolisdm/persepolis#312]
Operating System:Windows 7 SP1 64Bit.
Persepolis Version:2.4.2 64Bit

My system hard disk is SSD.
Its lifetime is very short.
So I need to change the download data folder from the system hard disk to another hard disk!
(above use google translate)

**Comment by alireza-amirsamimi** [comment]
@HFX3389 Hello
Please select "Preference" from "Edit" menu.
Then click on "Save as" tab.
You can change download folder there.

**Comment by BFNOC** [comment]
@alireza-amirsamimi Thanks.I see the "Temporary Download Folder".
