### ISSUE TITLE
no error mesage

### ISSUE THREAD

**Issue by moslemghazanfari** [persepolisdm/persepolis#317]
**System Details:**
Operating System: windows 10
Persepolis Version: 2.4.2
If there is no hard disk space, the downloader will not send the message properly and the user will go wrong.
![untitled](https://user-images.githubusercontent.com/33174787/32696849-2221ccce-c798-11e7-901f-0b0ba2b3c32c.png)

**Comment by alireza-amirsamimi** [comment]
thanks for reporting this bug. we will work on it.

**Comment by mostafaasadi** [comment]
9cc6004

**Comment by alireza-amirsamimi** [comment]
I fixed this bug:)
Thanks for reporting!
