### ISSUE TITLE
Can not change color scheme

### ISSUE THREAD

**Issue by ghost** [persepolisdm/persepolis#319]
**System Details:**
* Operating System: Linux
* Distro(For GNU/Linux and BSD users): Arch
* Desktop Environment(For GNU/Linux and BSD users): GNOME
* Persepolis Version: 2.5a0
* How do you install Persepolis? (Repositories, source, ...): AUR persepolis-git package

**Issue Description and steps to reproduce:**
Persepolis GUI color scheme can not be changed in settings menu and color scheme is wrong for Papirus icons:

![image](https://user-images.githubusercontent.com/2796369/32697808-bed9e6da-c790-11e7-9ce0-863c376ffe4c.png)

**Comment by alireza-amirsamimi** [comment]
Color schemes are work with "Fusion" style. so in other styles , color scheme's combo box is deactivated.
