### ISSUE TITLE
وجود حجم انبوهی زیر پروسه در سیستم، حتی پس از بستن برنامه

### ISSUE THREAD

**Issue by LinArcX** [persepolisdm/persepolis#32]
علی جان من برنامه رو بسته بودم.بعد رفتم تو پروسس منیجرم سرچ کردم پرسپولیس رو دیدم انبوهی زیر پروسه هنوز پشت صحنه دارن فعالیت میکنن.ببین:
<a href="http://uupload.ir/viewer.php?file=39nv_persepolisprocess.png"><img src="http://uupload.ir/files/39nv_persepolisprocess_thumb.png" border="0" alt="آپلود عکس" /></a>
اینم خروجی ترمینالم:
ps -aux | grep persepolis | wc -l
88

**Comment by Mr-undead** [comment]
چرا برای من اینطوری نیست

``` bash
[behrooz@Lenovo-G500 ~]$ ps -aux | grep persepolis        
behrooz   9994  0.0  0.0  13160  1000 pts/1    S+   18:32   0:00 grep persepolis
```

**Comment by LinArcX** [comment]
احتمالا تو یه حالت خاص این اتفاق افتاده برام.
در حالت عادی بله خروجی شما درسته بهروز جان.
