### ISSUE TITLE
Another tray icon name for Linux

### ISSUE THREAD

**Issue by varlesh** [persepolisdm/persepolis#325]
For tray now used `persepolis` icon name. This icon name used for desktop launcher and not good looking with monochrome icon themes on Linux.

![image](https://user-images.githubusercontent.com/8083855/32761773-a09ebe32-c90e-11e7-9935-f29e1fdb6e3f.png)

Will be good use different icon name for tray, for example `persepolis-tray` or `persepolis-panel`. 
```
# system_tray_icon
        self.system_tray_icon = QSystemTrayIcon()
        self.system_tray_icon.setIcon(
            QIcon.fromTheme('persepolis-panel', QIcon(':/persepolis.svg')))
```

PS: Some other Qt-apps fix that and suppoprt yet, for example:
https://github.com/zaps166/QMPlay2/blob/master/src/gui/MainWidget.cpp#L157
https://github.com/IJHack/QtPass/blob/master/src/trayicon.cpp#L14

**Comment by alireza-amirsamimi** [comment]
Thanks 👍

**Comment by alireza-amirsamimi** [comment]
I add a new icon (persepolis-tray.svg) for system tray.
Also I replaced persepolis default icon with persepolis icon in Papirus icon theme :)

**Comment by ghost** [comment]
@varlesh : Can we have monochrome icons for `persepolis-tray` or `persepolis-panel` in Papirus?
