### ISSUE TITLE
Change File Name doesn't work

### ISSUE THREAD

**Issue by chengchengXu** [persepolisdm/persepolis#327]
**System Details:**
* Operating System: MacOS
* Persepolis Version: 2.5a0
* How do you install Persepolis? (Repositories, source, ...)
I forget the detail, only remember I download from the github and build it by myself.

**Issue Description and steps to reproduce:**
I get some vedio real download address from this website (https://pan.baidu.com/share/link?uk=3543389151&shareid=1369430468#list/path=%2F) though tampermonkey.

Then I put that into Persepoils and select the button changing file name with a new file name.
My issue is the new file name doesn't work anymore and I got "8921119f46a64cedf655acad3d3dbc96" for the final file name.

Any advice for why the button doesn't work will be appreciated.

**Comment by alireza-amirsamimi** [comment]
@chengchengXu Hello
Thanks for reporting.
When did you build persepolis? 
I fixed this bug last week

**Comment by chengchengXu** [comment]
OMG, that's nice, thanks a lot for your hardworking. I build persepolis almost a month ago, so I will go to download the latest version.
