### ISSUE TITLE
Can you support Chinese?thanks

### ISSUE THREAD

**Issue by kfcceo** [persepolisdm/persepolis#328]
Can you support Chinese?thanks

**Comment by alireza-amirsamimi** [comment]
Sure :)
We plan to translate persepolis to different languages.
but now we are busy with some new features in persepolis. after that we will start to translate persepolis :)

**Comment by Navid-Ivanian** [comment]
Hi,
I don't know if you're aware of websites like "weblate.org" or "poeditor.com"; but you can use them to translate your software simultaneous with your development, collaboratively and with help of those who know that that language as their mother tongue.

**Comment by hayyan71** [comment]
@kfcceo 
@felixonmars 
@Navid-Ivanian 

We've added support for other language in the latest commits. So, now everyone can translate Persepolis to their native language!

You can find a quick guide how to translate Persepolis here:
https://github.com/persepolisdm/persepolis/wiki/translators-guide

Maybe we missed some phrases for translations. So, feel free to report bugs in Persepolis github page.

Regards

**Comment by Hitaro** [comment]
[Transifex.com](https://Transifex.com) is the best free online service for translating: https://transifex.com/persepolis/persepolis-translations/dashboard

**Comment by grahamperrin** [comment]
[Support simplified Chinese？ · Issue #278 · persepolisdm/persepolis](https://github.com/persepolisdm/persepolis/issues/278)
