### ISSUE TITLE
Are mac-package-build still being supported?

### ISSUE THREAD

**Issue by chengchengXu** [persepolisdm/persepolis#329]
**System Details:**
* Operating System: MacOS
* Persepolis Version: 2.5a0
* How do you install Persepolis? (Repositories, source, ...)
Build it from repository mac-package-build by myself 

**Issue Description and steps to reproduce:**
I have already asked one issue about change file name #327 , and alireza-amirsamimi told me it fixed a week ago.
So my question comes to that is repository mac-package-build still being supperted? And can I still use it for building new persepolis? I just found the files are updated five months ago.
Again, THANKS ALL YOUR HARDWORKING! That's really remarkable!

**Comment by chengchengXu** [comment]
I put my issue there for I found no one use the ISSUE into the repository mac-package-build.

**Comment by mavahedinia** [comment]
@chengchengXu Hi, due to last changes in the source, I have to modify the build script for mac. please be patient while it is being updated! don't worry it is still supported.

**Comment by mavahedinia** [comment]
now I have pushed new aria2c build to the repo and you can build Persepolis Download Manager using that script on mac. please do not hesitate to open issues on that repo too, if anything fails.

**Comment by chengchengXu** [comment]
Thanks for such fast job! I will use it immediately.
