### ISSUE TITLE
دانلود نکردن بعضی از فایلها

### ISSUE THREAD

**Issue by LinArcX** [persepolisdm/persepolis#33]
این لینک رو در نظر بگیرید:
http://dl.film2movie.biz/film/Insomnia.2002.720p.BluRay.Film2Movie_ORG.mkv
وقتی روش کلیک میکنم که با پرسپولیس دانلودش کنم صفحه دانلود باز میشه و یه صدای بوق میاد و تو نوتیفیکشن بارم دو تا پیام میده که یکی ش میگه :
aria2 did not respond.Try again.
و خود پرسپولیس هم وضعیت 
waiting 
میزنه.
جالیه همین فایل رو به راحتی با خود آریا 2 دانلود کردم بدون هیچ مشکلی.
مشکل چیه  علی جان؟
<a href="http://uupload.ir/"><img src="http://uupload.ir/files/45xt_screenshot_from_2016-07-23_23-22-21.png" border="0" alt="آپلود عکس" /></a>

**Comment by LinArcX** [comment]
جل الخالق !!
یک دقیقه بعد گفتم بذار از ترمینال ران کنم برنامه رو اگه ارور داد برات بفرستم.ولی در کمال تعجب این سری دانلود کرد
چراااا؟؟؟

**Comment by alireza-amirsamimi** [comment]
ببین بازم تکرار میشه یا نه
احتمالا اتفاقی بوده
وضعیت 
waiting
وقتی هست که دانلود منجر هنوز پیغامی از آریا دریافت نکرده

**Comment by aref993** [comment]
همین مشکل برای من هم وجود داره و در مورد لینک های زیادی همین خطا اتفاق می افته:
aria2 did not respond.Try again.
وضعیت
waiting
باقی می مونه و دانلودی اتفاق نمی افته

**Comment by alireza-amirsamimi** [comment]
برای لینک های خاصی این اتفاق می افته؟

**Comment by aref993** [comment]
فکر کنم برای لینک‌های خاصی اتفاق می افته.
لینک هایی که باید
redirect
بشن به لینک قابل دانلود.
مثلا همه ی لینک های زیر همین خطا رو دارند:
https://edgehill.nylas.com/download?platform=linux-deb
https://telegram.org/dl/desktop/linux
http://rufus.akeo.ie/downloads/rufus-2.10p.exe

**Comment by alireza-amirsamimi** [comment]
لینک تلگرام برای من دانلود شد
لینک اول هم آریا ۲ داره خطا میده
من یه سری آپدیت جدید روی گیت هاب گذاشتم ولی چون هنوز میخوام چیزهایی بهش اضافه کنم رسما منتشر نکردم
الان اگه آپدیت کنید و با پرسپولیس دانلود کنید دلیل خطایی که آریا برمیگردونه رو براتون مینویسه و متوجه میشید چرا خطا میده

**Comment by rahim1234** [comment]
لینک اول و دوم واسه من دانلود نمیشن ولی سومی خوبه.
نسخه پایدار با لینک اول مشکلی نداره ولی دومی که تلگرام هست رو نمیتونه دریافت کنه.
ubuntu 16.04 unity
