### ISSUE TITLE
Browser supported?

### ISSUE THREAD

**Issue by chengchengXu** [persepolisdm/persepolis#330]
**System Details:**
* Operating System: MacOS
* Persepolis Version: 2.5a0
* How do you install Persepolis? (Repositories, source, ...)
Build it from mac-package-build by myself

**Issue Description and steps to reproduce:**
Does it on the development list that add a browser right click menu for downloading by persepolis?
Or a download link sniffer?
I speak out that for some download link will be disable if I copy out the link, and the reason the Plug-in told me is the cookie is needed for downloading the file.
I'm a junior developer, but if there is anything I can help I will try my best.

**Comment by alireza-amirsamimi** [comment]
Hello :)
We had some big changes in persepolis's codes recently. We must change our browsers extension (Firefox, chromium, chrome, ...) for compatiblity too . I think it will be ready in the next two week . so stay tuned for new version of persepolis :)

**Comment by chengchengXu** [comment]
Thanks for reply. That's really wonderful for some new features will come out. I'm looking forward to your new persepolis!
