### ISSUE TITLE
Please support opera browser in linux!

### ISSUE THREAD

**Issue by dessasin** [persepolisdm/persepolis#332]

**Comment by alireza-amirsamimi** [comment]
@mhmmdtorun Hello
Yes, We will support opera in next version of persepolis :)

**Comment by mostafaasadi** [comment]
https://github.com/persepolisdm/persepolis/issues/187#issuecomment-295724011

**Comment by mostafaasadi** [comment]
with this addones https://addons.opera.com/en/extensions/details/download-chrome-extension-9/ you can install persepolis addons from chrome store.
it is just temporary method

**Comment by JafarAkhondali** [comment]
It's now supported. https://github.com/persepolisdm/persepolis/wiki/Opera
