### ISSUE TITLE
FireFox57

### ISSUE THREAD

**Issue by Pakrohk** [persepolisdm/persepolis#335]
![screenshot_20171121_005853](https://user-images.githubusercontent.com/27810360/33044156-021ba712-ce5d-11e7-8dc4-ec8b17480b93.png)

Look at the picture.
what do you see?
Oh God,  deleted flashgot.
lol  :joy:  :sweat_smile: 
Mr. Amirsamimi Do you have an idea?

**Comment by JafarAkhondali** [comment]
Hi,
Don't worry, Firefox disabled legacy extensions like Flashgot and many more in version 57 and will not support it.
New extension for Persepolis will be released soon, it should take less than a month.

**Comment by Pakrohk** [comment]
![screenshot_20171121_005853](https://user-images.githubusercontent.com/27810360/33045296-8e1e3fb4-ce61-11e7-9f57-0cc78a818b08.png)
Oveu is very good.

**Comment by JafarAkhondali** [comment]
This version doesn't work with FF 55+ :sweat_smile:

**Comment by Pakrohk** [comment]
Yes, I understood, unfortunately, it was only added.
