### ISSUE TITLE
Icon size

### ISSUE THREAD

**Issue by dimqua** [persepolisdm/persepolis#338]
Please allow to specify a size of these icons, like 16x16, 24x24, 32x32, etc.

![](https://i.imgur.com/SGBojwR.png)

**Comment by alireza-amirsamimi** [comment]
Hello
I changed the size to 32x32 month ago.

**Comment by dimqua** [comment]
Since you use SVG icons, I suggest to add an option about the icons size. Something [like this](https://doc.qt.io/qt-5/images/icons_size_groupbox.png) would be nice.
 So it's a feature request actually. ;-)

**Comment by alireza-amirsamimi** [comment]
I add your feature request.
In next version you can select icon size from preferences window(default is 32).
Thank you :)
