### ISSUE TITLE
Option to exclude certain filetype

### ISSUE THREAD

**Issue by Izzur** [persepolisdm/persepolis#339]
**System Details:**
* Operating System: Windows 10 x64
* Persepolis Version: 2.4.2
* How do you install Persepolis? Binary (.exe)

Is it possible for persepolis to ignore or exclude certain filetype (e.g jpg filetype) while downloading? So when I "save as" an image from web, the download is not override by persepolis

**Comment by JafarAkhondali** [comment]
Hi, Yes just click on extension icon and place any strings you would like to exclude from downloading. It's also possible to set multiple strings by using ',' as seperator.
By the way current version of extension doesn't work good with old persepolis(2.4.2). It's better to wait for our new release, It shouldn't take much time.

![image](https://user-images.githubusercontent.com/11364402/33558818-22748af6-d920-11e7-9e45-b83115c865b4.png)

**Comment by Izzur** [comment]
Thanks for the solution. I thought I will wait for next release. I'm closing this issue.
