### ISSUE TITLE
کم نشدن سرعت دانلود در صورتی که یک بار تیک را برداریم و سری دوم تیک را بزنیم

### ISSUE THREAD

**Issue by LinArcX** [persepolisdm/persepolis#34]
اگر برای بار اول اقدام به کم کردن سرعت دانلود کنیم خوب دکمه اپلای رو میزنیم و همه چی اوکیه.
اما اگه یک بار این تیک رو برداریم دیگه کلا یه سره میشه سرعت.شبیه شیر فلکه :)
یعنی دکمه اپلای پس از هر بار زدن اون تیک هم چنان دیزیبل باقی می مونه و به نظرم توتریگر تو گذاشتی رو اینکه کاربر بیاد رو دکمه اپلای کلیک کنه که اپلای بنده خدا کلا دیزیبل هست.

**Comment by alireza-amirsamimi** [comment]
ممنون از باگ ریپورت
حل شد :)
