### ISSUE TITLE
Changing overall Font size , doesn't effect Fields Font sizes 

### ISSUE THREAD

**Issue by arg1998** [persepolisdm/persepolis#341]
**System Details:**
* Operating System: Linux
* Distro : Ubuntu 16.04 LTS
* Desktop Environment : Gnome Desktop
* Persepolis Version : 2.4.2

changing font size in preferences doesn't effect on TextFields on other windows 

![screenshot from 2017-12-02 00-01-39](https://user-images.githubusercontent.com/19180964/33502246-9c0f9e92-d6f4-11e7-90cb-669e784c2d56.png)

**Comment by alireza-amirsamimi** [comment]
thanks for reporting.
Please make window's size bigger with your mouse and tell me if this resloves the issue.

**Comment by arg1998** [comment]
resizing the window and making it bigger brings back everything to normal situation .but in general cases , the default window's size doesn't go along with the font size and UI elements overlap or gets weird in default window's size.

**Comment by JafarAkhondali** [comment]
Please open a new issue if the problem exists within new version.
