### ISSUE TITLE
When it is opened, hope it to be max.

### ISSUE THREAD

**Issue by SawaraNazo** [persepolisdm/persepolis#343]
* Operating System: Windows 10 (64bit)
* Persepolis Version: 2.4.2

Every time when I open the application, it looks like this:

![snipaste_20171203_084638](https://user-images.githubusercontent.com/31041465/33521510-5fe0a5ea-d80e-11e7-8ca6-897fc8f11c1a.png)

But I think the below is better:

![snipaste_20171203_093919](https://user-images.githubusercontent.com/31041465/33521496-104ddcb4-d80e-11e7-96f9-f26f00a04526.png)

So it will cost me 1 second to maximize it every time :( And I think it is a little ugly. 
Can this become like that when I open it, it will show as max?

**Comment by alireza-amirsamimi** [comment]
Hello :)
it would be better if application saved maximize\unmaximize situation on exit 👍 
I'll work on it.
Thanks :)

**Comment by SawaraNazo** [comment]
Thanks for your reply and your work :)
Hope the software becomes better XD

**Comment by alireza-amirsamimi** [comment]
I add this feature request :) thank you
