### ISSUE TITLE
Hope to get the extension directly

### ISSUE THREAD

**Issue by SawaraNazo** [persepolisdm/persepolis#344]
* Operating System: Windows 10 (64 bit)
* Persepolis Version: 2.4.2
* Browser: Chrome

Hello.
In the world, some countries can't directly get to the Google Store, because of their network condition. I come from one of them. It will be a problem for us to download the extension in the store.
So I think if the next version can include the extension (*.crx file) in it or put it in some other places on github. We can add it to the Chrome directly. It would meet the needs of some people like me.

**Comment by Izzur** [comment]
Have you tried some other alternative which help you download .crx file like http://crxextractor.com/

**Comment by SawaraNazo** [comment]
@Izzur  Thanks for your help. I don't know this website before. And I have tried just now.
Unfortunately, it told me that the download was fail because of the network error :(

**Comment by SawaraNazo** [comment]
Oh, I'm sorry that I find there already have a WebExtension repository on the other page. I didn't find it yesterday.
But the release of it is just the source code, I couldn't find the usable file(*.crx) in the package I downloaded.
I think the extension file can be put to that place.

**Comment by Pakrohk** [comment]
The Firefox plugin will be ready soon.
Have you seen the new version of Firefox?
V57

**Comment by SawaraNazo** [comment]
@APakrohk   Thanks for your reply. But sorry, I hardly use Firefox :(  I'm more used to Chrome.

**Comment by Pakrohk** [comment]
My friend, the new version has changed a lot
I used the vivaldi browser in the past.
But after selecting Firefox 57 I changed.

**Comment by hayyan71** [comment]
I understand your problem but I don't recommend any third-party websites for downloading chrome extensions.

I'll ask @JafarAkhondali to release a .crx file for the next version of Persepolis Web Extension.

**Comment by JafarAkhondali** [comment]
@SawaraNazo 
I've attached crx and xpi files to install in chrom* or firefox, But please be aware that the extension is designed to work with lastest version of persepolis(2.5a or 3) which is only availabe via manuale installion using github. It's better to wait for our new release which will be available soon.
[https://github.com/persepolisdm/Persepolis-WebExtension/releases](https://github.com/persepolisdm/Persepolis-WebExtension/releases)

**Comment by SawaraNazo** [comment]
@APakrohk 
Thanks for your advice. I'll try it. :)

@hayyan71 
Thanks. Getting the lastest version of extension from store is better and safer. I also want to get it in that way. But the network condition doesn't allow me that. :(

@JafarAkhondali 
Thanks for your work. Looking forward to the next version. XD

**Comment by SawaraNazo** [comment]
I'll close this issue.
