### ISSUE TITLE
can't upgrade

### ISSUE THREAD

**Issue by ghost** [persepolisdm/persepolis#347]
**System Details:**
* Operating System: gnu/linux
* Distro(For GNU/Linux and BSD users): ubuntu 16.04
* Desktop Environment(For GNU/Linux and BSD users): gnome
* Persepolis Version: 3.0
* How do you install Persepolis? Repositories

The following packages have unmet dependencies:
 persepolis : Depends: python3-psutil (>= 5.0) but 3.4.2-1 is to be installed

**Comment by runo280** [comment]
با چه ذوقی اومدم نصب کنم که به این مانع خوردم 😩

**Comment by mostafaasadi** [comment]
Hi 
you shuold upgrade your system
`sudo apt update && sudo apt upgrade && sudo apt install -f && sudo apt install persepolis`

**Comment by ghost** [comment]
python3-psutil is already the newest version (3.4.2-1).

**Comment by runo280** [comment]
@mostafaasadi Based on this [link](https://launchpad.net/ubuntu/+archivemirrors):
`Network32 | http | 1 Gbps | Up to date`

```sudo apt update && sudo apt upgrade && sudo apt install -f && sudo apt install persepolis
Get:1 http://mirror.network32.net/ubuntu xenial InRelease [247 kB]                             
Get:2 http://ppa.launchpad.net/persepolis/ppa/ubuntu xenial InRelease [18.0 kB]                
Hit:3 https://deb.nodesource.com/node_6.x xenial InRelease                               
Get:4 http://archive.canonical.com/ubuntu xenial InRelease [11.5 kB]               
Get:5 http://mirror.network32.net/ubuntu xenial-updates InRelease [102 kB]
Get:6 http://mirror.network32.net/ubuntu xenial-backports InRelease [102 kB]
Get:7 http://mirror.network32.net/ubuntu xenial-security InRelease [102 kB]
Fetched 583 kB in 5s (110 kB/s)    
Reading package lists... Done
Building dependency tree       
Reading state information... Done
All packages are up to date.
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Calculating upgrade... Done
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Reading package lists... Done
Building dependency tree       
Reading state information... Done
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 persepolis : Depends: python3-psutil (>= 5.0) but it is not going to be installed
E: Unable to correct problems, you have held broken packages.```

**Comment by mostafaasadi** [comment]
thank you for reporting
according to [ubuntu package site](https://packages.ubuntu.com/search?keywords=python3-psutil&searchon=names&suite=all&section=all) , python3-psutil on xenial is 3.4.2 .
I rebuild package as soon as I can with fixed dependency for xenial

**Comment by mostafaasadi** [comment]
@Mosi2772 @runo280 thank you for reporting :rose: 
I updated package and you can upgrade to `3.0.0.1` through [ppa](https://launchpad.net/~persepolis/+archive/ubuntu/ppa/)
please check me out

**Comment by ghost** [comment]
thanks. it works now
