### ISSUE TITLE
جرا وقتی رو دکمه استاپ یا پوز کلیک میکنیم سرعت به تدریج کم می شود؟

### ISSUE THREAD

**Issue by LinArcX** [persepolisdm/persepolis#35]
اینو واسه این میگم که تو آی.دی.ام اینجوری نیست.یعنی سرعت یه دفعه قطع میشه.
آدم حس میکنه یه چیزی اون پشت داره دانلود میکنه هی :)
این موضوع تو افزایش کاهش سرعت هم تو ذوق میزنه یکم..لاک پشتی کم میشه سرعت.
نمیشه اینو درستش کرد علی جان؟

**Comment by alireza-amirsamimi** [comment]
ممنونم که اینقدر فعال هستی و همکاری میکنی :)
این زیر سر آریا ۲ هست و من نمیتونم دستکاریش کنم :)

**Comment by Mr-undead** [comment]
شاید باید به توسعه دهنده آریا خبر بدیم
