### ISSUE TITLE
مشکل در اجرای برنامه 

### ISSUE THREAD

**Issue by hadiyadollahi** [persepolisdm/persepolis#350]
**System Details:**
* Operating System: ?
* Distro(For GNU/Linux and BSD users): ?
* Desktop Environment(For GNU/Linux and BSD users): ?
* Persepolis Version: ?
* How do you install Persepolis? (Repositories, source, ...)

* _Please attach log files if crash or paste error message_

من از توزیع آرچ استفاده میکنم به همراه میز کارگنوم 
مشکلی که هر از گاهی با پرسپولیس داشتم و با آپدیت نسخه جدید جدی تر شد اینه که برنامه اجرا نمیشه تو محیط گرافیکی اوگو برای چند ثانیه توی تسک بار نمایش داده میشه و بعد هیچ و توی محیط کامنت هم بعد اجرا این پیام میاد
 "0
Aborted (core dumped)
"
داخل پوشه برنامه هم فایل لاگ نیست پوشه رو هم کلا پاک کردم و باز اتفاقی نیوفتاد با اجرای دستور  persepolis --clear هم اتفاقی نیفتاد

**Issue Description and steps to reproduce:**

**Comment by alireza-amirsamimi** [comment]
Always use english language here please.
Run this command in terminal and tell me the result.

`cat ~/.config/persepolis_download_manager/persepolisdm.log`
