### ISSUE TITLE
line 401 and 930

### ISSUE THREAD

**Issue by Sinagorgani** [persepolisdm/persepolis#351]
Traceback (most recent call last):
  File "/usr/share/persepolis/scripts/persepolis.py", line 401, in main
    mainwindow = MainWindow(start_in_tray, persepolis_download_manager, persepolis_download_manager.setting)
  File "/usr/share/persepolis/scripts/mainwindow.py", line 930, in __init__
    dict = download_table_dict[gid]
KeyError: '3c736cc963720c06'

**Comment by goldkeyber** [comment]
Same here.

**System Details:**
* Operating System: Linux
* Distro(For GNU/Linux and BSD users): Ubuntu 16.04 LTS
* Desktop Environment(For GNU/Linux and BSD users): Unity
* Persepolis Version: 3.0
* How do you install Persepolis Repositories

first start the app was works well,when i changed the style to GTK+,app can't start.shows this:

Traceback (most recent call last):
  File "/usr/share/persepolis/scripts/persepolis.py", line 401, in main
    mainwindow = MainWindow(start_in_tray, persepolis_download_manager, persepolis_download_manager.setting)
  File "/usr/share/persepolis/scripts/mainwindow.py", line 930, in __init__
    dict = download_table_dict[gid]
KeyError: '146897d0583b97a7'

**Comment by alireza-amirsamimi** [comment]
Please run this command in terminal and try to execute persepolis again.
`persepolis --clear`

Please tell me the result.

**Comment by alireza-amirsamimi** [comment]
It's compability problem with old version.
Please close all persepolis process
`killall persepolis`

run this code for removing persepolis config folder.
`rm -rf ~/.config/persepolis_download_manager/`

**Comment by alireza-amirsamimi** [comment]
We released new version(3.0.1) and this bug has been fixed :)
Please update persepolis.
Thanks for reporting this bug!
