### ISSUE TITLE
Application upgrade issue

### ISSUE THREAD

**Issue by ghost** [persepolisdm/persepolis#353]
**System Details:**
* Operating System: GNU/LINUX
* Architecture: armhf
* Distro(For GNU/Linux and BSD users):  Armbian Ubuntu Xenial 16.04
* Desktop Environment(For GNU/Linux and BSD users): XFCE 4
* Persepolis Version: 3
* How do you install Persepolis? (Repositories, source, ...) 
deb http://ports.ubuntu.com/ xenial-backports main restricted universe multiverse
deb http://ports.ubuntu.com/ xenial-updates main restricted universe multiverse
deb http://ports.ubuntu.com/ xenial-security main restricted universe multiverse
deb http://ports.ubuntu.com/ xenial main restricted universe multiverse

**Details:**
I've upgraded Persepolis DM using apt update & upgrade. But when i opened application, it was't upgraded!
I've removed app and reinstalled it to have new version.

**Comment by alireza-amirsamimi** [comment]
Thanks for reporting

**Comment by mostafaasadi** [comment]
Hi 
from wich version you upgraded ? 
how did you install lower version ? ppa? 
how did you upgrad ? ppa ?
was it open along upgrading ?
how did you find out that persepolis wasn't upgraded?

**Comment by ghost** [comment]
I'm sorry but i don't remember previous version! it was 2.x.x 😝 
after upgrade completed, I've checked up program. There was no GUI changes & program version in About page was 2.x.x
this package was exist in my official repositories and i doesn't add any other ppa!
I'm not sure about that program running during upgrade process!

**Comment by mostafaasadi** [comment]
there is no logical way to happen this , I guess your persepolis have been open .
thank you for reporting 🌹
