### ISSUE TITLE
Problem with installing persepolis from AUR

### ISSUE THREAD

**Issue by hadiyadollahi** [persepolisdm/persepolis#354]
برنامه را با yaourt -S persepolis نصب میکنم 
بعد در هنگام نصب به ارور زیر میرسم

Fatal Python error: Py_Initialize: Unable to get the locale encoding
LookupError: no codec search functions registered: can't find encoding

Current thread 0x00007f4ddfbb5740 (most recent call first):
/tmp/yaourt-tmp-hadi/aur-persepolis/./PKGBUILD: line 22:  3929 Aborted                 (core dumped) python setup.py install --root="$pkgdir/" --prefix=/usr --optimize=1
==> ERROR: A failure occurred in package().
    Aborting...
==> ERROR: Makepkg was unable to build persepolis.
==> Restart building persepolis ? [y/N]
==> -----------------------------------

**Comment by alireza-amirsamimi** [comment]
Hello
Please ALWAYS use english language here.
perhaps python on your system have some problem. Please read this [link](https://techglimpse.com/error-executing-python3-5-command-solution/)

**Comment by JafarAkhondali** [comment]
Please create a new issue if it still exists with new version.
