### ISSUE TITLE
runtime error

### ISSUE THREAD

**Issue by iman-salmani** [persepolisdm/persepolis#355]
**System Details:**
* Operating System: linux mint
* Distro(For GNU/Linux and BSD users): GNU/Linux
* Desktop Environment(For GNU/Linux and BSD users): xfce
* Persepolis Version: 3.0
* How do you install Persepolis? (Repositories, source, ...)
Repositories
* _Please attach log files if crash or paste error message_
Traceback (most recent call last):
  File "/usr/share/persepolis/scripts/persepolis.py", line 401, in main
    mainwindow = MainWindow(start_in_tray, persepolis_download_manager, persepolis_download_manager.setting)
  File "/usr/share/persepolis/scripts/mainwindow.py", line 930, in __init__
    dict = download_table_dict[gid]
KeyError: '30f88042f7e75418'

**Issue Description and steps to reproduce:**

**Comment by alireza-amirsamimi** [comment]
Please run this command in terminal and try to execute persepolis again.
`persepolis --clear`

Please tell me the result.

**Comment by alireza-amirsamimi** [comment]
It's compability problem with old version.
Please close all persepolis process
`killall persepolis`

run this code for removing persepolis config folder.
`rm -rf ~/.config/persepolis_download_manager/`

**Comment by alireza-amirsamimi** [comment]
We released new version(3.0.1) and this bug has been fixed :)
Please update persepolis.
Thanks for reporting this bug!
