### ISSUE TITLE
16 connections are not enough...

### ISSUE THREAD

**Issue by zxj5470** [persepolisdm/persepolis#356]
Nice product!

In China ,the most largest cloud repositories service named BaiDu Cloud Pan

 has a limit to only 100KB/s 

for one connection.
Even though there are 16 but still not enough...

I git clone the source and recompile it .
change to all 16 connections to 32...

and set 32 connections but get the download error...
It seems not work...

and then I want make install in windows.

Thanks.

**System Details:**
* Operating System: Windows/Linux
* Distro(For GNU/Linux and BSD users): ?
* Desktop Environment(For GNU/Linux and BSD users): ?Windows / Deepin Linux
* Persepolis Version: 3.0
* How do you install Persepolis? (Repositories, source, ...)
release in windows ,
and compile source in linux
* _Please attach log files if crash or paste error message_

**Comment by alireza-amirsamimi** [comment]
Hello
Unfortunately the maximum number for connections is 16.
Persepolis is a gui for [aria2](https://github.com/aria2/aria2). You can't have 32 connections with aria.

**Comment by zxj5470** [comment]
Oh....
That's the reason why even though I change the source code to replace all `16` then it still doesn't work.
Thank you all the same.

**Comment by zxj5470** [comment]
Maybe I would have a try on aria2 :joy:

**Comment by alireza-amirsamimi** [comment]
See [this](https://github.com/aria2/aria2/issues/580). may be it's help you :)

**Comment by zxj5470** [comment]
:smiley: Thanks a lot:)
