### ISSUE TITLE
how fix this error on fedora 27 ?

### ISSUE THREAD

**Issue by sajjads24** [persepolisdm/persepolis#357]
hi
how fix this error and crash on fedora 27 ?
`Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/persepolis/scripts/persepolis.py", line 401, in main
    mainwindow = MainWindow(start_in_tray, persepolis_download_manager, persepolis_download_manager.setting)
  File "/usr/lib/python3.6/site-packages/persepolis/scripts/mainwindow.py", line 930, in __init__
    dict = download_table_dict[gid]
KeyError: 'efe40957155b8283'
`

**Comment by alireza-amirsamimi** [comment]
Please run this command in terminal.
`persepolis --clear`

**Comment by sajjads24** [comment]
thanks for help me but Not fixed !
i am send massage in telegram for you ...
please see massage .

thanks

**Comment by alireza-amirsamimi** [comment]
Hello
I couldn't find your message! Can you send me your message again,please ?

**Comment by alireza-amirsamimi** [comment]
It's compability problem with old version.
Please close all persepolis process
`killall persepolis`

run this code for removing persepolis config folder.
`rm -rf ~/.config/persepolis_download_manager/`

**Comment by alireza-amirsamimi** [comment]
We released new version(3.0.1) and this bug has been fixed :)
Please update persepolis.
Thanks for reporting this bug!
