### ISSUE TITLE
persepolis crash 

### ISSUE THREAD

**Issue by Mr-undead** [persepolisdm/persepolis#358]
**System Details:**
* Operating System: Gnu/linux
* Distro(For GNU/Linux and BSD users): Arch Linux
* Desktop Environment(For GNU/Linux and BSD users): KDE 
* Persepolis Version: 3.0.0
* How do you install Persepolis? (Repositories, source, ...) AUR

* _Please attach log files if crash or paste error message_
```
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/persepolis/scripts/persepolis.py", line 401, in main
    mainwindow = MainWindow(start_in_tray, persepolis_download_manager, persepolis_download_manager.setting)
  File "/usr/lib/python3.6/site-packages/persepolis/scripts/mainwindow.py", line 930, in __init__
    dict = download_table_dict[gid]
KeyError: '12bd7ff5f972d081'
```
**Issue Description and steps to reproduce:**
When change theme to breeze persepolis crash

**Comment by alireza-amirsamimi** [comment]
It's compability problem with old version.
Please close all persepolis process
`killall persepolis`

run this code for removing persepolis config folder.
`rm -rf ~/.config/persepolis_download_manager/`
