### ISSUE TITLE
Download Later problem

### ISSUE THREAD

**Issue by aminbahraini** [persepolisdm/persepolis#359]
* Operating System: linux
* Distro: mint
* Desktop Environment: cinnamon
* Persepolis Version: 3.0.0
* How do you install Persepolis? repo

thanks for the new version.
download later function does Not get any info of file (size,file name,...)
it just gave us *** (3stars)

**Comment by alireza-amirsamimi** [comment]
@aminbahraini Hello
Thanks for reporting
I fixed this bug 2 hours ago in this [commit](https://github.com/persepolisdm/persepolis/commit/073ace7abe2c85b9e520a04a6d88abfca7f60b3f).
We released version 3.0.1 .
Repositories will be updated soon.
