### ISSUE TITLE
ستاره نشان دان نام فایل

### ISSUE THREAD

**Issue by mehdirajabi59** [persepolisdm/persepolis#36]
سلام

من یک فایل دو پارتی دارم داخل پرسپولیس.

اسم یکی از فایل هارو ***\* زده اسم یکی دیگه رو درست نشون میده
![screenshot from 2016-07-24 00-10-13](https://cloud.githubusercontent.com/assets/7848036/17079896/2d6a039e-5133-11e6-9dd8-71dbcfdff56f.png)

**Comment by alireza-amirsamimi** [comment]
سلام
وقتی اسم فایل رو ستاره میزنه یعنی هنوز اسمش رو پیدا نکرده
این اتفاق در اول دانلود میفته :)
کمی صبر کنید فایل رو پیدا میکنه و اسمش رو هم نشون میده
