### ISSUE TITLE
can't remove multiple download items at once 

### ISSUE THREAD

**Issue by MRdevX** [persepolisdm/persepolis#361]
**System Details:**
* Operating System: GNU/Linux
* Distro(For GNU/Linux and BSD users): Ubuntu 17.10
* Desktop Environment(For GNU/Linux and BSD users): Gnome
* Persepolis Version: 3.0.1
* How do you install Persepolis? Repositories (apt-get)

i tried selecting multiple download items with "Ctrl" button and remove them using these ways : 

1. Pressing Delete Button on Keyboard

1. Right Clicking on one of them and selecting "Remove Download" option from the pop-up menu

1. pressing "Ctrl + D" shortkey

none of them were able to remove downloads at once.
it would be nice to have an option to "remove download item from list" or "remove item with it's data (deletes the downloaded file)" too.

thanks a lot.

**Comment by alireza-amirsamimi** [comment]
Hello
Make sure you highlight that item.
If your download isn't completed, you can click on remove for removing your download item.
If your download is completed, you can select 'remove' for removing download item, and you can select 'delete' for removing download item and deleting it's file :)

Check 'Select multiple items' for selecting multiple items

![screenshot_20171220_125431](https://user-images.githubusercontent.com/7452500/34200191-6e15f460-e585-11e7-9a78-8c2a3ca9eda4.png)

**Comment by MRdevX** [comment]
Thanks a lot for explanation :)
selecting multiple items using right-click then selecting items is not very user friendly in my opinion, actually i didn't recognise this option before you make it clear with this post.
being able to selecting them using 'ctrl' and 'shift' buttons as other similar softwares  would be really cool.
thanks again for you hard work. Persepolis is amazing, i'm proud of using it :)

**Comment by alireza-amirsamimi** [comment]
I fixed this issue in this [commit](https://github.com/persepolisdm/persepolis/commit/01e64493bb8a35b1b7840eec4769cffda53a1476) .
Now you can select multiple items by highlighting them :) no need to check that checkbox :)
