### ISSUE TITLE
Fail to run it after install on windows64-bit

### ISSUE THREAD

**Issue by ZhenFLuo** [persepolisdm/persepolis#362]
**System Details:**
* Operating System: Windows 10
* Distro(For GNU/Linux and BSD users): 
* Desktop Environment(For GNU/Linux and BSD users): 
* Persepolis Version: 3.0.0
* How do you install Persepolis? (Repositories, source, ...)
Installation package
* _Please attach log files if crash or paste error message_

**Issue Description and steps to reproduce:**
I just install it on my surface pro 4, for 64-bit. I've installed Qt, and I've changed my path before. After my installation, I run it and went out a error:
{This application failed to start because it could not find or load the Qt platform plugin"windows"
in "".

Reinstalling the application may fix this problem.}
And I reinstall it for several times, but still fail to run it.

**Comment by alireza-amirsamimi** [comment]
Please test version 3.0.1 :)
Is this solved or not in version 3.0.1
You don't need Qt installed for using persepolis

**Comment by ZhenFLuo** [comment]
I just mean I’ve installed Qt for study before, maybe I changed something important like path? I‘ve tried to install 3.0.1 and fail again, the same problem. And I’ve not noticed that when I install it, there is no Firewall warning about aria2……Maybe due to the Norton Security on my computer? But the Firewall in Norton must be coming out. A friend of mine tried it on his computer(the same to mine except Norton), and everything goes well!
And thank you for reply.

发件人: AliReza AmirSamimi [mailto:notifications@github.com]
发送时间: 2017年12月20日 17:18
收件人: persepolisdm/persepolis <persepolis@noreply.github.com>
抄送: ZhenFLuo <louzhuFrank@outlook.com>; Author <author@noreply.github.com>
主题: Re: [persepolisdm/persepolis] Fail to run it after install on windows64-bit (#362)


Please test version 3.0.1 :)
Is this solved or not in version 3.0.1

**Comment by alireza-amirsamimi** [comment]
Please don't change install path and decactive your antivirus temorary and try again. Perhaps your antivirus or firewall blocks aria2c.

**Comment by ZhenFLuo** [comment]
There are something wrong with installing aria2. I can’t open it even I download alone. There might be no problem with PDM. I will find out what’s wrong with my computer. Thank you for helping me.

发件人: AliReza AmirSamimi [mailto:notifications@github.com]
发送时间: 2017年12月20日 18:16
收件人: persepolisdm/persepolis <persepolis@noreply.github.com>
抄送: ZhenFLuo <louzhuFrank@outlook.com>; Comment <comment@noreply.github.com>
主题: Re: [persepolisdm/persepolis] Fail to run it after install on windows64-bit (#362)


Please don't change install path and decactive your antivirus temorary and try again. Perhaps your antivirus or firewall blocks aria2c.

**Comment by yuanotes** [comment]
I have the same issue here on windows 10

**Comment by mostafaasadi** [comment]
@yuanotes hi
on wich version you have this error ?
is it X32 or X64 ?

**Comment by yuanotes** [comment]
@mostafaasadi x64 and it's a clean install of windows 10. I've tried to close all anti-virus software and it does't work

**Comment by mostafaasadi** [comment]
@yuanotes 
do you install last version from release page ? 
can you take screnshot from error?

**Comment by yuanotes** [comment]
@mostafaasadi 
![image](https://user-images.githubusercontent.com/174553/34468253-ce3f22bc-ef3f-11e7-9e79-ddc0dca2c3ec.png)

**Comment by yuanotes** [comment]
It's the 3.0.1 version. The filename of the installer is persepolis_3_0_1_windows_64bit.exe

**Comment by mostafaasadi** [comment]
thank you for reporting 
I think this problem made from [this bug](https://github.com/pyinstaller/pyinstaller/issues/2857) in pyinstaller
I try to build new package with latest pyinstaller.
please be patient

**Comment by mostafaasadi** [comment]
another question mr @yuanotes 
Do your [PATH](https://www.computerhope.com/issues/ch000549.htm) or username has NonAscii character ?

**Comment by yuanotes** [comment]
Um.. There are Chinese characters in the path to the installer but the path
to the executable is all ascii.

Mostafa Asadi <notifications@github.com>于2018年1月2日 周二04:37写道：

**Comment by yuanotes** [comment]
And my username is Chinese and it is non ascii character.

Mostafa Asadi <notifications@github.com>于2018年1月2日 周二04:37写道：

**Comment by mostafaasadi** [comment]
may I ask you install and test persepolis on a fresh user with ascii username and PATH ?

**Comment by yuanotes** [comment]
No problem . I will try that when I get home.

Mostafa Asadi <notifications@github.com>于2018年1月2日 周二09:15写道：

**Comment by jjandnn** [comment]
same

**Comment by mostafaasadi** [comment]
Hi
make sure you have last persepolis bundle, it is 3.0.1
according to our conversation on #362 if you have NonAscii character on your PATH or username cause this problem.
