### ISSUE TITLE
Minimize to tray

### ISSUE THREAD

**Issue by nghduc97** [persepolisdm/persepolis#363]
**System Details:**
* Operating System: Windows
* Persepolis Version: 3.0.1
* How do you install Persepolis? Chocolatey

When I minimize the windows ('-' sign), it stays on the taskbar. I want an option to hide taskbar icon leaving only tray icon by default when minimized instead of right-clicking on tray icon.

**Comment by alireza-amirsamimi** [comment]
@lazyc97 Please click on "minimize to tray" button from toolbar , or in view menu.

**Comment by nghduc97** [comment]
I see that but I think an option to make '-' sign act the same would be nice, it is first place everyone think of when they want to minimize and only 1 mouse click away.

**Comment by alireza-amirsamimi** [comment]
I agree with you :)
We work on it :)

**Comment by alireza-amirsamimi** [comment]
I add this feature :)
So users can minimize Persepolis to the system tray with close(x) button.
Thanks for your feature request :+1:
