### ISSUE TITLE
star instead of file name

### ISSUE THREAD

**Issue by mojtaba82** [persepolisdm/persepolis#364]
**System Details:**
* Operating System: Linux
* Distro(For GNU/Linux and BSD users): Manjaro
* Desktop Environment(For GNU/Linux and BSD users): KDE
* Persepolis Version: 3.01
* How do you install Persepolis? (Repositories, source, ...) AUR

Hi
Excuse me for may bad English
When in browser I select links and use Download selected links by Persepolis all link found but in file name show star instead of name of file.
I wish best for you

**Comment by alireza-amirsamimi** [comment]
I checked this, and this is worked for me.
Make sure you have the latest version of persepolis. 
do you have this problem with all links?

**Comment by mojtaba82** [comment]
> ?Make sure you have the latest version of persepolis.

I have latest version 3.0.1

> do you have this problem with all links?

Yes. For example go to [this link](https://www.tak3da.com/5463/%D8%AF%D8%A7%D9%86%D9%84%D9%88%D8%AF-%D9%81%D9%88%D9%84-%D8%A2%D9%84%D8%A8%D9%88%D9%85-%D9%BE%D8%A7%D8%B2%D9%84-%D8%A8%D8%A7%D9%86%D8%AF/) and select several mp3 links and then click on Download selected links with Persepolis

> I checked this, and this is worked for me.

Can you give me address of site you use to check this problem?
Thank you for your attention

**Comment by alireza-amirsamimi** [comment]
Try this [link](http://www.mediafire.com/file/sp2df0io4mf86np/Yasamin+ShahHosseini+-+Gahan+%28Shabzendeha.org%29.rar) please

**Comment by mojtaba82** [comment]
> Try this link please

For just one file, file name is ok. but when select **several file** and then right click > Persepolis Download Manager Integration > Download selected links with Persepolis this problem occure. Furthermore this problem occure when in a page use Download All Links With Persepolis.
Excuse me for my bad English
Thanks.

**Comment by alireza-amirsamimi** [comment]
@mojtababaghban Thank you for reporting
I'll check the problem.

**Comment by alireza-amirsamimi** [comment]
This bug is fixed. Thanks for reporting :)

**Comment by mojtaba82** [comment]
Thanks a lot Mr samimi
