### ISSUE TITLE
change file name not work

### ISSUE THREAD

**Issue by mojtaba82** [persepolisdm/persepolis#365]
**System Details:**
* Operating System: Linux
* Distro(For GNU/Linux and BSD users): Manjaro
* Desktop Environment(For GNU/Linux and BSD users): KDE
* Persepolis Version: 3.0.1
* How do you install Persepolis? (Repositories, source, ...) AUR

* _Please attach log files if crash or paste error message_

just this. change file name not work

**Comment by alireza-amirsamimi** [comment]
Thanks for reporting :)

**Comment by alireza-amirsamimi** [comment]
This bug is fixed! Thanks for reporting :)

**Comment by mojtaba82** [comment]
Very good. Thanks a lot.
