### ISSUE TITLE
Where's the proxy configuration?

### ISSUE THREAD

**Issue by nixmd** [persepolisdm/persepolis#368]
**System Details:**
* Operating System: Linux
* Distro(For GNU/Linux and BSD users): Archlinux
* Desktop Environment(For GNU/Linux and BSD users): KDE
* Persepolis Version: 3.0.1
* How do you install Persepolis? AUR, Git version

* _Please attach log files if crash or paste error message_

**Issue Description and steps to reproduce:**
Where's the proxy configuration actually?

**Comment by hayyan71** [comment]
@nixmd you can set proxy settings while adding new link in "enter your link" window.

**Comment by nixmd** [comment]
Jall-al Khalegh!
Thanx.

**Comment by alireza-amirsamimi** [comment]
Click on show more options
![screenshot_20171221_143840](https://user-images.githubusercontent.com/7452500/34253443-cf9bbe0e-e65c-11e7-99b7-eb60a1f19ccc.png)

Check the proxy
![screenshot_20171221_143906](https://user-images.githubusercontent.com/7452500/34253460-e195237a-e65c-11e7-815d-69eb8269263b.png)

But make sure you use http proxy! Don't use SOCKS proxy
If you use socks proxy, you must convert it. see this [link](https://github.com/persepolisdm/persepolis/wiki/Privoxy) for more information.
