### ISSUE TITLE
How to temporarily disable the capture download link

### ISSUE THREAD

**Issue by arstum** [persepolisdm/persepolis#369]
Sometimes，i did not want to download a link with persepolis.But i do not know how to realize it.
Did it has hot key?

**Comment by alireza-amirsamimi** [comment]
Hello
Please see [FAQ](https://github.com/persepolisdm/persepolis/wiki/Home-en#faq) in our wiki :)

**Comment by arstum** [comment]
I uninstall the soft before to see FAQ.
Perhaps I am too lazy.
