### ISSUE TITLE
Unusual disk IO usage

### ISSUE THREAD

**Issue by nixmd** [persepolisdm/persepolis#370]
**System Details:**
* Operating System: Linux
* Distro(For GNU/Linux and BSD users): Archlinux
* Desktop Environment(For GNU/Linux and BSD users): KDE
* Persepolis Version: 3.0.1
* How do you install Persepolis? AUR, Git version

**Issue Description and steps to reproduce:**
Whenever download manager starts a download, hard disk light constantly starts to blink and pc slows down. iotop shows persepolis disk io usage 99%, repetitively

**Comment by mostafaasadi** [comment]
Hi , I don't have this problem 
make sure it is not hardware problem or effect of another application
![screenshot_20171224_000040](https://user-images.githubusercontent.com/12208050/34322499-d8e6ff9a-e83d-11e7-805b-44519602a4ce.png)
