### ISSUE TITLE
name of queue 

### ISSUE THREAD

**Issue by Mr-undead** [persepolisdm/persepolis#374]
**System Details:**
* Operating System: Gnu/linux
* Distro(For GNU/Linux and BSD users): Arch Linux
* Desktop Environment(For GNU/Linux and BSD users): KDE 
* Persepolis Version: 3.0.1
* How do you install Persepolis? AUR
Sometimes the name of the queue do not show in add to queue section.

**Comment by alireza-amirsamimi** [comment]
hello
when is this occurred?
