### ISSUE TITLE
persepolis do not run 

### ISSUE THREAD

**Issue by Mr-undead** [persepolisdm/persepolis#375]
**System Details:**
* Operating System: Gnu/linux
* Distro(For GNU/Linux and BSD users): Arch Linux
* Desktop Environment(For GNU/Linux and BSD users): KDE 
* Persepolis Version: 3.0.1
* How do you install Persepolis? AUR
Sometimes persepolis do not run. for temporary fix issue i must run this command
```
killall persepolis
```
 then run persepolis.

**Comment by alireza-amirsamimi** [comment]
I haven't this problem. But when it's occurred, Please check persepolis log file and tell me the error message :)
