### ISSUE TITLE
file name issue 

### ISSUE THREAD

**Issue by Mr-undead** [persepolisdm/persepolis#376]
**System Details:**
* Operating System: Gnu/linux
* Distro(For GNU/Linux and BSD users): Arch Linux
* Desktop Environment(For GNU/Linux and BSD users): KDE 
* Persepolis Version: 3.0.1
* How do you install Persepolis? AUR
Sometimes the files names changes to "*", unintentially!

**Comment by alireza-amirsamimi** [comment]
I tried to make it better, Please test it :)
But when persepolis can't find the file's name(because of network problem or server problem or ...), then persepolis replaces the name with "***"

**Comment by JafarAkhondali** [comment]
@Ram3zani In new version of WebExtension, file names are captured from the web automatically.
