### ISSUE TITLE
category change items

### ISSUE THREAD

**Issue by Mr-undead** [persepolisdm/persepolis#377]
**System Details:**
* Operating System: Gnu/linux
* Distro(For GNU/Linux and BSD users): Arch Linux
* Desktop Environment(For GNU/Linux and BSD users): KDE 
* Persepolis Version: 3.0.1
* How do you install Persepolis? AUR
After start persepolis I change category items after one second persepolis doesn't change item in category. for fix issue i must restart persepolis when after restart i see issue #375.

**Comment by alireza-amirsamimi** [comment]
I checked this and I haven't this problem. 
Perhaps  "All Downloads" category was highlighted first in left side panel. All items are stored in this category and when you change the category for an specific item to a queue or "Single Downloads", the item isn't eliminate from "All Download" category.
