### ISSUE TITLE
Add new icon

### ISSUE THREAD

**Issue by Mr-undead** [persepolisdm/persepolis#378]
**System Details:**
* Operating System: Gnu/linux
* Distro(For GNU/Linux and BSD users): Arch Linux
* Desktop Environment(For GNU/Linux and BSD users): KDE 
* Persepolis Version: 3.0.1
* How do you install Persepolis? AUR

Please add select multiple items icon to toolbar.

**Comment by alireza-amirsamimi** [comment]
Hello
I solved this issue for ever in this [commit](https://github.com/persepolisdm/persepolis/commit/01e64493bb8a35b1b7840eec4769cffda53a1476)  😄

Now you can select download items by highlighting them whith mouse and ... :)
