### ISSUE TITLE
problem

### ISSUE THREAD

**Issue by newdie484** [persepolisdm/persepolis#380]
**System Details:**
* Operating System: ?
![selection_175](https://user-images.githubusercontent.com/34459232/34423814-cb65f9d6-ebec-11e7-8763-1a4df473c734.png)

* Distro(For GNU/Linux and BSD users): ?
* Desktop Environment(For GNU/Linux and BSD users): ?
* Persepolis Version: ?
* How do you install Persepolis? (Repositories, source, ...)

* _Please attach log files if crash or paste error message_

**Issue Description and steps to reproduce:**

**Comment by newdie484** [comment]
i cant install that

**Comment by mostafaasadi** [comment]
Hi
how do you try to install persepolis ? according to [wiki](https://github.com/persepolisdm/persepolis/wiki/debian-installation-instruction) ?

**Comment by newdie484** [comment]
kali 2017

**Comment by newdie484** [comment]
خوب فارسی میگم کالی میخوام نصب کنم پرسپولیس ارور مییده که محتاج پکیج ولی پکیج نصب نمیکنه دستورات هم طبق سایت رفتم

**Comment by newdie484** [comment]
![image](https://user-images.githubusercontent.com/34459232/34424036-5fe188b8-ebee-11e7-8fbb-26e89145909d.png)

**Comment by mostafaasadi** [comment]
please use english language.
run this:
```
sudo apt purge persepolis
sudo apt autoremove
sudo echo "deb http://ppa.launchpad.net/persepolis/ppa/ubuntu xenial main #deb-src http://ppa.launchpad.net/persepolis/ppa/ubuntu xenial main " > /etc/apt/sources.list.d/persepolis-ppa.list
sudo apt-get update
sudo apt-get update && sudo apt-get install persepolis
```
if still you see the error , run this : 
```
sudo apt install -f
sudo apt install persepolis
```

**Comment by newdie484** [comment]
بازم همون ارور

**Comment by newdie484** [comment]
![image](https://user-images.githubusercontent.com/34459232/34424086-d3e1e550-ebee-11e7-819c-69d736f38fe1.png)

**Comment by newdie484** [comment]
بازم همون

**Comment by mostafaasadi** [comment]
It seems you don't follow [wiki](https://github.com/persepolisdm/persepolis/wiki/debian-installation-instruction)
you should add ppa key 
after `apt update` you get an Error about key signature , you should add that key 
sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys AC4E8D9CDCB0980D

**Comment by newdie484** [comment]
i use instruction but again error

**Comment by newdie484** [comment]
in wiki said if error key but i dont have erorr key

**Comment by mostafaasadi** [comment]
I see the Error in your second image, anyway run this:
```
 sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys AC4E8D9CDCB0980D
sudo apt update & sudo apt install persepolis
```

**Comment by newdie484** [comment]
![image](https://user-images.githubusercontent.com/34459232/34424648-27c43d72-ebf3-11e7-8f0e-48f84d068e7b.png)

**Comment by newdie484** [comment]
![image](https://user-images.githubusercontent.com/34459232/34424738-bf79cd44-ebf3-11e7-9f1e-f8b03c5cd88f.png)

**Comment by newdie484** [comment]
now install?

**Comment by mostafaasadi** [comment]
you have some problem in your source file(s).
please fix source and after it:
```
sudo apt update
sudo apt upgrade
sudo apt autoremove
```
after this try to add key and install.

**Comment by newdie484** [comment]
what can i do?

**Comment by mostafaasadi** [comment]
you shuold remove thats line wich occur Errors from source

**Comment by newdie484** [comment]
no change

**Comment by newdie484** [comment]
how to do that??

**Comment by newdie484** [comment]
how to delete that?

**Comment by newdie484** [comment]
![image](https://user-images.githubusercontent.com/34459232/34425570-0423e7a2-ebfb-11e7-8501-aef060bdfbb1.png)

**Comment by newdie484** [comment]
stop and dont do anything

**Comment by newdie484** [comment]
ا

**Comment by newdie484** [comment]
س

**Comment by newdie484** [comment]
ب

**Comment by alireza-amirsamimi** [comment]
@newdie484 Hello
If your problem didn't solve, try this [link]( https://github.com/persepolisdm/persepolis/wiki/git-installation-instruction-fa)
