### ISSUE TITLE
Got EOF from the server.

### ISSUE THREAD

**Issue by madkne** [persepolisdm/persepolis#381]
**System Details:**
* Operating System: Linux
* Distro(For GNU/Linux and BSD users): Arch
* Desktop Environment(For GNU/Linux and BSD users): KDE
* Persepolis Version: 3.0.1
* How do you install Persepolis? (Repositories, source, ...)

- Persepolis Download Manager - ERROR - Download failed - GID : ad392eebce705b8b/nMessage : Got EOF from the server.

**Comment by alireza-amirsamimi** [comment]
This is aria2 error :) It's not related to persepolis. but perhaps i cna help you.How did you add your link to persepolis?
