### ISSUE TITLE
a little bug and some advise

### ISSUE THREAD

**Issue by qq892640791** [persepolisdm/persepolis#382]
aria2 不能下载任何有关pan.baidu.com的东西，会出现解析错误，在所有平台所有系统上都是这样，

建议增加中文支持，我可以帮助翻译，或者出一个语言列表 ，类似lazarus的多国语言支持

**Comment by onrea** [comment]
Please write in English or use [translate.google.com](https://translate.google.com) to convert to English.

**Comment by qq892640791** [comment]
Aria2 can't download anything about pan.baidu.com, and there will be a parsing error, which is the case on all systems on all platforms,

https://shcm09.baidupcs.com/file/090a034a4f7ed551b324801dc4a27a19?bkt=p3-000072a0b17664296b5f7828355d3ebf2fca&fid=4111562326-250528-919027498442603&time=1514855905&sign=FDTAXGERLQBHSKa-DCb740ccc5511e5e8fedcff06b081203-L6zUu4bD5Ia0pbbNsrb%2BPLSk9dE%3D&to=71&size=23650610&sta_dx=23650610&sta_cs=0&sta_ft=rar&sta_ct=5&sta_mt=5&fm2=MH,Yangquan,Anywhere,,henan,cmnet&vuk=4111562326&iv=0&newver=1&newfm=1&secfm=1&flow_ver=3&pkey=000072a0b17664296b5f7828355d3ebf2fca&sl=81068110&expires=8h&rt=pr&r=869911438&mlogid=32186897811905748&vbdid=1303345930&fin=Packers.vmp.rar&fn=Packers.vmp.rar&rtype=1&dp-logid=32186897811905748&dp-callid=0.1.1&hps=1&tsl=10&csl=10&csign=iCMKLENV9A1pz8elOvV5HAk%2FRHs%3D&so=0&ut=8&uter=4&serv=0&uc=2521629893&ic=733077179&ti=8717829bcb7e27260c06fbe53747396cbba18de7b03dc81f&by=themis
Links are like this, and both browsers and IDM can be parsed, aria2 does not work, and it will prompt errors


I think it's because I didn't pass cookies, or because the website needed the account password to login. Aria2 didn't pass these parameters. I didn't find the document to pass the parameters or cookies.

I suggest adding Chinese support,  I can help translate, or make a list of languages, and recommend the use of Lazarus's multilingual language to support that

**Comment by alireza-amirsamimi** [comment]
Hello
Sorry for my late answer :)
Try to add this link with persepolis's browser [extension](https://github.com/persepolisdm/persepolis/wiki/Home-en#extensions)

**Comment by alireza-amirsamimi** [comment]
You can pass cookies and referer and ... with persepolis extension automatically.
I added a feature now for users who want to add them manually :)
