### ISSUE TITLE
This PPA does not support xenial

### ISSUE THREAD

**Issue by hamedraad27** [persepolisdm/persepolis#383]
**My System Details:**
* Operating System: GNU-Linux
* Distro(For GNU/Linux and BSD users): Linux Mint 18.3 Sylvia
* Desktop Environment(For GNU/Linux and BSD users): Cinnamon
* Persepolis Version: *
* How do you install Persepolis? Repositories
******************************
Hello!
When i want to add a new repository with this:

`sudo add-apt-repository ppa:persepolis/ppa`

i get this answer

> ('http protocol error', 0, 'got a bad status line', None)
> Cannot add PPA: ''This PPA does not support xenial''.

and when i want to add this PPA in linux mint Software Sources i get this message:

> Cannot add PPA: ''This PPA does not support xenial''.

what should I do?
Please help me.
Thanks

**Comment by mostafaasadi** [comment]
Hi
we have a package for xenial in [ppa](https://launchpad.net/~persepolis/+archive/ubuntu/ppa/+packages)
It seems you don't follow [debian installation instruction on wiki](https://github.com/persepolisdm/persepolis/wiki/debian-installation-instruction) , you should add signature key

**Comment by hamedraad27** [comment]
Tanks
My Problem Solved
My mistake was installation method in this link
https://persepolisdm.github.io/
