### ISSUE TITLE
Add translated UI to this software

### ISSUE THREAD

**Issue by zyppe** [persepolisdm/persepolis#388]
**System Details:**
* Operating System: Windows
* Persepolis Version: ?
* How do you install Persepolis? (Repositories, source, ...)
Just Download from github.com
* _Please attach log files if crash or paste error message_

**Issue Description and steps to reproduce:**
#### Please report only one Issue (Bug or feature request or ...) in one issue! and open new Issue for another one :)
Would like to add translated UI to this software. I am a Chinese user and I can help you to translate this softeware to Chinese (Simple or Tranditional)

**Comment by alireza-amirsamimi** [comment]
Yes, Sure! 
We must translate it to many languages. We Start this as soon as possible :)

**Comment by hayyan71** [comment]
@aiwonanjing 

We've added support for other language in the latest commits. So, now everyone can translate Persepolis to their native language!

You can find a quick guide how to translate Persepolis here:
https://github.com/persepolisdm/persepolis/wiki/translators-guide

Maybe we missed some phrases for translations. So, feel free to report bugs in Persepolis github page.

Regards

**Comment by grahamperrin** [comment]
> … I can help you to translate this softeware to Chinese (Simple or Tranditional) …

[Support simplified Chinese？ · Issue #278 · persepolisdm/persepolis](https://github.com/persepolisdm/persepolis/issues/278)
