### ISSUE TITLE
اجرا نشدن برنامه بعد از هنگ کردن و بسته شدن

### ISSUE THREAD

**Issue by Mr-undead** [persepolisdm/persepolis#39]
برنامه در حین دانلود هنگ کرد و پیغام ومد که با اجبار برنامه بسته بشه منم تایید کردم برنامه بسته بشه
اما الان برنامه دیگه باز نمیشه
خروجی ها را میگذارم
ترمینال

``` bash
[behrooz@Lenovo-G500 ~]$ persepolis
***********************************
***********************************
****Persepolis Download Manager****
****  Version : 2.0.2 Unstable ****
***********************************
***********************************
0
```

فایل ارور

``` bash
Traceback (most recent call last):
  File "/usr/share/persepolis/persepolis-download-manager", line 106, in <module>
    mainwindow = MainWindow()
  File "/usr/share/persepolis/mainwindow.py", line 202, in __init__
    item = QTableWidgetItem(download_info_file_lines[i].strip())
IndexError: list index out of range
```

**Comment by alireza-amirsamimi** [comment]
`rm ~/.config/persepolis_download_manager/`

اینو بزن حل میشه :)

**Comment by Mr-undead** [comment]
حل شد مرسی
اما چرا برنامه دچار مشکل شده بود ؟

**Comment by alireza-amirsamimi** [comment]
روش کار میکنم و برای ورزن ۲.۱ یه تغییراتی میدم که ببینم مشکل حل میشه یا نه :)

**Comment by LinArcX** [comment]
من برنامه نویس پایتون نیستم اما به نظرم اونجایی که داری گرید برنامه رو بر اساس فایل های دانلودی میسازی فک کنم باید شرط تو تغییر بدی:
f = Open(download_info_file)
            download_info_file_lines = f.readlines()
            f.close()
            for i in range(10):
                item = QTableWidgetItem(download_info_file_lines[i].strip())
self.download_table.setItem(0 , i , item)
بشه این:
f = Open(download_info_file)
            download_info_file_lines = f.readlines()
            f.close()
            for i in range(download_list_file_lines.size()-1):
                item = QTableWidgetItem(download_info_file_lines[i].strip())
self.download_table.setItem(0 , i , item)

**Comment by alireza-amirsamimi** [comment]
برای این برنامه این شیوه جواب نمیده :)
توی ورژن جدید مشکل حل شده
هنوز روی گیت هاب نذاشتم
انشالله چند روز دیگه منتظر میکنم
