### ISSUE TITLE
If you have time, it is recommended to add Chinese choice

### ISSUE THREAD

**Issue by UnaHe** [persepolisdm/persepolis#390]
**System Details:**
* Operating System:mac
* Distro(For GNU/Linux and BSD users): ?
* Desktop Environment(For GNU/Linux and BSD users): ?
* Persepolis Version: ?
* How do you install Persepolis? (Repositories, source, ...)

* _Please attach log files if crash or paste error message_

**Issue Description and steps to reproduce:**

**Comment by alireza-amirsamimi** [comment]
Yes, Sure! 
We must translate it to many languages. We Start this as soon as possible :)

**Comment by hayyan71** [comment]
@UnaHe 

We've added support for other language in the latest commits. So, now everyone can translate Persepolis to their native language!

You can find a quick guide how to translate Persepolis here:
https://github.com/persepolisdm/persepolis/wiki/translators-guide

Maybe we missed some phrases for translations. So, feel free to report bugs in Persepolis github page.

Regards

**Comment by grahamperrin** [comment]
[Support simplified Chinese？ · Issue #278 · persepolisdm/persepolis](https://github.com/persepolisdm/persepolis/issues/278)
