### ISSUE TITLE
File name doesn't change when download added via Persepolis extension

### ISSUE THREAD

**Issue by rezabanivakil** [persepolisdm/persepolis#391]
**System Details:**
* Operating System: ? Windows 10
* Persepolis Version: ? 3.0.1
* How do you install Persepolis? (Repositories, source, ...) 64-bit package for windows

After Persepolis extension call Persepolis download window, I checked Change File name and type the name in English but download manager ignore it and name doesn't change.
Manually insert link and change name work correctly.
  Sorry for bad English.

**Comment by alireza-amirsamimi** [comment]
I solve this [bug](https://github.com/persepolisdm/persepolis/issues/365) . but we have not new release :) It's fixed in new release :)
