### ISSUE TITLE
Persepolis after shutdown

### ISSUE THREAD

**Issue by Pakrohk** [persepolisdm/persepolis#397]
![20180111_233245](https://user-images.githubusercontent.com/27810360/34895413-e76bf652-f7fa-11e7-919f-1c979bad4079.jpg)
**System Details:**
* Operating System: Win 10 x64
* Persepolis Version: 3.0.1

مشکل من در پرسپولیس در هنگام خاموش کردن سیستم پیش میاد
البته من از ویندوز استفاده نمی کنم. آشکار بود و زود تر گذارش می شد 

My problem in Persepolis is when you turn off the system.
I do not use Windows.
This problem this was obvious and reported

**Comment by mostafaasadi** [comment]
سلام 
این مشکل در نسخه جدید برطرف شده است 
لطفا بروزرسانی کنید
