### ISSUE TITLE
magnet link can't work

### ISSUE THREAD

**Issue by chengchengXu** [persepolisdm/persepolis#398]
**System Details:**
* Operating System: Mac 10.12.6
* Distro(For GNU/Linux and BSD users): ?
* Desktop Environment(For GNU/Linux and BSD users): ?
* Persepolis Version: 2.5a0
* How do you install Persepolis? (Repositories, source, ...)
Compile it by myself

* _Please attach log files if crash or paste error message_

**Issue Description and steps to reproduce:**
#### Please report only one Issue (Bug or feature request or ...) in one issue! and open new Issue for another one :)
I copy a magnet link into the Download Link input box and download it immediately.
But I wait a really long time without it downloading anything.
I tried Folx and it worked well, so can we analyse magnet link now?

**Comment by chengchengXu** [comment]
And now, after I close it, I can't open it anymore.
That's really confusing.

**Comment by alireza-amirsamimi** [comment]
@chengchengXu Hello
Persepolis can not download torrent , magnet , ....
Can you run persepolis from your terminal (console)? What is error message?
For resetting persepolis, run persepolis from terminal with --clear switch.

**Comment by chengchengXu** [comment]
Thx for your answer.
I found it must be something locked, for I can reopen it after I force quit it at my Dock.
And I also found that if I select lots of task in persepolis and click remove task, it not worked well, and I believe that would be the problem. Just because I have tried twice and they all rose problems.

**Comment by alireza-amirsamimi** [comment]
@chengchengXu For removing multiple items, after right clicking on download list in main window, check "select multiple items" . Then check items and remove them :-)

**Comment by chengchengXu** [comment]
@alireza-amirsamimi Thx a lot! I will try that later. But it's a little confused if I selected multi item and clicked remove task with a different program behaviour.
And do we have a plan for magnet link or something else like that?

**Comment by alireza-amirsamimi** [comment]
@chengchengXu Yes , we have plan for adding this feature in future :)

**Comment by chengchengXu** [comment]
That's wonderful~ Anyway, thx a lot!
