### ISSUE TITLE
عدم شناسایی نسخه Aria2

### ISSUE THREAD

**Issue by Mr-undead** [persepolisdm/persepolis#4]
به صورت تصادفی بعد از باز کردن برنامه ، برنامه کرش کرده و بسته می‌شود.
محتویات فایل persepolis_error
`QBasicTimer::stop: Failed. Possibly trying to stop from a different thread
QBasicTimer::stop: Failed. Possibly trying to stop from a different thread
QBasicTimer::stop: Failed. Possibly trying to stop from a different thread
QBasicTimer::stop: Failed. Possibly trying to stop from a different thread
QBasicTimer::stop: Failed. Possibly trying to stop from a different thread
QBasicTimer::stop: Failed. Possibly trying to stop from a different thread
QBasicTimer::stop: Failed. Possibly trying to stop from a different thread
QObject::connect: Cannot queue arguments of type 'QTextBlock'
(Make sure 'QTextBlock' is registered using qRegisterMetaType().)`
خروجی برنامه در ترمینال
`[behrooz@Lenovo-G500 ~]$ persepolis

---

---

***_Persepolis Download Manager**_*
***\*  Version : 2.0.0 Unstable ****

---

---

0
aria2 Error Version
Segmentation fault (core dumped)`
از توزیع آرچ+سینامون استفاده میکنم

**Comment by alireza-amirsamimi** [comment]
باگ هست و گاهی باعث کرش میشه ظاهرا
شیوه اطلاع به کاربر رو وقتی با آریا در تماس نیست رو تغییر میدم و خبر میدم
چک کن ببین حل میشه یا نه

**Comment by alireza-amirsamimi** [comment]
آپدیت کردم
دوباره از گیت هاب نصب کن لطفا
اگر مشکل حل شده بود اطلاع بده تا موضوع رو ببندیم

**Comment by Mr-undead** [comment]
سلام 
دوباره نصب کردم اما الان باز هم به صورت یکی در میان برنامه ارور میده 
خروجی ترمینال
`[behrooz@Lenovo-G500 ~]$ persepolis

---

---

***_Persepolis Download Manager**_*
***\*  Version : 2.0.0 Unstable ****

---

---

0
aria2 Error Version
None Starts
None Starts
None Starts
None Starts
None Starts
`
هیچ دانلودی نمیتونه شروع بشه اما برنامه دیگه کرش نمیکنه و بسته نمیشه

**Comment by alireza-amirsamimi** [comment]
منظورم کرش کردن بود که حل شد خدارو شکر
:)
حالا یه امکان اضافه میکنم که خطا رو به کاربر اطلاع بده
پس من این باگ رو میبندم
ممنون
