### ISSUE TITLE
مشکل نبودن آیکون در نوار ابزار

### ISSUE THREAD

**Issue by molaeiali** [persepolisdm/persepolis#40]
![persepolis-report](https://cloud.githubusercontent.com/assets/12999682/17300807/2963bc8e-5829-11e6-8c31-6c4354448806.png)
arch + xfce
no error from terminal running

**Comment by molaeiali** [comment]
گفته بودید این کار رو انجام بدم

−−−−−−−−−−−−−−−
این کد رو به یه اسم توی
home
ذخیره کن
مثلا
foo.py

https://paste.ubuntu.ir/pbno

بهش با زدن این کد توی ترمینال قابلیت اجرایی بده
chmod +x foo.py

حالا اینجوری توی ترمینال اجراش کن
./foo.py
ببین وقتی اجرا میشه آیکنی نمایش میده کنار
button
جوابش رو توی ورژن جدید بنویس
ممنونم
−−−−−−−−−−−−−−−

نتیجه اینکه آره آیکون درب خروج مانند اومد کنار دکمه

**Comment by alireza-amirsamimi** [comment]
پس الان مشکل اینجاست که آیکن رو 
resource
توی سیستم شما نمیخونه
ولی از تم میخونه!
چه جالب :)
یه سوال دیگه
از گیت هاب یه آپدیت کن و به من بگو پنجره ها آیکن دارند یا نه؟
تم آیکن رو هم عوض کن ببین تغییری ایجاد میشه یا نه

**Comment by alireza-amirsamimi** [comment]
و تاکید میکنم حتما ورژنی که از 
AUR
نصب کردی رو از سیستمت پاک کن
و بعد از گیت هاب نصب کن

**Comment by molaeiali** [comment]
آپدیت کردم
الان آخرین کامیت اینه
Author: alireza-amirsamimi alireza.amirsamimi@gmail.com
Date:   Sun Jul 31 07:12:12 2016 +0430

```
icon fromtheme support added
```

قدیمی رو پاک کردم جدید رو نصب کردم تغییری ایجاد نشد
نسخه
AUR
رو کامل پاک کردم با
-Rsnc
 فولدر
.persepolis
رو هم پاک کردم از
home
و این که توی
Notification Area
هم آیکون ندارم یه فضای خالی میاد براش
شاید مفید باشه که از اینا استفاده می‌کنم
Style Theme: Numix-Blue
Icon Theme: Numix Circle
Window Manager: Numix-Blue
هرچند که وقتی به این ترتیب عوضش کردمم فرقی نکرد
Style Theme: Adwaita
Icon Theme: Adwaita
Window Manager: Default

**Comment by alireza-amirsamimi** [comment]
پنجره های پرسپولیس آیکن داره یا نه؟

**Comment by molaeiali** [comment]
خیر، آیکون پنجره سفید که گوشه عکسایی که فرستادم رو اگه منظورته!
توی درباره هم آیکون نیست!
یه همچین مشکلی رو با 
TeamViewer 
داشتم که یسری دکمه‌ها رو نشون نمی‌داد
lib32-libpng
رو نصب کردم درست شد، اما اینجا آیکون ندارم هنوز، گفتم شاید مشکل یکسان باشه
یه مشکل جالب دیگه هم دارم که فکر می‌کردم مشکل منه فقط اما دیشب روی ماشین مجازی مانجارو (اکس‌اف‌سی‌ای) و فدورا(گنوم) هم نصب کردم دیدم این مشکل رو دارن! توی
Firefox > Prefrences > Advanced > Data Choices 
اینجا خالیه! ولی توی
xubuntu و ubuntu 
اینجا اوکیه
حس می‌کنم مشکل از یه کتابخونه باید باشه! که شاید برای شما به عنوان نیازمندی چیز دیگه‌ای نصب شده!
![persepolis-report-2](https://cloud.githubusercontent.com/assets/12999682/17321290/0047aa84-58ad-11e6-95ec-97b4fc7e7fe8.png)

**Comment by molaeiali** [comment]
روی مانجارو نصب کردمش مشکلی نداره آیکون‌ها ولی فایرفاکس هنوز اونجوریه، ربطی به هم ندارن

**Comment by alireza-amirsamimi** [comment]
قضیه فایرفاکس رو متوجه نشدم
ای کد رو تست کن ببین آیکن پنجره ها میاد یا نه
`gtk-update-icon-cache`

نمیدونم چه مشکلی هست که توی میزکارت آیکن ها نمیاد یا چه بسته ای نصب نیست
ولی روش کار میکنم مشکل رو پیدا کنم
ممنونم از اینکه اطلاع میدی

**Comment by molaeiali** [comment]
انجام دادم این کار رو هم جواب نداد، ممنون پیگیری :)

**Comment by molaeiali** [comment]
به طور کاملا اتفاقی مشکل رو حل کردم :)
goldendict 
نصب کردم بعد شانسی دانلود منیجر رو باز کردم دیدم آیکون‌ها اومده، پاکش کردم و دونه دونه وابستگی‌هایی که با 
goldendict
نصب شده بود رو تست کردم، با نصب
qt5-svg
مشکل حل می‌شه! اگه برات نصبه امتحان کن پاکش کن ببین آیکونات می‌ره؟ :)

**Comment by alireza-amirsamimi** [comment]
ممنونم!مشکل رو حل کردی 
دقیقا جوابت درست بود
همین مشکل رو یکی از دوستان در مینت  هم داشت که با راهنماییت  و نصب بسته معادل توی دبیان حل شد
تشکر فراوان :)
پیش نیازها رو هم در راهنمای برنامه به روز کردم
