### ISSUE TITLE
Is there any translation of UI text?

### ISSUE THREAD

**Issue by mowangjuanzi** [persepolisdm/persepolis#401]
Hello there:

I just installed the software, is there any plan to translate the application into multiple languages (eg Chinese)? I think if you can achieve better use of Chinese.

Thank you.

**Comment by alireza-amirsamimi** [comment]
Yes, Sure!
We must translate it to many languages. We Start this as soon as possible :)

**Comment by JafarAkhondali** [comment]
Check this link:
https://github.com/persepolisdm/persepolis/wiki/translators-guide
