### ISSUE TITLE
can't run persepolis, PermissionError: [Errno 13] Permission denied

### ISSUE THREAD

**Issue by salahoued** [persepolisdm/persepolis#402]
**System Details:**
* Operating System: GNU/Linux
* Distro(For GNU/Linux and BSD users): Kubuntu 16.04.3
* Desktop Environment(For GNU/Linux and BSD users): KDE
* Persepolis Version: 3.0.1
* How do you install Persepolis? (Repositories, source, ...) Debian/Ubuntu Repositories
* Browsers: Firefox 57 and Opera 50

* _Please attach log files if crash or paste error message_
```
Traceback (most recent call last):
  File "/usr/bin/persepolis", line 11, in <module>
    load_entry_point('persepolis==3.0.1', 'console_scripts', 'persepolis')()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 542, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2569, in load_entry_point
    return ep.load()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2229, in load
    return self.resolve()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2235, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/lib/python3/dist-packages/persepolis/__main__.py", line 21, in <module>
    from persepolis.scripts import persepolis
  File "/usr/lib/python3/dist-packages/persepolis/scripts/persepolis.py", line 93, in <module>
    from persepolis.scripts import initialization
  File "/usr/lib/python3/dist-packages/persepolis/scripts/initialization.py", line 178, in <module>
    browserIntegration(browser)
  File "/usr/lib/python3/dist-packages/persepolis/scripts/browser_integration.py", line 172, in browserIntegration
    f = open(native_message_file, 'w')
PermissionError: [Errno 13] Permission denied: '$HOME/.config/chromium/NativeMessagingHosts/com.persepolis.pdmchromewrapper.json'
```

**Issue Description and steps to reproduce:**
I couldn't start the DM from the app launcher nor terminal, in the first run the file ```com.persepolis.pdmchromewrapper.json``` wasn't in this path ```$HOME/.config/chromium/NativeMessagingHosts/``` so I searched for it and I found it on ```$HOME/.config/google-chrome/NativeMessagingHosts/``` directory then I copy it to ```$HOME/.config/chromium/NativeMessagingHosts/``` and ```$HOME/.mozilla/native-messaging-hosts/``` and changed the permissions for both files to 777 and worked but with some CHMOD errors in the terminal
```
chmod: modification des permissions de '$HOME/.config/chromium/NativeMessagingHosts/com.persepolis.pdmchromewrapper.json': Opération non permise
chmod: modification des permissions de '$HOME/.mozilla/native-messaging-hosts/com.persepolis.pdmchromewrapper.json': Opération non permise
```

**Comment by alireza-amirsamimi** [comment]
@salahoued Hello
You have permission problem on your system. Perhaps you executed your browser or persepolis or ... with sudo before and it caused this problem! Don't do that :)
Try to remove this file with rm command:
 perhaps sudo must be used before rm

`rm ~/.config/chromium/NativeMessagingHosts/com.persepolis.pdmchromewrapper.json`

**Comment by salahoued** [comment]
Hello @alireza-amirsamimi, as you said I closed all apps browser an PDM, remove the JSON file but PDM doesn't start so I run the command ```persepolis``` in terminl and get the same permission problem as above
I copied the JSON file from ```.mozilla``` directory to ```chromium``` and 'chmod' it with 777 and PDM worked again.
For browser or persepolis execution with sudo I didn't  do that, it's just after installing PDM and browsers plugins the JSON file doesn't exist in ```chromium``` nor ```.mozilla``` directories but found it in the ```.config/google-chrome``` directory.

Other than this warnings, all works fine
```
chmod: modification des permissions de '/home/sal/.config/chromium/NativeMessagingHosts/com.persepolis.pdmchromewrapper.json': Opération non permise
chmod: modification des permissions de '/home/sal/.mozilla/native-messaging-hosts/com.persepolis.pdmchromewrapper.json': Opération non permise
```

Not to forget, I would like to thank you for this DM realy beautiful, and helpful, I think I'm gonna let go uGet and XDM :)

**Comment by alireza-amirsamimi** [comment]
Hello
Sorry for my late answer ✋
I guess you have permission problem on your system.
Please run persepolis from terminal. If you have error for a file or folder please remove that yourself with `sudo rm -rf` command :)
