### ISSUE TITLE
why is that? I can't resolve this problem.

### ISSUE THREAD

**Issue by ddkk3000** [persepolisdm/persepolis#403]
**System Details:**
* Operating System: win10 1709
* Distro(For GNU/Linux and BSD users): ?
* Desktop Environment(For GNU/Linux and BSD users): ?
* Persepolis Version: ? updated to persepolis_3_0_1_windows_64bit
* How do you install Persepolis? (Repositories, source, ...) click this exe file

* _Please attach log files if crash or paste error message_
![_20180124211826](https://user-images.githubusercontent.com/10786234/35334109-23004042-014c-11e8-8c10-51a3a44431f2.png)

**Issue Description and steps to reproduce:**
#### Write in English language please, Thanks :)
why is that? I can't resolve this problem.

**Comment by mostafaasadi** [comment]
Hi
make sure you have last persepolis bundle, it is 3.0.1
according to our conversation on #362 if you have NonAscii character on your PATH or username cause this problem.
