### ISSUE TITLE
System tray icon not working

### ISSUE THREAD

**Issue by peylight** [persepolisdm/persepolis#404]
**System Details:**
* Operating System: Kubuntu 16.04
* Distro(For GNU/Linux and BSD users): Ubuntu
* Desktop Environment(For GNU/Linux and BSD users): KDE Plasma 5
* Persepolis Version: 3.0.1
* How do you install Persepolis? (Repositories, source, ...)
Personal Package Archives (PPA)
* _Please attach log files if crash or paste error message_
No log
**Issue Description and steps to reproduce:**

The system tray icon not working for my Operation System!

**Comment by salahoued** [comment]
Hi @peylight, I can tell you that this is my second day using PDM :), I did remark that when minimizing PDM to system tray there is no icon in it, but when reading your issue I try it out again and found it by clicking that little arrow in the dashboard.

![screenshot_20180125_164030](https://user-images.githubusercontent.com/17504423/35400422-9eccaf06-01ee-11e8-9ab9-fb648c62f7b9.png)

I'm not sure if this is the desired & predicted functionning of the system tray icon on KDE 5.

Have a nice day :)

**Comment by peylight** [comment]
Oh Sorry @salahoued . I didn't check the hidden icons.
That was my problem. Thank you

**Comment by salahoued** [comment]
You are welcome, I hope that was helpful :)
