### ISSUE TITLE
lack of remove all

### ISSUE THREAD

**Issue by KBCNa** [persepolisdm/persepolis#406]
**System Details:**
* Operating System: Linux
* Distro(For GNU/Linux and BSD users): Ubuntu
* Desktop Environment(For GNU/Linux and BSD users): Unity
* Persepolis Version: 3.0.1
* How do you install Persepolis? (Repositories, source, ...) Repo

**Issue Description and steps to reproduce:**
there is no option to emptying list at once

**Comment by alireza-amirsamimi** [comment]
Hello
You can find this option in edit menu :)
