### ISSUE TITLE
Proxy support is lacking

### ISSUE THREAD

**Issue by Baddest-Juju** [persepolisdm/persepolis#411]
A built-in method of using SOCKS5 proxies is greatly desired, as this is a feature almost all other download managers have at the moment. Aside from greater security they generally have fewer network 
compared to SSL proxies. (Seems to take a while for the download to start, but it's very fast once it gets going.) Using third party programs for this, especially on Windows, is quite tedious. 

Additionally, having to expand advanced options, check the 'proxy' box, and then put in your password is quite tedious. There should be a global option, it should remember what advanced options you had checked last download, and it shouldn't forget the proxy password ever.

**Comment by Baddest-Juju** [comment]
(I originally and erroneously claimed that aria2 had SOCKS5 support, but I was thinking of curl)

**Comment by alireza-amirsamimi** [comment]
Unfortunately aria2c wouldn't not support SOCKS5 proxy. Many users comment in [this issue for "supporting sucks" in aria2 repository in github](https://github.com/aria2/aria2/issues/153) . We hope it will be added in future.
But for now you can convert Socks proxy to http and use it for persepolis. We wrote  a workaround solotion for it in [our wiki](https://github.com/persepolisdm/persepolis/wiki/Home-en#faq)

**Comment by Baddest-Juju** [comment]
Have you thought about simply including privoxy with Persepolis? It is distributed under GNU as well, and it's multi-platform as well.

**Comment by hayyan71** [comment]
@Baddest-Juju different distros may have different versions of privoxy in their repos. It's not a good idea to include privoxy in Persepolis.

Regards

**Comment by alireza-amirsamimi** [comment]
It's good idea.
Perhaps we can do this for windows or mac :)

**Comment by Baddest-Juju** [comment]
The basic syntax on all the versions is the same, right?

You could just add privoxy as a required dependency on Linux and it should snag it from their distribution's repo. I dunno how it'd work for arch-based Linux though.

**Comment by b-simjoo** [comment]
It's 2023 and proxy support is not added yet 😕

**Comment by alireza-amirsamimi** [comment]
We added Socks5 support. thanks for your feature request. :+1:
