### ISSUE TITLE
(Windows 10) Qt notifications do not work

### ISSUE THREAD

**Issue by Baddest-Juju** [persepolisdm/persepolis#414]
On Windows 10, I changed notification type from 'Native' to 'QT notification', however they both seem to do the same thing and use native... which is very annoying because you have to dismiss one notification to see the next one.

**Comment by alireza-amirsamimi** [comment]
Yes, in windows both of them is same thing but in Mac OSX and some desktop environments in Linux and  they are diffrent. 
In Linux we can use `libnotify-bin` package and in mac, we can use some good APIs. Butt in windows i coudn't find better way.

**Comment by Baddest-Juju** [comment]
Telegram uses Qt for Windows. Have you tried looking at what they do?

https://github.com/telegramdesktop/tdesktop/blob/55e56a6788870e6d67d9938eaabdf87f2ebddb17/Telegram/SourceFiles/platform/win/notifications_manager_win.cpp

Screenshot (not mine) of what it looks like:
![](http://mspoweruser.com/wp-content/uploads/2015/08/image32.png)

**Comment by alireza-amirsamimi** [comment]
Thank you :) 
I'm Linux user and I didn't know this.
I'll work on it :)

**Comment by alireza-amirsamimi** [comment]
I added your feature request to persepolis.
Thanks for your feature request :)

![image_2018-02-05_13-16-13](https://user-images.githubusercontent.com/7452500/35798287-93937976-0a77-11e8-8653-b104838a594e.png)
