### ISSUE TITLE
Please add a way to edit the aria2 config file or add custom parameters

### ISSUE THREAD

**Issue by Baddest-Juju** [persepolisdm/persepolis#415]
aria2 has a lot of advanced options that this program does not yet support. It would be useful to have the option to edit the config or add the parameters if you have the knowledge.

**Comment by alireza-amirsamimi** [comment]
Sorry, We can't do this. Perhaps user's config file have some conflict with persepolis.It caused some problems and ... .

**Comment by Baddest-Juju** [comment]
The program could ignore config essential options/parameters that break it.

Or you could make it hidden away, something you can only access if you've read the documentation.

**Comment by alireza-amirsamimi** [comment]
Persepolis set and changes needed options in [initializaion.py](https://github.com/persepolisdm/persepolis/blob/master/persepolis/scripts/initialization.py) and  [setting.py](https://github.com/persepolisdm/persepolis/blob/master/persepolis/scripts/setting.py) and [download.py](https://github.com/persepolisdm/persepolis/blob/master/persepolis/scripts/download.py) .

I have no idea about your feature request :) I don't know it's work good or not now 😄 . But i'll work on it.
