### ISSUE TITLE
Convenient 'Save to' button outside of Advanced?

### ISSUE THREAD

**Issue by Baddest-Juju** [persepolisdm/persepolis#416]
If you want your file saved outside of the default downloads folder, right now you either have to choose a predefined category or go into the advanced options and click away from the default directory.

It would be very convenient to have a button next to 'Ok' that opens a file explorer so you can choose exactly where you want it in a much quicker manner, and starting from the directory the last file saved in this manner was put.

**Comment by alireza-amirsamimi** [comment]
Hello
We changed the window for the next version :)

![screenshot_20180201_115213](https://user-images.githubusercontent.com/7452500/35668354-651db1da-0746-11e8-830a-8fb21146a27d.png)


But in current version you can still change download folder. Open the "add link" for adding new link and then click on "more options" button at bottom of  the window in left side.

**Comment by Baddest-Juju** [comment]
I'm aware of this.

To be honest that isn't an improvement. It's just as many clicks, and it makes the window really large. I think I'd actually prefer the way it is right now over that.

What about something like this...?

![image](https://user-images.githubusercontent.com/33403660/35669143-c34fc86c-06f9-11e8-8c5b-fc2d5e3231b4.png)

**Comment by Baddest-Juju** [comment]
I saw you pushed a UI update. Since there's no instructions on compiling to Windows (yet) I'd like to ask if you could show me a screenshot of what the file download screen looks like now?

**Comment by alireza-amirsamimi** [comment]
![screenshot_20180201_145609](https://user-images.githubusercontent.com/7452500/35776604-d1aacc14-09b4-11e8-983a-becb824843e6.png)
