### ISSUE TITLE
چند اشکال کوچک

### ISSUE THREAD

**Issue by mostafaasadi** [persepolisdm/persepolis#42]
سلام 
باتشکر از زحمات شما 
۱. در پنجره دانلود فاصله خطوط اطلاعات (مثل سرعت و حجم و..) کم است بطوریکه قسمتی از متون در ارتفاع قابل دیدن نیست 
۲. دوم اینکه تغییراتی که در پنجره اصلی برنامه می دهیم با بستن برنامه از بین می روند بطور مثال من همیشه عرض ستون اسم فایل را بیشتر از استاندارد میکنم این درحالی است که با بازکردن دوباره پرسپولیس باز باید اینکار را تکرار کنیم همچنین است برای اندازه خود پنجره و ... 
۳. امکان شخصی سازی ستون های نمایشی نیست 
۴. ستونی که تاریخ و زمان اضافه شدن دانلود را بدهد نیست 
۵. امکان چینش صعودی نزولی ستون ها نیست (مثلا بر اساس حجم) 
۶. نیاز شدید به صف یا لیست دانلود حس می شود 
۷. انتظار می رود که از طریق خود پرسپولیس امکان دسترسی به پوشه یا خود فایل مهیا باشد 
۸. در قسمت محدودیت سرعت دانلود ، محدودیت بیشتر از ۹۹ کیلوبایت بر ثانیه ممکن نیست 
۹. پرسپولیس در حین اجرای ساده بدون هیچ دانلودی بیش ۲۰ درصد سی پی یو را درگیر میکند که این مقدار با فایرفاکس در حال اجرا برابری میکند  
۱۰ اگر پرسپولیس در مخازن رسمی یا غیر رسمی قرار بگیرد ، به مراتب بهتر و ساده تر است 

من پرسپپولیس را روی اوبونتو ۱۶.۱۰ دارم 
هدفم از بازگو کردن این نکات تعالی پرسپولیس است 
باتشکر از برنامه بسیار عالی شما

**Comment by alireza-amirsamimi** [comment]
مصفی جان آپدیت کن بعضی هاش رو حل کردم
۱  --- ۷ ---۸

بقیه رو انشالله روش کار میکنم
مورد ده کمی برام عجیبه
نباید اینجور باشه
روی اوبونتو ۱۶.۰۴ چک کردم
همیشه این مشکل رو داری؟

**Comment by ghost** [comment]
<div dir="rtl">
منم همین جا می خوام چندتا چیز رو درخواست کنم که اگه تو پرسپولیس باشه بهتره:         <br/>
۱-  امکان صف بندی دانلودها و تنظیم تعداد دانلودهایی که به صورت هم زمان ران میشه.    <br/>
۲-  امکان غیر فعال کردن notification برنامه. چون بعضی وقتها واقعا آزار دهنده میشه.     <br/>
۳-  امکان مرتب کردن لیست دانلودها بر اساس ستون های مختلف نمایش داده شده.           <br/>
۴- امکان استفاده از آیکونهای پیش فرض سیستم به جای آیکونهای برنامه.                          <br/>
و در نهایت تشکر از زحمات علیرضای عزیز
</div>

**Comment by alireza-amirsamimi** [comment]
شماره ۲ کار خوبی نیست
بعد ممکنه کاربر غیر فعالش کنه و خطاها به اطلاعش رسونده نشه و متوجه نشه چرا دانلودش انجام نمیشه
شماره ۴ رو اضافه کردم
توی ورژن چند روز آینده منتشر میشه :)
