### ISSUE TITLE
So disappoint.

### ISSUE THREAD

**Issue by leoxxx** [persepolisdm/persepolis#425]
I'm not a developer.
I‘m just a user.

> everything you have to do is to install pyqt5 and Qt Linguist packages

The translators guide is hard to a user. Maybe easy for developer.

I can just use editor to edit a file.

BTW.How to create a green version.
I install x86 versison. Then copy it to other driver.It's OK.But x64 is not.It seem to missing some files.
OS: WIN7 X64.
And Can you make installprogram to select  install path?

**Comment by hayyan71** [comment]
@leoxxx we are looking for some ways to make translations process much easier. you can join conversation here:
https://github.com/persepolisdm/persepolis/issues/301

**Comment by leoxxx** [comment]
@hayyan71
THX.
I have commented.
