### ISSUE TITLE
Compiling on Windows?

### ISSUE THREAD

**Issue by Baddest-Juju** [persepolisdm/persepolis#426]
Really want to use the new changes. Could you add instructions to compile on Windows?

VS2017 support would be ideal, with a proper .sln file, dependencies will be automatically detected and downloaded/installed.

**Comment by mostafaasadi** [comment]
Hi
I add a instructions for build on windows as soon as I can with some document and dependency and files
we build persepolis with pyinstaller and package it with inno
I don't know about VS and .slm , but I search about it
thank you

**Comment by mostafaasadi** [comment]
Hi  @Baddest-Juju 
I push persepolis build instruction on this repository
https://github.com/persepolisdm/persepolis-windows-package-build
have a good time 🌹
