### ISSUE TITLE
‫رفتن به system tray به جای بسته شدن برنامه

### ISSUE THREAD

**Issue by msajadi832** [persepolisdm/persepolis#43]
سلام.

‫اگه ممکنه طوری تنظیم کنید که وقتی دکمه x برنامه زده شد، به جای بسته شدن  به system tray بره. 
‫مثل clementine

ممنون

**Comment by alireza-amirsamimi** [comment]
یه مشکلی هست توی پایکیوت۵ که اجازه نمیده این کار رو بکنم
ولی دارم روش کار میکنم
ممنون :)
