### ISSUE TITLE
Site link

### ISSUE THREAD

**Issue by Pakrohk** [persepolisdm/persepolis#432]
**System Details:**
* Operating System: GNU
* Distro(For GNU/Linux and BSD users): Xubuntu
* Desktop Environment(For GNU/Linux and BSD users): Xfce
* How do you install Persepolis? ppa

In IDM, there is a possibility that the site link from which we downloaded the file is also stored.
Until downloaded.Site access is possible.

**Comment by alireza-amirsamimi** [comment]
Hello
If you want the download link, select download item and click on properties.
If you want referrer link, you can't access to it in current version of persepolis. but we added it to persepolis for next version :)
![screenshot_20180201_145609](https://user-images.githubusercontent.com/7452500/35776604-d1aacc14-09b4-11e8-983a-becb824843e6.png)
