### ISSUE TITLE
3.1.0 release and incomplete languages

### ISSUE THREAD

**Issue by hayyan71** [persepolisdm/persepolis#437]
In latest commits, we've added support for other languages to the Persepolis Download Manager. Some people involved in the translation project and made some helpful contribution.

We are going to release 3.1.0 soon. please review translation phrases in transifex.com/persepolis/persepolis-translations/dashboard/ and complete any missing translation for your language. We'll add language which reaches 100% translation to the next version of Persepolis automatically.

@mostafaasadi 
@mdmk
@leoxxx

**Comment by leoxxx** [comment]
@hayyan71 
I've finished Chinese language 100%

**Comment by simonporte** [comment]
@hayyan71 
I've finished French language.
Would it be possible to have a test build in order to check the work done before release?
It'd make it easier for me to proofread.
I've some more edits to propose to english.
Would you mind to wait to review them before release too ?
I'll update #429

**Comment by hayyan71** [comment]
@mdmk 
You may get source code from git and build and test it.

I'll ask @mostafaasadi to add an instruction how to build Persepolis Download Manager in Windows. But,  I'll ask the devs to try to release a beta version for anyone who can't build Persepolis from source code.

Regards

**Comment by simonporte** [comment]
@hayyan71
Yes of course, I just don't have time to fiddle with this at the moment.
I'll see if I can setup a working build environnement later.

Releasing a beta at each major string changes would be a plus, for the convenience of contributors without technical knowledge.

**Comment by leoxxx** [comment]
@hayyan71
https://github.com/persepolisdm/persepolis/issues/448
Please update.

**Comment by simonporte** [comment]
I updated french translation on Transifex to reach again 100% (two strings changed recently).
I notice persian is missing 25 strings.
I did not get the time to make my own build to test.
Is the Compilation on Windows howto still planned ?

**Comment by alireza-amirsamimi** [comment]
I updated ts files.
Please check languages for the last time on transfix and complete all translations :)

**Comment by simonporte** [comment]
Darn, the one last string before a stable release please :p

**Comment by leoxxx** [comment]
I've finished.

**Comment by alireza-amirsamimi** [comment]
I added new translations to the persepolis.
Thanks, all of you :+1: 

You can test persepolis with your language now :)
