### ISSUE TITLE
اجرا نشدن نرم افزار پس از آپدیت به نسخه 2.0.2

### ISSUE THREAD

**Issue by LinArcX** [persepolisdm/persepolis#44]
علی جان من نرم افزار رو از مخازن آی.یو.آر به روز کردم ولی متاسفانه موقع اجرا این پیام رو بهم میده و نرم افزار اجرا نمیشه:
 saeed@saeed :persepolis             

---

---

***_Persepolis Download Manager**_*
***\*  Version : 2.0.2 Unstable ****

---

---

0

**Comment by alireza-amirsamimi** [comment]
فایل خطا رو بهم بده لطفا :)

**Comment by LinArcX** [comment]
حل شد.از ایشوی:
https://github.com/alireza-amirsamimi/persepolis/issues/39
تونستم موقت حلش کنم.
فایل خطا کجاست مسیرش؟

**Comment by alireza-amirsamimi** [comment]
/tmp/persepolis_error

**Comment by LinArcX** [comment]
علی جان دوباره این مشکل برای من بوجود اومد.این سری نه آپدیت کردم نه کاری کردم.اینم فایل خطا:
Traceback (most recent call last):
  File "/usr/share/persepolis/persepolis-download-manager", line 115, in <module>
    mainwindow = MainWindow()
  File "/usr/share/persepolis/mainwindow.py", line 206, in **init**
    item = QTableWidgetItem(download_info_file_lines[i].strip())
IndexError: list index out of range

**Comment by alireza-amirsamimi** [comment]
ممنون از اینکه اطلاع دادی
این مشکل رو در ورژن ۲.۱ حل کردم ولی هنوز منتشر نکردم
انشالله چند روز دیگه ورژن ۲.۱ برای انتشار آماده میشه و این مشکل حل شده
:+1:
