### ISSUE TITLE
exact reason of not using the qt designer 

### ISSUE THREAD

**Issue by MrSmiler** [persepolisdm/persepolis#443]
why exactly didn't you use qt designer ? 
development would be so easy .

**Comment by alireza-amirsamimi** [comment]
@MrSmiler Hello
It's not hard now😄
I prefer pure python 😊

**Comment by alireza-amirsamimi** [comment]
@MrSmiler QT Designer is good! But when you convert ui file to py file, many unnecessary lines with out any comment and without space between lines and ...  is added to code! It's not clear and sometimes it's a little complex and sometimes it's hard to edit it. So i prefer python coding😊
