### ISSUE TITLE
run error

### ISSUE THREAD

**Issue by 624980976** [persepolisdm/persepolis#446]
Operating System:windows 10
Distro:16299
 Persepolis Version:3.1.0
How do you install Persepolis:exe package
![image](https://user-images.githubusercontent.com/36782787/36625672-0257afb2-195f-11e8-9508-9e45bf3ad7f8.png)

**Comment by mostafaasadi** [comment]
Hi
make sure you have last persepolis bundle, it is [3.0.1](https://github.com/persepolisdm/persepolis/releases/tag/3.0.1) 
according to our conversation on https://github.com/persepolisdm/persepolis/issues/362 if you have    NonAscii character on your PATH or username cause this problem.

**Comment by 624980976** [comment]
yes,My username is Chinese,So it can't run？

**Comment by mostafaasadi** [comment]
latest pyinstaller(builder of persepolis on windows) has this problem with pyqt5 apps and NonAscii characters, so for latest build we have this problem(you can change username), yesterday i saw a patch on pyinstaller github and I will test it on next version
