### ISSUE TITLE
please solve my problem

### ISSUE THREAD

**Issue by PhoenixNil** [persepolisdm/persepolis#447]
![default](https://user-images.githubusercontent.com/33974040/36625753-9c6079d0-1960-11e8-8600-0c464a5b6c17.PNG)

i need help!!!!On many websites, there is such a problem with downloading, for example downloading anything on github:(

i hope find out reason and solve my issue!!

**Comment by alireza-amirsamimi** [comment]
Yes, I confirm this Issue.
Persepolis have this problem with github.
Please try [persepolis browser extension](https://github.com/persepolisdm/persepolis/wiki/home-en#extensions) for sending links to persepolis from you browser. Perhaps it reduces issues :)

**Comment by alireza-amirsamimi** [comment]
I fixed this bug.
Thanks for reporting :)
