### ISSUE TITLE
about the Chinese translation

### ISSUE THREAD

**Issue by davinma** [persepolisdm/persepolis#448]
1. **&View** to **视图(&V)**
2. **&Video Finder** to **视频嗅探(&V)**

there are _**two same**_ shortcut key(Alt + V), that is a conflict. So we need a new shortcut key for **&Video Finder** :-)

**Comment by leoxxx** [comment]
Are they same level menu?
If they are,it is necessary.

**Comment by alireza-amirsamimi** [comment]
Yes, They are same level menu :)
This bug must be solved :)

**Comment by alireza-amirsamimi** [comment]
I fixed the issue :)
Thanks for reporting.
