### ISSUE TITLE
وضوح کم پنجره برنامه

### ISSUE THREAD

**Issue by mehdirajabi59** [persepolisdm/persepolis#45]
سلام

پنجره اصلی برنامه خیلی کوچک می باشد و وضوح نوشته و آیکون های برنامه کم می باشد.

بنظر من اندازه پنجر اگر بصورت پیش فرض بزرگتر باشه خیلی بهتر است.

تم هم درسته که میشه تعویض کرد ولی تم پیش فرض از نظر قشنگی خوب است ولی وضوح خوبی ندارد.

![screenshot from 2016-08-23 12-57-47](https://cloud.githubusercontent.com/assets/7848036/17885171/3c570c74-6931-11e6-91c8-6fb26b60f26f.png)

**Comment by alireza-amirsamimi** [comment]
سلام
ممنون از فیدبکت
اندازه پنجره و ... با سلیقه شخصی من و رزلوشن کمپیوتر  جور هست
حالا یه ترتیبی میدم که علاوه بر فونت و اندازه فونت کاربر وقتی اندازه پنجره رو تغییر میده سایز جدید پنجره ذخیره بشه که سایز پنجره مطابق سلیق کاربر باشه 
:)
