### ISSUE TITLE
Download any streaming video

### ISSUE THREAD

**Issue by candrapersada** [persepolisdm/persepolis#451]
![download-youtube-idm](https://user-images.githubusercontent.com/36833664/36702232-c5799db8-1b88-11e8-90e0-22b6e48ca236.jpg)
add panel download video

**Comment by Hitaro** [comment]
There' other tools like 'Video Download Helper' addon for it.

**Comment by alireza-amirsamimi** [comment]
Hello
We can't add this feature to our web extension because of copy right and ... .If we add this, google deletes our web extension from [web store](https://chrome.google.com/webstore/detail/persepolis-download-manag/legimlagjjoghkoedakdjhocbeomojao?hl=en) . But we added a feature in next version of persepolis for finding media from video links :) See this picture :)
![screenshot_20180303_233833](https://user-images.githubusercontent.com/7452500/36938774-0a0226ec-1f3c-11e8-8616-dcd2344feff3.png)

**Comment by candrapersada** [comment]
can download FLV videos from popular sites like YouTube, MySpaceTV, and Google Video

**Comment by alireza-amirsamimi** [comment]
@candrapersada 
Yes :)

**Comment by Hitaro** [comment]
> we added a feature in next version of persepolis for finding media from video links

Does it use `youtube-dl`?

**Comment by alireza-amirsamimi** [comment]
@Hitaro Yes, it uses youtube-dl.

**Comment by candrapersada** [comment]
dailymotion

**Comment by alireza-amirsamimi** [comment]
@candrapersada 
You can find supported sites list [here](https://rg3.github.io/youtube-dl/supportedsites.html)

**Comment by candrapersada** [comment]
for linux mint

**Comment by alireza-amirsamimi** [comment]
@candrapersada 
What do you mean?

**Comment by candrapersada** [comment]
ubuntu ppa

**Comment by alireza-amirsamimi** [comment]
@candrapersada We release next version soon, and you can update from ppa :)

**Comment by candrapersada** [comment]
the file selection dialog will remember last folder

**Comment by candrapersada** [comment]
save c to d but next restore to c why?

**Comment by alireza-amirsamimi** [comment]
@candrapersada 
I don't understand. What do you mean?
get screenshot or explain more please :)

**Comment by candrapersada** [comment]
![download](https://user-images.githubusercontent.com/36833664/37238485-c9b11a3a-2459-11e8-9589-5c361553ed2c.jpg)
remember this path for save file for windows and linux

**Comment by alireza-amirsamimi** [comment]
@candrapersada 
Please open new issue for new question :)
Select preferences from edit menu. you can change the default save path there.

**Comment by Suzie97** [comment]
Can I download videos form Amazon Prime Videos using Persepolis?

**Comment by candrapersada** [comment]
and HLS Downloader
