### ISSUE TITLE
[Feature Request] Not possible to remove all entries at once

### ISSUE THREAD

**Issue by Hitaro** [persepolisdm/persepolis#453]
When you want to clean entries, it can't remove selected items. It just remove entries one by one.

**System Details:**
* Operating System: Archlinux
* Desktop Environment: KDE Plasma
* Persepolis Version: 3.0.1
* How did you installed Persepolis? from AUR

**Comment by alireza-amirsamimi** [comment]
See this [issue](https://github.com/persepolisdm/persepolis/issues/361) please.

**Comment by Hitaro** [comment]
By right-clicking on selected items, it just removes one entry, right under the mouse pointer.

**Comment by alireza-amirsamimi** [comment]
@Hitaro As I described the solution in that issue, check multiple items selection from edit menu.

**Comment by Hitaro** [comment]
It's odd, isn't?

**Comment by alireza-amirsamimi** [comment]
@Hitaro 
As I sescribed in that issue, we changed this for next version.
