### ISSUE TITLE
no hidden options

### ISSUE THREAD

**Issue by iman-salmani** [persepolisdm/persepolis#454]
**System Details:**
* Operating System: GNU/Linux
* Distro(For GNU/Linux and BSD users): xubuntu
* Desktop Environment(For GNU/Linux and BSD users): xfce4
* Persepolis Version: 3.0.1
* How do you install Persepolis? (Repositories, source, ...)
intall with Repositories

Hello
in the category
from download list go to the single download, no hidden options for download list

**Comment by alireza-amirsamimi** [comment]
Hello
I don't understand your issue. Can you record a video or take a screenshot?
