### ISSUE TITLE
download torrent file

### ISSUE THREAD

**Issue by iman-salmani** [persepolisdm/persepolis#455]
**System Details:**
* Operating System: ?
* Distro(For GNU/Linux and BSD users): ?
* Desktop Environment(For GNU/Linux and BSD users): ?
* Persepolis Version: ?
* How do you install Persepolis? (Repositories, source, ...)

* _Please attach log files if crash or paste error message_

**Issue Description and steps to reproduce:**

**Comment by hayyan71** [comment]
Please add some descriptions to your comment.

This issue was discussed before many times. Persepolis WILL NOT support torrent downloading. The aim of project was to provide a good download manager for Linux distros. There are good torrent clients out there. So, there isn't necessary to add this feature to Persepolis.

Regards

**Comment by Cabus1982** [comment]
> Please add some descriptions to your comment.
> 
> This issue was discussed before many times. Persepolis WILL NOT support torrent downloading. The aim of project was to provide a good download manager for Linux distros. There are good torrent clients out there. So, there isn't necessary to add this feature to Persepolis.
> 
> Regards


<there isn't necessary to add this feature to Persepolis>

simplify and unify functions tell you something?

**Comment by open-sourcerertech** [comment]
I get it, it's not necessary.  Why would a download manager work with a system geared entirely towards uploading and downloading.  Why install one application that handles everything when you can install a whole bunch that do just a little bit.  You sure this was a unix project?  Put a few adds up, make it trialware, and it would fit right in on windows.

**Comment by JafarAkhondali** [comment]
@open-sourcerertech If you call yourself an open-source*, you shouldn't flame to people putting their free time to make a free software. A free team decided they don't have more free time to develop this software or either they don't want to put priority for implementing this feature.
You do really love this feature? Make a pull request for it, or fork the project. No one is gonna stop\flame you.  

Also not everything related to download should be considered into a download manager. Most of torrent clients do not support downloading http* files, and most of DMs do not support downloading torrent files. I believe this is a nice to have feature, but we can't put time on developing it.
