### ISSUE TITLE
help wanted about proxy settings in Perspolis

### ISSUE THREAD

**Issue by dddeveloperrr** [persepolisdm/persepolis#458]
Hi, an Iranian user here. I use Persepolis 3.0.1 on windows 10 and wanted to know whether Persepolis uses windows proxy settings by default? because I was running psiphon3 and I pasted direct link to a YouTube video and Persepolis could detect the video size even though I didn't hit "Detect system proxy settings". ( considering the fact that Youtube is banned inside Iran) 

This is the direct link to a video in Youtube ( note that it may not be valid for you because youtube changes direct links to videos after a few while).
[link](https://r6---sn-aigllnzy.googlevideo.com/videoplayback?pl=23&fvip=3&signature=86E284BFC38784C656145A3D3FE95089A1C68E5C.393FBFDB372484510435D39ACD248B0712A32F6D&ei=PUykWsPKHcLuWYDWsaAJ&ip=178.62.20.42&ratebypass=yes&initcwndbps=237500&requiressl=yes&key=yt6&mime=video%2Fmp4&source=youtube&id=o-AIh5jswW4OSa7oaQvsh1l8f_PsM4e8Kufle8hLWq7jaD&dur=299.908&mn=sn-aigllnzy%2Csn-5hne6nsz&mm=31%2C26&ipbits=0&c=WEB&expire=1520738461&lmt=1509107572360627&itag=22&ms=au%2Conr&sparams=dur%2Cei%2Cid%2Cinitcwndbps%2Cip%2Cipbits%2Citag%2Clmt%2Cmime%2Cmm%2Cmn%2Cms%2Cmv%2Cpl%2Cratebypass%2Crequiressl%2Csource%2Cexpire&mv=m&mt=1520716759)

![zzzz](https://user-images.githubusercontent.com/11577640/37246995-f1a71584-24c8-11e8-9f61-d5dede69e962.png)

**Comment by alireza-amirsamimi** [comment]
Hello
about default proxy settings in windows: 
I'm not windows user. @mostafaasadi  will check it.

I'm not familiar with Psiphone. But if it's SOCKS proxy, you must convert it to http for persepolis.Read [this](https://github.com/persepolisdm/persepolis/wiki/Privoxy) for more help.

**Comment by dddeveloperrr** [comment]
@alireza-amirsamimi  thank you, and this is Psiphone3 log if it helps...

![shot](https://user-images.githubusercontent.com/11577640/37568360-6ba33c02-2ae9-11e8-882b-d546a75c7deb.png)

**Comment by mostafaasadi** [comment]
Hi @dddeveloperrr 
please choose a valid name for your issues
persepolis can detect standard proxy settings from windows proxy options
in your case persepolis can use http proxy , set psiphon http proxy

**Comment by dddeveloperrr** [comment]
@mostafaasadi 
@alireza-amirsamimi 
OK. thank you. In my opinion it would be a good idea to put an option in Preferences that the user could choose whether Persepolis detects windows proxy settings by default or not,  just in case a user wants not to download files through proxy while Psiphone ( or any other proxy software)  is running and if the user does actually wants to download through a proxy, he/she could do it by clicking on the "Detect system proxy settings" in download dialog box shown in the picture above
