### ISSUE TITLE
i am can not download file with persepolis ?!

### ISSUE THREAD

**Issue by sajjads24** [persepolisdm/persepolis#460]
**System Details:**
* Operating System: ?fedora
* Distro(For GNU/Linux and BSD users): ?linux
* Desktop Environment(For GNU/Linux and BSD users): ?KDE
* Persepolis Version: ?3.0.1
* How do you install Persepolis? (Repositories, source, ...)fedora repo
i am can not download file from link :
https://github.com/mi-g/vdhcoapp/releases/download/v1.1.3/net.downloadhelper.coapp-1.1.3-1_amd64.tar.gz

how fix persepolis ?

**Comment by alireza-amirsamimi** [comment]
I confirm this issue. We'll work on this problem.

**Comment by sajjads24** [comment]
[persepolisdm.log](https://github.com/persepolisdm/persepolis/files/1824523/persepolisdm.log)

**Comment by alireza-amirsamimi** [comment]
It was reported [here](https://github.com/persepolisdm/persepolis/issues/447) before.

**Comment by alireza-amirsamimi** [comment]
I fixed this bug!
Thanks for reporting :)
