### ISSUE TITLE
Base and client!

### ISSUE THREAD

**Issue by journeyer** [persepolisdm/persepolis#47]
متن انگلیسی چون پیشفرضه این گیته!
Hello!
Most probably, you have already seen the projects like 'wicd' and 'cmus', which separated to two parts such as base and client. So separating persepolis to base and client can help other programmers to make alternative clients for it, furthermore, It can make it easier to develop. 

متن فارسی چون صاحب ریپو احتمالا هم وطنه :)
احتمالا پروژه هایی ور مثل cmus و wicd دیدید که اومدن برنامه رو به دو بخش base و client تقسیم کردن
اگه پرسپولیس هم مثل اون برنامه ها دوبخش داشته باشه هم کلینت های متنوع تری می تونه داشته باشه هم توسعه ی راحت تر!

**Comment by alireza-amirsamimi** [comment]
راستش متوجه نشدم دقیقا
یه مثال برام بزن که واضح تر بشه
کدوم قسمت پرسپولیس باید بیس بشه و کدوم قسمت کلاینت
و اصلا این کار چه حسنی داره و چه کمکی میکنه

**Comment by ghost** [comment]
<div dir=rtl>
پرسپولیس خودش یه کلاینت هست برای برنامه aria2 و به نظر من نیازی به اینکه خودش هم یه سرور بشه و کلاینت داشته باشه نداره.
</dir>

**Comment by journeyer** [comment]
> یه مثال برام بزن که واضح تر بشه

مثال بالا زدم: cmus و wicd

> پرسپولیس خودش یه کلاینت هست برای برنامه aria2 و به نظر من نیازی به اینکه خودش هم یه سرور بشه و کلاینت داشته باشه نداره.

منم به این موضوع فکر کردم اما اینجوری میشه کلینت های یکپارچه تری تحت عنوان پرسپولیس داشت. مثلا یه کلینت با gtk یا تحت وب یا یه اپ رو موبایل که پرسپولیس رو کامپیوتر رو کنترل کنه... اما اگه فکر می کنید که نیاز به اینجور کلینت ها نداره این کار زمان بر هم ارزشی نداره :)

به هر حال یه نظر بود که موقع دیدن سورس ها به ذهنم رسید!

**Comment by alireza-amirsamimi** [comment]
> . مثلا یه کلینت با gtk یا تحت وب یا یه اپ رو موبایل که پرسپولیس رو کامپیوتر رو کنترل کنه

پیشنهاد خیلی خوبیه مرسی
تا حالا بهش فکر نکرده بودم
البته الان زوده که بریم دنبالش و بعد از تکمیل تر شدن برنامه میرم دنبالش
