### ISSUE TITLE
File names display stars & multiple download does not work.

### ISSUE THREAD

**Issue by JedStephens** [persepolisdm/persepolis#470]
**System Details:**
* Operating System: Windows 10
* Persepolis Version: 3.0.1
* How do you install Persepolis: win_64.exe

**Issue Description and steps to reproduce:**
When trying to download multiple files, the file names do not display in Persepolis and do not download.

Using Chrome and add-in Persepolis add-in, navigate to: https://www.stat.ncsu.edu/research/sas/sicl/data/ , right click and choose "Download all links". Persepolis gets links and adds to queue. However, file names stay stars and do not download - error messages for each one.
Works on the same website when downloading a single file using right click from Chrome.

**Comment by alireza-amirsamimi** [comment]
Hello
I solved "displaying name" bug before. We will publish new version tomorrow and problem is solved in newer version.
I selected(highlighted) 10 links(in firefox and chromium) and downloded them with persepolis. every thing was ok in newer version.
