### ISSUE TITLE
i cant download some files

### ISSUE THREAD

**Issue by azkia98** [persepolisdm/persepolis#472]
**System Details:**
![image](https://user-images.githubusercontent.com/28800471/37898859-2cc26cf8-30ff-11e8-816c-8821df4423fa.png)

i can't download this file `https://github.com/adobe/brackets/releases/download/release-1.12/Brackets.Release.1.12.64-bit.deb` 
of this page:[brackets](http://brackets.io/)

and i can't stop the download.also i don't have any error in the console.

**Comment by alireza-amirsamimi** [comment]
@azkia98 I fix this bug yesterday. We will publish new release soon.
