### ISSUE TITLE
Minimize to system tray on close

### ISSUE THREAD

**Issue by ahmed-h-ayyad** [persepolisdm/persepolis#477]
I have installed persepolis from AUR on manjaro and it works well, but I have feature request I think there should be an option to enable mimimize to tray when I click on close button istead of close it  completely. I know that I can do it from the view menu and by the ctrl+W from keyboard  but every time I forget that and close the program.

**Comment by dddeveloperrr** [comment]
@ahmed-h-ayyad yes, I also agree with you, thats a good idea

**Comment by alireza-amirsamimi** [comment]
Yes, I agree with you. 
But we have some problems on some operating systems. "Minimizing with close button" causes crashing issue , ... .
We must solve this.

**Comment by ahmed-h-ayyad** [comment]
any progress on this issue?

**Comment by alireza-amirsamimi** [comment]
I add this feature :)
So users can minimize Persepolis to the system tray with close(x) button.
Thanks for your feature request :+1:

**Comment by ahmed-h-ayyad** [comment]
I install git version from AUR but still no option for enable the feature

**Comment by alireza-amirsamimi** [comment]
@ahmed-h-ayyad Please open the preferences window and enable this option.
Edit>> preferences
