### ISSUE TITLE
In WIN7 X64,32bit version can't be installed,and 64bit version is error.

### ISSUE THREAD

**Issue by leoxxx** [persepolisdm/persepolis#483]
**System Details:**
* Operating System: WIN7 X64
* Persepolis Version: 3.1.0

32bit version can't be installed.
![image](http://i65.tinypic.com/148kw15.png)

64bit version is error.
Click the exe,then popup two dialog boxes。
![image](http://i68.tinypic.com/2cftfg4.png)
![image](http://i67.tinypic.com/k4vymg.png)
This error seems to happen since 3.0.0 version
It seems to miss some library files.

**Comment by mostafaasadi** [comment]
Hi @leoxxx 
I think you should update your system(windows), can you check and report me ?

**Comment by mostafaasadi** [comment]
@leoxxx 
or you can download and install [VC 2015 Redistributable](https://www.microsoft.com/en-US/download/details.aspx?id=48145) 
according to https://github.com/pyinstaller/pyinstaller/issues/1566#issuecomment-146564554 & https://github.com/pyinstaller/pyinstaller/issues/1588 you shuold update your system

**Comment by leoxxx** [comment]
@mostafaasadi 
I'll try it.
Yes,you're right.THX.It need VC 2015 Redistributable or VC 2017 Redistributable.
But why can't 32bit version be installed?
BTW.I copy the persepolis' folder to another PC.Why is it error.This PC has istalled VC 2015 Redistributable.

**Comment by mostafaasadi** [comment]
32 bit version will work just on a 32 bit machin
and please explain second pc problem

**Comment by leoxxx** [comment]
@mostafaasadi 
I want get a portable version. So, I install it in first PC.Then copy the folder to second PC.It is error in second one as above picture. These PC have installed same version VC 2015 Redistributable.

**Comment by mostafaasadi** [comment]
for now you can't do this.
use the standard installe
