### ISSUE TITLE
Persepolis Download Manager has stopped when I import a aria2c.down file.

### ISSUE THREAD

**Issue by zyppe** [persepolisdm/persepolis#485]
**System Details:**
* Operating System: Windows 10 x64 1709
* Persepolis Version: 3.1
* How do you install Persepolis? (Repositories, source, ...) Releases
* _Please attach log files if crash or paste error message_
Persepolis Download Manager已停止运行（Persepolis Download Manager has stopped.）(Windows gives it.)
**Issue Description and steps to reproduce:**
I just import an aria2c.down file to the software, and it stopped at once.
To use aria2c.down files I just need to type aria2c -i aria2c.down in the command line/terminal.
Here is a piece of aria2c.down
"
https://d.pcs.baidu.com/file/3a3bda339e13faa83389c40a2de2d244?fid=828365796-250528-45879284212175&time=1522571640&rt=sh&sign=FDTAERVY-DCb740ccc5511e5e8fedcff06b081203-%2BJqj%2BoVNCx52CylkN6PMbMKx124%3D&expires=8h&chkv=1&chkbd=0&chkpc=et&dp-logid=2103363667597567268&dp-callid=0&r=741788395
 header=User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.132 Safari/537.36
 header=Referer: https://pan.baidu.com/disk/home
 header=Cookie: BDUSS=WhvbDI1YzRrekR6dXdKUzRCMndiUEItMDAyUlRWWG5DMlNRSERrdVR3TWFyLVphQUFBQUFBJCQAAAAAAAAAAAEAAACSQBQIsqjAvbK7vqqwyQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABoiv1oaIr9ae; pcsett=1522658029-51cbc3b4a52c2d42599414493d57a6c3
 out=[游戏编程数学和物理基础].(斯达乐).徐明亮等.扫描版[ED2000.COM].pdf
"
You can just use this piece as a aria2c.down file.

**Comment by alireza-amirsamimi** [comment]
I'm confused :) What is aria2c.down file?

**Comment by zyppe** [comment]
I create the file from another github project https://github.com/acgotaku/BaiduExporter.
The first line is the download url, second line is header... as you see.
This function can be seen from an android software from [https://play.google.com/store/apps/details?id=com.dv.adm](url)

**Comment by alireza-amirsamimi** [comment]
This is not work for persepolis :)

**Comment by leoxxx** [comment]
Aria seems not to support SSL url.
Try HTTP url.
And BaiduExporter is invaild now,because baidupan has updated.
