### ISSUE TITLE
Complete program closure

### ISSUE THREAD

**Issue by farazsahebdel** [persepolisdm/persepolis#486]
One big problem is that once you close the window, the entire program closes, so it's not better to go to the minimization and running programs ?

**Comment by alireza-amirsamimi** [comment]
Yes, I agree with you. But we have some problems on some operating systems.
Yes, I agree with you. 
But we have some problems on some operating systems. "Minimizing with close button" causes crashing issue , ... .
We must solve this. 
Try Ctrl+W or select minimize icon on persepolis toolbar  or from view menu minimize persepolis :)

**Comment by farazsahebdel** [comment]
It would be very good if you solved this problem. Because we used to

**Comment by ivanparvaresh** [comment]
In my case, after closing the window the application was frozen and did not completely closed. and the only choice was force-quit it.
