### ISSUE TITLE
About icon layout is below the menu text

### ISSUE THREAD

**Issue by davinma** [persepolisdm/persepolis#488]
**System Details:**
* Operating System: Windows 7 64 bit
* Persepolis Version: 3.1.0

The icon next to the menu text is not in the right position, here is the screenshot: <br/>
![image](https://user-images.githubusercontent.com/2345776/38189689-d32cd1d4-3693-11e8-9c1d-88dbe96d66d9.png)

**Comment by alireza-amirsamimi** [comment]
Yes, this style wouldn't work properly in Windows.
Try another [style](https://github.com/persepolisdm/persepolis/wiki/How-to-change-Persepolis-theme).
We'll fix this for Windows.

**Comment by alireza-amirsamimi** [comment]
Hi
I fixed this bug.
Thanks for reporting :+1: 

![image](https://user-images.githubusercontent.com/7452500/64565491-1e9ad080-d369-11e9-951a-a428feb6d862.png)
