### ISSUE TITLE
Update WebSite

### ISSUE THREAD

**Issue by Pakrohk** [persepolisdm/persepolis#492]
Update the Persepolis website.

**Comment by alireza-amirsamimi** [comment]
@APakrohk Website is already updated. Isn't it?

**Comment by Pakrohk** [comment]
Persepolis Download Manager is located in the official Fedora repository.
![screenshot_20180406-042611](https://user-images.githubusercontent.com/27810360/38397496-6dd80fb4-392d-11e8-87eb-05af1a5f959d.png)

**Comment by Alirezaies** [comment]
@APakrohk see [pull request 28](https://github.com/persepolisdm/persepolisdm.github.io/pull/28)
