### ISSUE TITLE
مشکل دانلود برخی از لینک های ویدیویی

### ISSUE THREAD

**Issue by mehrshadmti** [persepolisdm/persepolis#496]
سلام
لینک های ویدویی مشابه
http://f10.cdn.filmnet.ir/streamer/streamer.ashx?q=1080P&t=d&session=a563d7aa-fce7-4ba2-9a32-e8980e0634d8&clientType=3&deviceId=&token=uKkwMJ6jDnPx4H4a5Yh3g1zMVd-SaSsdSB-Wnma5D_KKrfoUR9KpaIN70GCNcCNgRQ1Q4XMVQ_rTXftQw032JsVzabFbxF4FGKCcRHNtYIKQerUgAUTQl8YjDhYGrxKT6XPkxf2j_ao5Chl815t8anfO-O35YEjEn9Lnw5sRsoVwRJ6BJoVwXcHE_UHFXomrDjf7WOh7anJXhO_XfQ73HXMZts5kznbo_LCQMG6Kt4MIHLLhPJgtO3-jwhgMrHCb5ofL-H4k3gnmdTUGyHO7Gmt-JJ-dJbCTwUgiHSQCIpPBlp8F0ioaYYEX9MAU9WFXfn6_9yVfCJKOycexy34WwyqPntmABHaO--qjWxyqsDWT7Inm2Pyvd71yU6bH59yCpMhSbqcDDbkNNsPklT2fCcTs2xz6lZEjp9ftLpKRqbqZx4g4L8TN8hwfiW7Gf7Ck7PzSqD9QecnIxWiOEuL8vE74rYYMKUAh_dK_OaQfE3c1

را نمیتواند به درستی بخواند لطفا درستش کنید

**Comment by mostafaasadi** [comment]
Hi @mehrshad000 
use english language here, please.
I tested your link with latest version (3.1.0) and persepolis was downloading the movie successfully
![screenshot_20180412_220419](https://user-images.githubusercontent.com/12208050/38694079-f4bc0434-3e9d-11e8-9307-15a3fbb114fa.png)

**Comment by mehrshadmti** [comment]
دانلود میکه اما فایل دانلود شده اجرا نمیشود
فرمت فایل را تغییر دادم اما کارنکرد

حتی این دانلود منیجر نتوانست مشابه idm 
 فرمت فایل و نام را به درستس تشخیص دهد
![dl](https://user-images.githubusercontent.com/15233625/38741701-c266ffe0-3f4f-11e8-9732-2f7152ec57af.PNG)

**Comment by alireza-amirsamimi** [comment]
@mehrshad000 Hello
Please use English language here.
Persepolis uses aria2 as downloading tool. So the name of downloaded file or ... is related to aria2, not Persepolis. you can rename the file name when you add a link for download. I will add a feature for showing file's name suggestion(similar to your IDM's screen shot). Perhaps this will solve the issue.

**Comment by alireza-amirsamimi** [comment]
I added your feature request :) You can see it in this video and You can use it in next version of persepolis.

[vokoscreen-2018-04-14_15-08-41.zip](https://github.com/persepolisdm/persepolis/files/1910266/vokoscreen-2018-04-14_15-08-41.zip)
