### ISSUE TITLE
"Fusion" UI Style shows strangly.

### ISSUE THREAD

**Issue by Yanstory** [persepolisdm/persepolis#498]
**System Details:**
* Operating System: Windows 10
* Persepolis Version: 3.1.0 (install it by using binary file and overwrite the old 3.0.1 files)

The "New" color scheme (name without "Old") of UI style "Fusion" shows strangly on my computer,no border line shown on buttons and other things.

**Comment by alireza-amirsamimi** [comment]
Hello
Thanks for reporting. this problem is reported [before](https://github.com/persepolisdm/persepolis/issues/488). So I close this issue.
Thank you.
