### ISSUE TITLE
عدم ادامه دانلود از سایت http://3tinyz.com

### ISSUE THREAD

**Issue by Mr-undead** [persepolisdm/persepolis#5]
فعلا فقط با این سایت همچین مشکلی دارم. برای دانلود از این سایت باید ثبت نام کرده و اکانت بخرید که من خریدم. اما مشکل یک لینک را به برنامه میدیم برای دانلود اگر در حین دانلود دکمه 
pause 
بزنیم و دوباره روی 
resume
بزنیم دانلود ادامه پیدا نمیکنه و برنامه نوتیفیکشن ارور دانلود میده و یه پنجره میاد با این مضمون
Aria2 did not respond! Try again!
وقتی روی دکمه اوکی این پنجره کلیک میکنم برنامه کرش کرده و بسته میشه 
به صورت تصادفی در هر باز اجرای برنامه دو تا خروجی متفاوت داخل ترمینال داده میشه که هر دو را میگذارم
نوع اول
`[behrooz@Lenovo-G500 ~]$ persepolis

---

---

***_Persepolis Download Manager**_*
***\*  Version : 2.0.0 Unstable ****

---

---

0
Aria2 Version : 1.25.0
None Starts
None Starts
8ed99e40c061c450 Starts
8ed99e40c061c450 paused
8ed99e40c061c450 unpaused
None Starts
Segmentation fault (core dumped)
`
نوع دوم
`[behrooz@Lenovo-G500 ~]$ persepolis

---

---

***_Persepolis Download Manager**_*
***\*  Version : 2.0.0 Unstable ****

---

---

0
Aria2 Version : 1.25.0
None Starts
**\* Error in `/usr/bin/python3': malloc(): memory corruption (fast): 0x00007fe75005f00f ***
======= Backtrace: =========
/usr/lib/libc.so.6(+0x6ed4b)[0x7fe7838b7d4b]
/usr/lib/libc.so.6(+0x74546)[0x7fe7838bd546]
/usr/lib/libc.so.6(+0x76981)[0x7fe7838bf981]
/usr/lib/libc.so.6(__libc_malloc+0x54)[0x7fe7838c11d4]
/usr/lib/libstdc++.so.6(_Znwm+0x18)[0x7fe781127968]
/usr/lib/libQt5Widgets.so.5(+0x164a4f)[0x7fe7784e6a4f]
/usr/lib/libQt5Widgets.so.5(+0x16566d)[0x7fe7784e766d]
/usr/lib/libQt5Widgets.so.5(_ZN7QWidget6updateERK5QRect+0x103)[0x7fe778507613]
/usr/lib/libQt5Widgets.so.5(_ZN7QWidget6updateEv+0x43)[0x7fe7785076c3]
/usr/lib/libQt5Widgets.so.5(_ZN11QPushButton10setDefaultEb+0x4d)[0x7fe7786552ad]
/usr/lib/libQt5Widgets.so.5(_ZN14QDialogPrivate10setDefaultEP11QPushButton+0x104)[0x7fe7786c2454]
/usr/lib/libQt5Widgets.so.5(_ZN11QPushButton13focusOutEventEP11QFocusEvent+0xb8)[0x7fe7786563d8]
/usr/lib/libQt5Widgets.so.5(_ZN7QWidget5eventEP6QEvent+0x6ff)[0x7fe77851d30f]
/usr/lib/libQt5Widgets.so.5(_ZN19QApplicationPrivate13notify_helperEP7QObjectP6QEvent+0x9c)[0x7fe7784d5e3c]
/usr/lib/libQt5Widgets.so.5(_ZN12QApplication6notifyEP7QObjectP6QEvent+0x261)[0x7fe7784dd5b1]
/usr/lib/python3.5/site-packages/PyQt5/QtWidgets.so(+0x399d1e)[0x7fe778f74d1e]
/usr/lib/libQt5Core.so.5(_ZN16QCoreApplication15notifyInternal2EP7QObjectP6QEvent+0x110)[0x7fe7816a5c80]
/usr/lib/libQt5Widgets.so.5(_ZN19QApplicationPrivate14setFocusWidgetEP7QWidgetN2Qt11FocusReasonE+0xc1)[0x7fe7784dafe1]
/usr/lib/libQt5Widgets.so.5(_ZN12QApplication15setActiveWindowEP7QWidget+0x4d5)[0x7fe7784db665]
/usr/lib/libQt5Widgets.so.5(_ZN14QWidgetPrivate23deactivateWidgetCleanupEv+0x37)[0x7fe778504137]
/usr/lib/libQt5Widgets.so.5(_ZN14QWidgetPrivate8hide_sysEv+0x47)[0x7fe7785119f7]
/usr/lib/libQt5Widgets.so.5(_ZN14QWidgetPrivate11hide_helperEv+0x8d)[0x7fe77851804d]
/usr/lib/libQt5Widgets.so.5(_ZN7QWidget10setVisibleEb+0x370)[0x7fe77851caf0]
/usr/lib/libQt5Widgets.so.5(_ZN7QDialog10setVisibleEb+0x232)[0x7fe7786c3352]
/usr/lib/python3.5/site-packages/PyQt5/QtWidgets.so(+0x22f27c)[0x7fe778e0a27c]
/usr/lib/libQt5Widgets.so.5(_ZN7QDialog4doneEi+0x12)[0x7fe7786c1ae2]
/usr/lib/python3.5/site-packages/PyQt5/QtWidgets.so(+0x22efea)[0x7fe778e09fea]
/usr/lib/libQt5Widgets.so.5(+0x36180a)[0x7fe7786e380a]
/usr/lib/libQt5Widgets.so.5(+0x363230)[0x7fe7786e5230]
/usr/lib/libQt5Core.so.5(_ZN11QMetaObject8activateEP7QObjectiiPPv+0x639)[0x7fe7816d14e9]
/usr/lib/libQt5Widgets.so.5(_ZN16QDialogButtonBox7clickedEP15QAbstractButton+0x3f)[0x7fe7785eb79f]
/usr/lib/libQt5Widgets.so.5(+0x269e0a)[0x7fe7785ebe0a]
/usr/lib/libQt5Core.so.5(_ZN7QObject5eventEP6QEvent+0xe9)[0x7fe7816d2349]
/usr/lib/libQt5Widgets.so.5(_ZN7QWidget5eventEP6QEvent+0x4fb)[0x7fe77851d10b]
/usr/lib/libQt5Widgets.so.5(_ZN16QDialogButtonBox5eventEP6QEvent+0x41)[0x7fe7785ed421]
/usr/lib/libQt5Widgets.so.5(_ZN19QApplicationPrivate13notify_helperEP7QObjectP6QEvent+0x9c)[0x7fe7784d5e3c]
/usr/lib/libQt5Widgets.so.5(_ZN12QApplication6notifyEP7QObjectP6QEvent+0x261)[0x7fe7784dd5b1]
/usr/lib/python3.5/site-packages/PyQt5/QtWidgets.so(+0x399d1e)[0x7fe778f74d1e]
/usr/lib/libQt5Core.so.5(_ZN16QCoreApplication15notifyInternal2EP7QObjectP6QEvent+0x110)[0x7fe7816a5c80]
/usr/lib/libQt5Core.so.5(_ZN23QCoreApplicationPrivate16sendPostedEventsEP7QObjectiP11QThreadData+0x2dd)[0x7fe7816a83fd]
/usr/lib/libQt5Core.so.5(+0x2db173)[0x7fe7816fa173]
/usr/lib/libglib-2.0.so.0(g_main_context_dispatch+0x2a7)[0x7fe780131dd7]
/usr/lib/libglib-2.0.so.0(+0x4a040)[0x7fe780132040]
/usr/lib/libglib-2.0.so.0(g_main_context_iteration+0x2c)[0x7fe7801320ec]
/usr/lib/libQt5Core.so.5(_ZN20QEventDispatcherGlib13processEventsE6QFlagsIN10QEventLoop17ProcessEventsFlagEE+0x5f)[0x7fe7816fa57f]
/usr/lib/libQt5Core.so.5(_ZN10QEventLoop4execE6QFlagsINS_17ProcessEventsFlagEE+0xfa)[0x7fe7816a40da]
/usr/lib/libQt5Widgets.so.5(_ZN7QDialog4execEv+0x1b7)[0x7fe7786c2747]
/usr/lib/python3.5/site-packages/PyQt5/QtWidgets.so(+0x38006d)[0x7fe778f5b06d]
/usr/lib/libpython3.5m.so.1.0(PyCFunction_Call+0xc9)[0x7fe783eb68a9]
/usr/lib/libpython3.5m.so.1.0(PyEval_EvalFrameEx+0x86fb)[0x7fe783f2e47b]
/usr/lib/libpython3.5m.so.1.0(+0x1282c3)[0x7fe783f2f2c3]
/usr/lib/libpython3.5m.so.1.0(PyEval_EvalCodeEx+0x23)[0x7fe783f2f3a3]
/usr/lib/libpython3.5m.so.1.0(+0x93008)[0x7fe783e9a008]
/usr/lib/libpython3.5m.so.1.0(PyObject_Call+0x47)[0x7fe783e6f2d7]
/usr/lib/libpython3.5m.so.1.0(+0x7ed44)[0x7fe783e85d44]
/usr/lib/libpython3.5m.so.1.0(PyObject_Call+0x47)[0x7fe783e6f2d7]
/usr/lib/libpython3.5m.so.1.0(PyEval_CallObjectWithKeywords+0x47)[0x7fe783f25a87]
/usr/lib/python3.5/site-packages/sip.so(+0x11714)[0x7fe77d1f5714]
/usr/lib/python3.5/site-packages/PyQt5/QtCore.so(+0x9eed0)[0x7fe781b94ed0]
/usr/lib/python3.5/site-packages/PyQt5/QtCore.so(+0xe7da3)[0x7fe781bddda3]
/usr/lib/libQt5Core.so.5(+0xacd78)[0x7fe7814cbd78]
/usr/lib/libpthread.so.0(+0x7484)[0x7fe783bf1484]
/usr/lib/libc.so.6(clone+0x6d)[0x7fe7839306dd]
======= Memory map: ========
00400000-00401000 r-xp 00000000 08:01 5013773                            /usr/bin/python3.5
00601000-00602000 r--p 00001000 08:01 5013773                            /usr/bin/python3.5
00602000-00603000 rw-p 00002000 08:01 5013773                            /usr/bin/python3.5
0221a000-0300a000 rw-p 00000000 00:00 0                                  [heap]
7fe740000000-7fe740021000 rw-p 00000000 00:00 0 
7fe740021000-7fe744000000 ---p 00000000 00:00 0 
7fe744000000-7fe744021000 rw-p 00000000 00:00 0 
7fe744021000-7fe748000000 ---p 00000000 00:00 0 
7fe748000000-7fe748048000 rw-p 00000000 00:00 0 
7fe748048000-7fe74c000000 ---p 00000000 00:00 0 
7fe74c000000-7fe74c021000 rw-p 00000000 00:00 0 
7fe74c021000-7fe750000000 ---p 00000000 00:00 0 
7fe750000000-7fe75016c000 rw-p 00000000 00:00 0 
7fe75016c000-7fe754000000 ---p 00000000 00:00 0 
7fe754000000-7fe754021000 rw-p 00000000 00:00 0 
7fe754021000-7fe758000000 ---p 00000000 00:00 0 
7fe7586f6000-7fe7586fe000 r-xp 00000000 08:01 6165358                    /usr/lib/qt/plugins/iconengines/libqsvgicon.so
7fe7586fe000-7fe7588fd000 ---p 00008000 08:01 6165358                    /usr/lib/qt/plugins/iconengines/libqsvgicon.so
7fe7588fd000-7fe7588fe000 r--p 00007000 08:01 6165358                    /usr/lib/qt/plugins/iconengines/libqsvgicon.so
7fe7588fe000-7fe7588ff000 rw-p 00008000 08:01 6165358                    /usr/lib/qt/plugins/iconengines/libqsvgicon.so
7fe7588ff000-7fe7589b9000 r-xp 00000000 08:01 5926895                    /usr/lib/python3.5/lib-dynload/unicodedata.cpython-35m-x86_64-linux-gnu.so
7fe7589b9000-7fe758bb8000 ---p 000ba000 08:01 5926895                    /usr/lib/python3.5/lib-dynload/unicodedata.cpython-35m-x86_64-linux-gnu.so
7fe758bb8000-7fe758bb9000 r--p 000b9000 08:01 5926895                    /usr/lib/python3.5/lib-dynload/unicodedata.cpython-35m-x86_64-linux-gnu.so
7fe758bb9000-7fe758bd2000 rw-p 000ba000 08:01 5926895                    /usr/lib/python3.5/lib-dynload/unicodedata.cpython-35m-x86_64-linux-gnu.so
7fe758bd2000-7fe758cbd000 rw-s 00000000 00:05 976486422                  /SYSV00000000 (deleted)
7fe758cbd000-7fe758cc8000 r-xp 00000000 08:01 4984020                    /usr/lib/libnss_files-2.23.so
7fe758cc8000-7fe758ec7000 ---p 0000b000 08:01 4984020                    /usr/lib/libnss_files-2.23.so
7fe758ec7000-7fe758ec8000 r--p 0000a000 08:01 4984020                    /usr/lib/libnss_files-2.23.so
7fe758ec8000-7fe758ec9000 rw-p 0000b000 08:01 4984020                    /usr/lib/libnss_files-2.23.so
7fe758ec9000-7fe758ecf000 rw-p 00000000 00:00 0 
7fe758ecf000-7fe758ed7000 r-xp 00000000 08:01 5006167                    /usr/lib/libpciaccess.so.0.11.1
7fe758ed7000-7fe7590d7000 ---p 00008000 08:01 5006167                    /usr/lib/libpciaccess.so.0.11.1
7fe7590d7000-7fe7590d8000 r--p 00008000 08:01 5006167                    /usr/lib/libpciaccess.so.0.11.1
7fe7590d8000-7fe7590d9000 rw-p 00009000 08:01 5006167                    /usr/lib/libpciaccess.so.0.11.1
7fe7590d9000-7fe7590e4000 r-xp 00000000 08:01 5006219                    /usr/lib/libdrm_radeon.so.1.0.1
7fe7590e4000-7fe7592e3000 ---p 0000b000 08:01 5006219                    /usr/lib/libdrm_radeon.so.1.0.1
7fe7592e3000-7fe7592e4000 r--p 0000a000 08:01 5006219                    /usr/lib/libdrm_radeon.so.1.0.1
7fe7592e4000-7fe7592e5000 rw-p 0000b000 08:01 5006219                    /usr/lib/libdrm_radeon.so.1.0.1
7fe7592e5000-7fe7592ec000 r-xp 00000000 08:01 5006226                    /usr/lib/libdrm_nouveau.so.2.0.0
7fe7592ec000-7fe7594eb000 ---p 00007000 08:01 5006226                    /usr/lib/libdrm_nouveau.so.2.0.0
7fe7594eb000-7fe7594ec000 r--p 00006000 08:01 5006226                    /usr/lib/libdrm_nouveau.so.2.0.0
7fe7594ec000-7fe7594ed000 rw-p 00007000 08:01 5006226                    /usr/lib/libdrm_nouveau.so.2.0.0
7fe7594ed000-7fe75950d000 r-xp 00000000 08:01 5006220                    /usr/lib/libdrm_intel.so.1.0.0
7fe75950d000-7fe75970c000 ---p 00020000 08:01 5006220                    /usr/lib/libdrm_intel.so.1.0.0
7fe75970c000-7fe75970d000 r--p 0001f000 08:01 5006220                    /usr/lib/libdrm_intel.so.1.0.0
7fe75970d000-7fe75970e000 rw-p 00020000 08:01 5006220                    /usr/lib/libdrm_intel.so.1.0.0
7fe75970e000-7fe759dad000 r-xp 00000000 08:01 5528347                    /usr/lib/xorg/modules/dri/i965_dri.so
7fe759dad000-7fe759fad000 ---p 0069f000 08:01 5528347                    /usr/lib/xorg/modules/dri/i965_dri.so
7fe759fad000-7fe759fec000 r--p 0069f000 08:01 5528347                    /usr/lib/xorg/modules/dri/i965_dri.so
7fe759fec000-7fe759ff4000 rw-p 006de000 08:01 5528347                    /usr/lib/xorg/modules/dri/i965_dri.so
7fe759ff4000-7fe759ffc000 rw-p 00000000 00:00 0 
7fe759ffc000-7fe759ffd000 ---p 00000000 00:00 0 
7fe759ffd000-7fe75a7fd000 rw-p 00000000 00:00 0 
7fe75a7fd000-7fe75a7fe000 ---p 00000000 00:00 0 
7fe75a7fe000-7fe75affe000 rw-p 00000000 00:00 0 
7fe75affe000-7fe75afff000 ---p 00000000 00:00 0 
7fe75afff000-7fe75b7ff000 rw-p 00000000 00:00 0 
7fe75b7ff000-7fe75b800000 ---p 00000000 00:00 0 
7fe75b800000-7fe75c000000 rw-p 00000000 00:00 0 
7fe75c000000-7fe75c022000 rw-p 00000000 00:00 0 
7fe75c022000-7fe760000000 ---p 00000000 00:00 0 
7fe7600c3000-7fe7600c4000 ---p 00000000 00:00 0 
7fe7600c4000-7fe7609c4000 rw-p 00000000 00:00 0 
7fe760a1b000-7fe760a72000 r--p 00000000 08:01 5786850                    /usr/share/fonts/TTF/Ubuntu-R.ttf
7fe760a72000-7fe760ac4000 r--p 00000000 08:01 5786254                    /usr/share/fonts/Ubuntu_Bold.ttf
7fe760ac4000-7fe760ac8000 r-xp 00000000 08:01 5011572                    /usr/lib/libwebpdemux.so.2.0.0
7fe760ac8000-7fe760cc7000 ---p 00004000 08:01 5011572                    /usr/lib/libwebpdemux.so.2.0.0
7fe760cc7000-7fe760cc8000 r--p 00003000 08:01 5011572                    /usr/lib/libwebpdemux.so.2.0.0
7fe760cc8000-7fe760cc9000 rw-p 00004000 08:01 5011572                    /usr/lib/libwebpdemux.so.2.0.0
7fe760cc9000-7fe760d26000 r-xp 00000000 08:01 5011569                    /usr/lib/libwebp.so.6.0.0
7fe760d26000-7fe760f25000 ---p 0005d000 08:01 5011569                    /usr/lib/libwebp.so.6.0.0
7fe760f25000-7fe760f26000 r--p 0005c000 08:01 5011569                    /usr/lib/libwebp.so.6.0.0
7fe760f26000-7fe760f27000 rw-p 0005d000 08:01 5011569                    /usr/lib/libwebp.so.6.0.0
7fe760f27000-7fe760f28000 rw-p 00000000 00:00 0 
7fe760f28000-7fe760f2d000 r-xp 00000000 08:01 6164053                    /usr/lib/qt/plugins/imageformats/libqwebp.so
7fe760f2d000-7fe76112c000 ---p 00005000 08:01 6164053                    /usr/lib/qt/plugins/imageformats/libqwebp.so
7fe76112c000-7fe76112d000 r--p 00004000 08:01 6164053                    /usr/lib/qt/plugins/imageformats/libqwebp.so
7fe76112d000-7fe76112e000 rw-p 00005000 08:01 6164053                    /usr/lib/qt/plugins/imageformats/libqwebp.so
7fe76112e000-7fe761132000 r-xp 00000000 08:01 6164055                    /usr/lib/qt/plugins/imageformats/libqwbmp.so
7fe761132000-7fe761332000 ---p 00004000 08:01 6164055                    /usr/lib/qt/plugins/imageformats/libqwbmp.so
7fe761332000-7fe761333000 r--p 00004000 08:01 6164055                    /usr/lib/qt/plugins/imageformats/libqwbmp.so
7fe761333000-7fe761334000 rw-p 00005000 08:01 6164055                    /usr/lib/qt/plugins/imageformats/libqwbmp.so
7fe761334000-7fe7613b0000 r-xp 00000000 08:01 5006933                    /usr/lib/libtiff.so.5.2.4
7fe7613b0000-7fe7615b0000 ---p 0007c000 08:01 5006933                    /usr/lib/libtiff.so.5.2.4
7fe7615b0000-7fe7615b1000 r--p 0007c000 08:01 5006933                    /usr/lib/libtiff.so.5.2.4
7fe7615b1000-7fe7615b7000 rw-p 0007d000 08:01 5006933                    /usr/lib/libtiff.so.5.2.4
7fe7615b7000-7fe7615b8000 rw-p 00000000 00:00 0 
7fe7615b8000-7fe7615bf000 r-xp 00000000 08:01 6164051                    /usr/lib/qt/plugins/imageformats/libqtiff.so
7fe7615bf000-7fe7617be000 ---p 00007000 08:01 6164051                    /usr/lib/qt/plugins/imageformats/libqtiff.so
7fe7617be000-7fe7617bf000 r--p 00006000 08:01 6164051                    /usr/lib/qt/plugins/imageformats/libqtiff.so
7fe7617bf000-7fe7617c0000 rw-p 00007000 08:01 6164051                    /usr/lib/qt/plugins/imageformats/libqtiff.so
7fe7617c0000-7fe7617c5000 r-xp 00000000 08:01 6164050                    /usr/lib/qt/plugins/imageformats/libqtga.so
7fe7617c5000-7fe7619c4000 ---p 00005000 08:01 6164050                    /usr/lib/qt/plugins/imageformats/libqtga.so
7fe7619c4000-7fe7619c5000 r--p 00004000 08:01 6164050                    /usr/lib/qt/plugins/imageformats/libqtga.so
7fe7619c5000-7fe7619c6000 rw-p 00005000 08:01 6164050                    /usr/lib/qt/plugins/imageformats/libqtga.so
7fe7619c6000-7fe761a17000 r-xp 00000000 08:01 5015518                    /usr/lib/libQt5Svg.so.5.7.0
7fe761a17000-7fe761c17000 ---p 00051000 08:01 5015518                    /usr/lib/libQt5Svg.so.5.7.0
7fe761c17000-7fe761c19000 r--p 00051000 08:01 5015518                    /usr/lib/libQt5Svg.so.5.7.0
7fe761c19000-7fe761c1a000 rw-p 00053000 08:01 5015518                    /usr/lib/libQt5Svg.so.5.7.0
7fe761c1a000-7fe761c1f000 r-xp 00000000 08:01 6165359                    /usr/lib/qt/plugins/imageformats/libqsvg.so
7fe761c1f000-7fe761e1e000 ---p 00005000 08:01 6165359                    /usr/lib/qt/plugins/imageformats/libqsvg.so
7fe761e1e000-7fe761e1f000 r--p 00004000 08:01 6165359                    /usr/lib/qt/plugins/imageformats/libqsvg.so
7fe761e1f000-7fe761e20000 rw-p 00005000 08:01 6165359                    /usr/lib/qt/plugins/imageformats/libqsvg.so
7fe761e20000-7fe761e76000 r-xp 00000000 08:01 5007290                    /usr/lib/liblcms2.so.2.0.7
7fe761e76000-7fe762075000 ---p 00056000 08:01 5007290                    /usr/lib/liblcms2.so.2.0.7
7fe762075000-7fe762076000 r--p 00055000 08:01 5007290                    /usr/lib/liblcms2.so.2.0.7
7fe762076000-7fe76207b000 rw-p 00056000 08:01 5007290                    /usr/lib/liblcms2.so.2.0.7
7fe76207b000-7fe7620e8000 r-xp 00000000 08:01 5014109                    /usr/lib/libmng.so.2.0.2
7fe7620e8000-7fe7622e8000 ---p 0006d000 08:01 5014109                    /usr/lib/libmng.so.2.0.2
7fe7622e8000-7fe7622eb000 r--p 0006d000 08:01 5014109                    /usr/lib/libmng.so.2.0.2
7fe7622eb000-7fe7622ed000 rw-p 00070000 08:01 5014109                    /usr/lib/libmng.so.2.0.2
7fe7622ed000-7fe7622f3000 r-xp 00000000 08:01 6164054                    /usr/lib/qt/plugins/imageformats/libqmng.so
7fe7622f3000-7fe7624f2000 ---p 00006000 08:01 6164054                    /usr/lib/qt/plugins/imageformats/libqmng.so
7fe7624f2000-7fe7624f3000 r--p 00005000 08:01 6164054                    /usr/lib/qt/plugins/imageformats/libqmng.so
7fe7624f3000-7fe7624f4000 rw-p 00006000 08:01 6164054                    /usr/lib/qt/plugins/imageformats/libqmng.so
7fe7624f4000-7fe762501000 r-xp 00000000 08:01 6161449                    /usr/lib/qt/plugins/imageformats/libqjpeg.so
7fe762501000-7fe762700000 ---p 0000d000 08:01 6161449                    /usr/lib/qt/plugins/imageformats/libqjpeg.so
7fe762700000-7fe762701000 r--p 0000c000 08:01 6161449                    /usr/lib/qt/plugins/imageformats/libqjpeg.so
7fe762701000-7fe762702000 rw-p 0000d000 08:01 6161449                    /usr/lib/qt/plugins/imageformats/libqjpeg.so
7fe762702000-7fe76276b000 r-xp 00000000 08:01 5006813                    /usr/lib/libjpeg.so.8.1.2
7fe76276b000-7fe76296a000 ---p 00069000 08:01 5006813                    /usr/lib/libjpeg.so.8.1.2
7fe76296a000-7fe76296b000 r--p 00068000 08:01 5006813                    /usr/lib/libjpeg.so.8.1.2
7fe76296b000-7fe76296c000 rw-p 00069000 08:01 5006813                    /usr/lib/libjpeg.so.8.1.2
7fe76296c000-7fe7629b9000 r-xp 00000000 08:01 5007086                    /usr/lib/libjasper.so.1.0.0
7fe7629b9000-7fe762bb8000 ---p 0004d000 08:01 5007086                    /usr/lib/libjasper.so.1.0.0
7fe762bb8000-7fe762bb9000 r--p 0004c000 08:01 5007086                    /usr/lib/libjasper.so.1.0.0
7fe762bb9000-7fe762bbd000 rw-p 0004d000 08:01 5007086                    /usr/lib/libjasper.so.1.0.0
7fe762bbd000-7fe762bc4000 rw-p 00000000 00:00 0 
7fe762bc4000-7fe762bcc000 r-xp 00000000 08:01 6164056                    /usr/lib/qt/plugins/imageformats/libqjp2.so
7fe762bcc000-7fe762dcb000 ---p 00008000 08:01 6164056                    /usr/lib/qt/plugins/imageformats/libqjp2.so
7fe762dcb000-7fe762dcc000 r--p 00007000 08:01 6164056                    /usr/lib/qt/plugins/imageformats/libqjp2.so
7fe762dcc000-7fe762dcd000 rw-p 00008000 08:01 6164056                    /usr/lib/qt/plugins/imageformats/libqjp2.so
7fe762dcd000-7fe762dd3000 r-xp 00000000 08:01 6161451                    /usr/lib/qt/plugins/imageformats/libqico.so
7fe762dd3000-7fe762fd3000 ---p 00006000 08:01 6161451                    /usr/lib/qt/plugins/imageformats/libqico.so
7fe762fd3000-7fe762fd4000 r--p 00006000 08:01 6161451                    /usr/lib/qt/plugins/imageformats/libqico.so
7fe762fd4000-7fe762fd5000 rw-p 00007000 08:01 6161451                    /usr/lib/qt/plugins/imageformats/libqico.so
7fe762fd5000-7fe762fde000 r-xp 00000000 08:01 6164049                    /usr/lib/qt/plugins/imageformats/libqicns.so
7fe762fde000-7fe7631dd000 ---p 00009000 08:01 6164049                    /usr/lib/qt/plugins/imageformats/libqicns.so
7fe7631dd000-7fe7631de000 r--p 00008000 08:01 6164049                    /usr/lib/qt/plugins/imageformats/libqicns.so
7fe7631de000-7fe7631df000 rw-p 00009000 08:01 6164049                    /usr/lib/qt/plugins/imageformats/libqicns.so
7fe7631df000-7fe7631e5000 r-xp 00000000 08:01 6161450                    /usr/lib/qt/plugins/imageformats/libqgif.so
7fe7631e5000-7fe7633e5000 ---p 00006000 08:01 6161450                    /usr/lib/qt/plugins/imageformats/libqgif.so
7fe7633e5000-7fe7633e6000 r--p 00006000 08:01 6161450                    /usr/lib/qt/plugins/imageformats/libqgif.so
7fe7633e6000-7fe7633e7000 rw-p 00007000 08:01 6161450                    /usr/lib/qt/plugins/imageformats/libqgif.so
7fe7633e7000-7fe7633f2000 r-xp 00000000 08:01 6164052                    /usr/lib/qt/plugins/imageformats/libqdds.so
7fe7633f2000-7fe7635f1000 ---p 0000b000 08:01 6164052                    /usr/lib/qt/plugins/imageformats/libqdds.so
7fe7635f1000-7fe7635f2000 r--p 0000a000 08:01 6164052                    /usr/lib/qt/plugins/imageformats/libqdds.so
7fe7635f2000-7fe7635f3000 rw-p 0000b000 08:01 6164052                    /usr/lib/qt/plugins/imageformats/libqdds.so
7fe7635f3000-7fe7635fe000 r-xp 00000000 08:01 6161454                    /usr/lib/qt/plugins/platforminputcontexts/libcomposeplatforminputcontextplugin.so
7fe7635fe000-7fe7637fd000 ---p 0000b000 08:01 6161454                    /usr/lib/qt/plugins/platforminputcontexts/libcomposeplatforminputcontextplugin.so
7fe7637fd000-7fe7637fe000 r--p 0000a000 08:01 6161454                    /usr/lib/qt/plugins/platforminputcontexts/libcomposeplatforminputcontextplugin.so
7fe7637fe000-7fe7637ff000 rw-p 0000b000 08:01 6161454                    /usr/lib/qt/plugins/platforminputcontexts/libcomposeplatforminputcontextplugin.so
7fe7637ff000-7fe763800000 ---p 00000000 00:00 0 
7fe763800000-7fe764000000 rw-p 00000000 00:00 0 
7fe764000000-7fe764021000 rw-p 00000000 00:00 0 
7fe764021000-7fe768000000 ---p 00000000 00:00 0 
7fe768013000-7fe768014000 ---p 00000000 00:00 0 
7fe768014000-7fe768814000 rw-p 00000000 00:00 0 
7fe768814000-7fe76884b000 r-xp 00000000 08:01 5022538                    /usr/lib/gvfs/libgvfscommon.so
7fe76884b000-7fe768a4b000 ---p 00037000 08:01 5022538                    /usr/lib/gvfs/libgvfscommon.so
7fe768a4b000-7fe768a50000 r--p 00037000 08:01 5022538                    /usr/lib/gvfs/libgvfscommon.so
7fe768a50000-7fe768a51000 rw-p 0003c000 08:01 5022538                    /usr/lib/gvfs/libgvfscommon.so
7fe768a51000-7fe768a81000 r-xp 00000000 08:01 5254267                    /usr/lib/gio/modules/libgvfsdbus.so
7fe768a81000-7fe768c81000 ---p 00030000 08:01 5254267                    /usr/lib/gio/modules/libgvfsdbus.so
7fe768c81000-7fe768c82000 r--p 00030000 08:01 5254267                    /usr/lib/gio/modules/libgvfsdbus.so
7fe768c82000-7fe768c84000 rw-p 00031000 08:01 5254267                    /usr/lib/gio/modules/libgvfsdbus.so
7fe768c84000-7fe768c8a000 r-xp 00000000 08:01 5008545                    /usr/lib/libogg.so.0.8.2
7fe768c8a000-7fe768e89000 ---p 00006000 08:01 5008545                    /usr/lib/libogg.so.0.8.2
7fe768e89000-7fe768e8a000 r--p 00005000 08:01 5008545                    /usr/lib/libogg.so.0.8.2
7fe768e8a000-7fe768e8b000 rw-p 00006000 08:01 5008545                    /usr/lib/libogg.so.0.8.2
7fe768e8b000-7fe768eb6000 r-xp 00000000 08:01 5008551                    /usr/lib/libvorbis.so.0.4.8
7fe768eb6000-7fe7690b6000 ---p 0002b000 08:01 5008551                    /usr/lib/libvorbis.so.0.4.8
7fe7690b6000-7fe7690b7000 r--p 0002b000 08:01 5008551                    /usr/lib/libvorbis.so.0.4.8
7fe7690b7000-7fe7690b8000 rw-p 0002c000 08:01 5008551                    /usr/lib/libvorbis.so.0.4.8
7fe7690b8000-7fe7690c1000 r-xp 00000000 08:01 5002018                    /usr/lib/libltdl.so.7.3.1
7fe7690c1000-7fe7692c0000 ---p 00009000 08:01 5002018                    /usr/lib/libltdl.so.7.3.1Aborted (core dumped)
`
وقتی خروجی نوع اول در ترمینال دارم داخل فایل 
persepolis_error
این ارور را دارم
`QWidget::repaint: Recursive repaint detected`
گاهی هم داخل فایل بالا هیچ اروری نوشته نمیشه
این مشکل فعلا فقط با همین یک سایت دارم

**Comment by alireza-amirsamimi** [comment]
به عنوان باگ تاییدش کردم
روش کار میکنم ببینم مشکل از مجاست و اطلاع میدم :)

**Comment by alireza-amirsamimi** [comment]
تنظیمات فلش گات رو با تغییراتی که روی گیت هاب گذاشتم تغییر بده
ببین مشکل دانلود اون سایت حل میشه یا نه

**Comment by Mr-undead** [comment]
به اخرین نسخه اپدیت کردم مشکل 
pause و resume 
برای این سایت به خصوص برای من حل شده

**Comment by alireza-amirsamimi** [comment]
ممنونم از اینکه خبر دادی
