### ISSUE TITLE
ایکون نوتیفیکیشن در جای درستی قرار ندارد

### ISSUE THREAD

**Issue by mohammadreza-keihani** [persepolisdm/persepolis#50]
Ubuntu 14.04 with Unity
Persepolis 2.1.1

Screenshot : 

![screenshot 2016-09-14 05 36 00](https://cloud.githubusercontent.com/assets/20636039/18501098/89cc4722-7a3d-11e6-8c92-f5fd66a629d1.png)

همانطور که می بینید آیکون در گوشه بالای چپ قرار دارد.

**Comment by alireza-amirsamimi** [comment]
سلام
مشکل مربوط به برنامه نیست
مشکل مربوط به میزکار یونیتی در توزیع اوبونتو ۱۴.۰۴ هست
این مشکل رو میزکار یونیتی در اوبونتو ۱۶.۰۴ حل کرده

**Comment by mohammadreza-keihani** [comment]
با تشکر از توجه تون
