### ISSUE TITLE
setting active download

### ISSUE THREAD

**Issue by torikulhabib** [persepolisdm/persepolis#503]
i hope there is option for active download.
so as not to download simultaneously.
like Uget.
![screenshot from 2018-04-20 17 22 38](https://user-images.githubusercontent.com/26135527/39046167-74e1373e-44bf-11e8-8b8b-8d011add4649.png)

**Comment by alireza-amirsamimi** [comment]
Hello
You can create a [queue for your downloads](https://github.com/persepolisdm/persepolis/wiki/How-to-create-queue) and persepolis can download them one by one :)
