### ISSUE TITLE
کیفیت بد ایکن ها

### ISSUE THREAD

**Issue by 1000001hnew** [persepolisdm/persepolis#505]
خسته نباشین
چرا ایکن ها اینقد کیفیت بدی دارن؟
توی یه سری نرم افزار دیگه هم هست مشکل از نرم افزاره یا از سیستم عامل
این تصویرش

http://s9.picofile.com/file/8324331318/DeepinScreenshot_select_area_20180422151415.png

**Comment by alireza-amirsamimi** [comment]
Hello
Please always use english language here.
What is your operating system and desktop and ... . Please tell us more information.
