### ISSUE TITLE
Verify and correct sha256 for homebrew-cask

### ISSUE THREAD

**Issue by alexozwald** [persepolisdm/persepolis#506]
**System Details:**
* Operating System: **macOS**
* Persepolis Version: **3.1.0**
* Installed via **homebrew-cask**

I created the pull request [here](https://github.com/caskroom/homebrew-cask/pull/46214) to fix this issue. It was originally referenced [here](https://github.com/caskroom/homebrew-cask/pull/45519) 

Could you confirm that the correct sha256 is in fact `70be7692e4b7a5f596a570dbcd4b9c5c077ab5481986952fa59c3dc228bc9bb5`  and the appcast checkpoint is `01a30c4eee0e904766abbf5b9f06206f58ace305f3321e8c503baafaa1f60c66`?

```
$ brew cask _appcast_checkpoint --calculate https://github.com/persepolisdm/persepolis/releases.atom
01a30c4eee0e904766abbf5b9f06206f58ace305f3321e8c503baafaa1f60c66
```
[VirusTotal link](https://www.virustotal.com/#/url/ebd6150c2b6676d4b66a586cb98666c8d1f66a493ac6056a9c512f2ac78d9f0f/details)

**Comment by alireza-amirsamimi** [comment]
Hello
The correct package is uploaded [here](https://github.com/persepolisdm/persepolis/releases/tag/3.1.0). This package is new. We uploaded this two weeks ago. Our first package had some problems so we fixed problems and upload it again.

**Comment by vitorgalvao** [comment]
Thank you. We [accepted the confirmation and merged the update](https://github.com/caskroom/homebrew-cask/pull/46214#issuecomment-383603887). Feel free to close the issue.
