### ISSUE TITLE
Windows taskbar progress indicator

### ISSUE THREAD

**Issue by gaberad** [persepolisdm/persepolis#509]
Would it be possible to implement Windows taskbar progress indicator to the download progress window?

https://msdn.microsoft.com/en-us/library/system.windows.shell.taskbariteminfo.progressstate(v=vs.110).aspx

Not sure if it's possible in python, but I found these that might be a start:
https://stackoverflow.com/questions/1736394/using-windows-7-taskbar-features-in-pyqt
https://stackoverflow.com/questions/17607415/python-tkinter-windows-7-taskbar-progress

**Comment by alireza-amirsamimi** [comment]
Thanks for your feature requst :) . I think It's possible.
