### ISSUE TITLE
Language set to Chinese, UI showing wrong

### ISSUE THREAD

**Issue by UnaHe** [persepolisdm/persepolis#513]
* Operating System: windows 10 1709
* Persepolis Version: 3.1.0
* How do you install Persepolis: github

RT.
![qq 20180504135324](https://user-images.githubusercontent.com/30680842/39614553-5ce7f1ce-4fa3-11e8-9080-df6ef0148489.jpg)

**Comment by alireza-amirsamimi** [comment]
Hello
Thanks for reporting. This issue was reported before. Please read the answer [here](https://github.com/persepolisdm/persepolis/issues/488)
