### ISSUE TITLE
Program error, software cannot open

### ISSUE THREAD

**Issue by liujvnes** [persepolisdm/persepolis#515]
persepolis_3_1_0_windows_64bit

Windows 10 1803

![snipaste_2018-05-04_22-09-04](https://user-images.githubusercontent.com/25132014/39661903-4a7cf87e-508c-11e8-82b7-f742fef8df71.png)

**Comment by mostafaasadi** [comment]
Hi 
make sure you have last persepolis bundle, it is 3.1.0
according to our conversation on #362 if you have NonAscii character on your PATH or username cause this problem.
