### ISSUE TITLE
خطای 0 پس از آپگرید

### ISSUE THREAD

**Issue by LinArcX** [persepolisdm/persepolis#52]
علی جان من هر سری خواستم پرسپولیس رو آپگرید کنم در اولین اجرا پس از آپگرید هیچ موعه موفق نبودم و خطای 0 روو میگرفتم؛
 ❯ persepolis                                       [23:18:32]
0
چرا؟
دستوری هم که توانجمن گفتی زدم بعدش:
persepolis --clear
اما افاقه نکرد.

**Comment by alireza-amirsamimi** [comment]
سلام
وقتی ار ترمینال برنامه رو اجرا میکنی
متن فایل خطا چیه؟
اونو به من بده لطفا
توی این مسیر هست
/tmp/persepolis_error
برنامه رو از ترمینال اجرا کن و محتویات این فایل رو برام بذار ببینم قضیه از چه قراره

**Comment by LinArcX** [comment]
خدمت شما:
 saeed@saeed  /tmp 
 ❯ cat persepolis_error                                              [22:24:10]
Traceback (most recent call last):
  File "/usr/share/persepolis/persepolis-download-manager", line 8, in <module>
    from mainwindow import MainWindow
  File "/usr/share/persepolis/mainwindow.py", line 14, in <module>
    from progress import ProgressWindow
  File "/usr/share/persepolis/progress.py", line 10, in <module>
    import download
  File "/usr/share/persepolis/download.py", line 31, in <module>
    port = int(setting_dict['rpc-port'])
KeyError: 'rpc-port'

**Comment by alireza-amirsamimi** [comment]
به نظر میات مشکل هماهنگی با ورژن قبلی نیست
اصلا برنامه درست نصب نشده و فایل های اجرایی برنامه اشکال دارند
چه جوری نصب کردی؟با گیت یا
aur
از هر کدوم نصب کردی کامل از نصب خارج کن و دوباره نصب کن
مخازن
aur
هم به روز هستند و آخرین ورژن گیت رو نصب میکنند

**Comment by LinArcX** [comment]
از Aur دانلود کردم علی جان
من کار خاصی نکردم فقط دستور زیر رو زدم:
packer persepolis
بعد شروع کرد از گیت کلون کردن.
یادمه سری های قبل هم دقیقا همین مشکل ها رو داشتم موقع بروزرسانی.

**Comment by alireza-amirsamimi** [comment]
به نظر میات که کدها درست به سیستمت دانلود نشدند
کامل از نصب خارج کن و با
aur
نصب کن

**Comment by alireza-amirsamimi** [comment]
یا خودت دستی از گیت هاب نصب کن

**Comment by LinArcX** [comment]
یعنی میگین مشکل از 
aur-helper
 ای هست که دارم ازش استفاده میکنم؟

**Comment by alireza-amirsamimi** [comment]
آره فکر میکنم
حالا دستی از گیت هاب امتحان کن ببینیم نتیجه چیه :)

**Comment by LinArcX** [comment]
جل الخالق!!!
از 
yaourt
 استفاده کردم به جای
packer
و به راحتی نصب شد و اون خطا رو هم نداد.
