### ISSUE TITLE
 I like to be a project member.

### ISSUE THREAD

**Issue by iman-salmani** [persepolisdm/persepolis#525]
Hello
I use Persepolis a few times. I like to be a project member.
I am 17 years old and I am a Python programmer and I am familiar with html and css and javascript.
I'm familiar with the tkinter user interface libraries, pygobject, kivy, pyqt (I worked with each one).
I worked with the Django framework and created several test sites.
Like this: http://hemmat.co.vu/
If you want, I can create a dynamic site with a blog and ... (for example, I think I can create a theme builder for Persepolis) with a free hosting and domain.

**Comment by alireza-amirsamimi** [comment]
Hello
Persepolis is free software project and any one can contribute to this porject on github. We wrote contributing guide [here](https://github.com/persepolisdm/persepolis/wiki/Home-en#contributers-guide).

We use github for developing our website and we don't like to change github for many reasons. Many projects on github are using github for developing and making their websites(for example aria2 , etc).

You can see our website repo [here](https://github.com/persepolisdm/persepolisdm.github.io) and you can contribute if you like :)

Good luck
