### ISSUE TITLE
GUI broke when switched to non-en languages

### ISSUE THREAD

**Issue by GamingInJail** [persepolisdm/persepolis#526]
**System Details:**
* Operating System: Windows 10 Home 1803 (x64)
* Persepolis Version: 3.1.0
* How do you install Persepolis? (Repositories, source, ...)
from persepolis releases on github

* _Please attach log files if crash or paste error message_
![image](https://user-images.githubusercontent.com/31848822/40276453-282b7216-5c3d-11e8-9be6-52d172dd3f18.png)
![image](https://user-images.githubusercontent.com/31848822/40276466-805ee6b6-5c3d-11e8-90b3-227f6a38b5c9.png)

**Issue Description and steps to reproduce:**
As the picture shows, as long as I switch the language to any non-en ones(Chinese for example in my pic), the GUI will just broke. Icons are missing, strings are squeezed and so on. If I turn it back to English, everything will be normal again. The problem only exists for other languages. 
Is this a bug or is there something with my computer? Maybe fonts or I don't know......themes?

**Comment by alireza-amirsamimi** [comment]
Hello
Thanks for reporting :)
This bug is repoterted before in [this issue](https://github.com/persepolisdm/persepolis/issues/488). Please read the answer [here](https://github.com/persepolisdm/persepolis/issues/488).
