### ISSUE TITLE
got error messsage while updating

### ISSUE THREAD

**Issue by dddeveloperrr** [persepolisdm/persepolis#528]
**System Details:**
* Operating System:  windows 10
* Persepolis Version: 3.0.1

Hi
I got this error message  when I wanted to check whether newer version of PDM was available or not. 

"an error occurred while checking update"
 
I have no idea why this happens. I think it would be much helpful if more detail is provided to the user in the error message

regards

![axx](https://user-images.githubusercontent.com/11577640/40349490-02f8df08-5dbc-11e8-9e62-c9ea21d97acc.png)

**Comment by mostafaasadi** [comment]
Hi
please check you have access to https://persepolisdm.github.io/version without any vpn, proxy ,..
