### ISSUE TITLE
‫ تمام کردن دانلود با خروجی html (اشتباه از من بود و برنامه مشکلی نداره)

### ISSUE THREAD

**Issue by msajadi832** [persepolisdm/persepolis#53]
سلام

‫وقتی هر فایلی از فایل های این صفحه رو دانلود می کنم، سریع پایان دانلود رو اعلام می کنه. ولی یک فایل html رو دانلود کرده که توی اون mediafire می گه لینک اشتباهه!
[https://www.mediafire.com/folder/5flh5dwmo85h2/xcode](https://www.mediafire.com/folder/5flh5dwmo85h2/xcode)
‫ولی من همون فایل ها رو با DownThemAll بدون مشکل دانلود می کنم!

‫لاگی هم ثبت نمیشه!

ممنون از زحماتتون و خدا قوت

**Comment by alireza-amirsamimi** [comment]
![screenshot_2016-10-06_23-27-11](https://cloud.githubusercontent.com/assets/7452500/19168336/8e674c64-8c1c-11e6-9a0f-ad5f2ae7344a.png)

برای من بدون مشکل دانلود میشه
روی لینک کلیک کنه تا لینک در صفحه جدید باز بشه
بعد روی دکمه دانلود خیلی معمولی راست کلیک کنید تا با فلش گات باز بشه و بعد با دانلود منجر دانلودش کنید:)

**Comment by msajadi832** [comment]
‫فهمیدم مشکل چیه!
‫شیلتر شکن روی کل سیستم فعال بوده و من متوجه نشده بودم.
‫اشتباه از من بود. 

‫چنین مشکلی اصلا وجود نداره و الان به بهترین وجه ممکن دارم دانلود می کنم. 

ممنون فراوون

**Comment by alireza-amirsamimi** [comment]
پس خدا رو شکر حل شد 
مشکلی بود در خدمتم :)
:+1:
