### ISSUE TITLE
don't close, just minimize tray

### ISSUE THREAD

**Issue by MohammadMokhalled** [persepolisdm/persepolis#530]
when click on x icon of program, it close completely (in Manjaro KDE). I think it's better to have its icon in the "system tray" after close the program and can access to it quickly.

**Comment by alireza-amirsamimi** [comment]
I'm agree with you. You can also use "minimize to tray icon" button in toolbar.
![screenshot_20180820_151058](https://user-images.githubusercontent.com/7452500/44336093-8eeb6100-a48b-11e8-810d-60d19a20c866.png)

**Comment by alireza-amirsamimi** [comment]
I add this feature :)
So users can minimize Persepolis to the system tray with close(x) button.
Thanks for your feature request :+1:
