### ISSUE TITLE
how to increase multi connection like xdm download manager

### ISSUE THREAD

**Issue by shahryarjb** [persepolisdm/persepolis#533]
Hi , I checked persepolis setting and found multi connection which was 16, I was trying to increase it , but I think it can't  be more than 16, but I use Xdm with 32 and I can use all bandwidth of my internet , for example the link concerned in XDM 1.5mg/s in your download manager 600kb/s

how to do that ?

Im using mac os last update

**Comment by salahoued** [comment]
16 is the max, you can't go further because it's a limit imposed by aria2c, if you want more you have to change aria's source code and set -x to whatever you want, then compile it.
[#1039](https://github.com/aria2/aria2/issues/1039),
