### ISSUE TITLE
is there any way to run persepolis as root ? Im using kali linux

### ISSUE THREAD

**Issue by amirmortezaie** [persepolisdm/persepolis#538]
**System Details:**
* Operating System: ?
* Distro(For GNU/Linux and BSD users): ?
* Desktop Environment(For GNU/Linux and BSD users): ?
* Persepolis Version: ?
* How do you install Persepolis? (Repositories, source, ...)

* _Please attach log files if crash or paste error message_

**Issue Description and steps to reproduce:**

**Comment by alireza-amirsamimi** [comment]
Hello
Sorry no!
Persepolis in not suitable for running as root :)

**Comment by JafarAkhondali** [comment]
@amirmortezaie  I'll just add your response in email here so it might help others:

> Running PDM and Browser using below command helped running programs since -H will use user directory

`sudo -u lc -H `
