### ISSUE TITLE
I can't start too !!!!!

### ISSUE THREAD

**Issue by Noah1995** [persepolisdm/persepolis#539]
* Operating System: 【win10  64】 
* Persepolis Version: 【3.1.0】
* How do you install Persepolis? 【exe】

* _Please attach log files if crash or paste error message_

![](https://i.loli.net/2018/06/25/5b31101042e2a.gif)

**Comment by mostafaasadi** [comment]
Hi
make sure you have last persepolis bundle
according to our conversation on #362 if you have NonAscii character on your PATH or username cause this problem.
latest pyinstaller(builder of persepolis on windows) has this problem with pyqt5 apps and NonAscii characters, so for latest build we have this problem(you can change username), I will test new pyinstaller on next version

**Comment by Noah1995** [comment]
I re-install  just now....
it's ok....can start....
Why  re-install invalided for last time ?
![snipaste20180824_133601](https://user-images.githubusercontent.com/25548230/44566950-d0894e00-a7a2-11e8-8a49-e82ba7a61153.jpg)

**Comment by JafarAkhondali** [comment]
@990721830 I don't know either, but will have to close the issue to arrange the issues :+1:
