### ISSUE TITLE
‫نمایش داده نشدن menu ها بعد از یک بار Minimize to system tray

### ISSUE THREAD

**Issue by msajadi832** [persepolisdm/persepolis#54]
سلام

‫وقتی یکبار گزینه Minimize to system tray رو می زنم و بعد گزینه Show Main window رو میزنم، منو های برنامه دیگه نمایش داده نمیشه. 
‫میزکار من Unity است و احتمالا این مشکل فقط برای این میزکار باشه

‫در ضمن اگر ممکنه برای گزینه Minimize to system tray یک دکمه در نوار ابزار برنامه بزارید. در منو ها یکم دور از دسترس هست

ممنون

**Comment by alireza-amirsamimi** [comment]
متاسفانه این مشکل فقط در میزکار یونیتی وجود داره و احتمالا برمیگرده به پچ ها و تغییرات کنونیکال روی کیوت
روش کار میکنم ببینم  میشه چه کارش کرد :)

برای مینیمایز کردن از 
ctrl+w
استفاده کنید :)
راه خوبیه

**Comment by msajadi832** [comment]
ممنون. 

‫ولی Ctrl+W هم برام کار نمی کنه!

**Comment by alireza-amirsamimi** [comment]
بررسی میکنم ببینم توی یونیتی چه جوری هست قضیه
ممنون از اینکه اطلاع دادی :)

**Comment by alireza-amirsamimi** [comment]
مشکل نشان ندادن منو رو یه راه حل براش پیدا کردم و گذاشتم روی گیت هاب
البته راه حل صد درصد نیست 
ولی خب حداقل منو رو نشون میده ولی نه در حالت گلوبال :)
روی حل مشکل کلی کار میکنم :)

**Comment by msajadi832** [comment]
‫ بهتر شد. ممنون
