### ISSUE TITLE
please add the install PATH choose function

### ISSUE THREAD

**Issue by SekiBetu** [persepolisdm/persepolis#540]
i m a chinese user, my win10 username is not ascii character so i cant run it

---------------------------
Persepolis Download Manager
---------------------------
This application failed to start because it could not find or load the Qt platform plugin "windows"
in "".

Reinstalling the application may fix this problem.
---------------------------
确定   
---------------------------

**Comment by mostafaasadi** [comment]
Hi
make sure you have last persepolis bundle
according to our conversation on #362 if you have NonAscii character on your PATH or username cause this problem.
latest pyinstaller(builder of persepolis on windows) has this problem with pyqt5 apps and NonAscii characters, so for latest build we have this problem(you can change username), I will test new pyinstaller on next version
