### ISSUE TITLE
Crash on new download

### ISSUE THREAD

**Issue by smaragdus** [persepolisdm/persepolis#542]
**System Details:**
* Operating System: ?
Windows 8 x64
* Persepolis Version: ?
3.1.0

**Issue Description and steps to reproduce:**
Crash after starting new download;

Persepolis Download Manager  crashed after I added and started new download, screen:

![persepolis download manager 3 1 0 - 2018-07-10 - error - 001](https://user-images.githubusercontent.com/9025757/42479614-69b4c8d2-83e2-11e8-81f7-046047566ed2.png)

Error message:

```
Traceback (most recent call last):
  File "persepolis\scripts\persepolis.py", line 430, in main
  File "persepolis\scripts\mainwindow.py", line 929, in __init__
KeyError: '8168243f134d1535'
```

_Reset Persepolis_ option helped (so far).

Also, after updating from [version 2.4.2](https://github.com/persepolisdm/persepolis/releases/tag/2.4.2) to [version 3.1.0](https://github.com/persepolisdm/persepolis/releases/tag/3.1.0) all previous downloads were duplicated.

**Comment by alireza-amirsamimi** [comment]
Hello
Resetting Persepolis may fix the problem
