### ISSUE TITLE
Arabic translation request

### ISSUE THREAD

**Issue by MajdiSobain** [persepolisdm/persepolis#543]
I requested to start Arabic translation at transifex.

Could you please accept that?

Thanks

**Comment by hayyan71** [comment]
@MajdiSobain Hi, sorry for late response, I was on vacation.

I'll accept all remaining language requests tonight.

Regards

**Comment by hayyan71** [comment]
@MajdiSobain I've added requested languages to Transifex.

Again, Sorry for late response

Regards.

**Comment by MajdiSobain** [comment]
@hayyan71 Thanks for let me know.

I willl try to translate whenever I have free time :)

Greetings

**Comment by MajdiSobain** [comment]
Hello All

I just wanna tell you that I have finished Arabic Translation on the Transifex.

Could you please accept it?

Greetings

**Comment by hayyan71** [comment]
@MajdiSobain Hi

Thanks for you contribution in Persepolis project.

We'll add all finished languages in the next version.

Regards

**Comment by MajdiSobain** [comment]
@hayyan71 Hi

Great to know that

have a nice time

Greetings
