### ISSUE TITLE
crash after adding youtube video

### ISSUE THREAD

**Issue by ghost** [persepolisdm/persepolis#545]
**System Details:**
* Operating System: Linux
* Distro(For GNU/Linux and BSD users): Arch
* Desktop Environment(For GNU/Linux and BSD users): GNOME
* Persepolis Version: 3.1.0
* How do you install Persepolis? (Repositories, source, ...)
AUR `persepolis-git`
* _Please attach log files if crash or paste error message_
```bash
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/persepolis/scripts/video_finder_addlink.py", line 387, in run
    self.FOUND.emit({'thread_key': self.key, 'file_size': spider(self.dictionary)[1]})
  File "/usr/lib/python3.6/site-packages/persepolis/scripts/spider.py", line 106, in spider
    return filename, file_size
UnboundLocalError: local variable 'file_size' referenced before assignment
Aborted (core dumped)
```
**Issue Description and steps to reproduce:**
Every time I add a YouTube link, after choosing download option and starting download, persepolis suddenly crash and main window closes.

**Comment by alireza-amirsamimi** [comment]
The bug is [fixed](https://github.com/persepolisdm/persepolis/commit/3176ffd0fd4467e4661ca1da105cc9225c08ca7d).
Thanks for reporting :+1:
