### ISSUE TITLE
When detecting the system proxy in linux it gets it wrong

### ISSUE THREAD

**Issue by slackhead** [persepolisdm/persepolis#548]
Slackware 14,2
persepolis 3.1.0 installed from source
fluxbox WM
http_proxy variable is set in shell to 127.0.0.1:8118

When I first added a download and clicked detect system proxy it detected IP as 8118 and port was empty.

Also please please please please add a way of setting default proxy in preferences :)

**Comment by mostafaasadi** [comment]
Hi 
I going to check proxy on your desktop and patch it as soon as i can, if you can check
 https://github.com/persepolisdm/persepolis/blob/30b55e02f5fee50883b805ba92559f5e1f3b2753/persepolis/scripts/check_proxy.py#L113 and show me https://github.com/persepolisdm/persepolis/blob/30b55e02f5fee50883b805ba92559f5e1f3b2753/persepolis/scripts/check_proxy.py#L114 output 

for your second suggestion we will try it

**Comment by slackhead** [comment]
I can see a bit of a problem with authing. I now use a username:password for my proxy. If I try:

http_proxy=http://user:password@192.168.1.2:35000 https_proxy=$http_proxy python3
```
>>> from urllib import request
>>> print(request.getproxies())
{'http': 'http://user:password@192.168.1.2:35000', 'https': 
 'http://user:password@192.168.1.2:35000'}
>>> proxy = {}
>>> proxysource = request.getproxies()
>>> proxy['http_proxy_ip'] = proxysource['http'].split(':')[1].replace('//','')
>>> print(proxy['http_proxy_ip'])
user
```

However, if I run the above with persepolis, for some reason it disregards $http_proxy and comes up with 192.168.1.2:30100 which must be an old one that I used somewhere. It must be cached somwhere but I couldn't find it. I deleted the config dir in ~/.config and checked in ~/.cache too.

I think my first problem was because I just used ip:port without http:// protocol at the start then. I didn't see any rules on this, but urllib still sees it as a proxy without the http://

http_proxy=user:password@192.168.1.2:35000 https_proxy=$http_proxy python3

```
>>> from urllib import request
>>> print (request.getproxies())
{'http': 'user:password@192.168.1.2:35000', 'https': 'user:password@192.168.1.2:35000'}
```

**Comment by mostafaasadi** [comment]
thank you @slackhead :rose: 
I will add some feature to prevent this

**Comment by slackhead** [comment]
Any idea offhand where that 192.168.1.2:30100 is coming from when I click the 'detect system proxy' button? urllib doesn't see it and running persepolis from the same terminal for testing.

**Comment by mostafaasadi** [comment]
I should check on your desktop
persepolis use urllib and some other method to find proxy on several desktops, you can see
https://github.com/persepolisdm/persepolis/blob/30b55e02f5fee50883b805ba92559f5e1f3b2753/persepolis/scripts/check_proxy.py#L26

**Comment by slackhead** [comment]
I'm using fluxbox and testing gives os_type, desktop_env = Linux, None.

Does persepolis use any other dirs than ~/.config/persepolis_download_manager and ~/.persepolis because I deleted those but that setting keeps appearing.

Edit* Scratch that. I'm an idiot. I forgot that I made a script that sets the proxy and then calls persepolis.
