### ISSUE TITLE
خطای ۰ 

### ISSUE THREAD

**Issue by farbodrashidi** [persepolisdm/persepolis#55]
سلام،
دوباره پرسپولیس رو نصب کردم و همچنان همون خطای ۰ رو میگیرم. برای بار اوله نصبش میکنم و پکیجهای مورد نیاز نصب شده هستن.

فایل گزارش این رو میگه:
`Traceback (most recent call last):
  File "/usr/share/persepolis/persepolis-download-manager", line 20, in <module>
    from mainwindow import MainWindow
  File "/usr/share/persepolis/mainwindow.py", line 17, in <module>
    from PyQt5 import QtCore, QtGui, QtWidgets  
ImportError: /usr/lib/libQt5Core.so.5: version Qt_5.7 not found (required by /usr/lib/python3.5/site-packages/PyQt5/QtCore.so)`‍‍

فکر کنم نیاز به کیو تی ۵.۷ داره ؟

**Comment by alireza-amirsamimi** [comment]
روی کی دی ای و آرچ الان یکی از دوستان چک کرد و مشکلی نداشت
به نظرت میات مشکل از مانجارو هست
پیش نیازها و مخصوصا پایکیوت رو چه جوری نصب کردی؟

**Comment by farbodrashidi** [comment]
ersepolis-git dependencies:
- aria2 (already installed)
- vorbis-tools (already installed)
- libnotify (already installed)
- python (already installed)
- python-pyqt5 (already installed)
- qt5-svg (already installed)
- git (already installed) [makedepend]

فکر کنم از قبل نصب شده بود روی مانجارو

**Comment by alireza-amirsamimi** [comment]
پایکیوت نصب شده :)
python-pyqt5 (already installed)

مشکل ظاهرا مربوط به توزیع مانجارو هست . این پیغام خطا رو سرچ کردم و دیدم یه سری برنامه هایی که با پایکیوت ۵ نوشته شدند توی مانجارو این خطا رو دارن میدن
ببین میتونی این بسته رو از نصب خارج کنیو دوباره نصب کنی؟

**Comment by farbodrashidi** [comment]
دوباره نصب کردم 
دوباره همون شرایطه

**Comment by alireza-amirsamimi** [comment]
بازهم سرچ کردم مشکل از کیوت در مخازن مانجارو هست
امشب مانجارو رو با میزکار 
KDE
دانلود میکنم و در ماشین مجازی نصب میکنم ببینم میشه چه جوری این مشکل رو حل کرد و به تیم توسعه دهنده مانجارو هم اطلاع میدم که مشکل رو بررسی کنند

**Comment by alireza-amirsamimi** [comment]
سلام
امروز مانجارو رو با 
kde 
نصب کردم ولی آپدیتش نکردم
و پرسپولیس رو از گیت نصب کردم . بدون مشکل کار میکنه.اسکرین شات رو ببینید
![manjaro](https://cloud.githubusercontent.com/assets/7452500/19230145/c1ada9b8-8edf-11e6-9ea0-c421b07cf5f7.jpg)

**Comment by Mr-undead** [comment]
من دقیقا این مشکل را روی مانجارو 
Xfce
دارم

**Comment by alireza-amirsamimi** [comment]
من مانجارو رو توی ماشین مجازی تست کردم و پرسپولیس اجرا میشد
البته گذاشتم سیستم عامل آپدیت بشه و ۹۰۰ مگ دانلود کرد و بعد از ریبوت دیگه کلا سیستم عامل بالا نیومد
هر کاریش هم کردم سیستم عامل درست نشد که بتونم پرسپولیس رو اجرا کنم ببینم مشکلش چیه
وقت هم نشد بیشتر باهاش سر و کله بزنم
سیستم عامل ناپایداری بود برای من . ظاهرا بسته کیوت مخازن مانجارو در آپدیت جدیدشون دچار مشکل هست

**Comment by Mr-undead** [comment]
اتفاقا من هنوز آپدیت نکردم حدود 800 مگ آپدیت داره احتمالا امشب آپدیت میکنم دوباره تست میکنم

**Comment by Mr-undead** [comment]
سلام 
خوب من مانجارو را آپدیت کردم. بعد از آپدیت مشکل اجرا نشدن برنامه حل شد.

**Comment by alireza-amirsamimi** [comment]
ممنونم
پس من مشکل رو میبندم
