### ISSUE TITLE
All information is star 

### ISSUE THREAD

**Issue by vtk06** [persepolisdm/persepolis#553]
**System Details:**
* Operating System: win 10 64
* Persepolis Version: 3.1.0
* How do you install Persepolis?exe

* _Please attach log files if crash or paste error message_

**Issue Description and steps to reproduce:**
![image](https://user-images.githubusercontent.com/41992017/43514275-70ca4606-95b2-11e8-8cc4-ff3853cb6112.png)
all of my DLs go like this , i rebooted my pc , reinstalled PDM and it's not working . This is the first time i use this program . i dont know if i missed anything , plz help me,

**Comment by mostafaasadi** [comment]
Hi 
please send log details from menu > Help > show log file
