### ISSUE TITLE
Can't Change the style(theme) in persepolis.

### ISSUE THREAD

**Issue by avi3333** [persepolisdm/persepolis#554]
**System Details:**
* Operating System: Linux
* Distro(For GNU/Linux and BSD users): Linux mint 19
* Desktop Environment(For GNU/Linux and BSD users): Cinnamon
* Persepolis Version: 3.1.0.0
* How do you install Persepolis? Repositories, Synaptic package manager

**Issue Description and steps to reproduce:**
I installed persepolis in my new linux mint, Changed the style(theme) to bb10dark from edit>preference>style and it broke the whole package.  :( 
Now I can't change the theme anymore. Even when I removed the app and reinstalled it the theme did not change. I tried so many things but couldn't get it right. Because of the theme I can't see anything when I open the app.
Please help me.

**Comment by alireza-amirsamimi** [comment]
Hello
Please run this code from terminal.
```
persepolis --default
```

**Comment by avi3333** [comment]
@alireza-amirsamimi  Solved!!! Thanks a lot...
