### ISSUE TITLE
Can't Run Persepolis on Ubuntu -> Qt XCB error

### ISSUE THREAD

**Issue by nikgolkar** [persepolisdm/persepolis#555]
**System Details:**
* Operating System: Linux
* Distro(For GNU/Linux and BSD users): Ubuntu 18.04
* Desktop Environment(For GNU/Linux and BSD users): Gnome
* Persepolis Version: Last Version From Repository
* How do you install Persepolis? (Repositories, source, ...)
     Repositories
* _Please attach log files if crash or paste error message_
Error Message
> This application failed to start because it could not find or load the Qt platform plugin "xcb"
in "".

>Available platform plugins are: eglfs, linuxfb, minimal, minimalegl, offscreen, vnc, xcb.

>Reinstalling the application may fix this problem.
Aborted (core dumped)

**Issue Description and steps to reproduce:**
i added 
export LD_LIBRARY_PATH=/usr/local/lib:~/Qt5.11.0/5.11.0/gcc_64/lib/ 
export QT_QPA_PLATFORM_PLUGIN_PATH=~/Qt5.11.0/5.11.0/gcc_64/plugins/

in /etc/environment . 
persepolis run just from terminal and can't run from Desktop Menu.

i post this issue in ->>https://stackoverflow.com/questions/51751582/qt-app-cant-run-in-ubuntu-18-04-with-xcb-not-found-error/51761399#51761399

**Comment by mostafaasadi** [comment]
It seems you have forced qt on old version or some change on it. 
please give me more detail and log and error
