### ISSUE TITLE
error in installation on manjaro GNOME

### ISSUE THREAD

**Issue by farzamkhan** [persepolisdm/persepolis#557]
**System Details:**
* Operating System: ? manjaro
* Distro(For GNU/Linux and BSD users): ?
* Desktop Environment(For GNU/Linux and BSD users): ? GNOME
* Persepolis Version: ?
* How do you install Persepolis? (Repositories, source, ...) yaourt -S persepolis

`==> Downloading persepolis PKGBUILD from AUR...
x .SRCINFO
x PKGBUILD
morealaz commented on 2017-01-23 05:32			 
@shen, I check checksum and it was correct, but I change checksum to sha256 and update the package.

Razor254 commented on 2018-01-17 15:31			 

alireza6677 commented on 2018-02-16 05:04			 

unixfox commented on 2018-03-31 10:09			 

morealaz commented on 2018-03-31 13:03			 

persepolis 3.1.0-3  (2018-08-07 13:05)
( Unsupported package: Potentially dangerous ! )
==> Edit PKGBUILD ? [Y/n] ("A" to abort)
==> ------------------------------------
==> 

==> persepolis dependencies:
 - aria2 (already installed)
 - libnotify (already installed)
 - libpulse (already installed)
 - python (already installed)
 - python-psutil (already installed)
 - python-pyqt5 (already installed)
 - python-requests (already installed)
 - python-setproctitle (already installed)
 - qt5-svg (already installed)
 - sound-theme-freedesktop (already installed)
 - youtube-dl (already installed)
 - python-setuptools (already installed) [makedepend]

==> Continue building persepolis ? [Y/n]
==> ------------------------------------
==> 

==> Building and installing package
==> ERROR: Cannot find the strip binary required for object file stripping.
==> ERROR: Makepkg was unable to build persepolis.
==> Restart building persepolis ? [y/N]
==> -----------------------------------`

**Comment by ghost** [comment]
you need to install `binutils` or better than that install entire `base-devel` group.

**Comment by farzamkhan** [comment]
tanks
