### ISSUE TITLE
cannot install persepolis on linux mint 19.

### ISSUE THREAD

**Issue by shokri-navid** [persepolisdm/persepolis#558]
**System Details:**
* Operating System? Linux mint 19
* Distro(For GNU/Linux and BSD users)? Ubuntu
* Desktop Environment(For GNU/Linux and BSD users)? cinnamon
* Persepolis Version: ? last version
* How do you install Persepolis? (Repositories, source, ...)
repository

I cannot install persepolis on Linux mint 19 with Cinnamon desktop environment. when I try to set new repository with this command:

`sudo add-apt-repository ppa:persepolis/ppa`
I am getting this error.

> Remote end closed connection without response
Cannot add PPA: ''This PPA does not support bionic''.

**Comment by A-Charvin** [comment]
Seems to have been cleared at this point, I got it installed in Mint 19 without any issues.

**Comment by mostafaasadi** [comment]
Hi
thank you for your reporting :rose: 
I added cosmic and disco repo
