### ISSUE TITLE
اضافه شدن افزونه کروم

### ISSUE THREAD

**Issue by LinArcX** [persepolisdm/persepolis#56]
علی جان اگه امکانش هست میخواستم ازت درخواست کنم افزونه کروم و کرومیومش هم ارایه بدی.
ماهایی که داریم از این مرورگرها استفاده میکنیم حیفه نتونیم از برنامه ت به خوبی استفاده کنیم.
ممنونم ازت پیشاپیش

**Comment by alireza-amirsamimi** [comment]
حتما انشالله
کسی رو سراغ داری که جاوا اسکریپت کار خوبی باشه و دوست داشته باشه با پرسپولیس همکاری کنه

**Comment by LinArcX** [comment]
هستن ولی متاسفانه علاقه ای به دنیای متن باز ندارن.
خودم یه چیزایی بلدم از جاوا اسکریپت.البته نمیدونم از کجا باید شروع کنم  واسه نوشتن اکشتنشن
علاقه هم دارم همکاری کنم.
:)

**Comment by alireza-amirsamimi** [comment]
عالی!
تلگرام داری به من پیغام خصوصی بدی برات توضیح بدم ؟
توی گروه آرچ میتونی پیدام کنی

**Comment by LinArcX** [comment]
نه متاسفانه ندارم.
البته یه سری مجموعه ویدیویی عالی از یوتیوب گیر آوردم که ریز به ریز داره توضیح میده همه چیو.
فک کنم بتونم اولین اکتنشنمو بنویسم:(
جایی گیر کردم بهت پیغام میدم یا میل میزنم بهتون علی جان

**Comment by alireza-amirsamimi** [comment]
اینجا یه افزونه آریا۲ برای کروم رو فورک کردیم
https://github.com/persepolisdm/chrome-aria2-integration
این افزونه با 
rpc
اطلاعات دانلود رو میفرسته برای آریا
کاری که باید انجام بشه اینه به جای اینکه با آر پی سی کد رو بفرسته برای آریا به وسیله
shell
بفرسته برای پرسپولیس
تنظیماتش هم حذف بشه و همیشه بفرسته
persepolis --help
رو ببین
باید از سوییچ ها استفاده کنی

**Comment by alireza-amirsamimi** [comment]
سلام
افزونه کروم به پیشنهاد شما و بقیه دوستان به برنامه اضافه شد
آپدیت کنید و راهنمای فعال سازی اون رو از سایت برنامه مطالعه کنید
