### ISSUE TITLE
Installation using "homebrew cask"

### ISSUE THREAD

**Issue by mahdavipanah** [persepolisdm/persepolis#560]
It would be nice and convenient for macOS users to be able to install perspolis using [_homebrew cask_](https://github.com/Homebrew/homebrew-cask):
`brew cask install perspolis`

More information about adding a cask can be found [here](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md).

**Comment by Maders** [comment]
@mahdavipanah thanks for your feedback, persepolis cask package is already available.
you can install it from homebew cask, the package name is`persepolis-download-manager`.

**Comment by binarykitchen** [comment]
should be documented somewhere
