### ISSUE TITLE
PDM not get filename correctly for this link

### ISSUE THREAD

**Issue by Retia-Adolf** [persepolisdm/persepolis#561]
**System Details:**
* Operating System: Windows 10 1803 (64-bit)

* Persepolis Version: 3.1.0 (64-bit)
* How do you install Persepolis? (Repositories, source, ...)
via Chocolatey

**Issue Description and steps to reproduce:**
Link with the issue: https://www.proxmox.com/en/downloads?task=callelement&format=raw&item_id=401&element=f85c494b-2b32-4109-b8c1-083cca2b7db6&method=download&args[0]=11db3e6d14b055ba02bcc73d57161630

A torrent file. Opened in Firefox and sent URL to PDM by its integration WebExtension.

Firefox Developer Edition 62.0b19 build-in downloads correctly:
![image](https://user-images.githubusercontent.com/34053927/44558559-ee0ed700-a712-11e8-9dd8-4595513ac62a.png)

PDM:
![image](https://user-images.githubusercontent.com/34053927/44558592-1d254880-a713-11e8-97a5-a60b5880c360.png)

**Comment by alireza-amirsamimi** [comment]
Persepolis can not download torrent :)
----------------------------------------------------------------
I suggest you to change the persepolis theme :) 
Visit this [link](https://github.com/persepolisdm/persepolis/wiki/How-to-change-Persepolis-theme)

**Comment by Retia-Adolf** [comment]
Yes, I know, but had just found it seems cannot get filename for this dynamic link correctly.

(P.S. I think this one isn't too bad for Windows, just if it's more 'modern' (e.g. like 7-zip's) it would be better :D
