### ISSUE TITLE
Text is massive in Ubuntu 18.04; Preferences are unable to be saved due to size of text.

### ISSUE THREAD

**Issue by TanukiKabuki** [persepolisdm/persepolis#562]
Not really sure what else to say about this, but the ui is massive. I have a w540 with a 3K display and it's usable but simply impossible to get all the information on the screen because of the size of the text.
**System Details:**
* Operating System: Linux
* Distro(For GNU/Linux and BSD users): Ubuntu 18.04 LTS
* Desktop Environment(For GNU/Linux and BSD users): Gnome Classic
* Persepolis Version: 3.1.0
* How do you install Persepolis? (Repositories, source, ...)
PPA via terminal
* _Please attach log files if crash or paste error message_

**Issue Description and steps to reproduce:**
Install it and run it to reproduce. Not sure how else to say it.

**Comment by mostafaasadi** [comment]
Hi 
please give us more detail about your problem such a screenshot
