### ISSUE TITLE
Problem in theme

### ISSUE THREAD

**Issue by amirali** [persepolisdm/persepolis#563]
**System Details:**
* Operating System: Windows 10 (64-bit)
* Persepolis Version: 3.1.0
* How do you install Persepolis? executable installer

I download this version and install it.  
after installation i changed persepolis theme to windows
and after that i changed theme again to fusion
after restart perspolis its be this look
[Screenshot Link](https://kutt.it/UPXO5o)

**Comment by itshaadi** [comment]
same issue, there isn't any log detail to why it happens, but clicking on default button will change everything back to normal.
![image](https://user-images.githubusercontent.com/10201704/46322248-b25e0b80-c5f4-11e8-8a1a-14ebfd8690e8.png)

**Comment by amirali** [comment]
Huh,  
Ok  
tnx
