### ISSUE TITLE
"Signature extraction failed" when using Video Finder

### ISSUE THREAD

**Issue by RisingInIris2017** [persepolisdm/persepolis#564]
**System Details:**
* Operating System: Windows 10 Home (Chinese-Simplified) x64
* Persepolis Version: 3.1.0
* How do you install Persepolis? (Repositories, source, ...)
   Download the installer from Release page.

* _Please attach log files if crash or paste error message_
PDM isn't crash, but just has some issue for its Youtube video finder.
https://gist.github.com/RisingInIris2017/3f17e6bcbdf663f5a41cab9aa7bd6acd

**Issue Description and steps to reproduce:**
1. Copy a Youtube video's link;
2. Open PDM's "Find Video Links" menu, and then click the button "Fetch Media List";
3. See such a error message.
4. Uninstall PDM and reinstall it again, but this issue can still be seen.

**Comment by alireza-amirsamimi** [comment]
Hello
Please see this [link](https://github.com/persepolisdm/persepolis/wiki/How-can-I-download-videos-from-youtube#faq) .
It's not related to Perspolis but perhaps it solved after our next update. We'll update youtube-dl for windows in next version.
