### ISSUE TITLE
Persepolis core dumpt

### ISSUE THREAD

**Issue by ghost** [persepolisdm/persepolis#566]
**System Details:**
* Operating System: GNU/Linux
* Distro(For GNU/Linux and BSD users): Manjaro-Gnome (Archlinux)
* Desktop Environment(For GNU/Linux and BSD users): Gnome
* Persepolis Version: 3.1.0
* How do you install Persepolis? source(AUR Package)

* _Please attach log files if crash or paste error message_
***********Error:***********
qt5ct: using qt5ct plugin
qt5ct: D-Bus global menu: no
qt5ct: D-Bus system tray: yes
qt5ct: custom style sheet is disabled
inotify_add_watch("/home/emptycpp/.config/qt5ct") failed: "No such file or directory"
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/persepolis/scripts/video_finder_addlink.py", line 387, in run
    self.FOUND.emit({'thread_key': self.key, 'file_size': spider(self.dictionary)[1]})
  File "/usr/lib/python3.7/site-packages/persepolis/scripts/spider.py", line 106, in spider
    return filename, file_size
UnboundLocalError: local variable 'file_size' referenced before assignment
Aborted (core dumped)

**Issue Description and steps to reproduce:**
when i fetch the youtube link into program, the following error occurs.

**Comment by alireza-amirsamimi** [comment]
The bug is [fixed](https://github.com/persepolisdm/persepolis/commit/3176ffd0fd4467e4661ca1da105cc9225c08ca7d).
Thanks for reporting :+1:
