### ISSUE TITLE
Ubuntu 18.10 rebo 

### ISSUE THREAD

**Issue by Pakrohk** [persepolisdm/persepolis#568]
**System Details:**
* Operating System: Gnu
* Distro(For GNU/Linux and BSD users): Ubuntu
* Desktop Environment(For GNU/Linux and BSD users): Budgie
* Persepolis Version: ubuntu repo 3.0.1 , github persepolis repo 3.1.0
Ubuntu's repository version was old.
I tried to add your repository to the Ubuntu repositorys.

**_BUT_**
````
Persepolis download manager is a GUI for aria2
website: https://persepolisdm.github.io
github: https://github.com/persepolisdm/persepolis
 More info: https://launchpad.net/~persepolis/+archive/ubuntu/ppa
Press [ENTER] to continue or Ctrl-c to cancel adding it.

Hit:1 http://ir.archive.ubuntu.com/ubuntu cosmic InRelease
Hit:2 http://ir.archive.ubuntu.com/ubuntu cosmic-updates InRelease             
Hit:3 http://ir.archive.ubuntu.com/ubuntu cosmic-backports InRelease           
Ign:4 http://ppa.launchpad.net/persepolis/ppa/ubuntu cosmic InRelease
Hit:5 http://ppa.launchpad.net/ubuntubudgie/backports/ubuntu cosmic InRelease
Err:6 http://ppa.launchpad.net/persepolis/ppa/ubuntu cosmic Release           
  404  Not Found [IP: 91.189.95.83 80]
Reading package lists... Done
E: The repository 'http://ppa.launchpad.net/persepolis/ppa/ubuntu cosmic Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
```

**Comment by itshaadi** [comment]
from what I found, 18.10 is still in beta and will be released on 18th October 2018. so this might not be a priority yet. can you follow the [manual installation](https://github.com/persepolisdm/persepolis/wiki/git-installation-instruction) to confirm that Persepolis is working on Cosmic Cuttlefish?

**Comment by mostafaasadi** [comment]
Hi 
thank you for your reporting :rose: 
I added cosmic and disco repo
