### ISSUE TITLE
بزرگ شدن پنجره ها در نسخه جدید

### ISSUE THREAD

**Issue by LinArcX** [persepolisdm/persepolis#57]
علی جان تو نسخه جدید پنجره ها به طرز تو ذوق زنی بزرگ هستن.
امکانش هست اندازه ها به نسخه سابق برگردن؟
https://i.imgsafe.org/8c1ef7067f.png

**Comment by LinArcX** [comment]
حل شد!
نمیدونم چه برنامه ای باعث شده بود اندازه صفحات پرسپولیس تا این اندازه بزرگ بشن!
حداقل تا جایی که من یادمه سایز صفحات رو بزرگ نکرده بودم.

**Comment by LinArcX** [comment]
من دوباره این ایشو رو  ری اوپن میکنم.چون حس میکنم واقعا مشکل وجود داره و خطای سهوی باعث این مشکل نشده.
ببین علی جان.
من امروز قشنگ بالای 20 تا فایل به صورت دونه دونه دانلود کردم.
تو هر سری که یه دانلود جدید رو شروع میکردم چند تا اتفاق عجیب برام میفتاد:
۱-اون پنجره شروع دانلود هر سری یه تغییر سایز خیلی کوچیک به خودش میگیره.
یعنی اگه هی کوچیکش نکنم بعد 10 بار دانلود چند برابر نسبت به اندازه استانداردش بزرگ تر میشه.
۲-پنجره اتمام دانلود گاها مشاهده شده تو قسمت های مختلف دسکتاپم بازمیشه.یه بار وسط صفحه باز میشه.یه بار گوشه سمت چپ بالا.
خلاصه فک کنم یه چیزی داره پوزیشن عناصر برنامه رو هی عوض میکنه.
دوست دارم خودت هم تست کنی و مطمین شیم واقعا خطای دید من نبوده:(

**Comment by alireza-amirsamimi** [comment]
محل باز شدن پنجره مربوط به مدیر پنجره میزکارت هست
دست پرسپولیس نیست

**Comment by Mr-undead** [comment]
این مشکل را روی میزکار یونیتی توزیع اوبونتو 16.04.1 داشتم که متاسفانه حل نشد. روی مانجارو 
Xfce 
مشکل سایز نداریم همه چیزش درست است

**Comment by alireza-amirsamimi** [comment]
ممنونم از اطلاعت
باید تمهیداتی بچینم که 
window manager
به سلیقه خودش پنجره رو تغییر نده و ...

**Comment by molaeiali** [comment]
برای منم پنجره دانلودها خیلی بزرگ بودن،ارتفاع پنجره‌ها تقریبا اندازه کل صفحه بود!
یک بار کوچک کردم پنجره‌ها رو، دیگه همونقدر موندن
اما سایزشون عوض نمی‌شه هر بار

**Comment by alireza-amirsamimi** [comment]
سلام
این باگ در نسخه جدید رفع شد
ممنونم از اینکه اطلاع دادید
آپدیت بفرمایید
