### ISSUE TITLE
Minor UI Issues

### ISSUE THREAD

**Issue by itshaadi** [persepolisdm/persepolis#570]
**System Details:**
* Operating System: **Windows10 (Build 17134)**
* Persepolis Version: **3.1.0**
* How do you install Persepolis? **x64 installer from Releases**

**Issue Description and steps to reproduce:**

### 1 - Opposite Functionality
Preferences > Notifications > notification type
**qt notification** does the opposite (switches to windows notifications) and **native notifications** switches to qt notifications

### 2 - Extra Divider Between Add Link And Pause
**figure 1 -** notice All Download category is selected
![image](https://user-images.githubusercontent.com/10201704/46318266-c4cf4980-c5e2-11e8-9629-1966e0cfcb46.png)
**figure 2 -** no divider between add link and pause when single downloads is selected
![image](https://user-images.githubusercontent.com/10201704/46318411-3e673780-c5e3-11e8-8918-e1df3b3db3f5.png)

**Comment by alireza-amirsamimi** [comment]
I fixed this bug.
Thanks for reporting :+1:
