### ISSUE TITLE
I can’t open persepoils download manager after instell it

### ISSUE THREAD

**Issue by txyyh** [persepolisdm/persepolis#572]
I can't use ”persepoils download manager” after install it.
here is the photo
![photo](https://user-images.githubusercontent.com/41893946/46942341-b16eb480-d09f-11e8-99d9-7852dfd7c2b0.PNG)

**I have reinstalled the app,but it dosen't work.**

**Comment by grahamperrin** [comment]
64-bit or 32-bit Windows?

**Comment by grahamperrin** [comment]
From <https://github.com/persepolisdm/persepolis/issues/531>: 

> This application failed to start because it could not find or load the Qt platform plugin "windows"

**Comment by txyyh** [comment]
64 bit windows 10
![default](https://user-images.githubusercontent.com/41893946/47629204-c7d34080-db74-11e8-9ced-059df7d0b45f.png)

**Comment by mostafaasadi** [comment]
Hi
make sure you have last persepolis bundle
according to our conversation on #362 if you have NonAscii character on your PATH or username cause this problem.
