### ISSUE TITLE
Queue doesn't work

### ISSUE THREAD

**Issue by hoseinMo2** [persepolisdm/persepolis#573]
**System Details:**
* Operating System: linux
* Distro(For GNU/Linux and BSD users): Mint
* Desktop Environment(For GNU/Linux and BSD users):cinamon
* Persepolis Version: 3.1.0
* How do you install Persepolis? (Repositories, source, ...) source

* _Please attach log files if crash or paste error message_

**Issue Description and steps to reproduce:**
سلام قابلیت زمانبندی نرم افزار کار نمیکنه و هرچی زمان شروع رو تنظیم می کنیم شروع به دانلود نمیکند ممنون میشم مشکل رو حل کنید

**Comment by grahamperrin** [comment]
Translated by Google: 

> Hello, the program timing does not work, and does not start downloading every time we start. Thank you, I'll fix the problem.

**Comment by alireza-amirsamimi** [comment]
Hello 
visit this [link](https://github.com/persepolisdm/persepolis/wiki/How-to-create-queue-fa) and this [link](https://github.com/persepolisdm/persepolis/wiki/How-to-create-queue-fa) please.
