### ISSUE TITLE
Shortcuts

### ISSUE THREAD

**Issue by TassdarZeratul** [persepolisdm/persepolis#574]
**System Details:**
* Operating System: ?
* Distro(For GNU/Linux and BSD users): ?
* Desktop Environment(For GNU/Linux and BSD users): ?
* Persepolis Version: ?
* How do you install Persepolis? (Repositories, source, ...)
* _Please attach log files if crash or paste error message_
![image](https://user-images.githubusercontent.com/29266528/47365952-3c3e5780-d70f-11e8-84b7-0dc13ee3b344.png)
**Issue Description and steps to reproduce:**

**Comment by JafarAkhondali** [comment]
Fixed in [https://github.com/persepolisdm/Persepolis-WebExtension/issues/16](https://github.com/persepolisdm/Persepolis-WebExtension/issues/16)
