### ISSUE TITLE
Persepolis and Waterfox

### ISSUE THREAD

**Issue by GianBarGian** [persepolisdm/persepolis#575]
Operating System: Kubuntu 18.04
Persepolis Version: Latest version from repositories

I'm using Waterfox and, while both Persepolis and his Firefox extension are installed correctly, when I click "Download with Persepolis" nothing happens. 
I tried both with Persepolis still closed, and already opened.
Should I do something in about:config in Waterfox?

Thx in advance

**Comment by grahamperrin** [comment]
Cross reference [Waterfox and Persepolis : waterfox](https://www.reddit.com/r/waterfox/comments/9rkxwb/waterfox_and_persepolis/)

Reproducible with 56.2.4 in single-process mode. 

(Waterfox 56.0 was based on Firefox 56.0.2.)

**Comment by grahamperrin** [comment]
`This extension does not have permission to use native application com.persepolis.pdmchromewrapper (or the application is not installed)`

– NativeMessaging.jsm:216

`Unchecked lastError value: Error: Attempt to postMessage on disconnected port`

– ExtensionCommon.jsm:304

**Comment by GianBarGian** [comment]
Thx for help! Solution can be found here: https://www.reddit.com/r/waterfox/comments/9s2qmh/possible_fix_for_addon_open_with/
