### ISSUE TITLE
عدم تمایز بین فایل های استاپ شده و فایل هایی که  در آینده دانلود خواهند شد

### ISSUE THREAD

**Issue by LinArcX** [persepolisdm/persepolis#58]
من یه لیست بلند بالا از ویدیوها رو دارم میگیرم.اومدم واسه راحتی کار موقعی که لینک برام تو پرسپولیس باز میشه تیک گزینه
download later
رو زدم.
اما متاسفانه به جای اینکه اسم فایل ها رو بهم نشون بده یه سری ستازه تو ستون نام و سایز و دانلود و ... نشون میده و از همه مهتر اینکه وضعیت رو 
stopped 
میزنه.
یعنی ممکنه لیست دانلود ها م طولانی باشه و بین اونایی که گذاشتم واسه دانلود و اونایی که واقعا استاپ شدن نتونم تمیز بدم!
(میتونی وضعیت رو از" استاپ" به "دانلود لیتر" تغییر بدی)
گفتم اینم بگم خدمتت علی جان واسه نسخه های آینده اعمال کنی:(

**Comment by alireza-amirsamimi** [comment]
سلام
خیلی لطف داری و پیشنهاد های خوب میدی
ممنونم
یه کامیت چند روز پیش فرستادم روی گیت هاب برای حل این مشکل و انشالله توی ورژن بعد رسما منتشر میشه
در این قابلیت اضافه شده وقتی کاربر دکمه دانلود برای بعد یا دانلود زمانبندی رو انجام میده دانلود منجر سعی میکنه اسم وسایز فایل رو پیدا کنه و اگه موفق بشه توی لیست مینویستش
الان هم اگر بسته 
persepolis-git
رو نصب کنی تغییرات برات نصب میشه و البته یه پیش نیاز جدید هم برات نصب میکنه

**Comment by LinArcX** [comment]
اره دستت درد نکنه.خوب شد
فقط یه نکته اینکه:
وضعیت رو اگه از 
stopped
بکنی
download later
بهتر نیست به نظرت؟

**Comment by alireza-amirsamimi** [comment]
از شدن باید بشه ولی خب یه کم دردسرش زیاده :))
ببینم چی میشه :)
