### ISSUE TITLE
مشکل باز نشدن

### ISSUE THREAD

**Issue by Abasalt-yar** [persepolisdm/persepolis#581]
سلام من از دیپین استفاده میکنم امروز میخواستم برم توی تنظیمات نرم افزار یدفعه کرش کرد و دیگ باز نشد چند بار حذف و دوباره نصب کردم بازم نشد اگر میشه کمک کنین لطفا

**Comment by iman-salmani** [comment]
hello
delete .config/persepolis or .config/persepolis_download_manager folder
سلام
پوشه پرسپولیس را که داخل پویشه ی .config است پاک کن بعد اگر پرسپولیس خطا داد دوباره نصب کن.
آدرس پوشه .config
/home/{user_name}/.config
