### ISSUE TITLE
تعیین مکان برای صف

### ISSUE THREAD

**Issue by Pakrohk** [persepolisdm/persepolis#582]
لطفا قابلیتی اضافه کنید که بشه برای هر صف مکانی اضافه کنیم
برای مثال برای سریال هایی مثل فلش بتونیم پوشه تعیین کنیم تا همه قسمت ها به همون پوشه بره.
ببخشید من نمی تونستم منظورم رو انگلیسی برسونم.

**Comment by alireza-amirsamimi** [comment]
این لینک رو ببین
https://github.com/persepolisdm/persepolis/issues/597

برای نسخه بعدی اضافه کردم. امیدوارم کمک کنه :)
