### ISSUE TITLE
کرش در حال دانلود کردن

### ISSUE THREAD

**Issue by ghost** [persepolisdm/persepolis#583]
سلام.
من از المنتری با دکستاپ پیش فرض در حال دانلود کردن یک صف دانلود 200 تایی بودم ، من برنامه را صورت مخفی در آوردم تا باز شود ولی باز نشد ، کمی صبر کردم ولی بازهم باز نشد سپس روی آیکون برنامه کلیک کردم که ناگهان برنامه کرش کرد و تمامی فایل ها و صف ها پرید . من از آخرین ورژن پرسپولیس استفاده میکنم . و همین طور آخرین ورژن المنتری

**Comment by ghost** [comment]
البته من پرسپولیس را از طریق خط فرمان اجرا کردم خطایی نداد ولی صف ها و دانلود ها پریده بود .

**Comment by alireza-amirsamimi** [comment]
It's weird.
Which version do you use?
Please use english language here :)

**Comment by JafarAkhondali** [comment]
Please open a new issue if the problem exists within new version.
