### ISSUE TITLE
وجود پارامترهای آدرس بعد از اسم و پسوند فایل

### ISSUE THREAD

**Issue by mehdico** [persepolisdm/persepolis#584]
وقتی فایلی دانلود میشه بعضی اوقات اگر پارامتر بعد از اسم فایل در آدرس اینترنتی وجود داشته باشه به همراه اسم فایل ذخیره میشه و این برای تعداد بالای دانلود آزار دهنده است و باید تک تک اسم فایلها رو عوض کنیم
مثال
S01E01_1080p.mkv?20181019180904

**Comment by alireza-amirsamimi** [comment]
Hello
thanks for reporting :+1: 
Please always use english language here.
Can you write download link of this file( S01E01_1080p.mkv?20181019180904)? So I can test it.

**Comment by mehdico** [comment]
This is a similar link :

http://tct-cdn.cdn.p30download.com/p30dl-tutorial/Packt.Building.RESTful.APIs.with.Go_p30download.com.part1.rar?1551825448

From this page :

https://p30download.com/fa/entry/85185/

Thanks Alireza.

**Comment by alireza-amirsamimi** [comment]
Hello
The problem is related to p30downloads.com
The file name on their server is "Packt.Building.RESTful.APIs.with.Go_p30download.com.part1.rar?1551825448"

see the screenshot please/
![image](https://user-images.githubusercontent.com/7452500/54127698-a25a1b80-441f-11e9-973a-901c444e8b1c.png)

**Comment by mehdico** [comment]
This is not p30downloads.com problem, many of sites to prevent caching or sites with premium accounts generate links like this, and other popular download softwares work well in this situation. And the number after file name is not part of real file name and only generated by php or so.

**Comment by alireza-amirsamimi** [comment]
@mehdico So what can we do with this🤔
Aria2 gets this file with that name!

**Comment by alireza-amirsamimi** [comment]
How can we distinguish this file? I have no idea!

**Comment by mehdico** [comment]
Please test the link using IDM, ADM, FDM , ..

**Comment by alireza-amirsamimi** [comment]
I have not windows and IDM on my system.
I test your link with Aria2 and Wget and curl. All of them got the file with this name :"Packt.Building.RESTful.APIs.with.Go_p30download.com.part1.rar?1551825448"

**Comment by mehdico** [comment]
All url parameters came after ? Question mark in the URL. I think we can check for . Dot before question mark in file name, if exist, remove url parameters from filename.

Clearly i suggest this : If extension exist befoe ? remove ? And trailing string.

**Comment by alireza-amirsamimi** [comment]
I'm not familiar with this links. What is the main pattern for this links?
"File_name.extension + ? + number" ???

**Comment by mehdico** [comment]
Yes, Correct pattern, but replace number with anyting.

**Comment by alireza-amirsamimi** [comment]
@mehdico Can you write some links with diffrent ending? So I can fix the problem :)

**Comment by mehdico** [comment]
Take a look at this:

https://superuser.com/questions/61025/how-can-i-make-wget-rename-downloaded-files-to-not-include-the-query-string

**Comment by alireza-amirsamimi** [comment]
Thanks :+1: 
I'll work on it :)

**Comment by alireza-amirsamimi** [comment]
I added your feature request :)
Thank you :)
