### ISSUE TITLE
Shutdown problem.

### ISSUE THREAD

**Issue by Achaean** [persepolisdm/persepolis#586]
**System Details:**
* Operating System: ?
* Distro(For GNU/Linux and BSD users): ? Debian.
* Desktop Environment(For GNU/Linux and BSD users): ? KDE.
* Persepolis Version: ? 3.1.0.
* How do you install Persepolis? (Repositories, source, ...) From the DEB package.

**Issue Description and steps to reproduce:**

I'm not able to shutdown.
At the bottom-left  panel after queue started, I can see only  the "Show options" button, which don't have any related option.
Either it's a bug, or I'm missing something. :-)

**Comment by alireza-amirsamimi** [comment]
Hello
 visit [this link](https://github.com/persepolisdm/persepolis/wiki/How-to-create-queue)
