### ISSUE TITLE
1 problem

### ISSUE THREAD

**Issue by axelgithub** [persepolisdm/persepolis#587]
**System Details:
* Operating System: windows 10
* Distro(For GNU/Linux and BSD users): KB4483234
* Desktop Environment(For GNU/Linux and BSD users): For Windows 10
* Persepolis Version: 3.1.0
* How do you install Persepolis? (Repositories, source, ...)
download from github
* _Please attach log files if crash or paste error message_
I have install Persepolis Download Manager Integration in chrome. But the System can't open Persepolis when I click the download  link. The download  link in http://player.qq.com/&https://pc.weixin.qq.com/
**Issue Description and steps to reproduce:**

**Comment by JafarAkhondali** [comment]
@axelgithub Hey, this page shows a 404 error !
