### ISSUE TITLE
مشکل پیدا نکردن لینک های دانلود یوتیوب

### ISSUE THREAD

**Issue by mehrshadmti** [persepolisdm/persepolis#588]
**System Details:**
* Operating System: windows 10 pro
سلام
نرم افزار دانلود منیجر پرسپولیس لینک های دانلود ویدیو های یوتیوب را پیدا نمیکند

افزونه مخصوص کروم هم نصب هست

--------------
ERROR: Signature extraction failed: Traceback (most recent call last): File "site-packages\youtube_dl\extractor\youtube.py", line 1191, in _decrypt_signature File "site-packages\youtube_dl\extractor\youtube.py", line 1102, in _extract_signature_function File "site-packages\youtube_dl\extractor\youtube.py", line 1163, in _parse_sig_js File "site-packages\youtube_dl\extractor\common.py", line 808, in _search_regex youtube_dl.utils.RegexNotFoundError: Unable to extract Initial JS player signature function name; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type youtube-dl -U to update. Be sure to call youtube-dl with the --verbose flag and include its complete output. (caused by RegexNotFoundError('Unable to extract Initial JS player signature function name; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type youtube-dl -U to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type youtube-dl -U to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
---------------------------------------------------

http://s8.picofile.com/file/8347781318/Annotation_2019_01_03_144328.jpg

**Comment by 0x73am43l** [comment]
hey, you are using an outdated version of **youtube-dl** ! Read [our FAQ](https://yt-dl.org/update) if you have troubles updating.

**Comment by alireza-amirsamimi** [comment]
Please visit [this link](https://github.com/persepolisdm/persepolis/wiki/How-can-I-download-videos-from-youtube-fa)
