### ISSUE TITLE
very important issue about sounds

### ISSUE THREAD

**Issue by develhopper** [persepolisdm/persepolis#589]
**System Details:**
* Operating System: GNU/Linux
* Distro(For GNU/Linux and BSD users): debian sid (buster)
* Desktop Environment(For GNU/Linux and BSD users): Gnome
* Persepolis Version: 3.1.0 (latest)
* How do you install Persepolis? repositories

* _Please attach log files if crash or paste error message_

**Issue Description and steps to reproduce:**
when download is finished after notification sound playing
the system sound increased to 100%

its very bad when im whatching porn and my 10% sound increasing to 100%
please fix that :)

my favorite damn dm

**Comment by alireza-amirsamimi** [comment]
هلاک صداقتت شدم😄
You can decrease the sound from preferences window :)

![image](https://user-images.githubusercontent.com/7452500/54089753-9750ae00-4381-11e9-9ad9-20109eccdaa9.png)
