### ISSUE TITLE
عدم حذف دسته ای فایل ها از لیست

### ISSUE THREAD

**Issue by LinArcX** [persepolisdm/persepolis#59]
اگه یه سری فایلی که تو لیست هستن رو انتخاب کنیم و از منوی راست کلیک ظاهر شده گزینه های
delete file
یا
remove download
رو بزنیم همه رو حذف نمیکنه با هم.
فک کنم حذف گروهی آپشن خوبی باشه که میتونه اعمال بشه

**Comment by alireza-amirsamimi** [comment]
از روی نوار ایزار با موفقیت حذف میشه؟

**Comment by LinArcX** [comment]
نه اونجا هم مشکل داره و تکی حذف میکنه.

**Comment by alireza-amirsamimi** [comment]
از منو حالت 
selection mode
رو انتخاب کن و به من یه اسکرین شات بده لطفا

**Comment by LinArcX** [comment]
حل شد.
سلکشون مود رو تازه الان دیدم.
