### ISSUE TITLE
Is it under development yet?

### ISSUE THREAD

**Issue by Hitaro** [persepolisdm/persepolis#590]
- It's a long time that I see no push into the repo. Have you stopped working on this software?

- Is it now using the latest Aria2 in the windows-compatible package?

**Comment by hayyan71** [comment]
@Hitaro Nope. Just we are a bit busy... Mr Amirsamimi had to work hard on his studies and prepare himself for some final course exams :-) we'll start developing persepolis again soon.

Regards
