### ISSUE TITLE
"Forced shutdown" message to restart the Ubuntu system.

### ISSUE THREAD

**Issue by yawnp0426** [persepolisdm/persepolis#593]
**System Details:**
* Operating System: Ubuntu
* Distro(For GNU/Linux and BSD users): 18.04
* Desktop Environment(For GNU/Linux and BSD users): MATE
* Persepolis Version: 3.1.0
* How do you install Persepolis? ppa:persepolis/ppa

Once it has downloaded the file, a "forced shutdown" message will appear when you need restart the Ubuntu system.

**Comment by alireza-amirsamimi** [comment]
Can you explain more? I didn't understand properly.
