### ISSUE TITLE
a suggestion about download path

### ISSUE THREAD

**Issue by mysq1isworst** [persepolisdm/persepolis#594]
**System Details:**
* Operating System: windows10 x64 1803
* Distro(For GNU/Linux and BSD users): ?
* Desktop Environment(For GNU/Linux and BSD users): ?
* Persepolis Version: 3.1.0
* How do you install Persepolis? from releases

* _Please attach log files if crash or paste error message_

**Issue Description and steps to reproduce:**
please add a download path memorizing function, need to change path everytime, waste of time.
wish to have a nice enhanced path function like IDM. 👍:)

**Comment by alireza-amirsamimi** [comment]
Hello
Why don't you change the download path from "Edit > Preferences > Sava as " ?

**Comment by alireza-amirsamimi** [comment]
I added a similar feature last week.See this [issue](https://github.com/persepolisdm/persepolis/issues/597).
