### ISSUE TITLE
Bug: Failure to identify the file if there is a quotation mark inside the file name

### ISSUE THREAD

**Issue by 2dvision** [persepolisdm/persepolis#596]
**System Details:**
* Operating System: Linux
* Distro(For GNU/Linux and BSD users): Xubuntu
* Desktop Environment(For GNU/Linux and BSD users): Xfce
* Persepolis Version: 3.1.0
* How do you install Persepolis? source

Related #595

I download a file and change that name to (abcd "efg".mp4) and Persepolis can't open file inside download manager. But i can open this file in file manager.

<div dir="rtl">
من یک فایل از آپارات انتخاب کردم و نام اون رو به abcd "efg".mp4 تغییر دادم و فایل را دانلود کردم. با دوبار کلیک یا راست کلیک و انتخاب گزینه باز کردن فایل، دانلود منیجر توانایی شناخت فایل‌هایی را که در نام آنها علامت نقل قول است را ندارد.

اما این فایل برای فایل منیجر من و یا پخش کنند ویدیو VLC قابل تشخیص و پخش است.
</div>

![file name](https://user-images.githubusercontent.com/16509592/52482272-1063b680-2bc6-11e9-975e-df6302a3c7f9.jpg)

**Comment by alireza-amirsamimi** [comment]
Thanks for reporting :)

**Comment by alireza-amirsamimi** [comment]
The bug is fixed.
Thanks for reporting :+1:
