### ISSUE TITLE
Feature Request: Move downloaded file to another location in hard disk directly

### ISSUE THREAD

**Issue by 2dvision** [persepolisdm/persepolis#597]
you can set a main directory for download. if you want manage your downloaded file and move to another directory (for archive, etc), you need use a file manager in your system.

I recomende add "move to another location", then user can move downloaded file from main download directory to favorit directory.

<div dir="rtl">
در خواست ویژگی: انتقال فایل‌ها از فولدر فایل‌های دانلود شده به فولدری دیگر

اگر شما هم مثل من از یوتیوب دانلود می‌کنید و فایل‌های دانلودی را در فولدر‌هایی با نام «کانال یوتیوبر» ذخیره می‌کنید، یا فایل‌هایی را دانلود می‌کنید و در فولدر‌هایی قرار می‌دید که بعدا دسترسی سریعتر داشته باشید، حتما برایتان راحت‌تره که فایل را بتونید مستقیم از دانلود منیجر به فولدر مورد نظر انتقال بدید.

روش کار
۱. یک یا چند فایل دانلود شده را از لیست دانلود منیجر انتخاب کنیم.
۲. روی دکمه «انتقال به فولدر دیگر» کلیک کنیم.
۳. در پنجره باز شده محل مورد نظر را انتخاب کنیم.
۴. روی دکمه انتقال کلیک کنیم.

فایل از فولدر فایل‌های دانلود شده به مکان مورد نظر انتقال پیدا کند.

حتی می‌شه در پنجره انتقال فایل بخشی برای بوک‌مارک کردن فولدرهایی که زیاد با اون‌ها سر و کار داریم در نظر گرفت.
</div>

![mv](https://user-images.githubusercontent.com/16509592/52482351-47d26300-2bc6-11e9-9ee2-2b74bb2f7daf.jpg)

**Comment by alireza-amirsamimi** [comment]
:+1:

**Comment by alireza-amirsamimi** [comment]
I add your feature request :)
Thank you :)

**Comment by 2dvision** [comment]
THANK YOU!!! This feature is really useful. :)
