### ISSUE TITLE
speed limiter problem

### ISSUE THREAD

**Issue by mingodoce** [persepolisdm/persepolis#598]
i use persepolis 3.0.1 on kubuntu 18.10 and have issue with speed limiter
for example i lmiited] speed to 300 k/b and and in transfer rate shows me 300 k/b!!!!
but in system monitor and nethogs it take all of my internet speed

**Comment by alireza-amirsamimi** [comment]
Hello
This problem is related to (Aria2)[http://github.com/aria2/aria2/] .Persepolis is a GUI for Aria2 :)
