### ISSUE TITLE
No response

### ISSUE THREAD

**Issue by mhasadi78** [persepolisdm/persepolis#599]
**System Details:**
* Operating System: Linux x64
* Distro(For GNU/Linux and BSD users): Manjaro (based on Arch)
* Desktop Environment(For GNU/Linux and BSD users): Gnome
* Persepolis Version: 3.1
* How do you install Persepolis? Source

* _Please attach log files if crash or paste error message_

**Issue Description and steps to reproduce:**
No response on clicking on the icon. No error message either. 
Re-installing might help but I did not check it.
The log file attached.
[persepolisdm.log](https://github.com/persepolisdm/persepolis/files/2902767/persepolisdm.log)

**Comment by iman-salmani** [comment]
hello
try with pip3 install youtube_dl

**Comment by alireza-amirsamimi** [comment]
Hello
Aria2 didn't respond. Try to solve this problem.
Some dependencies are not installed. Check this [link](https://github.com/persepolisdm/persepolis/wiki/git-installation-instruction#linux) for more information.

**Comment by JafarAkhondali** [comment]
I'll close the issue since there is no response from @mhasadi78 .
Create a new issue if it's not fixed yet.
