### ISSUE TITLE
تغییر چیدمان  ستون های داخل برنامه

### ISSUE THREAD

**Issue by Mr-undead** [persepolisdm/persepolis#6]
با توجه به اندازه پیشفرض برنامه در زمانی که برنامه اجرا میشود بهتر نیست ستون ها جابجا شوند 
به این ترتیب
File Name - Size - Status - Transfer rate - Percentage - Downloaded - Estimate time left

**Comment by alireza-amirsamimi** [comment]
با توجه بخ ساختار برنامه فکر نکنم امکانش باشه
ولی چک مکینم :)

**Comment by LinArcX** [comment]
آره پیشنهاد خوبی داد بهروز..مثل چیزی که تو آی.دی.ام بود میشد ستون ها رو به دلخواه کاربر جابجا کرد.
البته زیاد فورس ماجور نیست این تسک اما میشه به عنوان یه بهبود بهش نگاه کرد.
