### ISSUE TITLE
minimized to the system tray 

### ISSUE THREAD

**Issue by Mr-undead** [persepolisdm/persepolis#60]
سلام 
لطفا در صورت امکان در قسمت ابزار های برنامه آیکون
minimized to the system tray 
را اضافه کنید تا کاربر مجبور به گذشت و گذار در منو های برنامه نباشه

**Comment by alireza-amirsamimi** [comment]
حتما انشالله در ورژن ۲.۳ اضافه خواهم کرد :)

**Comment by alireza-amirsamimi** [comment]
سلام این امکان رو به برنامه اضافه کردم
الان روی گیت هاب هست و توی ورژن بعدی که ۲.۳ هست اعلامش میکنم
ولی شما که آرچ داری میتونی به وسیله
AUR
و بسته
persepolis-git
آخرین ورژن گیت هاب رو داشته باشی
که این قابلیت هم بهش اضافه شده

**Comment by Mr-undead** [comment]
بسیار عالی آپدیت کردم
