### ISSUE TITLE
عدم نمایش نام فایل

### ISSUE THREAD

**Issue by mojtabakheyri1997** [persepolisdm/persepolis#600]
سلام در آخرین نسخه پرسپولیس در اوبونتو
موقعی که یه لینکی رو میخوام باهاش دانلود کنم و پنجره قبل دانلود باز میشه 
حجم فایل رو نشون میشه ولی خب نام فایل به هیچ باره قابل دیدن نیست ...
![deepinscreenshot_persepolis_20190301160206](https://user-images.githubusercontent.com/47574391/53638405-61058700-3c3b-11e9-9367-d0c51da51fdb.png)

**Comment by JafarAkhondali** [comment]
@mojtabakheyri1997 
The extension is updated. Can you please update the extension and check again? Or share the link?
Thanks
