### ISSUE TITLE
مشکل دانلود از یوتیوب

### ISSUE THREAD

**Issue by morezalotfi** [persepolisdm/persepolis#602]
لینک ویدیو از یوتیوب رو کپی بعد با پرسپولیس دانلود میکنم ولی چیزی دانلود نمیشه با فیلترشکن و بدون فیلترشکن 
الانم نمیتونم دانلود کنم از یوتیوب  سرچ هم زدم ولی فایده نداشت
لطفا #علیرضا امیر صمیمی یک آموزش تصویری بزار برا دانلود از یوتیوب

_Originally posted by @morezalotfi in https://github.com/persepolisdm/persepolis/issues/601#issuecomment-471235142_

**Comment by alireza-amirsamimi** [comment]
Hello
Please use english language here :)
Check [this link](https://github.com/persepolisdm/persepolis/wiki/Home-fa#%D8%B3%D9%88%D8%A7%D9%84%D8%A7%D8%AA-%D8%B1%D8%A7%DB%8C%D8%AC). It will help you :)
