### ISSUE TITLE
after download : Shutdown

### ISSUE THREAD

**Issue by mehdico** [persepolisdm/persepolis#603]
After start a Schedule and check  [after download] checkbox, then select Shutdown, Application ask's for password, after enter password (correct password, event with copy & paste) app say [wrong password], and this happen for ever and not accept any password.

![Screen Shot 1397-12-20 at 01 47 06](https://user-images.githubusercontent.com/1978735/54092304-e7d70400-439f-11e9-9992-90fdf7ea70f0.png)
OS : Mac Os Mojave , High Sierra
PDM  :  3.1.0

**Comment by alireza-amirsamimi** [comment]
I tagged some of developers to check the problem.
Thanks for reporting.
Do you start persepolis from browser or from menu?

----------------------------------------------------------------
I suggest you to change the persepolis theme :) 
Visit this [link](https://github.com/persepolisdm/persepolis/wiki/How-to-change-Persepolis-theme)

**Comment by mehdico** [comment]
Thank you Alireza.
I Think this happens when i start it by clicking on a download link.

Im using PDM only when going to bed (set a schedule to use night shift for low cost internet !) , so really i dont need a theme ;)

**Comment by alireza-amirsamimi** [comment]
@mehdico Please run Persepolis from menu first and then add links with your browser. May it solves the problem.

**Comment by Maders** [comment]
@mehdico, It's working for me on macOS 10.14.3 (when downloading link from browser or adding link directly).

**Comment by mehdico** [comment]
This happen's 60% of times for me, i don't know why, but yes i think maybe it's connected to how we launch the app.

**Comment by alireza-amirsamimi** [comment]
Hello
I fix password problem with this [commit](https://github.com/persepolisdm/persepolis/compare/777072000f45...1dae8a5a14ed).

Thanks for reporting :+1:
