### ISSUE TITLE
incompatibility of the setup.py and debianhelper

### ISSUE THREAD

**Issue by ghost** [persepolisdm/persepolis#604]
**System Details:**
* Operating System: GNU/Linux
* Distro(For GNU/Linux and BSD users): Debian Buster (10)
* Desktop Environment(For GNU/Linux and BSD users): GNOME
* Persepolis Version: 3.0.1
* How do you install Persepolis? Repositories

**Issue Description and steps to reproduce:**

I would like to cross-reference this issue from Debian here: 
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=924204

**Comment by alireza-amirsamimi** [comment]
@salmanishere Hello
What is the problem? What can we do?

**Comment by ghost** [comment]
Currently I don't know, I should invest time and look at it.
