### ISSUE TITLE
No download speed then error

### ISSUE THREAD

**Issue by AmalwayshereU** [persepolisdm/persepolis#605]
**System Details:**
* Operating System: Windows 64bit
* Distro(For GNU/Linux and BSD users): No 
* Desktop Environment(For GNU/Linux and BSD users): ?
* Persepolis Version: 3.1.0
* How do you install Persepolis? (Repositories, source, ...) relase edtion 3.1.0

* _Please attach log files if crash or paste error message_

**Issue Description and steps to reproduce:**
I installed peisepolisdm, unfortunately it did not download(status is downloading but no speed at all) after adding download link. And I do not know what the problem is. I wander now wether i really install it successfully````
[PDM log.txt](https://github.com/persepolisdm/persepolis/files/2961139/PDM.log.txt)
![QQ截图20190313190549](https://user-images.githubusercontent.com/25956759/54274489-2f89a580-45c3-11e9-99e6-ecdef7f23b9a.png)

**Comment by alireza-amirsamimi** [comment]
Hello
It's weird problem! Persepolis can not connect to aria2 and can not get download information from aria2. Make sure that your firewall or antivirus hadn't block persepolis or aria2c.

**Comment by alireza-amirsamimi** [comment]
Persepolis doesn't support magnet link for now :)
