### ISSUE TITLE
Persepolis Download Manager for Steam

### ISSUE THREAD

**Issue by Pakrohk** [persepolisdm/persepolis#606]
**System Details:**
* Operating System: Gnu/Linux
* Distro(For GNU/Linux and BSD users): Arch
* Desktop Environment(For GNU/Linux and BSD users): Kde Plasma
* Persepolis Version: 3.1.0
* How do you install Persepolis? (Repositories, source, ...) : aur

Persepolis is a powerful download manager .
The problem that Steam does not pay attention to Donlowad manager.
Can you solve this problem ?!
An extension for connecting Persepolis to steam or vice versa.
-------------------------------------------------------------------------
[Steam GitHub](https://github.com/ValveSoftware)

**Comment by alireza-amirsamimi** [comment]
I don't use steam but I'll check this :)

**Comment by Pakrohk** [comment]
![Steam](https://user-images.githubusercontent.com/27810360/54388462-021c2500-46b3-11e9-8759-a0446f3450ac.png)
steam

**Comment by alireza-amirsamimi** [comment]
How can we get the download link?

**Comment by JafarAkhondali** [comment]
Steam doesn't allow that, in some cases if you could get direct download link of games it would be possible in PDM. Sorry but we can't help.

**Comment by Pakrohk** [comment]
Contact the steam team, are eager to cooperate.

**Comment by Alirezaies** [comment]
I'm a Steam user for +3 years and using it daily,

Steam does not offer any feature or API for implementing this requested feature, not just for download links, but also each downloaded game/app may have different installation folder and data directory that we can not detect them programmatically,

you better contact Steam support first to implement such feature (e.g. API) first then open an issue like this.

I think we'd better close this issue.

**Comment by Pakrohk** [comment]
https://github.com/ValveSoftware/steam-for-linux/issues/6187#event-2243715559


Plz, check link

**Comment by Alirezaies** [comment]
I can confirm that SteamCMD gives us the ability to implement the feature
you have been requested, thank you for your research, I will consider this
as an implementable feature and will ask other members to tag this issue as
"feature request" + keeping it open.

however this does not mean we have been decided to add this feature at the
moment :)

please be patient.

**Comment by Alirezaies** [comment]
I'll start writing a Python wrapper for SteamCMD tomorrow, but there is no guarantee that this feature would be implemented in Persepolis Download Manager or it would be possible to add a feature like directly integrate it with Steam itself (like Google Chrome's plugin and download directly within browser), hope it all goes fine and help you :)

**Comment by Alirezaies** [comment]
I think there is no way to get download links.

any idea?

**Comment by Pakrohk** [comment]
> I think there is no way to get download links.
> 
> any idea?

Announce in the post that  opened for the steam team.

**Comment by Alirezaies** [comment]
I'll open a new one, should be a ' feature request '


---- On Sun, 14 Apr 2019 18:00:07 +0430 notifications@github.com wrote ----



I think there is no way to get download links.

any idea?

Announce in the post that opened for the steam team.

**Comment by Pakrohk** [comment]
> I'll open a new one, should be a ' feature request '
> […](#)
> ---- On Sun, 14 Apr 2019 18:00:07 +0430 notifications@github.com wrote ---- I think there is no way to get download links. any idea? Announce in the post that opened for the steam team. — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or mute the thread.

Please let us know about the work.

**Comment by Livy-Inverse** [comment]
Steam is a digital content delivery platform, and has a download manager of its own, which can pause/resume downloads at will. The downloaded files need to be validated, then installed, probably with its own DRM depending on each game. Valve will never let you interfere with the internal working of Steam.

Even if you can somehow use PDM to interrupt the downloads, how do you plan to install the game using the compressed files you've downloaded? I can't get the idea behind this request. Do you ever think about that or just post random delusion ideas?

**Comment by Alirezaies** [comment]
well this is a more clear and explicit answer, we surely can not change the core of Steam, SteamCMD is also just another way of interacting with Steam, I'm afraid it's not going to help us increasing the download rate, as Steam itself offers it's own builtin download manager I see no need of implementing this feature in PDM.


---- On Tue, 07 May 2019 07:19:18 +0430 notifications@github.com wrote ----



Steam is a digital content delivery platform, and has a download manager of its own, which can pause/resume downloads at will. The downloaded files need to be validated, then installed, probably with its own DRM depending on each game. Valve will never let you interfere with the internal working of Steam.

I can't get the idea behind this request. Do you ever think or just post random delusion ideas?

**Comment by JafarAkhondali** [comment]
I think there is currently no way to do this, and DM shouldn't focus on integrating other downloads platform. However if anyone would like to do this, we would be happy to receive a PR.
