### ISSUE TITLE
Add Gentoo package installation

### ISSUE THREAD

**Issue by jorgicio** [persepolisdm/persepolis#607]
Hi!

I maintain my own Gentoo overlay with lots of packages. I just gave support for persepolis package, so anyone who uses that distro (or based ones) can install it as usual with Portage:

``emerge persepolis``

Check my repo for information about adding my overlay to the list.

Thank you for the package :)

**Comment by alireza-amirsamimi** [comment]
Hello
thank you :)
Can you be our maintainer for Gentoo? Can you keep the package update?

**Comment by jorgicio** [comment]
Sure, no problem. I just uploaded it yesterday and I'm using it, so yes, I can be your maintainer for Gentoo :)

**Comment by alireza-amirsamimi** [comment]
I added installation method to the [persepolis wiki](https://github.com/persepolisdm/persepolis/wiki/Gentoo-Installer).
Thank you :+1:

**Comment by alimirjamali** [comment]
I can confirm that @jorgicio's overlay works well. Just a quick note on perspolis installation on Gentoo. Python should be compiled with sqlite USE flag.

![image](https://user-images.githubusercontent.com/5407317/55833834-b895ed00-5b2d-11e9-842a-9b85fd8e7558.png)

**Comment by jorgicio** [comment]
Done.

Added PYTHON_REQ_USE="sqlite" to the ebuilds for persepolis.

Thank you!
