### ISSUE TITLE
‫گزینه open Download folder به همراه انتخاب فایل

### ISSUE THREAD

**Issue by msajadi832** [persepolisdm/persepolis#61]
سلام

‫وقتی روی یه فایل دانلود شده، گزینه Open download folder زده میشه، فقط با ناتیلوس فولدر اون فایل باز میشه.
‫لطفا طوری تنظیم کنید که علاوه بر باز کردن فولدر، فایل دانلود شده هم انتخاب شده باشه!
‫برای ناتیلوس جستجو کردم. کافیه به جای آدرس فولدر او فایل، آدرس خود فایل رو بدید. ناتیلوس فولدر رو باز می کنه و اون فایل رو انتخاب می کنه.
[http://askubuntu.com/questions/3363/how-to-open-a-nautilus-directory-and-select-a-file-in-it-from-the-command-line](http://askubuntu.com/questions/3363/how-to-open-a-nautilus-directory-and-select-a-file-in-it-from-the-command-line)

**Comment by alireza-amirsamimi** [comment]
سلام :)
وقتی فایلی دانلودش تمام میشه دو گزینه براش هست
open file
open download folder
گزینه اول فایل رو باز میکنه و گزینه دوم پوشه دانلود که فایل داخلش موجود هست رو باز میکنه
![screenshot_2016-10-26_12-21-09](https://cloud.githubusercontent.com/assets/7452500/19719451/de9a3318-9b76-11e6-81b2-a10534f3a14d.jpg)

**Comment by msajadi832** [comment]
آره. می دونم. 
‫برای همون مورد دوم (open download folder) وقتی فولدر باز شد، فایل دانلود شده انتخاب شده باشه

‫مانند این عکس:
[https://www.mediafire.com/convkey/3631/3wo2o8268sjqomq6g.jpg](https://www.mediafire.com/convkey/3631/3wo2o8268sjqomq6g.jpg)
‫وقتی آدرس فایل رو به ناتیلوس می دم، ناتیلوس باز میشه و فایل هم انتخاب شده!

‫نمی دونم متوجه شدید یا نه!
البته مورد زیاد مهمی نیس

**Comment by alireza-amirsamimi** [comment]
منظور شما هایلایت شدن فایل هست
الان متوجه شدم :)
راستش اونوقت باید بسته
xdotools
رو اضافه کنم و کمی بسته دردسر داری هست :)
گاهی با میزکارها و مدیر پنجره های دیگه ممکن هست کار نکنه :)
کمی دردسر داره این قضیه

**Comment by msajadi832** [comment]
‫چرا xdotools؟
‫توی یونیتی وقتی آدرس خود فایل رو (نه آدرس فولدر پدرش) به Nautilus بدید، فولدر پدر فایل رو باز می کنه و فایل رو هم انتخاب می کنه!
‫بسته xdotools هم نمی خواد!

**Comment by alireza-amirsamimi** [comment]
حرفت درسته :)
ولی یه مشکلی هست . وقتی کد رو مینویسم باید طوری بنویسم که کاربری هم که ناتیلوس نداره بتونه باهاش کار کنه(مثل خودم که میزکارم یونیتی نیست)
برای همسن باید از 
xdg-open
استفاده کنم که دستم بسته میشه

**Comment by msajadi832** [comment]
‫آها. درست می فرمایید. 

ممنون فراوان

**Comment by msajadi832** [comment]
سلام دوباره
[https://github.com/DoTheEvo/ANGRYsearch](https://github.com/DoTheEvo/ANGRYsearch)
‫این برنامه رو یافتم که به زبان python 3 با PyQt5 نوشته شده
و توش همین موردی که گفتم هست

**file_manager** By default empty. Whatever application/script is put there, it receives the path when the path column is double-clicked. If left empty angrysearch will try to autodetect default file manager using xdg-utils. If one of the following file managers are set/detected: ['dolphin', 'nemo', 'nautilus', 'doublecmd'], the behavior will change slightly, sending to those file managers full path to the file, highlighting the target file when opened in a file manager.
گفتم شاید بدردتون بخوره

باز هم ممنون به خاطر برنامه خوبتون

**Comment by alireza-amirsamimi** [comment]
ممنونم 
در اولین فرصت چک میکنم

**Comment by alireza-amirsamimi** [comment]
I added your feature request.
Thanks for your request :+1:
