### ISSUE TITLE
Window not close after download

### ISSUE THREAD

**Issue by mahmoud-eskandari** [persepolisdm/persepolis#611]
**System Details:**
* Operating System: MacOS Mojave
* Distro(For GNU/Linux and BSD users): Macintosh
* Desktop Environment(For GNU/Linux and BSD users): ?
* Persepolis Version: 3.1.0
* How do you install Persepolis? dmg file

**Issue Description:**
The download window is locked after a downloading in MacOS
all buttons inside window and corner buttons (close/minimize) not working correctly after download.

**Comment by Maders** [comment]
Hi @mahmoud-eskandari, it is working correctly for me in normal situation (even after I clean install persepolis)
make sure your dmg sha256 hash is `70be7692e4b7a5f596a570dbcd4b9c5c077ab5481986952fa59c3dc228bc9bb5`
If you can report more helpful details, checking logs when occur (help->show log file).

**Comment by mahmoud-eskandari** [comment]
My dmg hash is ```70be7692e4b7a5f596a570dbcd4b9c5c077ab5481986952fa59c3dc228bc9bb5```
and my OS has been installed recently ,It's clear 🤔
