### ISSUE TITLE
بستن پنجره دانلود و قطع نشدن دانلود

### ISSUE THREAD

**Issue by molaeiali** [persepolisdm/persepolis#62]
خوبه بشه پنجره دانلودها رو بست، اما دانلود قطع نشه، یعنی درواقع مینیمایز بشن به 
tray
 یا اصلا نباشن مگه اینکه دوباره بازشون کنیم از دانلود منیجر

**Comment by dinamycam** [comment]
من متوجه نمیشم.همین الان هم **Ctrl + W**
مینیمایز میکنه به tray.
اگه هم لازم باشه بسته بشه میتونی از کلید **Ctrl+Q**
استفاده کنی.

**Comment by molaeiali** [comment]
@pouya-barzegar 
منظورم پنجره دانلود هست، خود دانلود منیجر مینیمایز می‌شه، ولی پنجره‌های دانلود رو نمی‌شه بست یا فرستاد به tray
مثلا ۱۲ تا دانلود داشته باشی یا ۱۲ تا پنجره بازه یا مینیمایز میشه به 
taskbar
نه به 
tray

عکس آپلود نمی‌شه نمی‌دونم چرا

**Comment by dinamycam** [comment]
آهان.آره راست میگی.
ولی اون پنجره ها رو هم میشه بدون اینکه قطع بشه بست.
‫‫من توی ‫‫i3 مشکلی نداشتم با این قضیه.لازمه که به tray مینیمایز بشه؟

**Comment by molaeiali** [comment]
نمی‌دونم چرا جرأت نکرده بودم ببندمش همینطوری :|
شاید چون پنجره اصلی رو با ضربدر بسته بودم و کلا قطع شده بود اینو نبستم (این توی فیچر ریکوئستای قبلی هست ولی فک کنم بیخیالش شدید، اگه بشه که با ضربدر مینیمایز بشه خیلی خوب میشه)
آره قطع نمی‌شه می‌شه ببندیش
ممنون
