### ISSUE TITLE
Add nixos package

### ISSUE THREAD

**Issue by LinArcX** [persepolisdm/persepolis#622]
Hi. after some times struggling with nixos, i finally success to publish a package for it.
https://github.com/NixOS/nixpkgs/pull/58051
Users can now install persepolis in nixos in two ways:
1. __imperative way__:
`nix-env install nixpkgs.persepolis`
2. __declarative way__:  
add `persepolis` to __configuration.nix__,
```
environment.systemPackages = with pkgs; [
  persepolis
  ...
 ]
```
 then:
`sudo nixos-rebuild switch --upgrade`

Tip: Remember that you have to be on unstable channel.

**Comment by JafarAkhondali** [comment]
Thanks @LinArcX ,
Is it possible for you to add this to wiki using a PR?

**Comment by LinArcX** [comment]
@JafarAkhondali 
I cloned the wiki repo:
https://github.com/persepolisdm/persepolis.wiki.git
But i don't have access to push.
Also i cloned the main repo. but i can' see wiki in cloned repo!

**Comment by alireza-amirsamimi** [comment]
Hello
I'll update the wiki.
Please attach new file here. I'll add it.

**Comment by LinArcX** [comment]
@alireza-amirsamimi 
[Home-en.md](https://gist.github.com/LinArcX/060ddf8987dcb9f1eafc101e7f4a6952)
[Home-fa.md](https://gist.github.com/LinArcX/dec78502ccc1768c0dd19597dc20fbdb)
[Nixos-Installer.md](https://gist.github.com/LinArcX/69066a8cdeafca43e09a4d4af49d2b71)
[Nixos-Installer-fa.md](https://gist.github.com/LinArcX/d8950592645758640c6ffb7dae69c3c5)

**Comment by alireza-amirsamimi** [comment]
Thank you :+1: 
Wiki is updated.
