### ISSUE TITLE
Stucking in 99% 

### ISSUE THREAD

**Issue by kdbskjfbkdsjbfkjsbf** [persepolisdm/persepolis#629]
**System Details:**
* Operating System: Linux Mint
* Distro(For GNU/Linux and BSD users): Cinnamon
* Persepolis Version: latest version

**Issue Description and steps to reproduce:**
Hi Guys ...
The problem with this app is : It stucks at 99% for each download and i can do nothing. i just can stop the download, close and then open again and resume the download again nothing else ... is there any help?

**Comment by alireza-amirsamimi** [comment]
Can you test this link please?

```https://www.google.com/images/branding/searchlogo/1x/googlelogo_tablet_tier1_hp_color_183x64dp.png```
