### ISSUE TITLE
adding custom shortcuts

### ISSUE THREAD

**Issue by dinamycam** [persepolisdm/persepolis#63]
یه روش برای تعریف و تغییر شورتکات های دیفالت برنامه خیلی خوب میشه
مثلا وجود یه فایل کانفیگ شورتکات برای شروع خوبه؟

**Comment by alireza-amirsamimi** [comment]
والا من خودم اصلا موافق نیستم که برنامه پیچیده بشه
کلا با برنامه گرافیکی با تنظیمات شلوغ و پیچیده موافق نیستم برای همین همیشه تنظیمات برنامه رو سعی کردم ساده نگه دارم و فقط چیزهای ضروری رو در تنظیمات بیارم
ولی کار سختی هم نیست که برنامه کانفیگ شرتکات داشته باشه

**Comment by dinamycam** [comment]
به خاطر همین میگم فایل ساده ی متنی باشه.
ساده ترین حالتش هم فک کنم همین باشه.من میگم اون شورتکاتای استاندارد که اکثر برنامه ها دارن دیفالت فعال باشن.
ولی اگه کسی خواست بتونه عوضشون کنه.
override کنه

**Comment by dinamycam** [comment]
میخواین من سعی کنم یه چیزی بنویسم تو چند هفته ی آینده؟

**Comment by alireza-amirsamimi** [comment]
راستش رو بخوای نوشتنش چیز پیچیده ای نیست
شاید  چند ساعت وقت ببره
کمی درگیر فعالیت های موسیقی هستم
در اولین فرصت مینویسم

**Comment by alireza-amirsamimi** [comment]
I added your feature request.
Now user can set custom shortcut in preferences window.
Thanks for your request :+1:
