### ISSUE TITLE
okPushButtonPressed(): setting.py:644:okPushButtonPressed:AttributeError: 'list' object has no attribute 'changeIcon'

### ISSUE THREAD

**Issue by hedayat** [persepolisdm/persepolis#631]
**System Details:**
* Operating System: GNU/Linux
* Distro(For GNU/Linux and BSD users): Fedora
* Desktop Environment(For GNU/Linux and BSD users): ?
* Persepolis Version: 3.1.0
* How do you install Persepolis? Repository

* _Please attach log files if crash or paste error message_
setting.py:644:okPushButtonPressed:AttributeError: 'list' object has no attribute 'changeIcon'

Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/persepolis/scripts/setting.py", line 644, in okPushButtonPressed
    window.changeIcon(icons)
AttributeError: 'list' object has no attribute 'changeIcon'

Local variables in innermost frame:
window: []
list: [[], []]
icons: 'Papirus'
button: False
self: <persepolis.scripts.setting.PreferencesWindow object at 0x7eff280a3f78>

**Issue Description and steps to reproduce:**

Distro bug: https://bugzilla.redhat.com/show_bug.cgi?id=1622322

**Comment by alireza-amirsamimi** [comment]
I fixed this issue :)
Thanks for reporting :+1:
