### ISSUE TITLE
module(): persepolis.py:245:<module>:KeyError: 'url_links' 

### ISSUE THREAD

**Issue by hedayat** [persepolisdm/persepolis#632]
**System Details:**
* Operating System: GNU/Linux
* Distro(For GNU/Linux and BSD users): Fedora
* Desktop Environment(For GNU/Linux and BSD users): ?
* Persepolis Version: 3.1.0
* How do you install Persepolis? Repositories

* _Please attach log files if crash or paste error message_

[backtrace.txt](https://github.com/persepolisdm/persepolis/files/3195430/backtrace.txt)

**Comment by hedayat** [comment]
[backtrace.txt](https://github.com/persepolisdm/persepolis/files/3195430/backtrace.txt)

**Comment by alireza-amirsamimi** [comment]
I fixed this bug.
Thanks for reporting. :+1:
