### ISSUE TITLE
FF integration addon not working

### ISSUE THREAD

**Issue by ShakaZ75** [persepolisdm/persepolis#634]
**System Details:**
* Operating System: Linux
* Distro(For GNU/Linux and BSD users): Linux Mint  18.3
* Desktop Environment(For GNU/Linux and BSD users): KDE
* Persepolis Version: 3.0.1
* How do you install Persepolis? Repository from persepolis ppa

* _Please attach log files if crash or paste error message_

**Issue Description and steps to reproduce:**
#### Please report only one Issue (Bug or feature request or ...) in one issue! and open new Issue for another one :)
Hello, after 1st installation of Persepolis and FF integration addon, I have trouble with the following :
2° Persepolis Integration addon for Firefox doesn't seem to recognise Youtube links.

Here's some basic info about my config :
Linux Mint KDE 18.3
Firefox 67
Persepolis 3.0.1
Persepolis download Manager Integration 2.0.0

**Comment by JafarAkhondali** [comment]
Hello @ShakaZ75 ,
Downloading from YT videos( or any videos online ) is against copy-right laws, if we add such a feature, the extension will be removed from store.

**Comment by ShakaZ75** [comment]
Hello JafarAkhondali,

I'm not sure I'm following you, the wiki on this git repository seems to suggest otherwise [https://github.com/persepolisdm/persepolis/wiki/How-can-I-download-videos-from-youtube](url).
Besides most countries don't have such a strict copyright policy and in countries that do have strict copyright policies there are still many videos that can be downloaded without infringing any copyright.

**Comment by JafarAkhondali** [comment]
Adding this feature will make our extension get removed from the chrome store and MDN. We've discussed about it in our team and decided not to implement this. Sorry
