### ISSUE TITLE
تعیین تعداد دانلود همزمان

### ISSUE THREAD

**Issue by Mr-undead** [persepolisdm/persepolis#64]
سلام 
در صورت امکان گزینه‌ای جهت تعیین تعداد دانلود همزمان در برنامه گنجانده شود
در اخرین نسخه تعداد دانلود همزمان ۵ می‌باشد

**Comment by alireza-amirsamimi** [comment]
حتما انشالله تلاش میکنم اضافه کنم

**Comment by JafarAkhondali** [comment]
Duplicate of https://github.com/persepolisdm/persepolis/issues/115.
