### ISSUE TITLE
پیشنهاد

### ISSUE THREAD

**Issue by ghost** [persepolisdm/persepolis#65]
**سلام
لطفا گزارش گیری هم اضافه نمایید
قابلیت تغییر اندازه آیکون در سیستم تری هم ایجاد نمایید همانند استارکلندر عالی میشه**

**Comment by alireza-amirsamimi** [comment]
سلام
آیکن برنامه 
svg
هست و از لحاظ اندازه نباید برای شما مشکلی ایجاد کنه
شما مشکلی دارید باهاش
توزیع و میزکارتون چی هست؟

**Comment by ghost** [comment]
salam
ubuntu 16.04
gnome flashback

**Comment by Alirezaies** [comment]
مشکلتون با آیکون چی هست؟

**Comment by alireza-amirsamimi** [comment]
آیکن برنامه در این مسیر وجود داره
`/usr/share/pixmaps/persepolis.svg`

و فرمتش هم 
svg
هست و اصولا نباید برای شما مشکلی ایجاد کنه
اگر دیدید مشکلی وجود داره فایل آکن رو با گیمپ باز کنید و به سایز دلخواهتون با فرمت
png
تبدیل کنید و آیکن فعلی رو پاک کنید و آیکن خودتون رو جایگزین کنید

**Comment by ghost** [comment]
![persepolis_icon](https://cloud.githubusercontent.com/assets/14041666/20597835/352ffd20-b25b-11e6-90bd-9f3f41cb8650.jpg)
می خوام سایز رو کوچک کنم مثلا ۲۴×۲۴ در برنامه اعمال نمیشه 
**به فرمت 
png
تبدیل کردم نشد به فرمت
svg
هم تغییر سایز دادم کوچک کردم باز نشد
در هر دو حالت 
tmp
رو خالی کردم لوگ آوت کردم نشد
**

**Comment by alireza-amirsamimi** [comment]
برنامه از همون فایلی که گفتم استفاده میکنه
اگر اعمال نمیشه احتمالا مشکل از میزکار هست چون با 
xfce , unity , gnome , ....
مشکلی وجود نداره و البته چون فرمت آیکن
svg
هست اصولا نباید مشکل سایز وجود داشته باشه

من این مشکل رو باز میذارم و ببینم میشه کاریش کرد که درست بشه یا نه
ممنونم از اینکه اطلاع دادید :)

**Comment by ghost** [comment]
خواهش می کنم

**Comment by ghost** [comment]
![perspolis-icon2](https://cloud.githubusercontent.com/assets/14041666/20702638/dfa72230-b62d-11e6-9da5-7f77e516f9da.jpg)
آیکون رو کپی کردم به فولدر آیکون سیستم که استفاده می کنم
matefaenza
چون من فقط از آیکون مت استفاده می کنم نه میزکار مت گفتم شاید مشکل از
نصب آیکون باشه آیکون رو به
default 
تغییر دادم دیدم باز مشکل هست تنها راه کپی کردن در پوشه آیکون هاست
/usr/share/icons/.../apps/سایز مورد نظر
اینطوری حل میشه

**Comment by alireza-amirsamimi** [comment]
پس مشکل حل شد :)
