### ISSUE TITLE
crash in log widow

### ISSUE THREAD

**Issue by ahmadrezash** [persepolisdm/persepolis#651]
**System Details:**
* Operating System: Linux
* Distro(For GNU/Linux and BSD users): Fedora
* Desktop Environment(For GNU/Linux and BSD users): KDE
* Persepolis Version: 3.1.0
* How do you install Persepolis? (Repositories, source, ...)

* _Please attach log files if crash or paste error message_
 
When I click on Help> Show Log File and after close this widow it is crashed.
log is:

 ```
 File "/usr/lib/python3.7/site-packages/persepolis/scripts/download.py", line 264, in downloadAria

    answer = server.aria2.addUri([link], aria_dict)

  File "/usr/lib64/python3.7/xmlrpc/client.py", line 1112, in __call__

    return self.__send(self.__name, args)

  File "/usr/lib64/python3.7/xmlrpc/client.py", line 1452, in __request

    verbose=self.__verbose

  File "/usr/lib64/python3.7/xmlrpc/client.py", line 1154, in request

    return self.single_request(host, handler, request_body, verbose)

  File "/usr/lib64/python3.7/xmlrpc/client.py", line 1170, in single_request

    return self.parse_response(resp)

  File "/usr/lib64/python3.7/xmlrpc/client.py", line 1342, in parse_response

    return u.close()

  File "/usr/lib64/python3.7/xmlrpc/client.py", line 656, in close

    raise Fault(**self._stack[0])

xmlrpc.client.Fault: <Fault 1: 'No URI to download.'>

```

**Comment by alireza-amirsamimi** [comment]
@ahmadrezash Hi
When was crash occurred? When you closed log window?

**Comment by ahmadrezash** [comment]
Hi
At first, I click Esc key and after that click on the close button, after many seconds it's crashed and shows python error log.

**Comment by alireza-amirsamimi** [comment]
@ahmadrezash Can you record a video from this situation, please?
It helps me to understand the problem better. It's a little weird.

**Comment by ahmadrezash** [comment]
Now, I can't open persepolis anyway :(

**Comment by alireza-amirsamimi** [comment]
Run this commands please.
```
persepolis --clear
persepolis --default
```

**Comment by alireza-amirsamimi** [comment]
"<Fault 1: 'No URI to download.'>" bug is fixed. thanks for reporting. :+1:
