### ISSUE TITLE
Persepolis icon is incorrect on KDE Plasma Wayland session

### ISSUE THREAD

**Issue by glaubersm** [persepolisdm/persepolis#658]
**System Details:**
* Operating System: Linux
* Distro(For GNU/Linux and BSD users): Arch Linux
* Desktop Environment(For GNU/Linux and BSD users): KDE Plasma 5.16.3 (Wayland session)
* Persepolis Version: persepolis-git
* How do you install Persepolis? AUR

* _Please attach log files if crash or paste error message_

**Issue Description and steps to reproduce:**
We can see a Wayland generic icon in the title bar and when we press alt+tab.
Maybe this link can help you
https://community.kde.org/Guidelines_and_HOWTOs/Wayland_Porting_Notes#Application_Icon

Steps:
1. start KDE Plasma Wayland session
2. open persepolis

#### Please report only one Issue (Bug or feature request or ...) in one issue! and open new Issue for another one :)

![persepolis](https://user-images.githubusercontent.com/15967631/61578469-c87a8100-aacd-11e9-8b2c-5a7fea897252.png)

**Comment by alireza-amirsamimi** [comment]
Thanks  for reporting :+1:

**Comment by alireza-amirsamimi** [comment]
We fixed this bug. Thanks for reporting.

**Comment by glaubersm** [comment]
Hello
I have just updated to version 4.0.1 on Arch Linux and can confirm that this bug is now fixed. :)
Thank you very much, have a nice day.
