### ISSUE TITLE
عدم نمایش پنجره دانلود به صورت پیشفرض

### ISSUE THREAD

**Issue by Mr-undead** [persepolisdm/persepolis#66]
سلام
ایا امکان داره یه گزینه در برنامه گنجانده بشه که کاربر توسط اون نمایش پنجره  شروع دانلود که ظاهر میشه را غیرفعال کرد و دانلود فقط در پنجره اصلی نمایش داده بشه

**Comment by alireza-amirsamimi** [comment]
چشم
انشالله به تنظیمات اضافه میکنم
هر چند اون پنجره رو دوستش دارم و میخوام باشه :)

**Comment by alireza-amirsamimi** [comment]
سلام
پیشنهاد شما به ورژن جدید اضافه شد
میتونید از تنظیمات برنامه نمایش این پنجره رو غیر فعال کنید
