### ISSUE TITLE
How do i update youtube-dl on Windows version?

### ISSUE THREAD

**Issue by Nirose** [persepolisdm/persepolis#660]
**System Details:**
* Operating System: Windows 10 1809
* Persepolis Version: 3.1.0
* How did you install Persepolis? (Repositories, source, ...): Github release

* _Please attach log files if crash or paste error message_
`
ERROR: UT-mA673hLs: "token" parameter not in video info for unknown reason; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type youtube-dl -U to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
`
![Error Screenshot](https://i.imgur.com/0ex090l.png)
**Issue Description and steps to reproduce:**
Open up VIdeo finder.
Paste a youtube link
Press on "Fetch Media List"

**Comment by mostafaasadi** [comment]
Hi
thank you for reporting
this problem occur because of the old version of ffmpeg in last release of "persepolis" windows installer
we going to release new version in the near future
until then, I pack updated installer from master branch exclusively for you
please just say me what is architecture of your system, 64 or 32 bit?

**Comment by Nirose** [comment]
64 bit. Thank you very much.

Sent from ProtonMail mobile

-------- Original Message --------

**Comment by mostafaasadi** [comment]
Hi 
this is updated persepolis windows installer (64) from master branch (3.1.0.1)
https://mega.nz/#!u3JxWArT!fXJxzWh3qco2CPCKeMEukd4JuYJi7Vw9u2qciQMQuNQ

**Comment by Nirose** [comment]
Hi, thanks!

It installed flawlessly and found the media links but aborts download instantaneously. The link it grabbed is a correct one as i can copy it from the item properties and paste it in the browser and download it from there. other downloads work fine.

Here's a video i recorded of the failure.
https://i.imgur.com/mf94IgY.gifv

**Comment by alireza-amirsamimi** [comment]
Can you attach log window content please?
Help > Show log file

**Comment by Nirose** [comment]
I cleared the log file and started the video download process again and this is the log
```
Log File:
2019-07-25 08:48:18,483 - Persepolis Download Manager - ERROR - Spider couldn't find file name

2019-07-25 08:48:18,483 - Persepolis Download Manager - ERROR - Spider couldn't find file size

2019-07-25 08:48:37,837 - Persepolis Download Manager - INFO - 2c7a9fdc460c6622 Starts

2019-07-25 08:48:38,525 - Persepolis Download Manager - ERROR - Download failed - GID : 2c7a9fdc460c6622/nMessage : Download aborted.
```

**Comment by alireza-amirsamimi** [comment]
We released new version. Please update persepolis to 3.2.0

**Comment by candrapersada** [comment]
add menu update or change youtube-dl default path.
