### ISSUE TITLE
مشکل در ورود پسورد و کلوز کردن پنجره اصلی

### ISSUE THREAD

**Issue by mrostd** [persepolisdm/persepolis#662]
**System Details:**
* GNU/Linux
* Ubuntu 19.04 & Ubuntu 16.04 LTS
* Desktop: Gnome
* Persepolis version: 3.1.0
سلام
نسخه لینوکسی پرسپولیس(اوبونتو 16.04 و 19.04) بنظر یه سری باگ آزار دهنده داره:
1- وقتی تو پنجره دانلودینگ و از سربرگ دانلود آپشنز تیک گزینه افتر دانلودز رو میزنیم و شات داون رو اپلای میکنیم درخواست پسورد روت میده، اما با اینکه پسورد درستو میزنیم خطای اشتباه بودن پسورد رو میده
2- وقتی هم پنجره دانلودینگ بازه و هم پنجره اصلی پرسپولیس دانلود منیجر، با بستن پنجره اصلی ، پنجره دانلودینگ هم بسته میشه و کلا برنامه متوقف میشه رسما
در صورتی که باید پنجره دانلودینگ باز بمونه یا حد اقل تو پس زمینه اجرا بشه.

**Comment by alireza-amirsamimi** [comment]
@mrostd Hello
Please use English language here.
Thanks for reporting😊
I was fixed this two bug before but we don't release it yet.
In next version you will not see this bugs.

**Comment by mrostd** [comment]
> @mrostd Hello
> Please use English language here.
> Thanks for reporting
> I was fixed this two bug before but we don't release it yet.
> In next version you will not see this bugs.

Thanks for support.
