### ISSUE TITLE
A minor problem with deb based repositories.

### ISSUE THREAD

**Issue by ghost** [persepolisdm/persepolis#666]
**System Details:**
* Operating System: Linux
* Distro(For GNU/Linux and BSD users): Debian 10 buster
* Desktop Environment(For GNU/Linux and BSD users): KDE 5.54.0 / Plasma 5.14.5
* Persepolis Version: v3.0.1
* How do you install Persepolis? From Ubuntu/Debian Repositories.

* _Please attach log files if crash or paste error message_
Err http://ppa.launchpad.net/persepolis/ppa/ubuntu eoan Release                                                                           
  404  Not Found [IP: 91.189.95.83 80]
E: The repository 'http://ppa.launchpad.net/persepolis/ppa/ubuntu eoan Release' does not have a Release file.                             
E: Failed to download some files                                                                                                          
W: Failed to fetch http://ppa.launchpad.net/persepolis/ppa/ubuntu/dists/eoan/Release: 404  Not Found [IP: 91.189.95.83 80]                
E: Some index files failed to download. They have been ignored, or old ones used instead.

**Issue Description and steps to reproduce:**
Just running an update on Debian 10 buster will produce this error.

I'am aware that this problem can be fixed easily by the user. But just wanted to share it with you.
Seems that repositories need some new configurations.
Best regards :)

**Comment by mostafaasadi** [comment]
Hi
thank you for reporting
you should follow [this instruction](https://github.com/persepolisdm/persepolis/wiki/debian-installation-instruction) for debian based distro
https://github.com/persepolisdm/persepolis/wiki/debian-installation-instruction
