### ISSUE TITLE
How to download ”ed2k“ and "magnet" files

### ISSUE THREAD

**Issue by derryck404** [persepolisdm/persepolis#669]
**System Details:**
* Operating System: Win10 1903
* Persepolis Version: 3.1.0

**Issue Description and steps to reproduce:**
    I copy an "ed2k" link into the PDM but it doesn't work and it shows "error", then I copy a "magnet" link and it didn't download anything at all.  
    I'd like to know how to download ”ed2k“ and "magnet" files. Does Persepolis support to download  ”ed2k“ and "magnet" files now?

**Comment by alireza-amirsamimi** [comment]
Hello
Persepolis can not download torrent :)

**Comment by derryck404** [comment]
> Hello
> Persepolis can not download torrent :)

Oh,😱I am looking forward to that function. Thanks anyway.

**Comment by alireza-amirsamimi** [comment]
:)
Some one asked this feature request [here](https://github.com/persepolisdm/persepolis/issues/293). and I added "feature request" tag for it.
I hope that I adds this feature in future :)
