### ISSUE TITLE
Crashed on Ubuntu 19.04

### ISSUE THREAD

**Issue by mvahedii** [persepolisdm/persepolis#670]
**System Details:**
* Operating System: ? Linux
* Distro(For GNU/Linux and BSD users): ? Ubuntu 19.04
* Desktop Environment(For GNU/Linux and BSD users): ? GNOME
* Persepolis Version: ? Latest Version
* How do you install Persepolis? (Repositories, source, ...) Repo

This App Crashed on Ubuntu 19.04

**Comment by mvahedii** [comment]
![Crash_Message](https://user-images.githubusercontent.com/43504442/62821510-4ee52880-bb8b-11e9-9922-fa748de328f6.png)
That was crashed every 1 hour !! :(

**Comment by alireza-amirsamimi** [comment]
Hello
Please expand traceback part of crash report😊
Please run persepolis from terminal and take a screenshot from error message.
Thank you.

**Comment by mvahedii** [comment]
Oh...! Sorry
Hi dear Alireza and thankyou for your useful app :heart: 
This app was not crash when i ran it from terminal.
but a few minutes later that message ( in above screen shot ) shown to me.

**Comment by alireza-amirsamimi** [comment]
@Mvahedii 🌹🌹🌹🌹🌹
Please do a favor for me.
Please run persepolis from terminal every time. When it's crashed, put the error message here. Perhaps it's a bug.
Thank you very much.
