### ISSUE TITLE
پیشنهاد برای نمایش سرعت دقیق

### ISSUE THREAD

**Issue by Mahdiali313** [persepolisdm/persepolis#671]
سلام 
کاشکی نرمافزار سرعت دقیق دانلود رو میزاشت.کلا نرمافزار سرعت بالای ۱ مگ رو مثلا اگر ۱.۵ مگ باشه ۱ مگ نشون میده

**Comment by alireza-amirsamimi** [comment]
Hello
Please use English language here.
Thanks for your feature request.

**Comment by alireza-amirsamimi** [comment]
Hello
I added your feature request :)
Thanks for your feature request.

![image](https://user-images.githubusercontent.com/7452500/63119167-b7317100-bfb4-11e9-9e80-d5053eeefe04.png)
