### ISSUE TITLE
[feature request] X button should just hide app in sys tray against closing whole app

### ISSUE THREAD

**Issue by FadeMind** [persepolisdm/persepolis#672]
**System Details:**
* OS: Manjaro Linux (KDE)
* Persepolis Version: 3.1.0
* How do you install Persepolis? AUR

Please implement behaviour - X button DO NOT terminate main app and just hidding main app window in system tray. Notice, same behaviour happen when you click on any extra app window like settings. 

Regards

**Comment by alireza-amirsamimi** [comment]
Hello
I added this feature a few days ago. If you are archlinux user, install `persepolis-git` from aur. Make sure this option is activated in setting window.

**Comment by FadeMind** [comment]
@alireza-amirsamimi yep, git snapshot works like a charm :wink:  Thanks.
