### ISSUE TITLE
[feature request] Please merge polish language translation

### ISSUE THREAD

**Issue by FadeMind** [persepolisdm/persepolis#673]
Polish language translation is mostly finished (only few common dialogs left). Please merge pl_PL polish language translation. Thanks.

**Comment by LuxF3rre** [comment]
Finished translating it.

**Comment by alireza-amirsamimi** [comment]
Thank you very much :)
I'll add Polish language as soon as possible.

**Comment by alireza-amirsamimi** [comment]
I added "polski" and "nederlands" in this [commit](https://github.com/persepolisdm/persepolis/commit/c3a71732205c0a1db7993a3957035d948c44f7e7).
Thanks for your contribution :)
![image](https://user-images.githubusercontent.com/7452500/63004843-8a843900-be90-11e9-9692-f2a1d8d6d797.png)
