### ISSUE TITLE
import from text file وارد کردن لینک دانلود از فایل متنی

### ISSUE THREAD

**Issue by ghost** [persepolisdm/persepolis#68]
openfile
هم غیر فعاله منظورم لینک ها رو بریزیم تو فایل متنی بعد اون فایل رو بدیم به برنامه
اگه یه فایلی به چند قسمت جدا شده باشه برا راحتی دانلود ما باید لینک هر قسمت رو کپی کنیم
در برنامه قرار بدیم اما تو فایل بریزیم فایل رو بدیم به برنامه خیلی بهتره البته در ورژن
قبلی گویا فعال بود نمی دونم یا من مشکل دارم؟ سپاس

**Comment by alireza-amirsamimi** [comment]
سلام
توی ورژن یک بود ولی هنوز توی ورژن ۲ اضافه نشده ولی انشالله حتما در ورژن ۲.۳ که به زودی منتشر میشه این قابلیت رو میبینید :)

**Comment by alireza-amirsamimi** [comment]
سلام
پیشنهاد شما به ورژن جدید اضافه شد
کافی هست که از منوی فایل گزینه
import links from text file
رو انتخاب کنید.و دقت کنید در هر خط فقط یک لینک قرار بدید
