### ISSUE TITLE
Failed to execute script Persepolis Download Manager - 21.08.2019

### ISSUE THREAD

**Issue by gamgamstylep** [persepolisdm/persepolis#680]
still the same error with chrome and firefox (windows) 

![2019-08-21 08_45_15-Window](https://user-images.githubusercontent.com/43586166/63408797-1eee1e80-c3f0-11e9-9de2-b22e7e1184c0.png)
![2019-08-21 08_45_48-Window](https://user-images.githubusercontent.com/43586166/63408803-21507880-c3f0-11e9-938e-478f59a9dae7.png)

Windows 10 (18.03)
Persepolis Download Manager 3.1.0 (64bit)
Google Chrome Version 76.0.3809.100 (Offizieller Build) (64-Bit) + Persepolis Download Manager Integration 2.2.0
Firefox 68.0.2 (64-Bit) + Persepolis Download Manager Integration 2.2.0

_Originally posted by @gamgamstylep in https://github.com/persepolisdm/persepolis/issues/342#issuecomment-523320996_

**Comment by alireza-amirsamimi** [comment]
Hello
We released new version. Please update persepolis to 3.2.0 .
