### ISSUE TITLE
Typo in wiki

### ISSUE THREAD

**Issue by simonporte** [persepolisdm/persepolis#682]
Hello,
Persepolis is mispelled in wiki.
On this page : [https://github.com/persepolisdm/persepolis/wiki/translators-guide](https://github.com/persepolisdm/persepolis/wiki/translators-guide)

![image](https://user-images.githubusercontent.com/32496803/63643450-a24d8f80-c6d0-11e9-96f3-cde87e6b9083.png)

**Comment by alireza-amirsamimi** [comment]
Corrected :) 
Thank you.
