### ISSUE TITLE
Shut down after download completes

### ISSUE THREAD

**Issue by fabianski7** [persepolisdm/persepolis#684]
Any plans to add this function soon?

**Comment by alireza-amirsamimi** [comment]
Hello
For single download:
Start download progress. 
Click on "more options" tab in progress window.
You can find shutdown option in this tab.

For download queue, please visit this [link](https://github.com/persepolisdm/persepolis/wiki/How-to-create-queue).

**Comment by fabianski7** [comment]
So it stays in the progress window, well, I usually closed it after starting the download, now I can see this option. 
Thanks!
