### ISSUE TITLE
  rtcwakeup مشکل

### ISSUE THREAD

**Issue by ghost** [persepolisdm/persepolis#69]
**سلام 
همانگونه که میدونید با بستن برنامه یا خاموش کردن سیستم صف دانلود متوقف می شود
من با اسکریپتی سیستم رو در ساعت معین اتوماتیک روشن می کنم دراین حالت سیستم هایبرنت یا
ساسپند می شود پس باید دانلودر پرسپولیس کار کند اما دو روزه بعد از ساسپند هم صف
دانلود متوقف می شود**

**Comment by alireza-amirsamimi** [comment]
سلام
مشکل رو بررسی میکنم 
:)

**Comment by Mr-undead** [comment]
مگه برنامه قابلیت صف داره؟

**Comment by ghost** [comment]
منظور
schedule 
هست

**Comment by ghost** [comment]
**سپاس این قابلیت در نسخه ۲.۴.۲ گنجانده شده**🌹🙏
