### ISSUE TITLE
Will there be a 32-bit version?

### ISSUE THREAD

**Issue by mrkaban** [persepolisdm/persepolis#690]
Hello! Will there be a 32-bit version?

The program has been added to my website (link). I’m wondering if it’s worth removing the link to the 32-bit version. In fact, it’s popular.

**Comment by alireza-amirsamimi** [comment]
Hello
We have some issues with 32 bit system for building Persepolis. We are trying to solve problems. We'll upload 32 bit package soon :)

**Comment by mostafaasadi** [comment]
Hello
we released 32 bit version and you can download it from [release page](https://github.com/persepolisdm/persepolis/releases/tag/3.2.0)
