### ISSUE TITLE
Default style not compatible with system Qt5 style

### ISSUE THREAD

**Issue by ilius** [persepolisdm/persepolis#691]
**System Details:**
* Operating System: GNU/Linux
* Distro(For GNU/Linux and BSD users): Debian GNU/Linux bullseye/sid
* Desktop Environment(For GNU/Linux and BSD users): LXDE
* Persepolis Version: 3.2.0
* How do you install Persepolis? `git glone ...` and `sudo python3 setup.py install`

**Issue Description and steps to reproduce:**
As you can see in the screenshot, the Qt5 theme is changed with "qt5ct" tool (Qt5 Configuration Tool), to a dark theme, and it's already applied on "qt5ct" itself, as well as Okular. But not applied for Persepolis.
![persepolis-qt5ct-okular](https://user-images.githubusercontent.com/197648/65084014-4fa97f80-d9bf-11e9-8eb4-bf4d6b674691.png)

And this is the environment variable that is set for the theme:
`QT_QPA_PLATFORMTHEME=qt5ct`

These are the versions I'm using:

```
$ python3 --version
Python 3.7.4+

$ apt show python3-pyqt5 | grep Version
Version: 5.12.3+dfsg-2

$ apt show libqt5gui5 | grep Version
Version: 5.11.3+dfsg1-4
```

**Comment by ilius** [comment]
Also installed deb package (`persepolis_3.2.0.0_all.deb`), looks exactly the same.

**Comment by alireza-amirsamimi** [comment]
Hello :-)
Unfortunately persepolis doesn't use system's fusion style. LXDE is GTK+ DE.
So I suggest you to install adwaita-qt and select adwaita style from preferences window.
Check out [this link](https://github.com/persepolisdm/persepolis/wiki/How-to-change-Persepolis-theme) for more information.

**Comment by ilius** [comment]
Hi
I didn't know I have to change the style form Preferences.
It works now (Adwaita-Dark, Fusion and qt5ct-style are all listed BTW).

Also, I changed the Style to "System", and it still works (it has dark theme)

Then I removed `~/.config/persepolis_download_manager`, and it's broken again.
And the Style is changed to Adwaita. I changed it to "System" again and it's fixed.

**I think "System" style should be the default.**
It should be compatible with desktop by default.
Don't you agree?

**Comment by alireza-amirsamimi** [comment]
@ilius Persepolis uses QSettings for saving user's configuration.
In Linux QSettings creates a .conf file in this path:


~/. config/persepolis_download_manager/persepolis.conf

**Comment by ilius** [comment]
Yes, that's alright.

The only thing that remains is this:
I think "System" style should be the default.

**Comment by alireza-amirsamimi** [comment]
Unfortunately system style is very ugly in some operating systems.

**Comment by ilius** [comment]
You mean Windows?
At least you can set a different default value for Linux.

**Comment by alireza-amirsamimi** [comment]
@ilius No
On Windows and Mac and some of desktop environment on some of linux and BSD distributions, system's style is really ugly!

**Comment by ilius** [comment]
What do you mean ugly?
Ugly in terms of appearance or in terms of code?
Most Qt5 applications don't even support customizing the style, and they use the system/desktop style on all Linux distributions. How do they work then?

**Comment by alireza-amirsamimi** [comment]
See this screenshot. For example in Macintosh and ... system's style is similar to Windows 98

![screenshot](https://user-images.githubusercontent.com/1978735/55720128-4f22bb00-5a15-11e9-9197-215a29c5e557.png)

**Comment by ilius** [comment]
I'm not a Qt expert. But ideally we should check if the system has any previous Qt style and configuration. If does not, it means Qt is not system's native, so you can choose your own style.
But on Linux, you are not supposed to do that. Ugly or pretty, that's up to user to decide, because Qt is one of the native GUI libraries in Linux.
Although I Windows, Qt applications look like native windows apps, not sure what is not that the case for Mac.

**Comment by alireza-amirsamimi** [comment]
@ilius I'll try to fix it :-)

**Comment by ilius** [comment]
I have some Linux distros in VM, so I can help testing it.
