### ISSUE TITLE
Close dialogs with Escape key

### ISSUE THREAD

**Issue by ilius** [persepolisdm/persepolis#692]
**System Details:**
* Operating System: GNU/Linux
* Distro(For GNU/Linux and BSD users): Debian GNU/Linux bullseye/sid
* Desktop Environment(For GNU/Linux and BSD users): LXDE
* Persepolis Version: 3.2.0
* How do you install Persepolis? deb package

**Issue Description and steps to reproduce:**
It's a common and standard behavior to close all dialogs (and the main window if there is a tray icon) by pressing Escape.

This applies to:
- Main window
- Add New Download Link
- Preferences (should Cancel on Escape)
- Video Finder
- About

**Comment by alireza-amirsamimi** [comment]
@ilius I'm agree with you.
I'll try to fix it :-)

**Comment by alireza-amirsamimi** [comment]
I fixed this bug. Thanks for reporting :+1:
