### ISSUE TITLE
Persepolis has problem with ffmpeg dependency 

### ISSUE THREAD

**Issue by imanmoghimiq30** [persepolisdm/persepolis#694]
**System Details:**
* Operating System: Ubuntu 
* Distro(For GNU/Linux and BSD users): 19.04 (Disco Dingo)
* Desktop Environment(For GNU/Linux and BSD users): gnome
* Persepolis Version: last
* How do you install Persepolis? follow your manual on Github. Add PPA>update>install
Persepolis PPA add and update repo without problem but when I tried to install gave me an error and said something about FFmpeg. I remove Persepolis PPA from the repo and tried again. amazingly it installed.
![Screenshot from 2019-09-18 10-51-59](https://user-images.githubusercontent.com/33248902/65123633-ea7a7c00-da08-11e9-9ae2-9a3156a00f16.png)
![Screenshot from 2019-09-18 11-03-00](https://user-images.githubusercontent.com/33248902/65123637-ed756c80-da08-11e9-914e-f141356e49b3.png)

* _Please attach log files if crash or paste error message_

**Issue Description and steps to reproduce:**

**Comment by mostafaasadi** [comment]
Hi 
thank you for your reporting :rose: 
I confirm it is a package problem with ffmpeg package version in some distro 
we update package as soon as we can

**Comment by mostafaasadi** [comment]
Hi
we updated packages ✌🏻
upgrade and enjoy

**Comment by imanmoghimiq30** [comment]
TNX @mostafaasadi for fast reaction and your good app. I using Persepolis for while. And waiting for mobile versions
