### ISSUE TITLE
Is there any plan to port for qt/c++ version for performance sake?

### ISSUE THREAD

**Issue by jkmpariab** [persepolisdm/persepolis#698]
**System Details:**
* Operating System: ?
* Distro(For GNU/Linux and BSD users): ?
* Desktop Environment(For GNU/Linux and BSD users): ?
* Persepolis Version: ?
* How do you install Persepolis? (Repositories, source, ...)

* _Please attach log files if crash or paste error message_

**Issue Description and steps to reproduce:**

**Comment by alireza-amirsamimi** [comment]
Hello
Thanks for asking.
No, We continue to develop persepolis with PyQt5.
