### ISSUE TITLE
ایجاد دسته بندی

### ISSUE THREAD

**Issue by Mr-undead** [persepolisdm/persepolis#7]
برای مدیریت هرچه بهتر موارد دانلودی بهتر نیست دسته بندی بر اساس وضعیت دانلود 
اتمام یافته و نیمه کاره 
و ساخت دسته بندی بر اساس نوع فایلها همان دسته بندی در دایرکتوری هایی که برنامه در محل ذخیره فایل ها میسازد انجام پذیرد

**Comment by alireza-amirsamimi** [comment]
قسمت دوم حرفت رو متوجه نشدم بهروز جان
منظورت از قسمت اول اینه که دانلود ها توی لیست بر اساس وضعیت 
sort
بشن؟

**Comment by Mr-undead** [comment]
قسمت دوم ایجاد دسته بندی بر اساس گروه های زیر است 
`Audios  Compressed  Documents  Others  Videos`
قسمت اول هم
سه تا وضعیت داشته باشیم 
اتمام یافته 
در حال دانلود
متوقف شده
یه همچین چیزی

**Comment by alireza-amirsamimi** [comment]
فعلا برنامه پیش بره و مشکلاتش حل بشه بعد انشالله یه کاریش میکنم :)
