### ISSUE TITLE
[Wiki]: fix typo

### ISSUE THREAD

**Issue by amiremohamadi** [persepolisdm/persepolis#700]
"module" is misspelled on this page: [git-installation-instruction](https://github.com/persepolisdm/persepolis/wiki/git-installation-instruction)

![Screenshot](https://user-images.githubusercontent.com/31338382/65310583-e2a30f00-dba3-11e9-9aa3-60ef0562316e.png)

I have fixed this in wiki at [git-installation-instruction (fix typo)](https://github.com/amiremohamadi/persepolis/wiki/git-installation-instruction#in-some-old-distributionsubuntu-1604-youtube-dl-is-installed-as-python2-module-but-persepolis-need-youtube_dl-as-python3-module-if-you-get-error-for-youtube-dl-module-you-must-install-youtube-dl-with-pip3)

[Help](https://gist.github.com/larrybotha/10650410)

**Comment by alireza-amirsamimi** [comment]
Thanks for reporting. Wiki is corrected :+1:
