### ISSUE TITLE
Tabular layout must adapt to the long filenames and hence, increase the height of elements

### ISSUE THREAD

**Issue by mazharz** [persepolisdm/persepolis#701]
**System Details:**
* Operating System: GNU/Linux
* Distro(For GNU/Linux and BSD users): Ubuntu 19.04
* Desktop Environment(For GNU/Linux and BSD users): Gnome
* Persepolis Version: 3.2.0
* How do you install Persepolis? provided ppa

* _Please attach log files if crash or paste error message_

**Issue Description and steps to reproduce:**
Downloading files with extreme long names causes the main layout to look bizarre due to the name occupying more than one line. To better clarify what i mean, down below is an image of this issue:
[Image of the issue](https://ibb.co/MPLdrhw)
As you can see the first two items take up two lines each, but the last line does not because it's too long! When increasing the field width, the last line becomes like those above as well (due to personal reasons i can't prevent obscuring the content names).

**Comment by alireza-amirsamimi** [comment]
I fixed this bug. Thanks for reporting:+1:
