### ISSUE TITLE
"Download with persepolis" button does not work on firefox

### ISSUE THREAD

**Issue by ghost** [persepolisdm/persepolis#709]
**System Details:**
* Operating System: GNU/Linux
* Distro: Arch Linux
* Desktop Environment: Xfce
* Persepolis Version: git 3.2.0.r4.gc8f2a07-1
* How do you install Persepolis? AUR

**Issue Description and steps to reproduce:**

"Download with persepolis" or any other button does not work on firefox
same thing on both 3.2.0-3 and 3.2.0.r4.gc8f2a07-1

**Comment by alireza-amirsamimi** [comment]
Hello
Please attach log file.
You can access the log window from,: help >> log window
