### ISSUE TITLE
Perspolis crashed when I select all item in list.

### ISSUE THREAD

**Issue by YasinEnigma** [persepolisdm/persepolis#710]
**System Details:**
* Operating System: GNU/Linux
* Distro(For GNU/Linux and BSD users): ubuntu 18.04
* Desktop Environment(For GNU/Linux and BSD users): Gnome
* Persepolis Version: 3.1.0
* How do you install Persepolis? Repositories

* _Please attach log files if crash or paste error message_

**Issue Description and steps to reproduce:**

**Comment by alireza-amirsamimi** [comment]
@YasinEnigma Hello
Please update persepolis to 3.2.0
You are using old version.
