### ISSUE TITLE
bb10dark Theme bug

### ISSUE THREAD

**Issue by sobuj53** [persepolisdm/persepolis#715]
**System Details:**
* Operating System: Linux mint 19.2 Tina
* Distro(For GNU/Linux and BSD users): Ubuntu 18.04 LTS
* Desktop Environment(For GNU/Linux and BSD users): Cinnamon
* Persepolis Version: 3.2.0
* How do you install Persepolis: repository ppa:persepolis/ppa

* _Please attach log files if crash or paste error message_
I've tried to change my current theme to bb10dark and it resulted in mess that I can't repair. The window is not resizing that's why I can't press the ok button (Please refer to attached screenshot file).
![Screenshot](https://user-images.githubusercontent.com/25761237/66344751-67e23e00-e970-11e9-8087-d54b5b6265f3.png)

I also completely uninstalled it and reinstalled persepolis again but somehow the theme preference was saved in somewhere so it picked up the problematic theme automatically.
 
Please advice me how I can reset or completely uninstall persepolis so that it won't left any trances of previous installation.

**Issue Description and steps to reproduce:**

**Comment by alireza-amirsamimi** [comment]
Hello
The problem is related to bb10dark style and It's related to bb10dark's developers.
Please reset Persepolis with this command and please use another style. bb10dark is broken.

`persepolis --clear`

**Comment by alireza-amirsamimi** [comment]
I added "bb10dark" and "bb10bright" to the styles black list. So they will not appear in style comboBox.

**Comment by sobuj53** [comment]
Thank you very much for the help. `persepolis --clear` did the job

**Comment by pri-pro** [comment]
persepolis --clear did not work for me. I still can't change color scheme.

**Comment by alireza-amirsamimi** [comment]
Try
`persepolis --default`
