### ISSUE TITLE
Error when resuming downloads

### ISSUE THREAD

**Issue by TiredMir** [persepolisdm/persepolis#73]
هنگام ادامه(Resume) دانلودها با خطا مواجه میشم.
 اما وقتی فایل های مربوطه رو از `.persepolis` به جای دیگه کپی میکنم، دانلود رو از پرسپولیس حذف میکنم و دوباره فایلها رو توی `.persepolis` میریزم، بعد از اضافه کردن مجدد لینک دانلود، بارگذاری از همون جایی که قطع شده بود ادامه پیدا میکنه.

**Comment by alireza-amirsamimi** [comment]
سلام:)
توزیعتون و میزکارتون چی هست؟

**Comment by TiredMir** [comment]
سلام. اوبونتو ۱۶.۱۰ یونیتی

**Comment by mostafaasadi** [comment]
سلام 
من اوبونتو ۱۶.۱۰ دارم و همچین مشکلی ندارم 
میشه بگید به چه روشی پرسپولیس رو نصب کردید ؟

**Comment by alireza-amirsamimi** [comment]
@mostafaasadi 
احتمالا کاری به شیوه نصبشون نداره

@Schwarzer-Schwan 
از چند نفر پرسیدم این مشکل رو نداشتند . البته اگر مشکلی باشه توی این زمینه مربوط به آریا ۲ هست
ولی برای تست لطفا توزیع اوبونتو رو دانلود کنید ببین مشکل پا برجاست؟
https://www.ubuntu.com/download/desktop

**Comment by Alirezaies** [comment]
سعی کردید دوباره نصب کنید یا روی نسخه 16.04 امتحان کنید؟

**Comment by TiredMir** [comment]
توزیعم اوبونتو 16.10 هست.
از مخزن نصب کردم و اینکه در رابطه با سایت tinyz.in بود.
روی 16.04 هم امتحان میکنم خبر میدم.

**Comment by alireza-amirsamimi** [comment]
این قضیه دلایل مختلفی میتونه داشته باشه
یکی از دلایل میتونه این باشه که دفعه اول لینک رو با فلش گات گرفته باشید و 
cookie
و ...
داشته باشه و منقضی شده باشه و برای همین نتونید دانلود کنید
اینجور موقع ها تلاش کنید لینک دانلود رو به تنهایی و بدون فلش گات به پرسپولیس بدید (البته اگر از سایتهایی نباشه که نیاز به کوکی داشته باشند) ببینید آریا دوباره دانلود رو از سر میگیره یا نه
