### ISSUE TITLE
Brave Extenstion not working

### ISSUE THREAD

**Issue by proneon267** [persepolisdm/persepolis#738]
**System Details:**
* Operating System: GNU/Linux
* Distro(For GNU/Linux and BSD users): Fedora 31
* Desktop Environment(For GNU/Linux and BSD users): Gnome
* Persepolis Version: 3.2.0
* How do you install Persepolis?: Fedora Repositories

**Issue Description and steps to reproduce:**
I have installed the latest version of the extenstion on Brave(Chromium). But when I click on any download link, nothing happens(no start downloading dialog appears), even though the persepolisdm is running. Here is the current state of the extenstion: 
`Interrupt Downloads`: `On`
`Context Menu`: `On`
Am I doing something wrong here?

**Comment by JafarAkhondali** [comment]
Hey @proneon267 
No you are not, but support for Brave browser has been added recently in the code and not released yet. If you want you can make it work manually till we release new version of PDM.
https://github.com/persepolisdm/Persepolis-WebExtension/issues/25#issuecomment-532906450

**Comment by proneon267** [comment]
Ok. I'll be waiting for the new release. In the mean time I'll do it manually. Thanks!
