### ISSUE TITLE
Light Theme for persepolis on Linux

### ISSUE THREAD

**Issue by iGameChanger** [persepolisdm/persepolis#74]
Can you also make a light theme that will support the current desktop theme of Linux. Because the colours are too dark for me

**Comment by alireza-amirsamimi** [comment]
Hello
You can select light theme in prefrences
1 - from edit menu select prefrences
2- in appearance tab select "Fusion" for style and select "Persepolis light red" or "Persepolis light blue" for color scheme
3- restart persepolis :)
