### ISSUE TITLE
[Wiki Change Request]Scoop and Chocolatey installation method in wiki

### ISSUE THREAD

**Issue by Witchilich** [persepolisdm/persepolis#742]
https://github.com/persepolisdm/persepolis/wiki/Microsoft-Windows
Just like Homebrew for OS X, Windows users can also use Scoop
```
scoop bucket add extras
scoop install persepolis
```
https://github.com/lukesampson/scoop-extras/blob/master/bucket/persepolis.json
Or Chcolatey
`choco install persepolis`
There is no way to edit the wiki, so I am just suggesting it here.
https://chocolatey.org/packages/persepolis

**Comment by alireza-amirsamimi** [comment]
Hello
Thanks for reporting.
I fixed it :)
