### ISSUE TITLE
[Wiki Change Request] Add AppGet for windows

### ISSUE THREAD

**Issue by Witchilich** [persepolisdm/persepolis#747]
**System Details:**
* Operating System: Windows 10
* Distro(For GNU/Linux and BSD users): ?
* Desktop Environment(For GNU/Linux and BSD users): ?
* Persepolis Version: 3.2.0
* How do you install Persepolis? AppGet

* _Please attach log files if crash or paste error message_

**Issue Description and steps to reproduce:**
`appget install persepolis`
Appget is a new package manager that aims to get rid of Chocolatey's issues
https://medium.com/@keivan/appget-what-chocolatey-wasnt-61f2b658d95b
I went ahead and made a manifest for persepolis and created a pull request, which now got merged
https://github.com/appget/appget.packages/blob/master/manifests/persepolis/persepolis.yaml
https://appget.net/packages/i/persepolis

**Comment by alireza-amirsamimi** [comment]
Thank you very much :)
I edited the wiki :+1:
