### ISSUE TITLE
مشکل در دانلود

### ISSUE THREAD

**Issue by madani-hamid** [persepolisdm/persepolis#75]
سلام
با flash got
ویا کپی پیست کردن فرقی نداره
در هر دو حالت دانلود شروع میشه ولی رو صفر درصد باقی میمونه و جلو نمیره
بعد چند دقیقه هم خودش متوقف میشه
روز اولی که نصب کردم تونستم با پرسپولیس دانلود کنم ولی بعد از اون دیگه برام کار نکرد
ممنون

**Comment by madani-hamid** [comment]
مثلا این لینک به عنوان نمونه
http://www.gavazn.com/file/Mohsen-Namjoo-138-Sanamaa.mp3

**Comment by alireza-amirsamimi** [comment]
سلام
لینکی که دادید فیلتر هست
![filter](https://cloud.githubusercontent.com/assets/7452500/21113214/e4a53f3e-c0bd-11e6-81f4-407a639c3b8f.png)

**Comment by alireza-amirsamimi** [comment]
با یه لینک دانلود سالم از یه سرور مطمئن امتحان کنید
مثل این 
https://www.ubuntu.com/download/desktop

**Comment by madani-hamid** [comment]
با تشکر از پاسخ دهی فوق سریع
همچنان همون مشکل رو دارم
تفاوتی نداره...

**Comment by alireza-amirsamimi** [comment]
ببینیم مشکل چیه :)
الان از این سایتی که لینک دادم چه طوری لینک دانلود رو گرفتید و اگه ممکن هست لینک دانلود رو بذارید

از چه توزیعی استفاده میکنید و از چه میزکاری 
و همینطور از چه ورژنی از پرسپولیس استفاده میکنید و چه جوری نصبش کردید

**Comment by madani-hamid** [comment]
با کلیک راست رو لینک و گزینه
flash got link
اقدام به دانلود کردم
اینم لینک فایل
http://releases.ubuntu.com/16.04.1/ubuntu-16.04.1-desktop-amd64.iso
دبیان هشت با میز کار گنوم
البته KDE هم دارم ولی ازش استفاده نمیکنم
از ورژن
۲.۲.۲ unstable  
استفاده میکنم
 و برنامه رو با قرار دادن لینک داخل سورس و بعدش دستور آپدیت نصب کردم
و البته تور هم رو سیستم نصبه

**Comment by madani-hamid** [comment]
نصب طبق دستورالعمل خودتون انجام شد
روش دقیقش یادم نیست

**Comment by alireza-amirsamimi** [comment]
برای من داره بدون مشکل دانلود میشه
البته توصیه میکنم روی لینک چپ کلیک کنید برای دانلود بهتره

وقتی روی لینک کلیک میکنید دقیقا چه اتفاقی میفته و اگر دانلود نمیشه در پایان چه خطایی رو نشون میده
این دستور رو از ترمینال که میزنید ، آریا دانلود میکنه؟

`aria2c  http://releases.ubuntu.com/16.04.1/ubuntu-16.04.1-desktop-amd64.iso`

**Comment by madani-hamid** [comment]
هیچ خطایی نمیده
فقط گاهی و نه همیشه مینویسه
download fail
و تمام فیلد های توی دانلود منیجر(فیلد های اطلاعات فایل مثل اسم و غیره) تبدیل به چند تا ستاره میشن
غیر استاتوس که میشه  
stopped
 و
connections 
که میشه 
none
 آریا۲ هم ارور تایم اوت داد

**Comment by alireza-amirsamimi** [comment]
حدس میزنم سیستمتون مشکل پروکسی داره
روی سیستم پروکسی تنظیم کردید؟
غیرفعالش کنید
گوگل رو توی ترمینال پینگ کنید
`ping google.com`

**Comment by madani-hamid** [comment]
من از تور استفاده میکنم 
اون رو غیر فعال کردم ولی باز هم به نتیجه ای نرسید
البته کلا نتم قطع شد
یعنی مرورگرم کار نمیکرد
هرچند بروکسی مو تو تنظیمات مرورگرمم غیر فعال کرده بودم

پینگم هم در هر دو حالت حدود ۱۳۵ بود

**Comment by alireza-amirsamimi** [comment]
ازونجایی که آریا۲ هم نمیتونه توی ترمینال دانلود کنه پس مشکل از پرسپولیس نیست
حالا باید ببینیم مشکل چیه :)
شما پینگ دارید ولی نمیتونید با آریا دانلود کنید
احتمالا مشکل این هست که سیستم شما میخواد آریا۲ برای دانلود از تور استفاده کنه و نمیتونه
چون آریا ۲ پروکسی های
SOCKS
رو ساپورت نمیکنه و برای همین نمیتونه دانلود کنه
برای استفاده از تور با آریا ۲ باید از چیزی مثل
privoxy
استفاده کنید . برای آشنایی باهاش این لینک رو ببینید
http://amirsamimi.ir/persepolis2
در آخر مقاله توضیح دادم

اگر بتونید مشکل آریا ۲ رو حل کنید پرسپولیس هم میتونه دانلود کنه

**Comment by madani-hamid** [comment]
با 
unset HTTP_PROXY 
هم امتحان کردم باز هم تفاوتی نداشت

**Comment by alireza-amirsamimi** [comment]
باز هم آریا نتونست دانلود کنه؟

**Comment by madani-hamid** [comment]
ممنونم 
خیلی لطف کردید که وقت گذاشتید

**Comment by madani-hamid** [comment]
نه نتونست دانلود کنه
طبق مقالتون پیش میرم
اون کار ها رو هم امتحان میکنم...

**Comment by alireza-amirsamimi** [comment]
الان ازون مقاله پیش نرید!
مشکل این هست که ترافیک کل سیستمتون از تور رد میشه
اول باید این مسئله رو حل کنید
و بعد از حل اون مسئله میتونید از طریق اون مقاله پیش برید

تنظیمات پروکسی سیستمتون و کانفیگ تور رو چک کنید. این رو هم ببینید
https://wiki.archlinux.org/index.php/proxy_settings#Proxy_settings_on_GNOME3

**Comment by alireza-amirsamimi** [comment]
این رو هم ببینید
http://forum.ubuntu.ir/index.php/topic,141116.msg1115851.html#msg1115851
