### ISSUE TITLE
نمی‌توان از گوگل درایو دانلود کرد

### ISSUE THREAD

**Issue by hakhsin** [persepolisdm/persepolis#750]
**System Details:**
* Operating System: Linux
* Distro(For GNU/Linux and BSD users): Ubuntu 18.04
* Persepolis Version: latest
* How do you install Persepolis? (Repositories, source, ...) sudo apt ...

سلام، چرا نمی‌توانم از گوگل درایو دانلود کنم؟ به طور خودکار خودش دانلود را شروع نمی‌کند و هنگامی که لینک را دستی بهش اضافه می‌کنم بهم خطای زیر را می‌دهد:
Too many request: count 20
چطوری درستش کنم؟

**Comment by k8scat** [comment]
Why not comment in English?

**Comment by hakhsin** [comment]
Hi @hsowan-me, I thought Iranian people will give me the answer quickly. But my answer is this:
Why do I can't download a file from google drive? When I click on the link the downloader doesn't run and when I add the link into it for download I get this error:
Too many request: count 20 or Too many redirect: count 20
How can I solve it?

**Comment by JafarAkhondali** [comment]
Hello @hakhsin. Currently aria2 can't handle requests from Google Drive, so there is nothing (easy) we can do about it.
