### ISSUE TITLE
Persepolis becomes unusable on KDE Plasma

### ISSUE THREAD

**Issue by proneon267** [persepolisdm/persepolis#758]
**System Details:**
* Operating System: `GNU/Linux`
* Distro(For GNU/Linux and BSD users): `Fedora 31 KDE Plasma`
* Desktop Environment(For GNU/Linux and BSD users): `KDE PLasma`
* Persepolis Version: `3.2.0`
* How do you install Persepolis:   `sudo dnf install persepolis`
* Additional Details: 
```
Fedora 31 KDE Plasma
KDE Plasma version: 5.16.5
KDE Framework version: 5.61.0
Qt Version: 5.12.5
Kernel version:5.3.7-301.fc31.x86_64
```

**Issue Description and steps to reproduce:**
Persepolis doesn't show anything when started. See the attached picture.
![persepolis](https://user-images.githubusercontent.com/45512885/73706097-9523da80-471d-11ea-8340-c693a94a42f0.png)
Even if I add a download link manually, I can't tell for sure if it is downloading since the download dialog freezes.

**Comment by alireza-amirsamimi** [comment]
@proneon267 Hello
Please select deferent icons from preferences window.

**Comment by proneon267** [comment]
Thanks, that solved the problem.
