### ISSUE TITLE
عدم ادامه دانلود در آیتم قبلی

### ISSUE THREAD

**Issue by Mr-undead** [persepolisdm/persepolis#76]
سلام
یه مورد دیدم در پرسپولیس 
بعضی مواقع عملیات دانلود در اواسط کار شکست میخوره و هرچقدر هم روی اون 
resume
میزنم باز ارور میده در نهایت مجددا به صفحه دانلود اون فایل میرم و دوباره اون فایل را با پرسپولیس دانلود میکنم.
حالا پرسپولیس یه ایتم جدید درست میکنه برای دانلود ولی از ادامه فایل قبلی دانلود را شروع میکنه

**Comment by alireza-amirsamimi** [comment]
سلام این اتفاق به خاطر منقضی شدن کوکی و ... هست که همراه فایل با فلش گات به دانلود منجر داده میشه که باعث میشه دانلود قطع بشه و با تازه سازی لینک مشکل حل میشه
و یه دلیل دیگه هم میتونه داشته باشه برای سایت هایی که لینک مستقیم تولید نمیکنند و لینک داینامیک هست و منقضی میشه و دانلود قطع میشه و باید دوباره لینک تازه سازی بشه

**Comment by Mr-undead** [comment]
اخه لبنک مستقیم است

**Comment by alireza-amirsamimi** [comment]
از کدوم سایت لینک رو میگیری بهروز جان
از طریق فلش گات لینک میدی؟

**Comment by Mr-undead** [comment]
چندین بار روی سایت فایل گیر پیش اومده و دفعه اخری هم برای دانلود یه نسخه از توزیع مانجارو بود

**Comment by Mr-undead** [comment]
بله از طریق فلش گات

**Comment by alireza-amirsamimi** [comment]
این جور موقع ها اگر اون سایت خاص نیاز به کوکی و ... نداره سعی کن لینک مستقیم رو دستی به پرسپولیس بدی و از فلش گات نگیری
اینجوری احتمالا مشکل حل میشه :)

**Comment by mavahedinia** [comment]
خب نمیشه به پرسپولیس یه چیزی اضافه کنیم چک کنه کوکی اگه منقضی شده بود، یدور خودش همون مراحل اضافه کردنو بره؟

**Comment by JafarAkhondali** [comment]
Please open a new issue if the problem exists within new version.
Also please provide a sample example so we can check further.
