### ISSUE TITLE
درخواست

### ISSUE THREAD

**Issue by dddeveloperrr** [persepolisdm/persepolis#77]
سلام اقای امیر صمیمی عزیز
لطفا ادرس ایمیل خودتون رو در وبلاگتون هم قرار بدید.

نکته ی بعدی اینکه میخاستم تشکر کنم از اینکه این دانلود منیجر پرسپولیس رو ساختید.
و بگم که اگر امکانش هست این دانلود منیجر رو بصورت
app image 
هم دربیارید خیلی عالی میشه . با تشکر

[](http://appimage.org)

**Comment by alireza-amirsamimi** [comment]
@dddeveloperrr سلام :)
ممنونم از لطفتون
دلیل اینکه ایمیل نذاشتم برای این بود که توی گیت هاب بهتر میشه مشکلات رو پیگیری کرد.
انشاالله در ورژن جدید که به زودی منتشر میشه برای مک برنامه رو به شکل پکیج ارائه خواهیم کرد. توزیع های معروف هم همین الان میتونن برنامه رو از مخزن نصب کنند . انشاالله در آینده نه چندان دور برنامه رو برای ویندوز هم به شکل پکیج ارائه میدیم

**Comment by Alirezaies** [comment]
@alireza-amirsamimi خیلی خوبه این 😀

**Comment by dddeveloperrr** [comment]
بازم ممنونم. حتما به شکل 
app image 
هم منتشر کنید، چون هم دانلود و هم استفاده ازش خیلی راحته. 
پروژتون روی گیتهاب هست طبق توضیحات سایتش، میشه ب راحتی اونو به شکل اپ ایمیج در اورد

لطفا به سایتش سر بزنید مرسی

http://appimage.org/

**Comment by alireza-amirsamimi** [comment]
@dddeveloperrr آخه برای توزیع های لینوکس ، بهتر هست که از مخزن استفاده بشه چون آریا۲ و پرسپولیس مدام در حال به روز شدن هستند و اینجوری با هر بار بروز رسانی سیستم برنامه هم با یه آپدیت کم حجم به روز میشه

**Comment by dddeveloperrr** [comment]
درسته اینم هست. اوکی
