### ISSUE TITLE
Persepolis exits everytime it's set to Shut Down system after Download Completion

### ISSUE THREAD

**Issue by jarmos-san** [persepolisdm/persepolis#786]
**System Details:**
* Operating System: Ubuntu 19.10
* Distro(For GNU/Linux and BSD users): Ubuntu
* Desktop Environment(For GNU/Linux and BSD users): Gnome
* Persepolis Version: 3.2.0
* How do you install Persepolis? Snap

**Issue Description and steps to reproduce:**
As I download a file, there's the option to shut down the system after completion. The option is available under _"Download Option"_ tab in the progress UI. After applying the option to shut down the system when downloads complete, Persepolis would quit, stopping all downloads as well.

Screenshot of the UI for better clarification.

![image](https://user-images.githubusercontent.com/31373860/82527572-69a1f000-9b54-11ea-87f5-624f704e81fe.png)

**EDIT**: Provided a screenshot of the progress UI where the option to shut down the system after download completion & elaborated the issue as much as possible.

**Comment by Aury88** [comment]
sorry, but I don't find the "Shutdown after download" option not in Edit->Preferences->Download option nor in Download->Properties
can you please post the precise path to find that option ? thx
from your description part of the behavior look like the persepolis option to hide itself when close button is clicked (the main tab is closed but the application is still running and you have to close/open it from the system tray).

**Comment by jarmos-san** [comment]
@Aury88 I provided a screenshot of the UI where you can find the option to shut down the system after the download is complete & apologies for not making the issue clear enough. I made some necessary edits & hopefully it makes sense about the issue I'm facing atm.
