### ISSUE TITLE
Support for MEGA

### ISSUE THREAD

**Issue by Mennaruuk** [persepolisdm/persepolis#792]
Is support for MEGA coming anytime soon?

**Comment by mhkarimi1383** [comment]
MEGA have they own way to download files and I think there is no way to do that.

**Comment by laksh225** [comment]
There is an application MegaDownloader that can download files directly from MEGA. I think it uses some kind of streaming server option.

**Comment by laksh225** [comment]
[Mega tools by Megous](https://megatools.megous.com/) could be used to achieve this. But the only problem is that it stores the login in plain text.

**Comment by Mennaruuk** [comment]
Also, does anyone know how JDownloader 2 is doing it? I know once it finishes downloading, it decrypts the file. Can this be mimicked in Persepolis?

**Comment by mhkarimi1383** [comment]
This can be done using https://pypi.org/project/mega.py/ if you really want it....
