### ISSUE TITLE
عدم حذف نسخه قبلی برنامه

### ISSUE THREAD

**Issue by Arch-Lover** [persepolisdm/persepolis#8]
سلام
وقتی نسخه ۲ رو نصب کردم قبلا نسخه ۱٫۱۸ رو داشتم ولی برنامه قبل نصب شدن اون نسخه رو پاک نکرد در نتیجه الان ۲ تا ایکن پرسپولیس تو بخش برنامه ها هست!
http://uupload.ir/files/qryv_perspoles.jpg
http://uupload.ir/files/owx_persepolis.png

**Comment by alireza-amirsamimi** [comment]
عمدا نصاب رو جوری طراحی کردم که نسخه قبلی رو پاک نکنه
چون هنوز این ورژن پایدار نیست . برای همین کاربر بتونه از ورژن قبلی هم استفاده کنه
توی فیلم هم توضیح دادم :)
