### ISSUE TITLE
Icons

### ISSUE THREAD

**Issue by shoshtari** [persepolisdm/persepolis#816]
Hi
i delete some icon from my arch linux and then persepolis icon's are hide
i know it is not bug but i don't know where  i should get help so i write this
what should i do?
![Screenshot_20200914_145401](https://user-images.githubusercontent.com/45182735/93074883-3b639580-f69a-11ea-8917-bb8555c27390.png)

**Comment by rasoulgh917** [comment]
Reinstall the program, or go to settings and change the icon pack and see if it works

**Comment by itisrasoul** [comment]
@shoshtari Reinstall the program, or go to settings and change the icon pack and see if it works

**Comment by SurealCereal** [comment]
Changing the default icon set from "Breeze Dark" to "Breeze" solved it for me
