### ISSUE TITLE
Chrome extension removed?

### ISSUE THREAD

**Issue by cg00001** [persepolisdm/persepolis#824]
Search in store doesn't find Persepolis anymore.
Direct link from github goes to 404 error:
https://github.com/persepolisdm/persepolis/wiki/Chrome-Extension

**Comment by JafarAkhondali** [comment]
@cgcgcgcgcg Fixed

**Comment by cg00001** [comment]
@JafarAkhondali Thank you, I had Persepolis in Chrome but I'm giving Brave a try.
The best download manager in the known universe.
