### ISSUE TITLE
Persepolis crash: Application: python3.7 (python3.7), signal: Aborted

### ISSUE THREAD

**Issue by Moltkex** [persepolisdm/persepolis#835]
**System Details:**
Operating System:: Debian GNU/Linux 10
KDE Plasma: 5.14.5
Qt: 5.11.3
KDE Frameworks: 5.54.0
kernel: 4.19.0-11-amd64
OS: 64 bits
CPU: 2 × AMD E-300 APU with Radeon(tm) HD Graphics
RAM: 1,5 GiB de RAM
**Operating System:** 
Debian 10
**Persepolis Version:** 
3.2.0
**How did you install Persepolis?** 
Downloaded the .deb from github's releases page and installed with apt `sudo apt install ./persepolis_3.2.0.2_all.deb` and got no errors.
It just crashed as soon as I try downloading anything. Also, it looks like this:
https://i.imgur.com/5XOVCq7.png

[python3.7-20201125-140255.kcrash.txt](https://github.com/persepolisdm/persepolis/files/5598513/python3.7-20201125-140255.kcrash.txt)

**Comment by mhsattarian** [comment]
I had the same problem with the icons, changing program icons helped:

![image](https://user-images.githubusercontent.com/29674767/101161231-865fca00-3645-11eb-9b03-fcb5522cfa06.png)
