### ISSUE TITLE
ffmpeg error

### ISSUE THREAD

**Issue by 86ul** [persepolisdm/persepolis#837]
**System Details:**
* Operating System: Mint 20 Ulyana
* Distro(For GNU/Linux and BSD users): Linux mint
* Desktop Environment(For GNU/Linux and BSD users): Cinnamon
* Persepolis Version: 3.2.0
* How do you install Persepolis? by adding this PPA: deb http://ppa.launchpad.net/persepolis/ppa/ubuntu focal main

2020-12-05 13:48:49,080 - Persepolis - ERROR - ffmpeg error: ffmpeg version 4.2.4-1ubuntu0.1 Copyright (c) 2000-2020 the FFmpeg developers

  built with gcc 9 (Ubuntu 9.3.0-10ubuntu2)

  configuration: --prefix=/usr --extra-version=1ubuntu0.1 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --arch=amd64 --enable-gpl --disable-stripping --enable-avresample --disable-filter=resample --enable-avisynth --enable-gnutls --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libjack --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librsvg --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzmq --enable-libzvbi --enable-lv2 --enable-omx --enable-openal --enable-opencl --enable-opengl --enable-sdl2 --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-nvenc --enable-chromaprint --enable-frei0r --enable-libx264 --enable-shared

**Issue Description and steps to reproduce:**
After starting successfully download a YouTube video (https://www.youtube.com/watch?v=pw23cHhdJuY) I get an error when Persepolis tries to start muxing.

**Comment by alireza-amirsamimi** [comment]
I fixed this bug. thanks for reporting.
