### ISSUE TITLE
Chrome extension removed

### ISSUE THREAD

**Issue by hamiltonrn** [persepolisdm/persepolis#848]
**System Details:**
* Operating System: Linux
* Distro(For GNU/Linux and BSD users): Kubuntu 20.10
* Desktop Environment(For GNU/Linux and BSD users): KDE Plasma
* Persepolis Version: 3.2.0
* How do you install Persepolis? PPA

**Issue Description and steps to reproduce:**

Persepolis Extension is not in Chrome Web Store. I think it was removed.

**Comment by zany130** [comment]
download or clone https://github.com/persepolisdm/Persepolis-WebExtension then move/rename stuff to look like this then you can load it through chromes dev mode
<img width="611" alt="Screenshot 2021-01-25 231646" src="https://user-images.githubusercontent.com/25832539/105799862-81dbd180-5f63-11eb-9b28-fbfcd3237ee9.png">

**Comment by zany130** [comment]
however, I get several errors when I try to load it in Vivaldi, and the extension is not sending downloads to persepolis
<img width="960" alt="Screenshot 2021-01-25 233314" src="https://user-images.githubusercontent.com/25832539/105800897-dda75a00-5f65-11eb-81d5-c9a7912c67a4.png">

**Comment by shoshtari** [comment]
I don't know but maybe it come back again!
i search using brave browser
[https://chrome.google.com/webstore/detail/persepolis-download-manag/legimlagjjoghkoedakdjhocbeomojao?hl=en](url)

**Comment by JafarAkhondali** [comment]
This was a temporary problem with chrome staff. They apologized and restored it.

Installing extension offline is possible, however you need to change chrome id native hosts messaging manually cause the id of installed extension is different each time, so that's not something I would recommend.

Thanks for the report.
