### ISSUE TITLE
feature fequest: confirmation-less download from browsers

### ISSUE THREAD

**Issue by AvverbioPronome** [persepolisdm/persepolis#850]
**System Details:**
* Operating System: Ubuntu 20.10
* Distro(For GNU/Linux and BSD users): ?
* Desktop Environment(For GNU/Linux and BSD users): Gnome 3.38.3 / Wayland
* Persepolis Version: 3.2.0
* How do you install Persepolis? apt install persepolis

* _Please attach log files if crash or paste error message_

**Issue Description and steps to reproduce:**
This is a feature request. I wish for persepolis to just start downloading without asking for confirmation when the download is initiated from the firefox extension.

**Comment by Moortu** [comment]
bump, but then for chrome extension as well

**Comment by JafarAkhondali** [comment]
Can you please provide a screenshot of the confirmation window that you wish to not see?

**Comment by Moortu** [comment]
![Untitled](https://github.com/persepolisdm/persepolis/assets/29175880/7aecf2b1-589f-42a0-b02d-b7a52bbc9cbc)

at least, I can't find any option to turn this off and just download to a default folder right away.

**Comment by Moortu** [comment]
> Can you please provide a screenshot of the confirmation window that you wish to not see?

![Untitled](https://github.com/persepolisdm/persepolis/assets/29175880/7aecf2b1-589f-42a0-b02d-b7a52bbc9cbc)

at least, I can't find any option to turn this off and just download to a default folder right away.

**Comment by alireza-amirsamimi** [comment]
Hello
We would work on it as a feature request.
Thank you.

**Comment by JafarAkhondali** [comment]
@Moortu We will implement this feature ... but ... why did you download uGet 😢  ...
![perse](https://github.com/persepolisdm/persepolis/assets/11364402/12ee5056-5ab0-4b73-b5f4-0e58bb866bb5)

**Comment by Moortu** [comment]
@JafarAkhondali 🤣 
I was shopping around for a good download manager.

mortix doesn't even work for me
uget is a really weird install and didn't tickle my fancy.
JDownloader isn't as sleek as persepolis.

I really want to use persepolis, but I don't want to confirm every download in a seperate window.

I get that confirming is good, otherwise you might download stuff you don't want.
but it should be a confirmation on the plugin side, so it stays within the browser and it should be toggleable, perhaps even whitelist able?

**Comment by alireza-amirsamimi** [comment]
@Moortu 
Hello
[Your feature has been added.](https://github.com/persepolisdm/persepolis/commit/197edd21b0b7f541d6c31d709a7a3c75eb610580) You can enable it from preferences window. check the last check box.

![Screenshot_%Y%M%D_%H%m%S](https://github.com/persepolisdm/persepolis/assets/7452500/007c5991-b66f-4882-92aa-61086702c10b)
