### ISSUE TITLE
نصب روی مرورگر brave

### ISSUE THREAD

**Issue by ghost** [persepolisdm/persepolis#862]
سلام عرض میکنم
در مورد این دانلود منیجر سوالی داشتم
من روی مرورگر brave نصب کردم و سیستمم اوبونتو هستش 
داخل مرورگر فایر فاکس به خوبی میتونم از این دانلود منیجر استفاده کنم ولی توی این مرورگر نه
ممنون میشم که من رو راهنمایی کنید که به یک صورتی این مشکل رو حل کنم

**Comment by alireza-amirsamimi** [comment]
سلام
لطفا انگلیسی بنویسید.
ممنونم که اطلاع دادید. این باگ حل شده و در نسخه بعدی که بزودی منتشر خواهد شد این باگ نخواهد بود.
