### ISSUE TITLE
Persepolis broken on Firefox Nightly

### ISSUE THREAD

**Issue by jdrch** [persepolisdm/persepolis#864]
**System Details:**
* Operating System: Windows 10 x64
* Distro(For GNU/Linux and BSD users): ?
* Desktop Environment(For GNU/Linux and BSD users): ?
* Persepolis Version: 3.2.0
* How do you install Persepolis? Windows installer

* _Please attach log files if crash or paste error message_

**Issue Description and steps to reproduce:**

If you try to download anything from Firefox using Persepolis, nothing happens.

**Comment by SuperKaninchen** [comment]
Im guessing that this is about the standalone application and not a browser plug-in, so your Firefox installation is probably not the problem. Please send logs/error messages to make troubleshooting easier.

**Comment by jdrch** [comment]
Hmmm I just tested it on a known good link and it works. So either the bug was fixed in Firefox Nightly or it was a server-side problem. Thanks for the quick response!
