### ISSUE TITLE
Mac Application Link, in readme

### ISSUE THREAD

**Issue by hsnfirooz** [persepolisdm/persepolis#87]
this link: https://github.com/persepolisdm/persepolis/blob/master/how_to_package_for_mac.md is not available, change it to : https://github.com/persepolisdm/mac-package-build

**Comment by alireza-amirsamimi** [comment]
@HsnFirooz Thank you

**Comment by alireza-amirsamimi** [comment]
It's corrected now
thanks for reporting this this issue .
I suggest to use our mac package in release page.
No need to build package yourself
