### ISSUE TITLE
Provide Updated Release (3.2.x) for Ubuntu 21.04 (Hirsute) via Official PPA (launchpad.net/~persepolis/+archive/ubuntu/ppa)

### ISSUE THREAD

**Issue by robfrawley** [persepolisdm/persepolis#872]
## System Details

- Operating System: `Ubuntu 21.04 (Hirsute)`
- Desktop Environment: `Gnome 3.38`
- Persepolis Version: `n/a`
- Installation Method: `apt`

## Issue Description (Formatted as a "Friendly Rant" :-)

The Persepolis package version provided through Ubuntu's "universe" repository is not current and stuck at the `3.0.x` release series; such a situation is common (and expected by many) as the build and approval process for getting packages into a distribution's repository takes a substantial amount of time, effort, and energy.

I also do realize that you publish a current `3.2.x` release series snap package that is compatible with Ubuntu, but many people (including myself) do not particularly care for snap packages and avoid them unless absolutely necessary.

"No worries," I thought to myself, "Persepolis also provide a Launchpad PPA with their latest releases!" _But, to my surprise, the official Launchpad PPA ([launchpad.net/~persepolis/+archive/ubuntu/ppa](https://launchpad.net/~persepolis/+archive/ubuntu/ppa)) **does not yet offer builds for Ubuntu 21.04** (Hirsute), despite it being **released over two months ago**!_

## Requested Resolution

Please provide **current Persepolis `.deb` packages (`3.2.x`)** on the official [Launchpad Page (ppa:persepolis/ppa)](https://launchpad.net/~persepolis/+archive/ubuntu/ppa) **for Ubuntu 21.04 (Hirsute)**, alongside the existing builds already provided for all other active Ubuntu releases.

**Comment by mostafaasadi** [comment]
Hello
thank you for your report 
the launchpad ppa is our official repository
I copied deb file for hirsute from our last build for groovy and it released on ppa, please update and review
