### ISSUE TITLE
Persepolis doesn't start in Manjaro KDE Plasma 21.0.7

### ISSUE THREAD

**Issue by rafidalhaque** [persepolisdm/persepolis#874]
**System Details:**
* **Operating System:** Manjaro KDE Plasma 21.0.7
* **Distro(For GNU/Linux and BSD users):** Manjaro 
* **Desktop Environment(For GNU/Linux and BSD users):** KDE Plasma 
* **Persepolis Version:** latest
* **How do you install Persepolis?** by this command ```sudo pacman -S persepolis```

Assalamu Alaikum Wa Rahmatullah. Persepolis doesn't start. When I click to start it, it loading for some seconds in taskbar. and doesn't start. Please consider to check this screen record: 

https://user-images.githubusercontent.com/68812773/127013711-02e914d7-9d32-43b8-b848-cddace4da2ec.mp4

Waiting for solve.

**Regards.**

**Comment by alireza-amirsamimi** [comment]
Hello
Run Persepolis from terminal, Please and tell me the output.
`persepolis`

**Comment by rafidalhaque** [comment]
Now it's ok. But when I see the problem, the command `persepolis` didn't give any output.
