### ISSUE TITLE
مشکل در ورژن ۲.۲.۲

### ISSUE THREAD

**Issue by shahabsaf1** [persepolisdm/persepolis#89]
لینک http://dl.hastidownload.biz/2/The%20Grand%20Tour/T.G.T.S01E06.720p.mkv
میز کار یونیتی ۷
اوبونتو ۱۶.۰۴

**Comment by shahabsaf1** [comment]
در ۱۶.۱۰ هم همین مشکل رو دارم.

**Comment by alireza-amirsamimi** [comment]
سلام
توصیه میکنم برنامه رو آپدیت بفرماید
نسخه برنامتون قدیمی هست
لینک شما رو تست کردم و بدون مشکل دانلود میشه(اسکرین شات رو ببینید) . چه خطایی میگیرید؟
![screenshot_2017-01-12_18-47-03](https://cloud.githubusercontent.com/assets/7452500/21895401/d7e7b0c2-d8f7-11e6-9d14-7ce487c340ab.png)

**Comment by shahabsaf1** [comment]
خطایی نمیده 
Freeze میشه

**Comment by shahabsaf1** [comment]
ممنون از گیتهاب بروزرسانی کنم؟

**Comment by mavahedinia** [comment]
@shahabsaf1 تو مخازن آپدیتش هست!

**Comment by alireza-amirsamimi** [comment]
@shahabsaf1 نه
توصیه میکنم از مخازن لانچپد نصب کنید و همیشه با بقیه برنامه ها به روز میشه
دستور نصب رو در سایت ببینید

**Comment by alireza-amirsamimi** [comment]
@shahabsaf1 منظورتون از فریز شدن چیه؟
با بقیه لینک ها هم این مشکل وجود داره؟

**Comment by shahabsaf1** [comment]
خیر با بقیه ی لینک ها مشکلی نداره 
منظورم از فریز شدن اینه که فقط با دستور 
kilall -9  
میتونم برنامرو ببندم

**Comment by alireza-amirsamimi** [comment]
@shahabsaf1 آپدیت کردید؟ باز هم فریز میشه؟
