### ISSUE TITLE
کرش کردن برنامه

### ISSUE THREAD

**Issue by j-akbari** [persepolisdm/persepolis#9]
درود بر شما جناب امیرصمیمی
برنامه بعد از بازکردن ارور داد و کرش کرد
سیستم مورد استفاده زوبونتو 16.04 
متن خطا خدمت شما

> Xlib: sequence lost (0x10220 > 0x233) in reply type 0x1c!
> QObject::connect: Cannot queue arguments of type 'QTextBlock'
> (Make sure 'QTextBlock' is registered using qRegisterMetaType().)

**Comment by alireza-amirsamimi** [comment]
سلام
ممنونم
یکی دیگه هم از دوستان مورد مشابهی اطلاع داده بودند
الان یه آپدیت فرستادم
لطفا دوباره از گیت هاب نصب کن ببین مشکل رفع شده یا نه :)
و اگر اکی شده بود اطلاع بده تا موضوع رو اینجا ببندم

**Comment by j-akbari** [comment]
با تشکر از شما و با عرض پوزش بابت تاخیر در پاسخ
مشکل برطرف شد
بازم اگه با مشکل خاصی برخورد کردم اطلاع میدم
پایدار باشید

**Comment by alireza-amirsamimi** [comment]
ممنونم از همکاریت :)
