### ISSUE TITLE
open default download folder

### ISSUE THREAD

**Issue by r00tnt** [persepolisdm/persepolis#90]
سلام
ممنون از کار عالیتون
از منوی فایل open default download folder رو که می زنم کرش می کنه
![err](https://cloud.githubusercontent.com/assets/7997145/21923475/976cc568-d989-11e6-9eb9-ee64b6664697.png)
 
درضمن یه چیز دیگه که فکر می کنم چون شاید براتون زیاد اهمیت نداشته باشه ایشوی جدید باز نکردم
من برنامه نویس جاوام چند سال پیش پایتون کار می کردم اگر یخورده کد ها ترو تمیز و منظم بشه که سریعتر بشه سر در آورد ازش می تونم کانتریبیوت کنم
خیلی ممنون

**Comment by alireza-amirsamimi** [comment]
سلام
ممنونم از اینکه باگ رو ریپورت کردید
مشکل رو روی گیت هاب حل کردم و انشالله در آپدیت بعدی باگ فیکس خواهد شد.
حجم کدهای برنامه کمی زیاد هست و من سعی کردم بیشتر قسمت های مهم و اصلی کامنت گذاری بشه
کدام قسمت برنامه براتون نامفهوم هست تا واضح ترش کنم

**Comment by alireza-amirsamimi** [comment]
سلام
باگ فیکس شد
آپدیت کنید
