### ISSUE TITLE
کندی هنگام دریافت نسخه گیت

### ISSUE THREAD

**Issue by LinArcX** [persepolisdm/persepolis#91]
علی جان بنده روی آرچ خودم همیشه با 
aur-helper 
ها برنامه تونو آپدیت میکنم.اما به مرحله دریافت از گیت که میرسه با یه تاخیر معنا دار
(بین 5 تا 8 دقیقه)
فایلهای پروژه رو دانلود میکنه.که فک میکنم از 25 مگ بیشتر نباشه.درسته؟
دلیل این تاخیر زیاد در دریافت از گیت چیست؟

**Comment by ghost** [comment]
<div dir="rtl">
سعیدجان مخزن پرسپولیس حدودا ۲۵ مگ میشه و وقتی که بسته پرسپولیس نسخه گیت رو نصب میکنی برنامه گیت اون رو دانلود میکنه. ۴ تا ۵ دقیقه زمان فکر میکنم منطقی باشه.
</div>

**Comment by LinArcX** [comment]
عرض ادب خدمت محمد عزیز.
محمد جان من این سری دقیق تایم گرفتم و  با یه عدد عجیب تر مواجه شدم.
16 دقیقه!!!!!
خودمم باورم نمیشد انقد طولانی بشه.
حدس زدم مشکل از کندی اینترنتم باشه که یه آپدیت کلی زدم و با سرعت همیشگی-130 ک/ث -دانلود کردم.
واقعا مشکل از سیستم منه یا بقیه دوستان هم این مشکلو دارن؟

**Comment by ghost** [comment]
<div dir="rtl">
سعیدجان من خودم آخرین دفعه که دانلود کردم با سرعت ۴۰۰ ک دانلود شد که سرعت نت من بود و مشکلی نداشت و سریع دانلود شد. نمیدونم مشکل سرعت شما چیه. با سرعت ۱۳۰ ک باید سریعتر از اینا دانلود بشه!!!
</div>

**Comment by alireza-amirsamimi** [comment]
برای من هم اینقدرها طول نکشید و سریع کلون شد

**Comment by hayyan71** [comment]
@alireza-amirsamimi اصولا کندی دریافت clone یک بسته از گیت هاب ارتباطی به خود بسته ندارد. به هر حال به عنوان تست هم بنده هم اکنون در حالیکه مشغول دریافت پرونده ای دیگر بودم، پرسپولیس را از github به صورت clone دریافت نموده و فرآیند دریافت با سرعت مناسب انجام شد
