### ISSUE TITLE
web extension does Not connect software Ubuntu 22.4 , 21.10

### ISSUE THREAD

**Issue by matin1099** [persepolisdm/persepolis#913]
**System Details:**
* Operating System: Ubuntu 22.4 
* Distro(For GNU/Linux and BSD users): ubuntu
* Desktop Environment(For GNU/Linux and BSD users): Gnome 40.5
* Persepolis Version: 3.2.0(22.4) 3.1.0 (21.10)
* How do you install Persepolis? 
* 22.4( by official website)
* 21.10 (ubuntu software)  
* _Please attach log files if crash or paste error message_
 No crash  happened!
**Issue Description and steps to reproduce:**
web extension does not work! 
been worked on Ubuntu 21.4 but after OS updates , doesn't work anymore.
reinstalling doesn't work.

**Comment by jazijazi** [comment]
Hello, after update ubuntu from 20.04 to 22.04 firefox extension stop working for me too

**Comment by matin1099** [comment]
> Hello, after update ubuntu from 20.04 to 22.04 firefox extension stop working for me too
