### ISSUE TITLE
man page

### ISSUE THREAD

**Issue by ghost** [persepolisdm/persepolis#92]
سلام.
در اوبونتو صفحه راهنما با دستور
man persepolis
با خطا مواجه میشه.  چک کردم، توی فایل نصب، فایل فشرده راهنما توی مسیر درستی کپی نمیشه.
ظاهرا باید به این صورت اصلاح بشه
 sudo cp -rf "./persepolis.1.gz" "/usr/local/share/man/man1/"

**Comment by alireza-amirsamimi** [comment]
@Zamaaan سلام
دقیقا چه مشکلی داره
چو برنامه در اوبونتو از مخزن نصب میشه باید راهنما در مسیر
/usr/share/man/man1
باشه
از مخزن نصب کردید؟

**Comment by mostafaasadi** [comment]
@Zamaaan سلام 
ممنون از گزارشتون 
بله مشکل بصورت اشتباهی هست 
بزودی در آپدیت رفع خواهد شد ان شاء الله

**Comment by ghost** [comment]
myname@mypc:~$ man persepolis
man: can't open /usr/share/man/man1/persepolis.1.gz: No such file or directory
man: can't open /usr/share/man/man1/persepolis.1.gz: No such file or directory
No manual entry for persepolis
See 'man 7 undocumented' for help when manual pages are not available.

myname@mypc:~$ ls -la /usr/share/man/man1/ | egrep "persepolis"
drwxr-xr-x  2 root root   4096 Jan 13 15:51 persepolis.1.gz/

myname@mypc:~$ ls -la /usr/share/man/man1/persepolis.1.gz/
drwxr-xr-x 2 root root  4096 Jan 13 15:51 ./
drwxr-xr-x 3 root root 77824 Jan 13 15:51 ../
-rw-r--r-- 1 root root  1105 Jan 12 13:41 persepolis.1.gz

اول یه دیرکتوری میسازه و داخل اون دیرکتوری فایل فشرده رو کپی می کنه

**Comment by alireza-amirsamimi** [comment]
سلام
مشکل حل شد آپدیت کنید
