### ISSUE TITLE
[QUESTION] Is this project abandoned?

### ISSUE THREAD

**Issue by khaled-0** [persepolisdm/persepolis#927]
Just wondering is this project alongside the [Persepolis-WebExtentsion](https://github.com/persepolisdm/Persepolis-WebExtension) 
abandoned by the devs?
Or are you guys still open for pull requests?

I'm sorry to be asking this because the last commits were 2+ years ago and I feel like this project is abandoned.
If not then please say so.
Thanks

**Comment by khaled-0** [comment]
@alireza-amirsamimi

**Comment by mortezaataiy** [comment]
I'm interested too

**Comment by khaled-0** [comment]
looks like the project is abandoned

**Comment by mrostd** [comment]
Soon.. 🥴
![Uploading IMG_20230123_171933.jpg…]()

**Comment by LaoshuBaby** [comment]
Just like the name of the project Persepolis, the leader of this project seems to be from Iran, and he seems to be rarely able to continue to be active on GitHub (or his access to GitHub is affected by GitHub's sanctions on Iran in compliance with the requirements of the US government). So it seems that after 2021, he has never merged a PR or responded to any issue.
What a sad thing 😭

But from another perspective, two years later, the released program can still run stably, indicating that its code is still very robust.

**Comment by Nirose** [comment]
moving to a different git host could solve the issue. does anyone know if codeberg has similar restrictions?

**Comment by LaoshuBaby** [comment]
> moving to a different git host could solve the issue. does anyone know if codeberg has similar restrictions?

Looks like codeberg doens't shown to have a strong politic tendency, so that platform maybe more safe for US restricted countries's developer?

However, whether former core maintainer can access Internet freely is also a important point to continue the project.

(I come from China, so I often guess that similar situation will happen to me.)

**Comment by iFreilicht** [comment]
There was a new release a few weeks ago! https://github.com/persepolisdm/persepolis/releases/tag/4.0.0

However, it seems the project is pretty much in maintenance mode. Some critical PRs may occasionally get merged, but I wouldn't expect much more than that.

**Comment by alireza-amirsamimi** [comment]
> There was a new release a few weeks ago! https://github.com/persepolisdm/persepolis/releases/tag/4.0.0
> 
> However, it seems the project is pretty much in maintenance mode. Some critical PRs may occasionally get merged, but I wouldn't expect much more than that.

Hello
Next version will be released in next month.
Please report bugs 🙏
