### ISSUE TITLE
کار نکردن در کروم

### ISSUE THREAD

**Issue by cnmeysam** [persepolisdm/persepolis#93]
بعد از 1000بدبختی پلاگین کروم رو نصب کردم به دلیل تحریم ها اجازه نمیداد حالا کلا اجرا نمیشه وقتی لینک رو بهش میدم مجبورم کپی کنم لینک رو ببرم تو برنامخ تا بتونم دانلود کنم

**Comment by JafarAkhondali** [comment]
@cnmeysam 😐😐😐
یه فیلتر شکن‌ + کلیک روی نصب = ۱۰۰۰ بد بختی 😐

**Comment by JafarAkhondali** [comment]
@cnmeysam

**Comment by JafarAkhondali** [comment]
@cnmeysam سلام

**Comment by JafarAkhondali** [comment]
@cnmeysam 
سلام
 متاسفانه تحریم کروم دست ما نیست. اولین باره همچین مشکلی گزارش میشه توی بخش افزونه های کروم تیک گزینه‌
 "Allow access to file URLS" 
باید زده بشه و بعد از اون مرورگر رو ببندین و دوباره باز کنین. اگه این کار هارو انجام دادین بگین که بررسی بیشتری انجام بشه.
ممنون که گزارش دادین

**Comment by alireza-amirsamimi** [comment]
@cnmeysam 
در ضمن بعد از مراحلی که دوستمون گفتند
فراموش نکنید که از منوی 
Help
پرسپولیس گزینه 
Browser integration
رو بزنید و بعد مرورگر خودتون رو از اونجا انتخاب کنید

**Comment by ghost** [comment]
من چون طریقه نصب رو کامل نخونده بودم ابتدا به همین مشکل برخوردم.
ولی بعد با دقت خوندم دیدم این مرحله ای که شما گفتین رو هم باید انجام بدیم.
مشکل حل شد.

اینکه موقع نصب یا آپدیت پرسپولیس، این دوتا فایل
json
 بدون دخالت کاربر توی دیرکتوری های مربوط به خودشون کپی نمیشن، 
علت خاصی داره؟
مثلا مشکل مجوز داشته که این کار رو نکردید؟

**Comment by alireza-amirsamimi** [comment]
@Zamaaan 
اصولا نصاب موقع نصب نباید فایل های شاخه خانه کاربر رو دستکاری کنه
و یک مورد مهم دیگه حقوق کاربر :)
شاید کاربر اصلا از این مرورگرها استفاده نکنه
نباید پوشه اضاقی توی سیستمش ایجاد کنیم

**Comment by cnmeysam** [comment]
ممنون مشکل حل شد Browser integration
 رو نمیدونستم و انجام نداده بودم
در ضمن با فیلتر شکن هم دانلود نمیشد از طریق دادن کد برنامه توی یک سایت دانلودش کردم
یک سوال دیگه چرا وقتی صف رو استپ میکن آیکن برنامه که توی سینی هست میپره و عوض میشه و تا از برنامه خارج نشم آیکنش درست نمیشه؟

**Comment by alireza-amirsamimi** [comment]
@cnmeysam سلام
سعی کنید برای مشکلات جدید ، موضوع جدید باز کنید :) اینجوری راحت تر میتونیم دسته بندیش کنیم
همین سوال رو لطفا در موضوع جدید بنویسید ، لطفا سیستم عامل و میزکار رو هم بنویسید 
و البته مطمئن بشید که از نسخه
2.3.1
پرسپولیس استفاده میکنید
چون مشکل قبل حل شده پس من این موضوع رو میبندم
سپاس
