### ISSUE TITLE
Problem Install with Error x86

### ISSUE THREAD

**Issue by Rayiumir** [persepolisdm/persepolis#939]
Hi @alireza-amirsamimi 

I take When Install Error x86 in Windown 11. 

For Version 4 Download Manager Perspolis.

![Screenshot 2024-02-09 213620](https://github.com/persepolisdm/persepolis/assets/11635923/9e98c484-bb1b-4c7a-bb28-ff10400a2117)

**Comment by mostafaasadi** [comment]
From version four, due to the small number of users and the prevalence of 64-bit versions, we no longer build the 32-bit version.
You can build for yourself according to this [document](https://github.com/persepolisdm/persepolis-windows-package-build)

**Comment by Rayiumir** [comment]
@mostafaasadi 

Thank you from answer
