### ISSUE TITLE
ICON

### ISSUE THREAD

**Issue by cnmeysam** [persepolisdm/persepolis#94]
سلام چرا وقتی که توقف صف رو میزنم آیکن برنامه شبیه به علامت ورود ممنوع تغییر پیدا میکنه از اوبونتو 16.10 استفاده میکنم
نمیدونم چطور بفهمم میزکارم چیه تازه کارم ولی همون پیشفرض اوبونتو هستش
پرس پلیسم هم 2.3.1 هستش
و تا زمانی که کلا از برنامه خارج نشم آیکنش درست نمیشه

**Comment by alireza-amirsamimi** [comment]
سلام
من توی ماشین مجازی اوبونتو ۱۶.۱۰ رو نصب کردم و برای من مشکلی نداشت

**Comment by Alirezaies** [comment]
سلام.

میتونید مشخصات سیستم رو از طریق کد زیر پیدا کنید.

کد:

`sudo apt install screenfetch && clear && screenfetch;`

من روی اوبونتو 16.04 امتحان کردم مشکلی نبود.

امکانش هست اسکرینشات یا دمو بگیرید؟

**Comment by alireza-amirsamimi** [comment]
@Alirezaies برای پیدا کردن میزکار همین کد کافیه :)

echo $DESKTOP_SESSION

**Comment by mostafaasadi** [comment]
سلام دوست عزیز 
بنده تست کردم روی اوبونتو ۱۶.۱۰ و یونیتی مشکلی نبود 
لطفا اگر هنوز با چنین مشکلی مواجهید توضیحات بیشتر یا تصاویر را ارسال کنید 
لازم به یادآوریست علامت ورود ممنوع در اوبونتو زمانی ظاهر می شود که اپت دچار خطا در اپدیت است

**Comment by cnmeysam** [comment]
عکس اول برای شروع صف دانلوده به آیکن دانلود منیجر توی سینی دقت کنید
`http://uupload.ir/files/68d5_1.png`
عکس دوم برای زمانیه که توقف صف رو میزنم باز به آیکن دانلود منیجر کنار ساعت دقت کنید
`http://uupload.ir/files/7u70_2.png`
تا زمانی که کلا نرمافزار رو نبندم و دوباره اجراش نکنم آیکن درست نمیشه

اینم مشخصاتی که بهم داده از سیستمم

                          ./+o+-       administrat0r@Maysam
                  yyyyy- -yyyyyy+      OS: Ubuntu 16.10 yakkety
               ://+//////-yyyyyyo      Kernel: x86_64 Linux 4.8.0-34-generic
           .++ .:/++++++/-.+sss/`      Uptime: 17h 14m
         .:++o:  /++++++++/:--:/-      Packages: 2498
        o:+o+:++.`..```.-/oo+++++/     Shell: bash 4.3.46
       .:+o:+o/.          `+sssoo+/    Resolution: 1366x768
  .++/+:+oo+o:`             /sssooo.   DE: Unity 7.5.0
 /+++//+:`oo+o               /::--:.   WM: Compiz
 \+/+o+++`o++o               ++////.   WM Theme: Ambiance
  .++.o+++oo+:`             /dddhhh.   GTK Theme: Ambiance [GTK2/3]
       .+.o+oo:.          `oddhhhh+    Icon Theme: ubuntu-mono-dark
        \+.++o+o``-````.:ohdhhhhh+     Font: Ubuntu 11
         `:o+++ `ohhhhhhhhyo++os:      CPU: Intel Core i7-4702MQ CPU @ 3.2GHz
           .o:`.syhhhhhhh/.oo++o`      GPU: Mesa DRI Intel(R) Haswell Mobile 
               /osyyyyyyo++ooo+++/     RAM: 1996MiB / 7899MiB
                   ````` +oo+++o\:    
                          `oo++.

**Comment by alireza-amirsamimi** [comment]
ممنونم از اطلاعاتی که دادید
عجیب هست که فقط شما این مشکل رو دارید
این موضوع رو باز میذارم و نمیبندمش تا اگر دوستان دیگر هم اومدن و این مشکل مشابه رو داشتند ، گزارش بدند
سپاس

**Comment by JafarAkhondali** [comment]
Please open a new issue if the problem exists within new version.
