### ISSUE TITLE
Where Can I Download the macOS Version?

### ISSUE THREAD

**Issue by LordArma** [persepolisdm/persepolis#945]
**System Details:**
* Operating System: macOS 14.3.1 (23D60)

It seems Persepolis Download Manager is currently on the [4.0.1](https://github.com/persepolisdm/persepolis/releases/tag/4.0.1) version.

The latest version of the program that I can find that have a macOS build is [3.1.0](https://github.com/persepolisdm/persepolis/releases/tag/3.1.0)!

Should I try to build the program myself? Does it suppprts Apple silicon?

**Comment by alireza-amirsamimi** [comment]
Hello
Mac build package will be uploaded tomorrow.

**Comment by LordArma** [comment]
> Hello Mac build package will be uploaded tomorrow.

Thank you. Unfortunately it doesn't work for me. I opened a new issue for it here: [#946](https://github.com/persepolisdm/persepolis/issues/946)
