### ISSUE TITLE
Problem with Running Version 4.0.1 on macOS

### ISSUE THREAD

**Issue by LordArma** [persepolisdm/persepolis#946]
**System Details:**
* Operating System: macOS 14.3.1 (23D60)
* Persepolis Version: 4.0.1
* I downloaded the dmg file from here: [Persepolis Download Manager 4.0.1](https://github.com/persepolisdm/persepolis/releases/tag/4.0.1)

I downloaded the latest dmg file for Apple silicones and simply opened it and draged & droped the app to the Aplication folders. After I tried to run it I got this error as what I uploaded.

Can you help me to install it?

If you need more tests on the macOS with Apple silicon (M1) please count on me.

![Screenshot 2024-03-14 at 5 37 39 AM](https://github.com/persepolisdm/persepolis/assets/6020960/5e228bee-3619-48c0-8c7a-56d327087c28)

**Comment by kiahamedi** [comment]
Hi dear LordArma

By default, the Mac operating system only allows installation from "App Store" and "App Store and Identified developers".

To install the Mac file from GitHub, you must use the following command to open the installation from anywhere

`sudo spctl --master-disable` 

After running the following command in the terminal, restart your operating system

In the privacy settings and the installation section, the **anywhere** option must be selected

**Comment by jdrch** [comment]
> By default, the Mac operating system only allows installation from "App Store" and "App Store and Identified developers".

Thanks for the solution, but why does this version have this issue while the previous versions haven't?

**Comment by kiahamedi** [comment]
Hello @jdrch 

We used to use a method to rebuild the info.plist file, which solved this problem for us, but it caused other problems in the new versions, such as notifications and accesses.
We are solving it, but for our team, it is more important for Persepolis to work correctly and without problems, and that all its facilities can be used by users.
It is normal that the Apple company does not allow normal installation to projects that are not signed by the developer account, so this is not a problem and it is the normal state of the Apple operating system. We will try to work on it in the next versions and fix it.
