### ISSUE TITLE
[macOS] 4.0.1: version numbers broken

### ISSUE THREAD

**Issue by core-code** [persepolisdm/persepolis#947]
i've downloaded version ```4.0.1``` but after selecting it in the Finder (Quick Look, Column View, Get Info) it claims to be version  ```0.0.0```

<img width="552" alt="Screenshot 2024-03-14 at 18 16 14" src="https://github.com/persepolisdm/persepolis/assets/1261954/800251df-f80a-4cd8-8cea-5a088b5cc99c">
<img width="260" alt="Screenshot 2024-03-14 at 18 15 58" src="https://github.com/persepolisdm/persepolis/assets/1261954/2cd47fdf-0ce6-4f0e-88b0-0019a7767214">
<img width="619" alt="Screenshot 2024-03-14 at 18 16 03" src="https://github.com/persepolisdm/persepolis/assets/1261954/143cd81f-76f3-4929-9430-a519ee6d3573">

the ```CFBundleShortVersionString``` and ```CFBundleVersion``` entries in your ```Info.plist``` file are faulty

**Comment by kiahamedi** [comment]
Hello @core-code 

Thank you very much for letting us know about the problem

This problem is caused by the logic of the info.plist file.
We have temporarily disabled the file to solve the Persepolis notification problem on Mac and we will fix the problem for the next version.

Best wishes
