### ISSUE TITLE
perspolis crash [bug]

### ISSUE THREAD

**Issue by Monirzadeh** [persepolisdm/persepolis#95]
خطای پیش آمده در هنگام ارسال لینک  از طریق فلش گات 
بعد از راه اندازی مجدد کل تنظیمات پرسپولیس ریست شده و کل لینکها نیز از بین رفت  
```
Traceback (most recent call last):
  File "/usr/share/persepolis/persepolis", line 232, in <module>
    mainwindow = MainWindow( start_in_tray , persepolis_download_manager , persepolis_download_manager.setting )
  File "/usr/share/persepolis/mainwindow.py", line 588, in __init__
    download_info_file_list = readList(download_info_file,'string')
  File "/usr/share/persepolis/newopen.py", line 100, in readList
    dictionary = ast.literal_eval(f_string.strip())
  File "/usr/lib/python3.5/ast.py", line 46, in literal_eval
    node_or_string = parse(node_or_string, mode='eval')
  File "/usr/lib/python3.5/ast.py", line 35, in parse
    return compile(source, filename, mode, PyCF_ONLY_AST)
  File "<unknown>", line 0
    
    ^
SyntaxError: unexpected EOF while parsing
```

**Comment by alireza-amirsamimi** [comment]
@Monirzadeh سلام 
از چه ورژن برنامه استفاده میکنید
توزیع شما چی هست
برنامه رو چه جور نصب کردید؟
آیا این اشکال موقت بوده یا باز هم رخ داده

**Comment by Monirzadeh** [comment]
perspolis 2.3.1
ubuntu 16.04 + unity
repository
اولین بار

**Comment by alireza-amirsamimi** [comment]
@Monirzadeh برنامه رو که دوباره اجرا میکنید باز هم این خطا وجود داره؟ با ریست کردن برنامه حل نشد ؟

**Comment by Monirzadeh** [comment]
توی پنجره ای که خطای بالا نمایش داده شده بود گزینه 
reset perspolis 
وجود داشت با کلیک برنامه دوباره راه اندازی شد و به طور کامل به تنظیمات اولیه بازگشت
و در حال حاظر بدون مشکل کار میکند

**Comment by alireza-amirsamimi** [comment]
سلام 
این باگ در این کامیت
[Commit](https://github.com/persepolisdm/persepolis/commit/178d29e0006e777ee746926563076ae77e95e7b7)
درست شد! سپاس از اینکه اطلاع دادید . انشالله در نسخه جدید پرسپولیس این باگ رو نمیبینید :)
