### ISSUE TITLE
کرش کردن اپلیکیشن در دبیان بعد چند دقیقه دانلود کردن

### ISSUE THREAD

**Issue by aligholipour1** [persepolisdm/persepolis#956]
سلام من درحال دانلود یک فایل با استفاده از اپلیکیشن بودم ولی بعد چند دقیقه اپلیکیشن کلا بسته شد و دانلود به ارور خورد و باید دوباره دانلود میکردم مشکل کجاست؟

**Comment by alireza-amirsamimi** [comment]
Hello
Please write in English  and tell me more details.
Thank you
