### ISSUE TITLE
No file size when link is being added!

### ISSUE THREAD

**Issue by Arch-Lover** [persepolisdm/persepolis#958]
**System Details:**
* Operating System: windows 11
* Distro(For GNU/Linux and BSD users): ?
* Desktop Environment(For GNU/Linux and BSD users): ?
* Persepolis Version: 4.0.1
* How do you install Persepolis? (Repositories, source, ...)
From new WIKI instruction!

* _Please attach log files if crash or paste error message_
no error messages sadly!
**Issue Description and steps to reproduce:**
#### Please report only one Issue (Bug or feature request or ...) in one issue! and open new Issue for another one :)

The issue is when you add a download link it used to show the file size but now it only shows zero and wont change it until the file starts to be downloaded!
Also as someone reported #957 before in windows you cant download at all let alone to reach a specific percentage and hung/crash there!
مشکل اینطوریه که قبلا وقتی لینک اد میکردی بهت حجم رو نشون میداد ولی الان نشون نمیده و حجم تا زمانی که فایل شروع به دانلود نکنه نشون داده نمیشه.
اگر اسکرین شات لازمه خونه رفتم به این ایشو اضافه میکنم.

**Comment by alireza-amirsamimi** [comment]
Hello
Thanks for reporting. Persepolis uses aria2c for downloading. Persepolis has to wait for aria2c to give it information. so the problem cannot be solved
