### ISSUE TITLE
Add option to download with server timestamp

### ISSUE THREAD

**Issue by ZorinFoss** [persepolisdm/persepolis#959]
Hi,

First of all, i really appreciating  your efforts in developing `persepolis`.

As `persepolis` is a GUI to `aria`, downloading with server timestamp can be achieved by adding this option
![Screenshot_20240327_124142](https://github.com/persepolisdm/persepolis/assets/132728893/d65253d7-543d-4175-83f0-1e328d9459d6)

Thanks,

**Comment by alireza-amirsamimi** [comment]
Hi
Thank you. I'll add it soon.

**Comment by ZorinFoss** [comment]
> Hi Thank you. I'll add it soon.

Thank you,

**Comment by alireza-amirsamimi** [comment]
Hello
I add your feature request. Open preferences window from edit menu. In download options tab, You can check remote-time checkbox.
![Screenshot_%Y%M%D_%H%m%S-2](https://github.com/persepolisdm/persepolis/assets/7452500/f1a95889-feec-46c8-a90d-32ca21e73aff)

**Comment by ZorinFoss** [comment]
I'm waiting for new release to try it on. :+1: 
Thank you,
