### ISSUE TITLE
[Feature Request] Raspberry Pi Web GUI

### ISSUE THREAD

**Issue by ramazansancar** [persepolisdm/persepolis#963]
**System Details:**
* Operating System: Raspberry Pi
* Distro(For GNU/Linux and BSD users): Raspbian GNU/Linux 11 (bullseye)
* Desktop Environment(For GNU/Linux and BSD users): -
* Persepolis Version: -
* How do you install Persepolis? -
* _Please attach log files if crash or paste error message_

**Issue Description and steps to reproduce:**

I want to use this on raspberry device. But for GUI interface I need to connect via port. Do you have any work for this?

I want to use this on raspberry device. But for the Web GUI interface I need to connect via port. Do you have any work for this?
If this already exists, how can I do it?

**Comment by alireza-amirsamimi** [comment]
Hello
Please checkout this [project](https://github.com/ziahamza/webui-aria2).

**Comment by ramazansancar** [comment]
@alireza-amirsamimi  Thanks for the suggestion
