### ISSUE TITLE
Impossible to detect the hidden html5 player and download anime streaming video

### ISSUE THREAD

**Issue by trimechee** [persepolisdm/persepolis#965]
Hello, thank you again so much for this awesome great downloader ! 💯 🥇

I noticed it is impossible to detect the html5 video player in this anime streaming site and therefore we cannot download this videos :

https://aniwave.to/watch/erased.kkw/ep-6

and 

https://kissanime.com.ru/Anime/boku-dake-ga-inai-machi-dub.22213/Episode-003?id=131684

maybe the site hides the html5 video player against extensions and download manager....I even tried for the kissaanime site with Filecenitpede, FDM, coc coc browser, downthemall for the palemoon browser but these softwares did not succeed in detecting and download the videos in kissanime website and we hope this issue will be resolved, thank you very much :)

**Comment by alireza-amirsamimi** [comment]
Hello
Thank you.
Persepolis uses [yt-dlp](https://github.com/yt-dlp) for finding videos. so you must ask yt-dlp to support this site.

**Comment by trimechee** [comment]
interesting, thank you :) 👍
