### ISSUE TITLE
Firefox extension dont work in Librewolf (Linux)

### ISSUE THREAD

**Issue by Milor123** [persepolisdm/persepolis#966]
**System Details:**

 noe@  ~  neofetch
██████████████████  ████████    
██████████████████  ████████   ------------------------- 
██████████████████  ████████   OS: Manjaro Linux x86_64 
██████████████████  ████████   Kernel: 6.6.19-1-MANJARO 
████████            ████████   Uptime: 2 hours, 15 mins 
████████  ████████  ████████   Packages: 1963 (pacman) 
████████  ████████  ████████   Shell: zsh 5.9 
████████  ████████  ████████   Resolution: 1920x1200 
████████  ████████  ████████   DE: Plasma 5.27.11 
████████  ████████  ████████   WM: KWin 
████████  ████████  ████████   Theme: [Plasma], Breeze [GTK2/3] 
████████  ████████  ████████   Icons: [Plasma], breeze-dark [GTK2/3] 
████████  ████████  ████████   Terminal: tilix 
████████  ████████  ████████   CPU: Intel i5-14500 
                              

                                                       

* Persepolis Version: 4.0.1
* How do you install Persepolis?  Yay -S persepolis-git

Interrup Downloads is ON
and Context Menu ON

I try download files from https://myjob.page/tools/test-files

I've tried change `privacy.firstparty.isolate` settings to `false`, and all related but nothing work, persepolis dont detect the file

I have all as default  in persepolis and it is in the system tray
![image](https://github.com/persepolisdm/Persepolis-WebExtension/assets/14153649/af3156f0-bc4e-4587-a838-294e9045c7a6)

What should I do guys?

In Vivaldi it work correctly, but not in firefox (Librewolf)

**Comment by alireza-amirsamimi** [comment]
Hello
I guess the config folder of LibreWolf is different from FireFox. I'll install LibreWolf and I'll fix this issue.

**Comment by alireza-amirsamimi** [comment]
Hello
You must create two symlinks to solve the issue. Checkout this [link](https://librewolf.net/docs/faq/#how-do-i-get-native-messaging-to-work) for more information.
```

ln -s ~/.mozilla/native-messaging-hosts ~/.librewolf/native-messaging-hosts

sudo ln -s /usr/lib/mozilla/native-messaging-hosts /usr/lib/librewolf/native-messaging-hosts

```

**Comment by Milor123** [comment]
> Hello You must create two symlinks to solve the issue. Checkout this [link](https://librewolf.net/docs/faq/#how-do-i-get-native-messaging-to-work) for more information.
> 
> ```
> 
> ln -s ~/.mozilla/native-messaging-hosts ~/.librewolf/native-messaging-hosts
> 
> sudo ln -s /usr/lib/mozilla/native-messaging-hosts /usr/lib/librewolf/native-messaging-hosts
> ```

Ohh thank you very much, I've copied the file into my librewolf folder and it works !!!
```
cp -r /home/noe/.mozilla/native-messaging-hosts/com.persepolis.pdmchromewrapper.json /home/noe/.librewolf/native-messaging-hosts/com.persepolis.pdmchromewrapper.json
```

Solved !!! Thanks guys
