### ISSUE TITLE
download problems

### ISSUE THREAD

**Issue by B-Nerd** [persepolisdm/persepolis#969]
**System Details:**
* Operating System: Linux
* Distro(For GNU/Linux and BSD users): [Arch Linux]
* Desktop Environment(For GNU/Linux and BSD users): KDE Plasma 6
* Persepolis Version: 4.0.1-1
* How do you install Persepolis? Arch Repositories

when i download it cuts away parts of the file name or leaves it blank
![Screenshot_20240412_011425](https://github.com/persepolisdm/persepolis/assets/65131530/5c1459f5-df05-4b6f-8fc9-feafe718469c)
![Screenshot_20240412_011438](https://github.com/persepolisdm/persepolis/assets/65131530/56106c91-6632-43bd-9b79-20729f983c3f)

edit also tested building from source same problem

**Comment by alireza-delavari** [comment]
**System Details:**

- Linux Ubuntu 22.04, Gnome
- Persepolis Version: currently last commit (4a58c1ac0bd7c0ee33da278786b6bf2759cd376d)
- How do you install Persepolis? build from source code

I have the same problem.
It removes first and last character of file name.
I checked source code and find this line:
[spider.py#L212](https://github.com/persepolisdm/persepolis/blob/4a58c1ac0bd7c0ee33da278786b6bf2759cd376d/persepolis/scripts/spider.py#L212C13-L212C52)
```
file_name = str(filename_splited[1:-1])
```

I changed to this and it worked correctly:
```
file_name = filename_splited.strip()
```

this two lines also has the same problem:
[spider.py#L88](https://github.com/persepolisdm/persepolis/blob/4a58c1ac0bd7c0ee33da278786b6bf2759cd376d/persepolis/scripts/spider.py#L88)
[spider.py#L152](https://github.com/persepolisdm/persepolis/blob/4a58c1ac0bd7c0ee33da278786b6bf2759cd376d/persepolis/scripts/spider.py#L152)


I don't know why it was working correctly until a few days ago.
