### ISSUE TITLE
Not importing links from txt 

### ISSUE THREAD

**Issue by mrostd** [persepolisdm/persepolis#970]
**System Details:**
* Operating System: GNU/Linux
* Distro(For GNU/Linux and BSD users): Endeavour os (Arch linux)
* Desktop Environment(For GNU/Linux and BSD users): GNOME
* Persepolis Version: 4.0.1
* How do you install Persepolis? Repository

It seems that Persepolis download manager does not add the links in the txt file to its download list.
[Screencast from 2024-04-13 05-34-29.webm](https://github.com/persepolisdm/persepolis/assets/53259265/5e65b940-4d83-40e4-b613-fba3561a191c)

**Comment by alireza-amirsamimi** [comment]
Hello
Thanks for reporting. I confirm this bug. I fixed this bug two weeks ago.
