### ISSUE TITLE
Youtube Downloader Dependency

### ISSUE THREAD

**Issue by ghahramani** [persepolisdm/persepolis#975]
Hi,

It seems Persepolise still requires youtube-dl in Manjaro distribution, could you please update it to the latest version that uses yt-dlp?

It gives the error below:

```
could not satisfy dependencies:
- unable to satisfy dependency 'youtube-dl' required by persepolis
```

Installation command

```
sudo pacman -S persepolis
```

**Comment by alireza-amirsamimi** [comment]
Hi
Please tell me the output:
`pacman -Ss persepolis`

**Comment by ghahramani** [comment]
```
pacman -Ss persepolis
extra/persepolis 3.2.0-8
    Qt front-end for aria2 download manager
```

**Comment by ghahramani** [comment]
```
sudo pacman -S persepolis
resolving dependencies...
warning: cannot resolve "youtube-dl", a dependency of "persepolis"
:: The following package cannot be upgraded due to unresolvable dependencies:
      persepolis
```

**Comment by alireza-amirsamimi** [comment]
It's ArchLinux  output:

```
pacman -Ss persepolis
extra/persepolis 4.0.1-1
    Qt front-end for aria2 download manager
```

change your mirrors.
`/etc/pacman.d/mirrorlist`

**Comment by ghahramani** [comment]
changing to what? this is my mirrorlist

```
##
## Manjaro Linux default mirrorlist
## Generated on 2024-04-20 18:10
##
## Please use 'pacman-mirrors -f [NUMBER] [NUMBER]' to modify mirrorlist
## (Use 0 for all mirrors)
##

## Country : United_Kingdom
Server = https://mirror.vinehost.net/manjaro/stable/$repo/$arch

## Country : Global
Server = https://mirrors.cicku.me/manjaro/stable/$repo/$arch

## Country : Netherlands
Server = https://ftp.nluug.nl/pub/os/Linux/distr/manjaro/stable/$repo/$arch

## Country : France
Server = https://manjaro.ynh.ovh/stable/$repo/$arch

## Country : United_States
Server = https://repo.ialab.dsu.edu/manjaro/stable/$repo/$arch

## Country : Uruguay
Server = https://manjaro.repo.cure.edu.uy/stable/$repo/$arch

## Country : Ukraine
Server = https://fastmirror.pp.ua/manjaro/stable/$repo/$arch

## Country : China
Server = https://mirrors.jlu.edu.cn/manjaro/stable/$repo/$arch
```

**Comment by alireza-amirsamimi** [comment]
Sorry. I made a mistake. Manjaro repositories are different from ArchLinux.
I checked Manaro repositories. Apparently, new version of Persepolis is still in Manjaro testing repositories. checkout this [link](https://packages.manjaro.org/?query=persepolis).

**Comment by ghahramani** [comment]
how can I install the testing package in Manjaro? and how long it does take to go to stable repo usually?

**Comment by alireza-amirsamimi** [comment]
Unfortunately, I am not familiar with Manjaro. I am ArchLinux user. But maybe you can install Persepolis from [AUR](https://aur.archlinux.org/packages/persepolis-git).

**Comment by ghahramani** [comment]
Ah I see, unfortunately, I tried the `persepolis-git` package with `pamac` but could not find it

```
pamac install persepolis-git
Error: target not found: persepolis-git
```

**Comment by ghahramani** [comment]
is there a option to install it via source code?

**Comment by alireza-amirsamimi** [comment]
yes, Please checkout [persepolis wiki](https://github.com/persepolisdm/persepolis/wiki/git-installation-instruction).

**Comment by ghahramani** [comment]
Great, thank you. I successfully installed it.
