### ISSUE TITLE
Add batch downloading and automatic detection and addition of and automatic paste url addresses of the clipboard without clicking paste button

### ISSUE THREAD

**Issue by trimechee** [persepolisdm/persepolis#978]
Hello, sometimes we need to download quickly specific videos from a youtube channel, so to speed up and simplify the process and avoid clicking on "paste link" each time, it would be great please if our beloved Persepolis could detect the url address contained in the clipboard and automatically add it and paste it to the batch downloader, thank you so much !

**Comment by alireza-amirsamimi** [comment]
Hello
there is no need to copy and paste the links. Use the [Persepolis browser extension](https://github.com/persepolisdm/persepolis/wiki/Home-en#extensions). Just highlight the links in your browser and send them to download manager with the Persepolis browser extension.

**Comment by parsariyahi** [comment]
I think it's a great feature if we add it to **Persepolis**, cause I saw similar features like this in other downloaders, I would be happy to work on this feature

**Comment by alireza-amirsamimi** [comment]
This feature was added. You can activate it from the **preferences** window.

![image](https://github.com/persepolisdm/persepolis/assets/7452500/c7e244d1-4414-4b3c-8a24-87c68e04fa9f)

**Comment by trimechee** [comment]
Great ! Thank you so mch :) 💯 🥇
