### ISSUE TITLE
تنظیمات پروکسی متنوع تر برای پرسپولیس [feature request]

### ISSUE THREAD

**Issue by Monirzadeh** [persepolisdm/persepolis#98]
تعریف پروکسی علاوه بر لینکها به صورت مجزا برای لیست های دانلود و همچنین پروکسی برای کل برنامه

**Comment by alireza-amirsamimi** [comment]
سلام
در موقع اضافه کردن لینک ها به صورت دسته ای میتوانید از زبانه
download options
برای دسته دانلود پروکسی مشخص کنید
