### ISSUE TITLE
Segmentation fault (core dumped) on Fedora KDE 6.0.5

### ISSUE THREAD

**Issue by nimbold** [persepolisdm/persepolis#985]
**System Details:**
* Operating System: `Fedora Based`
* Distro(For GNU/Linux and BSD users):  `Nobara Linux`
* Desktop Environment(For GNU/Linux and BSD users): `KDE 6.0.5`
* Persepolis Version: `4.1.0.1`
* How do you install Persepolis? (Repositories, source, ...)
`Fedora repository: sudo dnf install persepolis`

* _Please attach log files if crash or paste error message_
```
The error is this: Segmentation fault (core dumped)
Please tell me what logs do you need.
```

**Issue Description and steps to reproduce:**
```
-Install Persepolis via terminal: sudo dnf install persepolis
-Open Persepolis (or run via terminal)
-Nothing happens (shows error in terminal)
```

It's similar to this old issue: 

> https://github.com/persepolisdm/persepolis/issues/520

`It was fine on KDE 6.0.4 but it broke after KDE 6.0.5 update. I don't know which package change caused this. I already tried multiple install/reinstall.`

**Comment by alireza-amirsamimi** [comment]
Hello
Perhaps It's related to KDE Plasma update. I have no problem on KDE Plasma 6.0.4.

**Comment by nimbold** [comment]
Yes, I think it was KDE's fault because it's working fine on a new Arch installation and the latest plasma package.
Thanks a lot, I'll mark it as completed.

**Comment by nimbold** [comment]
Yes, I think it was the KDE's fault because it's working fine on a new Arch installation and the latest plasma package.
Thanks a lot, I'll mark it as completed.
