### ISSUE TITLE
Increase max number of connections

### ISSUE THREAD

**Issue by Aesis7271** [persepolisdm/persepolis#986]
This is a feature request that is more of a 1st world problem than a feature.

I've used IDM up until now and it allows me to set max number of connections up to 32 whereas persepolis maxes out at 16. Since I have a tendency to archive large amounts of livestreams/livestream VODs from youtube, being capped at 16 slows down the speed I can download at quite a bit (because of the way youtube caps the download speed at 2x video speed per connection, so a 2h video can be downloaded in a minimum time of 3m45s with 16 connections, and 1m52s with 32). I have 1.5Gbps connection so I can definitely make use of the 32 connections (as I have with IDM) and I'm not sure if there's a limitation or a developer choice to stop at 16 but would like to see 32 as an option.

**Comment by alireza-amirsamimi** [comment]
Hello
Hello
Thank you for your feature request.
We hope to add this feature by the end of summer.

**Comment by alireza-amirsamimi** [comment]
With today's [pull request](https://github.com/persepolisdm/persepolis/pull/1009), this feature was added. The new version of Persepolis, which will be released soon, can download with 64 connections.
