### ISSUE TITLE
[better UI]  عدم جابجایی آنی لینکها بین دولیست

### ISSUE THREAD

**Issue by Monirzadeh** [persepolisdm/persepolis#99]
در صورت جابجایی لینک ها از یک لیست به لیست دیگر تغییرات به صورت آنی قابل مشاهده نیست و برای دیدن تغییرات نیاز به جابجایی بین لیست ها (برای بارگذاری مجدد لیست) می باشد

**Comment by alireza-amirsamimi** [comment]
سلام
من این مشکل رو در آرچ لینوکس با میزکار 
xfce
ندارم
بررسی میکنم ببینم مشکل در توزیع شما از کجاست
سپاس

**Comment by alireza-amirsamimi** [comment]
سلام
بررسی دوباره ای کردم و در اوبونتو ۱۶.۱۰ و مکینتاش هم مشکلی نداشت
مطمئن هستید که دانلود را به دسته درستی میفرستید یا در دسته
All Downloads
قرار ندارید؟
چون همه دانلودها چه صف و چه تک دانلود در این دسته قرار دارند و با جا به جایی بین دسته ها از دسته 
All Downloads
حذف نمیشوند

**Comment by Monirzadeh** [comment]
بله بین دو لیست کاملا جدید لینک را جابجا میکنم
ویدیو زیر یک اسکرین کست از همین مشکل روی سیستم من است سیستم عامل
Ubuntu 16.0.4 LTS 
http://uplod.ir/6zbrid8iwmh2/perspolis-bug.mp4.htm

**Comment by alireza-amirsamimi** [comment]
سپاس از اینکه باگ را اطلاع دادید
منظور شما رو اشتباه فهمیده بودم
البته با راست کلیک روی دانلود و استفاده از گزینه
send to
هم میتونید راحت تر دانلود ها رو انتقال بدید
روی این باگ کار خواهم کرد تا در آپدیت بعدی مشکل برطرف بشه

**Comment by alireza-amirsamimi** [comment]
باگ رو در این کامیت
[commit](https://github.com/persepolisdm/persepolis/compare/8c7bfb4657b5...5358916f8665)
فیکس کردم
انشالله در آپدیت بعدی پرسپولیس این مشکل وجود نخواهد داشت
سپاس از همکاری شما

**Comment by alireza-amirsamimi** [comment]
سلام
آپدیت کنید
باگ فیکس شد
