### ISSUE TITLE
OK button dose not work in Windows 11

### ISSUE THREAD

**Issue by Arch-Lover** [persepolisdm/persepolis#991]
**System Details:**
* Operating System: Windows 11
* Distro(For GNU/Linux and BSD users): none
* Desktop Environment(For GNU/Linux and BSD users): none
* Persepolis Version: 4.2.0
* How do you install Persepolis? (Repositories, source, ...)
* windows installation from wiki

* _Please attach log files if crash or paste error message_

**Issue Description and steps to reproduce:**
#### Please report only one Issue (Bug or feature request or ...) in one issue! and open new Issue for another one :)
Open application > edit > preferences change any thing and try to set them. OK button wont work without any apparent error.
I also have an other issue which I am not sure if related or not.
but here it goes: after opening any secondary window performances or about you have to fully kill/close application till you can perform the same action again.
hope this be helpful.

**Comment by alireza-amirsamimi** [comment]
I confirm this bug. This bug is fixed with this [commit](https://github.com/persepolisdm/persepolis/commit/66a5d7caad8f43adad517dcf2d8f8fefccc1af2b). We will release an update soon. Thanks for reporting the bug.
