### ISSUE TITLE
Problem with the new version on MacOS

### ISSUE THREAD

**Issue by mehdico** [persepolisdm/persepolis#995]
Hey,

New version (4.3.0) of the app has many issues in MacOS. I don't have time to explain them but I think the mac version of the app needs a full test.

Thanks.

**Comment by mehdico** [comment]
An example:
![Uploading Screenshot 2024-07-22 at 14.08.13.png…]()

**Comment by mehdico** [comment]
An example:

<img width="861" alt="Screenshot 2024-07-22 at 14 08 13" src="https://github.com/user-attachments/assets/f3f10979-5430-427a-b9b9-5262ddb86daa">

I'm trying to download a file using the `add a new download link` option, it displays wrong file name. actually it displays my other file's name that i have it in download list.

**Comment by mehdico** [comment]
Another one:

<img width="526" alt="Screenshot 2024-07-22 at 14 16 09" src="https://github.com/user-attachments/assets/d228f05f-e1b0-46b8-b0df-9e6e40fee45e">

In the new version (4.3.0) incomplete (in-progress) downloads appears in my download folder! (I didn't touch the app settings)

**Comment by alireza-amirsamimi** [comment]
> An example:
> <img alt="Screenshot 2024-07-22 at 14 08 13" width="861" src="https://private-user-images.githubusercontent.com/1978735/350935207-f3f10979-5430-427a-b9b9-5262ddb86daa.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI1NDQ2MDYsIm5iZiI6MTcyMjU0NDMwNiwicGF0aCI6Ii8xOTc4NzM1LzM1MDkzNTIwNy1mM2YxMDk3OS01NDMwLTQyN2EtYjliOS01MjYyZGRiODZkYWEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDgwMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA4MDFUMjAzMTQ2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OTkyMzlhMzJhOWU1ZDYxZTAyNDYxYzI3YzBlYmE4NDc1ZDIyNmE5OTYxZTYwOTk2NDg4ZDkyODg0OGZlMGNhMyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.DVTzb1JS-CKBGkp5HMJfic6h5XtOHN9_f11cnCVqHls">
> 
> I'm trying to download a file using the `add a new download link` option, it displays wrong file name. actually it displays my other file's name that i have it in download list.

Hello
Thank for reporting. Perhaps It's related to issue #998 .

**Comment by alireza-amirsamimi** [comment]
> An example:
> <img alt="Screenshot 2024-07-22 at 14 08 13" width="861" src="https://private-user-images.githubusercontent.com/1978735/350935207-f3f10979-5430-427a-b9b9-5262ddb86daa.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUyODYzODQsIm5iZiI6MTcyNTI4NjA4NCwicGF0aCI6Ii8xOTc4NzM1LzM1MDkzNTIwNy1mM2YxMDk3OS01NDMwLTQyN2EtYjliOS01MjYyZGRiODZkYWEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDkwMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA5MDJUMTQwODA0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9M2ExZTVhNGY3YmIyOGFkMDJkN2U2OGMxNzQ4ZWI3ODQzMTBiZDI3Y2I0ZGM4MWM4ZDVmNDFlNjMwODFhMWM0ZiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.GDRh_5RyM8nPfChs-RmvsErc2m8c5EWJ0qUjew0nqc8">
> 
> I'm trying to download a file using the `add a new download link` option, it displays wrong file name. actually it displays my other file's name that i have it in download list.

This bug has been fixed. Thanks for reporting.

**Comment by mehdico** [comment]
> Another one:
> 
> <img width="526" alt="Screenshot 2024-07-22 at 14 16 09" src="https://github.com/user-attachments/assets/d228f05f-e1b0-46b8-b0df-9e6e40fee45e">
> 
> In the new version (4.3.0) incomplete (in-progress) downloads appears in my download folder! (I didn't touch the app settings)


@alireza-amirsamimi 
What about this one?

**Comment by alireza-amirsamimi** [comment]
> > Another one:
> > <img alt="Screenshot 2024-07-22 at 14 16 09" width="526" src="https://private-user-images.githubusercontent.com/1978735/350936783-d228f05f-e1b0-46b8-b0df-9e6e40fee45e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU0Njc4MzUsIm5iZiI6MTcyNTQ2NzUzNSwicGF0aCI6Ii8xOTc4NzM1LzM1MDkzNjc4My1kMjI4ZjA1Zi1lMWIwLTQ2YjgtYjBkZi05ZTZlNDBmZWU0NWUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDkwNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA5MDRUMTYzMjE1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MWE0OGM3NTg1ZmRjNjkwODRiMjNhOWJkMzdiNjVhZmVhMmZlYzI3Mjg2MmZlNmFjOWY1YTQzNzYwMzYyZGM3MCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.un0yjQzUpFndpIJw7LWxGVd4nip4YgPrsT5zirxMc3s">
> > In the new version (4.3.0) incomplete (in-progress) downloads appears in my download folder! (I didn't touch the app settings)
> 
> @alireza-amirsamimi What about this one?

It seems that the problem is with your settings. We tested it on a Mac and there was no problem. The new version is released today. Please test the new version. I hope the problem is solved.
