### ISSUE TITLE
2 issues: UI and YT video

### ISSUE THREAD

**Issue by jackuars7** [persepolisdm/persepolis#996]
**System Details:**
* Operating System: Win 11
* Persepolis Version: 4.3

1. UI has an issue. Right click next to the menu bar, and you see 2 checkboxes, but no text content. I'm using the default theme (Dark Fusion) on my Windows 11 system which is in dark mode. 
2. It doesn't download certain Youtube videos. I go to this link: https://www.youtube.com/watch?v=GBnOLYg1f4M  in video finder, and try to download. It's able to fetch the video, but starting the download produces an error and says download aborted. I'm running under default settings.

**Comment by alireza-amirsamimi** [comment]
Hello
Thanks for reporting.
1. Can you attach screenshot, please?
2. Please select "show log file" from help menu and  paste the log related to this download here.

**Comment by alireza-amirsamimi** [comment]
I tried to download your youtube link. Select the advanced options. Choose 1080 from the video format section and choose the last option from the audio format section. It downloads without problems.

![image](https://github.com/persepolisdm/persepolis/assets/7452500/e60ece10-7df4-43d1-adae-57a696af4be7)
