### ISSUE TITLE
wrong filename in the download list

### ISSUE THREAD

**Issue by dzwdev** [persepolisdm/persepolis#998]
**System Details:**
* Operating System: Mnajaro Linux
* Desktop Environment: KDE
* Persepolis Version: 4.3
* How do you install Persepolis? (Repositories, source, ...): AUR

 Description and steps to reproduce:**
i added 1 download link
then i added another one, the second one takes the name of the first one 
even after deleting the first download from the list the second one shows the name of the first one

![image](https://github.com/user-attachments/assets/858951e5-957f-4deb-8715-88499831749d)

**Comment by alireza-amirsamimi** [comment]
Hello
Thanks for reporting.

**Comment by amirho3einn** [comment]
Hello guys
It is absolutely true and this bug is also present in the latest version of Ubuntu.

**Comment by alireza-amirsamimi** [comment]
This bug has been fixed. Thanks for reporting.
