### ISSUE TITLE
Impossible to install on Apple Silicon

### ISSUE THREAD

**Issue by ihubgit** [persepolisdm/persepolis#999]
Hi running latest version Sonoma 14.5 on Apple Silicon M2 macbook air 15".
When downloading latest version, getting error saying the file is damaged and cannot be opened. And should be trashed.
Any suggestions as to make it work ?

**Comment by hoishing** [comment]
refer to https://github.com/persepolisdm/persepolis/wiki/MacOS-Installer

to allow install software from `Anywhere`

**Comment by ihubgit** [comment]
thanks that did the job. Did need to trash the already installed application and reinstall it to work with the altered system settings.
